/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn start(); // weak
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// LPSTR __stdcall GetCommandLineA();
// void __stdcall __noreturn ExitProcess(UINT uExitCode);

//-------------------------------------------------------------------------
// Data declarations

CHAR Text[] = { '3', 'Y', ']', '+' }; // idb
int dword_401075 = -1311725887; // weak
__int16 word_40107A = 29696; // weak


//----- (00401000) --------------------------------------------------------
void __noreturn start()
{
  LPSTR CommandLineA; // eax
  LPSTR v1; // eax
  int v2; // esi
  LPSTR v3; // edi
  int v4; // ecx
  int v5; // eax
  int v6; // edx

  CommandLineA = GetCommandLineA();
  do
    ++CommandLineA;
  while ( *CommandLineA != 0 );
  v1 = CommandLineA - 10;
  v2 = *((_DWORD *)v1 - 1);
  v3 = v1;
  v4 = 0;
  v5 = 0;
  while ( 1 )
  {
    v6 = (unsigned __int8)v3[v4];
    if ( (_BYTE)v6 == 0 )
      break;
    LOBYTE(v6) = v6 - 48;
    v5 = v6 + 10 * v5;
    ++v4;
  }
  *(_DWORD *)Text ^= v2;
  dword_401075 ^= v5;
  MessageBoxA((HWND)(v5 + v2 + 1), Text, (LPCSTR)&word_40107A + 1, 0);
  ExitProcess(0);
}
// 401000: using guessed type void __noreturn start();
// 401075: using guessed type int dword_401075;
// 40107A: using guessed type __int16 word_40107A;

// nfuncs=4 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
