;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : FC78EB900757F454E9E2065DB2AF3C5D8EEF306999BF45EA534094C7971EFA1C
; Input MD5    : A03C3B5CA3CCFD7CED15B3E1EEEB2F94
; Input CRC32  : A1868175
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-11/timotei-crackme-11.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 64D92D17 (Sun Aug 13 19:20:55 2023 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 00000148 (    328.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000200
; Flags E0000020: Text Executable Readable Writable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Write/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing


; Attributes: noreturn

public start
start proc near
call    GetCommandLineA
xor     ebx, ebx

loc_401007:
inc     eax
mov     bl, [eax]
cmp     bl, 0
jz      short loc_401011
jmp     short loc_401007

loc_401011:
sub     eax, 0Ah
mov     esi, [eax-4]
mov     edi, eax
xor     ecx, ecx
xor     eax, eax
xor     edx, edx

loc_40101F:
movzx   edx, byte ptr [ecx+edi]
test    dl, dl
jz      short loc_401032
sub     dl, 30h ; '0'
imul    eax, 0Ah
add     eax, edx
inc     ecx
jmp     short loc_40101F

loc_401032:
xor     Text, esi
xor     dword_401075, eax
add     esi, eax
inc     esi
push    0               ; uType
mov     ebx, offset word_40107A
inc     ebx
push    ebx             ; lpCaption
push    offset Text     ; lpText
push    esi             ; hWnd
call    MessageBoxA
push    0               ; uExitCode
call    ExitProcess
start endp

; [00000006 BYTES: COLLAPSED FUNCTION MessageBoxA]
; [00000006 BYTES: COLLAPSED FUNCTION GetCommandLineA]
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
align 10h
; CHAR Text[]
Text dd 2B5D5933h
db 20h
dword_401075 dd 0B1D0A6C1h
align 2
word_40107A dw 7400h
aImoteiCrackme1 db 'imotei crackme #11 1K-Edition',0
align 4
__IMPORT_DESCRIPTOR_user32 dd rva off_4010D8 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aUser32Dll       ; DLL Name
dd rva __imp_MessageBoxA ; Import Address Table
__IMPORT_DESCRIPTOR_kernel32 dd rva off_4010E0 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_GetCommandLineA ; Import Address Table
dd 5 dup(0)
;
; Import names for user32.dll
;
off_4010D8 dd rva word_401100
dd 0
;
; Import names for kernel32.dll
;
off_4010E0 dd rva word_40111A
dd rva word_40112C
dd 0
_text ends

;
; Imports from user32.dll
;

; Segment type: Externs
; _idata
; int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)
extrn __imp_MessageBoxA:dword ; user32

;
; Imports from kernel32.dll
;
; LPSTR (__stdcall *GetCommandLineA)()
extrn __imp_GetCommandLineA:dword ; kernel32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
extrn __imp_ExitProcess:dword ; kernel32



; Segment type: Pure code
; Segment permissions: Read/Write/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401100h
assume es:nothing, ss:nothing, ds:_text, fs:nothing, gs:nothing
word_401100 dw 1B1h
db 'MessageBoxA',0
aUser32Dll db 'user32.dll',0
align 2
word_40111A dw 0E6h
db 'GetCommandLineA',0
word_40112C dw 9Bh
db 'ExitProcess',0
aKernel32Dll db 'kernel32.dll',0
align 100h
dd 380h dup(?)
_text ends


end start
