;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 11A9ACCD9AFB18245C559DBBBC93A5CEB833E118DFD52A6299BC1B97E6BDC37E
; Input MD5    : 13B51432E2A0755EA5631D455976A8D4
; Input CRC32  : B4E3BD1C
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-08/timotei-crackme-08.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 64909732 (Mon Jun 19 17:58:10 2023 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 00000206 (    518.)
; Section size in file          : 00000400 (   1024.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing


; Attributes: noreturn

public start
start proc near
push    0FFFFFFF5h      ; nStdHandle
call    GetStdHandle
mov     hConsoleOutput, eax
push    0FFFFFFF6h      ; nStdHandle
call    GetStdHandle
mov     hConsoleInput, eax
xor     ebx, ebx
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    75h ; 'u'       ; nNumberOfCharsToWrite
push    offset aWelcomeToTheCr ; "_.: Welcome to the Crackme History Quiz"...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    64h ; 'd'       ; nNumberOfCharsToWrite
push    (offset aWelcomeToTheCr+75h) ; lpBuffer
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    8Dh             ; nNumberOfCharsToWrite
push    offset aBackInTheDayTk ; "-->Back in the day \"tKC\" was famous. "...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    5Ah ; 'Z'       ; nNumberOfCharsToWrite
push    offset aWhatWasSmartch ; "-->What was Smartcheck used for: (1) VB"...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    58h ; 'X'       ; nNumberOfCharsToWrite
push    offset aWhoWroteTheFir ; "-->Who wrote the first cracking tutoria"...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    4Eh ; 'N'       ; nNumberOfCharsToWrite
push    offset aWhatWasAFamous ; "-->What was a famous dissassembler: (1)"...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    81h             ; nNumberOfCharsToWrite
push    offset aInThePastCrack ; "-->In the past crackmes were used for l"...
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
add     bl, Buffer
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    26h ; '&'       ; nNumberOfCharsToWrite
push    offset aWhatIsTheAnswe ; "-->What is the answer to everything :"
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA
push    0               ; pInputControl
push    offset NumberOfCharsRead ; lpNumberOfCharsRead
push    64h ; 'd'       ; nNumberOfCharsToRead
push    offset Buffer   ; lpBuffer
push    hConsoleInput   ; hConsoleInput
call    ReadConsoleA
push    offset Buffer   ; String
call    ds:__imp_atoi   ; msvcrt
sub     ebx, eax
sub     bl, 1
jnz     short loc_4011E0
push    0               ; lpReserved
push    0               ; lpNumberOfCharsWritten
push    14h             ; nNumberOfCharsToWrite
push    offset aWellDone ; "_.: Well Done :._  "
push    hConsoleOutput  ; hConsoleOutput
call    WriteConsoleA

loc_4011E0:             ; uExitCode
push    0
call    ExitProcess
start endp

align 4
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION GetStdHandle]
; [00000006 BYTES: COLLAPSED FUNCTION ReadConsoleA]
; [00000006 BYTES: COLLAPSED FUNCTION WriteConsoleA]
; [00000006 BYTES: COLLAPSED FUNCTION atoi]
align 200h
dd 300h dup(?)
_text ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 000000D4 (    212.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000800
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from kernel32.dll
;

; Segment type: Externs
; _idata
; HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle)
extrn __imp_GetStdHandle:dword ; kernel32
; BOOL (__stdcall *ReadConsoleA)(HANDLE hConsoleInput, LPVOID lpBuffer, DWORD nNumberOfCharsToRead, LPDWORD lpNumberOfCharsRead, PCONSOLE_READCONSOLE_CONTROL pInputControl)
extrn __imp_ReadConsoleA:dword ; kernel32
; BOOL (__stdcall *WriteConsoleA)(HANDLE hConsoleOutput, const void *lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved)
extrn __imp_WriteConsoleA:dword ; kernel32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
extrn __imp_ExitProcess:dword ; kernel32

;
; Imports from msvcrt.dll
;
; int (__cdecl *atoi)(const char *String)
extrn __imp_atoi:dword  ; msvcrt



; Segment type: Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 40201Ch
__IMPORT_DESCRIPTOR_kernel32 dd rva off_402058 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_GetStdHandle ; Import Address Table
__IMPORT_DESCRIPTOR_msvcrt dd rva off_40206C ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aMsvcrtDll       ; DLL Name
dd rva __imp_atoi       ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for kernel32.dll
;
off_402058 dd rva word_402082
dd rva word_402092
dd rva word_4020A2
dd rva word_402074
dd 0
;
; Import names for msvcrt.dll
;
off_40206C dd rva word_4020C0
dd 0
word_402074 dw 9Bh
db 'ExitProcess',0
word_402082 dw 16Ah
db 'GetStdHandle',0
align 2
word_402092 dw 233h
db 'ReadConsoleA',0
align 2
word_4020A2 dw 2EEh
db 'WriteConsoleA',0
aKernel32Dll db 'kernel32.dll',0
align 10h
word_4020C0 dw 220h
db 'atoi',0
align 4
aMsvcrtDll db 'msvcrt.dll',0
align 1000h
_rdata ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 000003F9 (   1017.)
; Section size in file          : 00000400 (   1024.)
; Offset to raw data for section: 00000A00
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 403000h
aWelcomeToTheCr db '_.: Welcome to the Crackme History '
db 'Quiz :.___(best viewed in fullscree'
db 'n :-)',0Dh,0Ah
db '_.:Enter the number of your answer.'
db '.. ',0Dh,0Ah
db '-->Which website offered crackmes a'
db 't first: (1) crackmes.de (2) crackm'
db 'es.cjb.net (3) crackmes.one :',0
aBackInTheDayTk db '-->Back in the day "tKC" was famous'
db '. What stand the abbreviation for: '
db '(1) The Kool Crackers (2) The Keybo'
db 'ard Caper (3) Tech Kills Contacts :'
db 0
aWhatWasSmartch db '-->What was Smartcheck used for: (1'
db ') VB Debugging (2) .NET Debugging ('
db '3) JAVA Debugging :',0
aWhoWroteTheFir db '-->Who wrote the first cracking tut'
db 'orials: (1) TheEgoist!  (2) -ETERNA'
db 'LBLISS (3) +ORC :',0
aWhatWasAFamous db '-->What was a famous dissassembler:'
db ' (1) Sourcer (2) PEDump (3) Hex Wor'
db 'kshop :',0
aInThePastCrack db '-->In the past crackmes were used f'
db 'or learning but also for: (1) compe'
db 'tition  (2) joining a cracking grou'
db 'p (3) school projects :',0
aWhatIsTheAnswe db '-->What is the answer to everything'
db ' :',0
aWellDone db '_.: Well Done :._  ',0
; char Buffer
Buffer db 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; DWORD NumberOfCharsRead
NumberOfCharsRead dd 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; HANDLE hConsoleInput
hConsoleInput dd 0
; HANDLE hConsoleOutput
hConsoleOutput dd 0
align 1000h
_data ends


end start
