;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 7E6DA2C5799C001E41087CA7A3E109DD530E486617DE6C66E9F23DCC1FA41453
; Input MD5    : 2581DF5B9022722ED494BE8637D656AA
; Input CRC32  : D70BC4FF
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-06/timotei-crackme-06.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 6452B8DB (Wed May 03 19:41:15 2023 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 000001CE (    462.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing


; Attributes: noreturn

public start
start proc near
push    0               ; hTemplateFile
push    80h             ; dwFlagsAndAttributes
push    3               ; dwCreationDisposition
push    0               ; lpSecurityAttributes
push    0               ; dwShareMode
push    80000000h       ; dwDesiredAccess
push    offset FileName ; "timotei.crackme#6.enjoy!"
call    CreateFileA
cmp     eax, 0FFFFFFFFh
jz      short loc_40109E
mov     hFile, eax
push    0               ; lpOverlapped
push    offset NumberOfBytesRead ; lpNumberOfBytesRead
push    50h ; 'P'       ; nNumberOfBytesToRead
push    offset unk_403019 ; lpBuffer
push    hFile           ; hFile
call    ReadFile
cmp     eax, 0
jz      short loc_40109E
xor     edx, edx
xor     ecx, ecx
sub     NumberOfBytesRead, 0Dh
jnz     short loc_40109E
mov     eax, offset unk_403019
add     edx, [eax]
sub     edx, [eax+4]
add     edx, [eax+8]
cmp     edx, 0BC614Eh
jl      short loc_40109E
cmp     dl, [eax+0Ch]
jnz     short loc_40109E
cmp     byte ptr [eax+0Ah], 36h ; '6'
jnz     short loc_40109E
push    offset aKeyfileAccepte ; ".:keyfile:.accepted:."
call    sub_4010B0
push    offset asc_403087 ; "\r\n"
call    sub_4010B0
push    offset aPressAnyKeyToC ; "Press any key to continue ..."
call    sub_4010B0
call    sub_4010F0
push    offset asc_4030AA ; "\r\n"
call    sub_4010B0

loc_40109E:             ; hObject
push    hFile
call    CloseHandle
push    0               ; uExitCode
call    ExitProcess
start endp



; Attributes: bp-based frame

; int __stdcall sub_4010B0(LPCVOID lpBuffer)
sub_4010B0 proc near

nNumberOfBytesToWrite= dword ptr -0Ch
NumberOfBytesWritten= dword ptr -8
hFile= dword ptr -4
lpBuffer= dword ptr  8

push    ebp
mov     ebp, esp
add     esp, 0FFFFFFF4h
push    0FFFFFFF5h      ; nStdHandle
call    GetStdHandle
mov     [ebp+hFile], eax
push    [ebp+lpBuffer]
call    sub_401120
mov     [ebp+nNumberOfBytesToWrite], eax
push    0               ; lpOverlapped
lea     eax, [ebp+NumberOfBytesWritten]
push    eax             ; lpNumberOfBytesWritten
push    [ebp+nNumberOfBytesToWrite] ; nNumberOfBytesToWrite
push    [ebp+lpBuffer]  ; lpBuffer
push    [ebp+hFile]     ; hFile
call    WriteFile
mov     eax, [ebp+NumberOfBytesWritten]
leave
retn    4
sub_4010B0 endp

align 10h



sub_4010F0 proc near
push    0FFFFFFF6h      ; nStdHandle
call    GetStdHandle
push    eax             ; hConsoleInput
call    FlushConsoleInputBuffer

loc_4010FD:             ; dwMilliseconds
push    1
call    Sleep
call    ds:__imp__kbhit ; msvcrt
test    eax, eax
jz      short loc_4010FD
call    ds:__imp__getch ; msvcrt
retn
sub_4010F0 endp

align 10h



sub_401120 proc near

arg_0= dword ptr  4

mov     eax, [esp+arg_0]
lea     edx, [eax+3]
push    ebp
push    edi
mov     ebp, 80808080h

loc_40112E:
mov     edi, [eax]
add     eax, 4
lea     ecx, [edi-1010101h]
not     edi
and     ecx, edi
and     ecx, ebp
jnz     short loc_40117A
mov     edi, [eax]
add     eax, 4
lea     ecx, [edi-1010101h]
not     edi
and     ecx, edi
and     ecx, ebp
jnz     short loc_40117A
mov     edi, [eax]
add     eax, 4
lea     ecx, [edi-1010101h]
not     edi
and     ecx, edi
and     ecx, ebp
jnz     short loc_40117A
mov     edi, [eax]
add     eax, 4
lea     ecx, [edi-1010101h]
not     edi
and     ecx, edi
and     ecx, ebp
jz      short loc_40112E

loc_40117A:
test    ecx, 8080h
jnz     short loc_401188
shr     ecx, 10h
add     eax, 2

loc_401188:
shl     cl, 1
sbb     eax, edx
pop     edi
pop     ebp
retn    4
sub_401120 endp

align 2
; [00000006 BYTES: COLLAPSED FUNCTION CloseHandle]
; [00000006 BYTES: COLLAPSED FUNCTION CreateFileA]
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION ReadFile]
; [00000006 BYTES: COLLAPSED FUNCTION GetStdHandle]
; [00000006 BYTES: COLLAPSED FUNCTION WriteFile]
; [00000006 BYTES: COLLAPSED FUNCTION FlushConsoleInputBuffer]
; [00000006 BYTES: COLLAPSED FUNCTION Sleep]
; [00000006 BYTES: COLLAPSED FUNCTION _getch]
; [00000006 BYTES: COLLAPSED FUNCTION _kbhit]
align 40h
dd 380h dup(?)
_text ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 0000013E (    318.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000600
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from kernel32.dll
;

; Segment type: Externs
; _idata
; BOOL (__stdcall *CloseHandle)(HANDLE hObject)
extrn __imp_CloseHandle:dword ; kernel32
; HANDLE (__stdcall *CreateFileA)(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile)
extrn __imp_CreateFileA:dword ; kernel32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
extrn __imp_ExitProcess:dword ; kernel32
; BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped)
extrn __imp_ReadFile:dword ; kernel32
; HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle)
extrn __imp_GetStdHandle:dword ; kernel32
; BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped)
extrn __imp_WriteFile:dword ; kernel32
; BOOL (__stdcall *FlushConsoleInputBuffer)(HANDLE hConsoleInput)
extrn __imp_FlushConsoleInputBuffer:dword ; kernel32
; void (__stdcall *Sleep)(DWORD dwMilliseconds)
extrn __imp_Sleep:dword ; kernel32

;
; Imports from msvcrt.dll
;
; int (__cdecl *_kbhit)()
extrn __imp__kbhit:dword ; msvcrt
; int (__cdecl *_getch)()
extrn __imp__getch:dword ; msvcrt



; Segment type: Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 402030h
__IMPORT_DESCRIPTOR_kernel32 dd rva off_40206C ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_CloseHandle ; Import Address Table
__IMPORT_DESCRIPTOR_msvcrt dd rva off_402090 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aMsvcrtDll       ; DLL Name
dd rva __imp__kbhit     ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for kernel32.dll
;
off_40206C dd rva word_40209C
dd rva word_4020AA
dd rva word_4020B8
dd rva word_4020C6
dd rva word_4020D2
dd rva word_4020E2
dd rva word_4020EE
dd rva word_402108
dd 0
;
; Import names for msvcrt.dll
;
off_402090 dd rva word_402128
dd rva word_40211E
dd 0
word_40209C dw 23h
db 'CloseHandle',0
word_4020AA dw 3Dh
db 'CreateFileA',0
word_4020B8 dw 9Bh
db 'ExitProcess',0
word_4020C6 dw 23Dh
db 'ReadFile',0
align 2
word_4020D2 dw 16Ah
db 'GetStdHandle',0
align 2
word_4020E2 dw 2F7h
db 'WriteFile',0
word_4020EE dw 0C6h
db 'FlushConsoleInputBuffer',0
word_402108 dw 2B7h
db 'Sleep',0
aKernel32Dll db 'kernel32.dll',0
align 2
word_40211E dw 0CEh
db '_getch',0
align 4
word_402128 dw 111h
db '_kbhit',0
align 2
aMsvcrtDll db 'msvcrt.dll',0
align 1000h
_rdata ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 000000B0 (    176.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000800
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 403000h
; CHAR FileName[]
FileName db 'timotei.crackme#6.enjoy!',0
unk_403019 db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; HANDLE hFile
hFile dd 0
; DWORD NumberOfBytesRead
NumberOfBytesRead db 0
db    0
db    0
db    0
aKeyfileAccepte db '.:keyfile:.accepted:.',0
asc_403087 db 0Dh,0Ah,0
align 4
aPressAnyKeyToC db 'Press any key to continue ...',0
asc_4030AA db 0Dh,0Ah,0
align 1000h
_data ends


end start
