/**
 * 
 */
package net.ttlhacker.jittery;

/**
 * @author jonathan
 *
 */
public class VmHeaderGeneratorMain {
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		String jitFuncArgs = "struct vm_program_info *info, struct vm_insn *insn, uint8_t **pos, uint32_t currentPc";
		
		System.out.println("// !!! AUTOGENERATED HEADER FILE !!!");
		System.out.println();
		
		System.out.println("#include <stdint.h>");
		System.out.println("#include \"../vm.h\"");
		System.out.println();
		
		System.out.print("#define JITFUNC(name) int jit_gen_##name(");
		System.out.print(jitFuncArgs);
		System.out.println(")");
		System.out.println();
		
		
		for (var insn: InstructionTemplate.values()) {
			System.out.println("#define OP_" + insn.name() + " " + insn.ordinal());
			System.out.println("JITFUNC(" + insn.name() + ");");
			System.out.println();
		}
		
		System.out.println("#ifdef JITTERY_NEED_FUNCTION_TABLE");
		System.out.print("typedef int (*jit_gen_fn)(");
		System.out.print(jitFuncArgs);
		System.out.println(");");
		System.out.println();
		
		System.out.println("static jit_gen_fn jit_funcs[] = {");
		for (var insn: InstructionTemplate.values()) {
			System.out.print("\t[OP_");
			System.out.print(insn.name());
			System.out.print("] = jit_gen_");
			System.out.print(insn.name());
			System.out.println(",");
		}
		System.out.println("};");
		System.out.println("#endif");
	}

}
