/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <math.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// struct tm *localtime(const time_t *timer);
// int puts(const char *s);
// size_t strlen(const char *s);
// char *strchr(const char *s, int c);
// int printf(const char *format, ...);
// int ioctl(int fd, unsigned __int64 request, ...);
// void srand(unsigned int seed);
// char *fgets(char *s, int n, FILE *stream);
// time_t time(time_t *timer);
// char *getlogin(void);
// size_t strftime(char *s, size_t maxsize, const char *format, const struct tm *tp);
// double sin(double x);
// int sprintf(char *s, const char *format, ...);
// int rand(void);
// const unsigned __int16 **__ctype_b_loc(void);
// int _cxa_finalize(void *);
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
FILE **sub_1270();
__int64 sub_12A0(); // weak
FILE **sub_12E0();
__int64 __fastcall sub_1320(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall prettymenu(__int64 a1);
int printmenu();
int badboy();
int goodboy();
__int64 __fastcall vmstart(__int64 a1, __int64 a2);
char __fastcall sub_1830(__int64 a1);
void _libc_csu_fini(); // idb
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// int __cxa_finalize(void *);
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 _gmon_start__(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN _libc_csu_init;
_UNKNOWN unk_2180; // weak
__int128 xmmword_2290 = 0x9891968B918A909CDF9B919EF59B93DALL; // weak
__int64 (__fastcall *funcs_1E31[2])() = { &sub_1320, &sub_12E0 }; // weak
__int64 (__fastcall *off_3DC0)() = &sub_12E0; // weak
void *_dso_handle = &_dso_handle; // idb
char *off_40C0[2] = { "bagolymadar", "2020.08" }; // weak
char *off_40C8 = "2020.08"; // weak
char *off_40E0 = "__     ___ ____ _____ _   _   _    _       _ "; // idb
char *off_40E8 = "\\ \\   / (_)  _ \\_   _| | | | / \\  | |     / |"; // idb
char *off_40F0 = " \\ \\ / /| | |_) || | | | | |/ _ \\ | |     | |"; // idb
char *off_40F8 = "  \\ V / | |  _ < | | | |_| / ___ \\| |___ _| |"; // idb
char *off_4100 = "   \\_/  |_|_| \\_\\|_|  \\___/_/   \\_\\_____(_)_|"; // idb
_UNKNOWN unk_4108; // weak
_UNKNOWN unk_4230; // weak
_UNKNOWN unk_4250; // weak
_UNKNOWN unk_4258; // weak
_UNKNOWN unk_4268; // weak
FILE *stdin; // idb
char byte_42F8; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ != nullptr )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4398: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001130) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  char v3; // al
  char *v4; // rdx
  char v5; // al
  char *v6; // rdx
  char v8[256]; // [rsp+0h] [rbp-218h] BYREF
  char s[280]; // [rsp+100h] [rbp-118h] BYREF

  printmenu();
  printf("%s", "Username: ");
  if ( fgets(v8, 250, stdin) == nullptr )
    goto LABEL_14;
  v3 = v8[0];
  v4 = v8;
  if ( v8[0] != 0 )
  {
    while ( v3 != 10 )
    {
      v3 = *++v4;
      if ( v3 == 0 )
        goto LABEL_7;
    }
    *v4 = 0;
  }
LABEL_7:
  printf("%s", "Serial: ");
  if ( fgets(s, 250, stdin) == nullptr )
    goto LABEL_14;
  v5 = s[0];
  if ( s[0] != 0 )
  {
    v6 = s;
    while ( v5 != 10 )
    {
      v5 = *++v6;
      if ( v5 == 0 )
        goto LABEL_13;
    }
    *v6 = 0;
  }
LABEL_13:
  if ( (unsigned int)vmstart((__int64)v8, (__int64)s) == 1 )
    puts("\n    Yep, you got it!\n");
  else
LABEL_14:
    puts("\n    Nope, this is incorrect!\n");
  return 0;
}

//----- (0000000000001240) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(
    (int (*)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)())_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// 1246: positive sp value 8 has been found
// 124D: variable 'v3' is possibly undefined

//----- (0000000000001270) ----------------------------------------------------
FILE **sub_1270()
{
  return &stdin;
}
// 4390: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (00000000000012A0) ----------------------------------------------------
__int64 sub_12A0()
{
  return 0;
}
// 12A0: using guessed type __int64 sub_12A0();
// 43A0: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (00000000000012E0) ----------------------------------------------------
FILE **sub_12E0()
{
  FILE **result; // rax

  if ( byte_42F8 == 0 )
  {
    if ( &__cxa_finalize != nullptr )
      _cxa_finalize(_dso_handle);
    result = sub_1270();
    byte_42F8 = 1;
  }
  return result;
}
// 42F8: using guessed type char byte_42F8;

//----- (0000000000001330) ----------------------------------------------------
__int64 __fastcall prettymenu(__int64 a1)
{
  int v1; // r12d
  size_t v2; // rax
  size_t v3; // rax
  size_t v4; // rbx
  size_t v5; // rax
  size_t v6; // rax
  int v7; // ebp
  char **v8; // rbx
  int v9; // ebp
  const char *v10; // rcx
  int v11; // r12d
  unsigned int v12; // eax
  int v13; // eax
  __int64 v14; // r15
  unsigned int v15; // ebx
  char *v16; // r13
  char v17; // dl
  char v18; // bl
  char v19; // dl
  char v20; // al
  struct tm *v21; // rax
  time_t v22; // rdx
  char *v23; // rbx
  int v24; // r13d
  unsigned int v25; // r14d
  char *i; // rbp
  __int64 v27; // rsi
  unsigned int v28; // r10d
  int v29; // eax
  int v30; // esi
  int v31; // r14d
  int v33; // r12d
  unsigned int v34; // ebp
  int v36; // [rsp+Ch] [rbp-16Ch]
  double v37; // [rsp+18h] [rbp-160h]
  time_t timer[2]; // [rsp+20h] [rbp-158h] BYREF
  char v39; // [rsp+30h] [rbp-148h]
  char s[312]; // [rsp+40h] [rbp-138h] BYREF

  v1 = strlen(off_40E0);
  v2 = strlen(off_40E8);
  if ( v2 > v1 )
    v1 = v2;
  v3 = strlen(off_40F0);
  v4 = v1;
  if ( v3 > v1 )
  {
    v4 = (int)v3;
    v1 = v3;
  }
  v5 = strlen(off_40F8);
  if ( v5 > v4 )
  {
    v4 = (int)v5;
    v1 = v5;
  }
  v6 = strlen(off_4100);
  if ( v4 < v6 )
    v1 = v6;
  v7 = *(unsigned __int16 *)(a1 + 2);
  if ( v7 >= v1 )
  {
    v8 = &off_40E0;
    v9 = (v7 - v1) >> 1;
    puts("\n");
    do
    {
      v10 = *v8++;
      printf("%*s%s\n", v9, "", v10);
    }
    while ( v8 != (char **)&unk_4108 );
    v36 = v1 + v9;
    v11 = *(unsigned __int16 *)(a1 + 2);
    v12 = time(nullptr);
    srand(v12);
    rand();
    if ( (rand() >> 3) % 40 == 39 )
    {
      v13 = rand();
      v14 = 1;
      v15 = ((((unsigned int)(v13 >> 31) >> 29) + (unsigned __int8)(v13 >> 4)) & 7) - ((unsigned int)(v13 >> 31) >> 29);
      v37 = sin((double)(int)(11 * (v15 + 1)) / 57.29577951308232);
      v16 = (char *)&unk_2180 + 31 * (int)v15;
      v17 = *v16;
      v18 = LOBYTE(v37) ^ *v16;
      s[0] = v18;
      if ( v17 == LOBYTE(v37) )
      {
LABEL_24:
        v23 = s;
        v24 = -1;
        v25 = -1;
        for ( i = strchr(s, 10); i != nullptr; i = strchr(i + 1, 10) )
        {
          v28 = (_DWORD)i - (_DWORD)v23;
          if ( v24 == -1 )
          {
            v25 = v11 - v28;
            if ( (int)(v11 - v28) > v36 )
              v25 = v36;
            printf("%*s%.*s\n", v25, "", v28, v23);
            v24 = (_DWORD)i - (_DWORD)v23;
          }
          else
          {
            v27 = v25 + v24 / 2 - (int)v28 / 2;
            if ( (int)v27 > (int)(v11 - v28) )
              v27 = v11 - v28;
            printf("%*s%.*s\n", v27, "", v28, v23);
          }
          v23 = i + 1;
        }
        v29 = strlen(v23);
        if ( v24 == -1 )
        {
          v33 = v11 - v29;
          v30 = v36;
          if ( v33 <= v36 )
            v30 = v33;
        }
        else
        {
          v30 = v11 - v29;
          v31 = v24 / 2 + v25 - v29 / 2;
          if ( v31 <= v11 - v29 )
            v30 = v31;
        }
        printf("%*s%.*s\n", v30, "", v29, v23);
LABEL_38:
        puts("\n\n");
        return 0;
      }
      while ( 1 )
      {
        if ( v18 == 13 )
        {
          timer[0] = time(nullptr);
          v21 = localtime(timer);
          strftime(s, 0xFFu, "%c", v21);
          goto LABEL_24;
        }
        if ( v18 == 9 )
        {
          v39 = 33;
          *(__m128i *)timer = _mm_xor_si128((__m128i)-1LL, (__m128i)xmmword_2290);
          v22 = time(nullptr);
LABEL_23:
          sprintf(s, (const char *)timer, v22);
          goto LABEL_24;
        }
        if ( v18 == 1 )
          break;
        if ( v18 != 10 && ((*__ctype_b_loc())[v18] & 0x4000) == 0 )
          goto LABEL_44;
        v19 = v16[v14];
        v20 = *((_BYTE *)&timer[-1] + (v14 & 7));
        v18 = v20 ^ v19;
        s[v14++] = v20 ^ v19;
        if ( v19 == v20 )
          goto LABEL_24;
      }
      v22 = (time_t)getlogin();
      if ( v22 != 0 )
      {
        qmemcpy(timer, "Hi %s!", 6);
        goto LABEL_23;
      }
    }
LABEL_44:
    v34 = v36;
    if ( *(unsigned __int16 *)(a1 + 2) - 11 <= v36 )
      v34 = *(unsigned __int16 *)(a1 + 2) - 11;
    printf("%*s%s\n", v34, "", off_40C0[0]);
    printf("%*s%s\n", v34 + 2, "", off_40C8);
    goto LABEL_38;
  }
  return 0xFFFFFFFFLL;
}
// 2290: using guessed type __int128 xmmword_2290;
// 40C0: using guessed type char *off_40C0[2];
// 40C8: using guessed type char *off_40C8;

//----- (0000000000001790) ----------------------------------------------------
int printmenu()
{
  int result; // eax
  _BYTE v1[16]; // [rsp+8h] [rbp-10h] BYREF

  result = ioctl(1, 0x5413u, v1);
  if ( result != -1 )
    return prettymenu((__int64)v1);
  return result;
}

//----- (00000000000017D0) ----------------------------------------------------
int badboy()
{
  return puts("\n    Nope, this is incorrect!\n");
}

//----- (00000000000017E0) ----------------------------------------------------
int goodboy()
{
  return puts("\n    Yep, you got it!\n");
}

//----- (00000000000017F0) ----------------------------------------------------
__int64 __fastcall vmstart(__int64 a1, __int64 a2)
{
  __int64 v2; // rdi

  memset(&unk_4230, 0, 0xC0u);
  unk_4250 = (char *)&unk_4230 + 192;
  unk_4258 = a2;
  unk_4268 = (char *)&unk_4230 + 192;
  sub_1830((__int64)&unk_4230);
  return *(_QWORD *)(v2 + 16);
}
// 182B: variable 'v2' is possibly undefined

//----- (0000000000001830) ----------------------------------------------------
char __fastcall sub_1830(__int64 a1)
{
  __int64 v1; // rax
  _BYTE *v2; // rsi
  char result; // al
  unsigned __int8 *v4; // rsi
  unsigned __int64 v5; // rcx
  unsigned __int64 v6; // rcx
  unsigned __int64 v7; // rcx
  __int64 *v8; // r9
  __int64 *v9; // rax
  unsigned __int64 v10; // r10
  __int64 *v11; // r9
  _BYTE *v12; // rsi
  _QWORD *v13; // r9
  __int64 v14; // rax
  __int64 *v15; // r9
  unsigned __int64 v16; // rcx
  unsigned __int8 v17; // al
  _BYTE *v18; // rsi
  __int64 v19; // rax
  __int64 *v20; // r8

  while ( 1 )
  {
    while ( 1 )
    {
      while ( 1 )
      {
        while ( 1 )
        {
          while ( 1 )
          {
            while ( 1 )
            {
              while ( 1 )
              {
                while ( 1 )
                {
                  v2 = (char *)&unk_4108 + *(_QWORD *)(a1 + 24);
                  result = *v2;
                  v4 = v2 + 1;
                  if ( result != 1 )
                    break;
                  v1 = *(_QWORD *)(a1 + 8LL * v4[1]);
                  *(_QWORD *)(a1 + 8LL * *v4) = v1;
                  *(_QWORD *)(a1 + 24) += 3LL;
                }
                if ( result != 2 )
                  break;
                *(_BYTE *)(a1 + 8LL * *v4) = *(_BYTE *)(a1 + 8LL * v4[1]);
                *(_QWORD *)(a1 + 24) += 3LL;
              }
              if ( result != 9 )
                break;
              *(_BYTE *)--*(_QWORD *)(a1 + 56) = *v4;
              *(_QWORD *)(a1 + 24) += 2LL;
            }
            if ( result != 17 )
              break;
            BYTE1(v1) = *(_WORD *)v4;
            LOBYTE(v1) = HIBYTE(*(_WORD *)v4);
            v1 = (unsigned __int16)v1;
            *(_QWORD *)(a1 + 24) = (unsigned __int16)v1;
          }
          if ( result != 20 )
            break;
          --*(_QWORD *)(a1 + 8LL * *v4);
          *(_QWORD *)(a1 + 24) += 2LL;
        }
        if ( result != 30 )
          break;
        v1 = *(_QWORD *)(a1 + 8LL * *v4);
        v5 = *(_QWORD *)(a1 + 48) & 0xFFFFFFFFFFFFFFFELL;
        LOBYTE(v5) = (*(_BYTE *)v1 == 0) | v5;
        *(_QWORD *)(a1 + 48) = v5;
        *(_QWORD *)(a1 + 24) += 2LL;
      }
      if ( result != 65 )
        break;
      ++*(_QWORD *)(a1 + 8LL * *v4);
      *(_QWORD *)(a1 + 24) += 2LL;
    }
    if ( result == 76 )
      break;
    switch ( result )
    {
      case 82:
        v1 = **(unsigned __int8 **)(a1 + 40);
        *(_QWORD *)a1 = v1;
        ++*(_QWORD *)(a1 + 40);
        ++*(_QWORD *)(a1 + 24);
        break;
      case 84:
        v1 = *(_QWORD *)(a1 + 8LL * *v4);
        v6 = *(_QWORD *)(a1 + 48) & 0xFFFFFFFFFFFFFFFELL;
        LOBYTE(v6) = (v1 == 0) | v6;
        *(_QWORD *)(a1 + 48) = v6;
        *(_QWORD *)(a1 + 24) += 2LL;
        break;
      case 85:
        if ( (*(_QWORD *)(a1 + 48) & 1LL) != 0 )
        {
          BYTE1(v1) = *(_WORD *)v4;
          LOBYTE(v1) = HIBYTE(*(_WORD *)v4);
          v1 = (unsigned __int16)v1;
          *(_QWORD *)(a1 + 24) = (unsigned __int16)v1;
        }
        else
        {
          *(_QWORD *)(a1 + 24) += 3LL;
        }
        break;
      case 86:
        v1 = v4[1];
        *(_QWORD *)(a1 + 8LL * *v4) = (unsigned __int8)v1;
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case 105:
        v1 = **(unsigned __int8 **)(a1 + 32);
        *(_QWORD *)a1 = v1;
        ++*(_QWORD *)(a1 + 32);
        ++*(_QWORD *)(a1 + 24);
        break;
      case 127:
        v1 = v4[1];
        v7 = *(_QWORD *)(a1 + 48) & 0xFFFFFFFFFFFFFFFCLL;
        LOBYTE(v7) = (2 * (*(_QWORD *)(a1 + 8LL * *v4) < (__int64)(unsigned __int8)v1))
                   | (*(_QWORD *)(a1 + 8LL * *v4) == (unsigned __int8)v1)
                   | v7;
        *(_QWORD *)(a1 + 48) = v7;
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -127:
        if ( (*(_QWORD *)(a1 + 48) & 1LL) != 0 )
        {
          *(_QWORD *)(a1 + 24) += 3LL;
        }
        else
        {
          BYTE1(v1) = *(_WORD *)v4;
          LOBYTE(v1) = HIBYTE(*(_WORD *)v4);
          v1 = (unsigned __int16)v1;
          *(_QWORD *)(a1 + 24) = (unsigned __int16)v1;
        }
        break;
      case -115:
        *(_QWORD *)(a1 + 56) -= 8LL;
        **(_QWORD **)(a1 + 56) = *(_QWORD *)(a1 + 8LL * *v4);
        *(_QWORD *)(a1 + 24) += 2LL;
        break;
      case -114:
        v8 = (__int64 *)(a1 + 8LL * *v4);
        v9 = *(__int64 **)(a1 + 56);
        *(_QWORD *)(a1 + 56) = v9 + 1;
        v1 = *v9;
        *v8 = v1;
        *(_QWORD *)(a1 + 24) += 2LL;
        break;
      case -113:
        *(_QWORD *)(a1 + 8LL * *v4) >>= v4[1];
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -112:
        v1 = v4[1];
        v10 = *(_QWORD *)(a1 + 48) & 0xFFFFFFFFFFFFFFFELL;
        LOBYTE(v10) = (((unsigned __int8)v1 & *(_QWORD *)(a1 + 8LL * *v4)) == 0) | v10;
        *(_QWORD *)(a1 + 48) = v10;
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -109:
        v11 = (__int64 *)(a1 + 8LL * *v4);
        v1 = *(_QWORD *)(a1 + 8LL * v4[1]) + *v11;
        *v11 = v1;
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -108:
        LOBYTE(v1) = *v4;
        v12 = v4 + 1;
        v13 = (_QWORD *)(a1 + 8LL * (unsigned __int8)v1);
        LOBYTE(v1) = *v12++;
        v14 = v1 << 8;
        LOBYTE(v14) = *v12++;
        v14 <<= 8;
        LOBYTE(v14) = *v12++;
        v14 <<= 8;
        LOBYTE(v14) = *v12++;
        v14 <<= 8;
        LOBYTE(v14) = *v12++;
        v14 <<= 8;
        LOBYTE(v14) = *v12++;
        v14 <<= 8;
        LOBYTE(v14) = *v12;
        v1 = v14 << 8;
        LOBYTE(v1) = v12[1];
        *v13 &= v1;
        *(_QWORD *)(a1 + 24) += 10LL;
        break;
      case -107:
        if ( (*(_QWORD *)(a1 + 48) & 2LL) != 0 )
        {
          BYTE1(v1) = *(_WORD *)v4;
          LOBYTE(v1) = HIBYTE(*(_WORD *)v4);
          v1 = (unsigned __int16)v1;
          *(_QWORD *)(a1 + 24) = (unsigned __int16)v1;
        }
        else
        {
          *(_QWORD *)(a1 + 24) += 3LL;
        }
        break;
      case -106:
        *(_BYTE *)(a1 + 8LL * *v4) -= v4[1];
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -105:
        *(_QWORD *)(a1 + 8LL * *v4) <<= v4[1];
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -104:
        v15 = (__int64 *)(a1 + 8LL * v4[1]);
        v1 = *v15;
        v16 = *(_QWORD *)(a1 + 48) & 0xFFFFFFFFFFFFFFFCLL;
        LOBYTE(v16) = (2 * (*(_QWORD *)(a1 + 8LL * *v4) < *v15)) | (*(_QWORD *)(a1 + 8LL * *v4) == *v15) | v16;
        *(_QWORD *)(a1 + 48) = v16;
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -103:
        v17 = *v4;
        v18 = v4 + 1;
        v19 = 8LL * v17;
        v20 = (__int64 *)(a1 + v19);
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18++;
        v19 <<= 8;
        LOBYTE(v19) = *v18;
        v1 = v19 << 8;
        LOBYTE(v1) = v18[1];
        *v20 = v1;
        *(_QWORD *)(a1 + 24) += 10LL;
        break;
      case -102:
        v1 = 8LL * v4[1];
        *(_QWORD *)(a1 + 8LL * *v4) = __ROL8__(*(_QWORD *)(a1 + 8LL * *v4), *(_BYTE *)(a1 + v1));
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -101:
        v1 = 8LL * *v4;
        *(_BYTE *)(a1 + v1) = ~*(_BYTE *)(a1 + v1);
        *(_QWORD *)(a1 + 24) += 2LL;
        break;
      case -100:
        v1 = 8LL * v4[1];
        *(_BYTE *)(a1 + 8LL * *v4) ^= *(_BYTE *)(a1 + v1);
        *(_QWORD *)(a1 + 24) += 3LL;
        break;
      case -85:
        *(_QWORD *)(a1 + 56) -= 2LL;
        **(_WORD **)(a1 + 56) = *(_WORD *)(a1 + 24) + 3;
        BYTE1(v1) = *(_WORD *)v4;
        LOBYTE(v1) = HIBYTE(*(_WORD *)v4);
        v1 = (unsigned __int16)v1;
        *(_QWORD *)(a1 + 24) = (unsigned __int16)v1;
        break;
      case -70:
        v1 = **(unsigned __int16 **)(a1 + 56);
        *(_QWORD *)(a1 + 56) += 2LL;
        *(_QWORD *)(a1 + 24) = v1;
        break;
      default:
        *(_QWORD *)(a1 + 16) = 0;
        return result;
    }
  }
  return result;
}
// 1C15: variable 'v1' is possibly undefined

//----- (0000000000001DF0) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v6; // rbp
  __int64 i; // rbx

  init_proc();
  v6 = &off_3DC0 - funcs_1E31;
  if ( v6 != 0 )
  {
    for ( i = 0; i != v6; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))funcs_1E31[i])(a1, a2, a3);
  }
}
// 1320: using guessed type __int64 __fastcall sub_1320(_QWORD, _QWORD, _QWORD);
// 3DB8: using guessed type __int64 (__fastcall *funcs_1E31[2])();
// 3DC0: using guessed type __int64 (__fastcall *off_3DC0)();

//----- (0000000000001E54) ----------------------------------------------------
// Alternative name is '_fini'
void term_proc()
{
  ;
}

// nfuncs=53 queued=15 decompiled=15 lumina nreq=0 worse=0 better=0
// ALL OK, 15 function(s) have been successfully decompiled
