/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

// double __stdcall rtcCos(_DWORD, _DWORD); weak
// double __stdcall rtcTan(_DWORD, _DWORD); weak
// int __fastcall __vbaVarMove(_DWORD, _DWORD); weak
// int __thiscall __vbaFreeVar(_DWORD); weak
// int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaHresultCheckObj(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaObjSet(_DWORD, _DWORD); weak
// int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaStrCmp(_DWORD, _DWORD); weak
// int __stdcall __vbaVarTstEq(_DWORD, _DWORD); weak
// int __stdcall __vbaVarMul(_DWORD, _DWORD); weak
// int __stdcall rtcHexVarFromVar(_DWORD, _DWORD); weak
// double __stdcall __vbaR8Var(_DWORD); weak
// int __fastcall __vbaVarDup(_DWORD, _DWORD); weak
// int __thiscall __vbaFreeStr(_DWORD); weak
// int __thiscall __vbaFreeObj(_DWORD); weak
// void __fastcall __noreturn _vbaFPException(_DWORD, _DWORD, _DWORD); weak
int __cdecl sub_401A0C(int a1);
int __stdcall sub_401A19(int a1);
int __cdecl sub_4021B0(int a1);
// int __userpurge sub_4028A1@<eax>(int a1@<ebp>, int a2);
int __stdcall sub_4028D0(int a1);

//-------------------------------------------------------------------------
// Data declarations

int dword_4010B8[4] = { 524295, 4204493, 4204652, 4204504 }; // weak
int dword_4010C8[3] = { 524293, 4204960, 0 }; // weak
int dword_401BE4[5] = { 866995937, 298804889, -1442837321, -1814863872, 0 }; // weak
int dword_401BF8[2] = { 0, 0 }; // weak
_UNKNOWN loc_4029C4; // weak


//----- (00401A0C) --------------------------------------------------------
int __cdecl sub_401A0C(int a1)
{
  return sub_4021B0(a1 - 55);
}

//----- (00401A19) --------------------------------------------------------
int __stdcall sub_401A19(int a1)
{
  return sub_4028D0(a1 - 59);
}

//----- (004021B0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __cdecl sub_4021B0(int a1)
{
  int v1; // eax
  int v2; // eax
  int v3; // edi
  int v4; // eax
  int v5; // edi
  int v6; // eax
  unsigned __int64 v7; // st7
  int v8; // eax
  _DWORD *v9; // eax
  int v10; // ecx
  int v11; // eax
  int v12; // eax
  unsigned __int64 v13; // st7
  double v14; // st7
  char v15; // fps
  int v16; // eax
  int v17; // eax
  int v18; // eax
  int v19; // eax
  int v20; // eax
  int v21; // eax
  __int16 v22; // bx
  int v24; // [esp+7Ch] [ebp-208h] BYREF
  _DWORD *v25; // [esp+9Ch] [ebp-1E8h]
  double v26; // [esp+A0h] [ebp-1E4h]
  _DWORD v27[2]; // [esp+C8h] [ebp-1BCh] BYREF
  const wchar_t *v28; // [esp+D0h] [ebp-1B4h]
  _DWORD v29[2]; // [esp+D8h] [ebp-1ACh] BYREF
  double v30; // [esp+E0h] [ebp-1A4h]
  int v31; // [esp+E8h] [ebp-19Ch]
  _DWORD v32[4]; // [esp+F8h] [ebp-18Ch] BYREF
  _DWORD v33[4]; // [esp+108h] [ebp-17Ch] BYREF
  _DWORD v34[4]; // [esp+118h] [ebp-16Ch] BYREF
  _DWORD v35[4]; // [esp+128h] [ebp-15Ch] BYREF
  _DWORD v36[4]; // [esp+138h] [ebp-14Ch] BYREF
  _DWORD v37[4]; // [esp+148h] [ebp-13Ch] BYREF
  _DWORD v38[4]; // [esp+158h] [ebp-12Ch] BYREF
  _DWORD v39[4]; // [esp+168h] [ebp-11Ch] BYREF
  _DWORD v40[4]; // [esp+178h] [ebp-10Ch] BYREF
  _DWORD v41[4]; // [esp+188h] [ebp-FCh] BYREF
  _DWORD v42[4]; // [esp+198h] [ebp-ECh] BYREF
  _DWORD v43[2]; // [esp+1A8h] [ebp-DCh] BYREF
  int v44; // [esp+1B0h] [ebp-D4h]
  _DWORD v45[2]; // [esp+1B8h] [ebp-CCh] BYREF
  int v46; // [esp+1C0h] [ebp-C4h]
  _DWORD v47[4]; // [esp+1C8h] [ebp-BCh] BYREF
  _DWORD v48[4]; // [esp+1D8h] [ebp-ACh] BYREF
  int v49; // [esp+1E8h] [ebp-9Ch] BYREF
  int v50; // [esp+1ECh] [ebp-98h] BYREF
  _DWORD v51[4]; // [esp+1F0h] [ebp-94h] BYREF
  _DWORD v52[4]; // [esp+200h] [ebp-84h] BYREF
  _DWORD v53[4]; // [esp+210h] [ebp-74h] BYREF
  _DWORD v54[4]; // [esp+220h] [ebp-64h] BYREF
  _DWORD v55[4]; // [esp+230h] [ebp-54h] BYREF
  _DWORD v56[4]; // [esp+240h] [ebp-44h] BYREF
  _DWORD v57[4]; // [esp+250h] [ebp-34h] BYREF
  _DWORD *v58; // [esp+260h] [ebp-24h] BYREF
  int (__userpurge *v59)@<eax>(int@<ebp>, int); // [esp+264h] [ebp-20h]
  int *v60; // [esp+278h] [ebp-Ch]
  int *v61; // [esp+27Ch] [ebp-8h]
  int v62; // [esp+280h] [ebp-4h]
  int v63; // [esp+28Ch] [ebp+8h]

  v60 = &v24;
  v61 = dword_4010B8;
  v1 = a1;
  v62 = a1 & 1;
  LOBYTE(v1) = a1 & 0xFE;
  v63 = v1;
  (*(void (__cdecl **)(int))(*(_DWORD *)v1 + 4))(v1);
  v57[0] = 0;
  v56[0] = 0;
  v55[0] = 0;
  v54[0] = 0;
  v53[0] = 0;
  v52[0] = 0;
  v51[0] = 0;
  v50 = 0;
  v49 = 0;
  v47[0] = 0;
  v45[0] = 0;
  v43[0] = 0;
  v42[0] = 0;
  v41[0] = 0;
  v40[0] = 0;
  v39[0] = 0;
  v38[0] = 0;
  v37[0] = 0;
  v36[0] = 0;
  v35[0] = 0;
  v34[0] = 0;
  v33[0] = 0;
  v32[0] = 0;
  v31 = 0;
  v27[0] = 0;
  __vbaVarMove(v55, v29);
  __vbaVarMove(v54, v29);
  __vbaVarMove(v51, v29);
  __vbaVarMove(&v58, v29);
  __vbaVarMove(v56, v29);
  __vbaVarMove(v53, v29);
  v48[2] = 2160;
  v48[0] = 2;
  rtcHexVarFromVar(v47, v48);
  __vbaVarMove(v57, v47);
  __vbaFreeVar(v48);
  v30 = rtcCos(0, 1084284928);
  v29[0] = 5;
  __vbaVarMove(v52, v29);
  v2 = (*(int (__stdcall **)(int))(*(_DWORD *)v63 + 772))(v63);
  v3 = __vbaObjSet(&v49, v2);
  v4 = (*(int (__stdcall **)(int, int *))(*(_DWORD *)v3 + 160))(v3, &v50);
  __asm { fnclex }
  if ( v4 < 0 )
    __vbaHresultCheckObj(v4, v3, dword_401BE4, 160);
  v5 = -(__vbaStrCmp(dword_401BF8, v50) == 0);
  __vbaFreeStr(&v50);
  __vbaFreeObj(&v49);
  if ( (_WORD)v5 != 0 )
  {
    v44 = -2147352572;
    v46 = -2147352572;
    v43[0] = 10;
    v45[0] = 10;
    v28 = L"Crack me";
    v27[0] = 8;
    __vbaVarDup(v47, v27);
    LODWORD(v30) = L"Type the serial in the textbox.";
    v29[0] = 8;
    __vbaVarDup(v48, v29);
    rtcMsgBox(v48, 0, v47, v45, v43);
    __vbaFreeVarList(4, v48, v47, v45, v43);
  }
  else
  {
    v58 = v52;
    v6 = __vbaVarMul(v47, v55);
    *(double *)&v7 = __vbaR8Var(v6);
    v26 = rtcTan(v7, HIDWORD(v7));
    v8 = (*(int (__stdcall **)(int))(*(_DWORD *)v63 + 772))(v63);
    v9 = (_DWORD *)__vbaObjSet(&v49, v8);
    v10 = *v9;
    v25 = v9;
    v11 = (*(int (__stdcall **)(_DWORD *, int *))(v10 + 160))(v9, &v50);
    __asm { fnclex }
    if ( v11 < 0 )
      __vbaHresultCheckObj(v11, v25, dword_401BE4, 160);
    v32[2] = v50;
    v58 = v57;
    v50 = 0;
    v32[0] = 32776;
    v12 = __vbaVarMul(v48, v52);
    *(double *)&v13 = __vbaR8Var(v12);
    v14 = rtcTan(v13, HIDWORD(v13));
    v59 = (int (__userpurge *)@<eax>(int@<ebp>, int))v29;
    v30 = v14 * v26;
    if ( (v15 & 0xD) != 0 )
      _vbaFPException(v54, v45, v63);
    v29[0] = 5;
    v58 = v55;
    v16 = __vbaVarMul(v45, v54);
    v58 = (_DWORD *)__vbaVarMul(v43, v16);
    v57[3] = v54;
    v17 = __vbaVarMul(v42, v51);
    v58 = (_DWORD *)__vbaVarMul(v41, v17);
    v57[3] = &v58;
    v18 = __vbaVarMul(v40, v56);
    v58 = (_DWORD *)__vbaVarMul(v39, v18);
    v57[3] = v56;
    v19 = __vbaVarMul(v38, v53);
    v58 = (_DWORD *)__vbaVarMul(v37, v19);
    v57[3] = v53;
    v20 = __vbaVarMul(v36, v55);
    v21 = __vbaVarMul(v35, v20);
    __vbaVarMove(v34, v21);
    rtcHexVarFromVar(v33, v34);
    v22 = __vbaVarTstEq(v33, v32);
    __vbaFreeObj(&v49);
    __vbaFreeVarList(3, v34, v32, v33, v59);
    v44 = -2147352572;
    v46 = -2147352572;
    v43[0] = 10;
    v45[0] = 10;
    v28 = L"Crack me";
    v27[0] = 8;
    __vbaVarDup(v47, v27);
    if ( v22 != 0 )
      LODWORD(v30) = L"Congratulation! You did it.";
    else
      LODWORD(v30) = L"Ha! Ha! Ha! Try it again.";
    v29[0] = 8;
    __vbaVarDup(v48, v29);
    rtcMsgBox(v48, 0, v47, v45, v43);
    __vbaFreeVarList(4, v48, v47, v45, v43);
  }
  v62 = 0;
  v59 = sub_4028A1;
  __vbaFreeVar(&v58);
  __vbaFreeVar(v57);
  __vbaFreeVar(v56);
  __vbaFreeVar(v55);
  __vbaFreeVar(v54);
  __vbaFreeVar(v53);
  __vbaFreeVar(v52);
  return __vbaFreeVar(v51);
}
// 4021EF: bad sp value at call
// 4022AE: bad sp value at call
// 4022C5: bad sp value at call
// 4022E3: bad sp value at call
// 4022FE: bad sp value at call
// 402319: bad sp value at call
// 402334: bad sp value at call
// 402354: bad sp value at call
// 402363: bad sp value at call
// 40236B: bad sp value at call
// 402399: bad sp value at call
// 4023AF: bad sp value at call
// 4023C1: bad sp value at call
// 402400: bad sp value at call
// 40240C: bad sp value at call
// 402464: bad sp value at call
// 402482: bad sp value at call
// 4024A1: bad sp value at call
// 4024C5: bad sp value at call
// 4024E8: bad sp value at call
// 402517: bad sp value at call
// 40252D: bad sp value at call
// 40257F: bad sp value at call
// 4025CA: bad sp value at call
// 4025D4: bad sp value at call
// 4025E9: bad sp value at call
// 4025F3: bad sp value at call
// 402605: bad sp value at call
// 40260F: bad sp value at call
// 402621: bad sp value at call
// 40262B: bad sp value at call
// 40263D: bad sp value at call
// 402647: bad sp value at call
// 402651: bad sp value at call
// 402661: bad sp value at call
// 402675: bad sp value at call
// 402683: bad sp value at call
// 4026A6: bad sp value at call
// 4026F3: bad sp value at call
// 402715: bad sp value at call
// 402738: bad sp value at call
// 4027C5: bad sp value at call
// 402875: bad sp value at call
// 40287A: bad sp value at call
// 40287F: bad sp value at call
// 402884: bad sp value at call
// 402889: bad sp value at call
// 40288E: bad sp value at call
// 402896: bad sp value at call
// 40289E: bad sp value at call
// 4028C0: bad sp value at call
// 401000: using guessed type double __stdcall rtcCos(_DWORD, _DWORD);
// 401004: using guessed type double __stdcall rtcTan(_DWORD, _DWORD);
// 401010: using guessed type int __fastcall __vbaVarMove(_DWORD, _DWORD);
// 401014: using guessed type int __thiscall __vbaFreeVar(_DWORD);
// 401018: using guessed type int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401024: using guessed type int __stdcall __vbaHresultCheckObj(_DWORD, _DWORD, _DWORD, _DWORD);
// 40102C: using guessed type int __stdcall __vbaObjSet(_DWORD, _DWORD);
// 401030: using guessed type int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401048: using guessed type int __stdcall __vbaStrCmp(_DWORD, _DWORD);
// 40104C: using guessed type int __stdcall __vbaVarTstEq(_DWORD, _DWORD);
// 401060: using guessed type int __stdcall __vbaVarMul(_DWORD, _DWORD);
// 401080: using guessed type int __stdcall rtcHexVarFromVar(_DWORD, _DWORD);
// 401088: using guessed type double __stdcall __vbaR8Var(_DWORD);
// 401094: using guessed type int __fastcall __vbaVarDup(_DWORD, _DWORD);
// 4010A8: using guessed type int __thiscall __vbaFreeStr(_DWORD);
// 4010AC: using guessed type int __thiscall __vbaFreeObj(_DWORD);
// 4010B8: using guessed type int dword_4010B8[4];
// 4010EC: using guessed type void __fastcall __noreturn _vbaFPException(_DWORD, _DWORD, _DWORD);
// 401BE4: using guessed type int dword_401BE4[5];
// 401BF8: using guessed type int dword_401BF8[2];
// 401C04: using guessed type wchar_t aTypeTheSerialI[32];
// 401C48: using guessed type wchar_t aCrackMe[9];
// 401C60: using guessed type wchar_t aCongratulation[28];
// 401C9C: using guessed type wchar_t aHaHaHaTryItAga[26];

//----- (004028A1) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __userpurge sub_4028A1@<eax>(int a1@<ebp>, int a2)
{
  (*(void (__cdecl **)(_DWORD))(**(_DWORD **)(a1 + 8) + 8))(*(_DWORD *)(a1 + 8));
  return *(_DWORD *)(a1 - 4);
}
// 4028BD: positive sp value C has been found
// 4028A1: could not find valid save-restore pair for ebx
// 4028A1: could not find valid save-restore pair for edi
// 4028A1: could not find valid save-restore pair for esi

//----- (004028D0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __stdcall sub_4028D0(int a1)
{
  int v1; // eax
  _DWORD v3[13]; // [esp-34h] [ebp-A8h] BYREF
  _DWORD v4[2]; // [esp+0h] [ebp-74h] BYREF
  const wchar_t *v5; // [esp+8h] [ebp-6Ch]
  int v6; // [esp+Ch] [ebp-68h]
  _DWORD v7[2]; // [esp+10h] [ebp-64h] BYREF
  const wchar_t *v8; // [esp+18h] [ebp-5Ch]
  int v9; // [esp+1Ch] [ebp-58h]
  _DWORD v10[2]; // [esp+20h] [ebp-54h] BYREF
  int v11; // [esp+28h] [ebp-4Ch]
  int v12; // [esp+2Ch] [ebp-48h]
  _DWORD v13[3]; // [esp+30h] [ebp-44h] BYREF
  _DWORD *v14; // [esp+3Ch] [ebp-38h]
  _DWORD v15[4]; // [esp+40h] [ebp-34h] BYREF
  _DWORD v16[8]; // [esp+50h] [ebp-24h] BYREF
  int v17; // [esp+70h] [ebp-4h]
  int v18; // [esp+7Ch] [ebp+8h]

  v16[6] = v3;
  v16[7] = dword_4010C8;
  v1 = a1;
  v17 = a1 & 1;
  LOBYTE(v1) = a1 & 0xFE;
  v18 = v1;
  (*(void (__stdcall **)(int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, const wchar_t *, int, _DWORD, _DWORD, const wchar_t *, int, _DWORD, _DWORD, int, int, _DWORD, _DWORD, _DWORD, _DWORD *, _DWORD))(*(_DWORD *)v1 + 4))(
    v1,
    v3[0],
    v3[1],
    v3[2],
    v3[3],
    v3[4],
    v3[5],
    v3[6],
    v3[7],
    v3[8],
    v3[9],
    v3[10],
    v3[11],
    v3[12],
    v4[0],
    v4[1],
    v5,
    v6,
    v7[0],
    v7[1],
    v8,
    v9,
    v10[0],
    v10[1],
    v11,
    v12,
    v13[0],
    v13[1],
    v13[2],
    v14,
    v15[0]);
  v11 = -2147352572;
  v16[0] = 0;
  v10[0] = 10;
  v5 = L"Crack me";
  v4[0] = 8;
  __vbaVarDup(v15, v4);
  v8 = L"Find the real serial and be the real cracker.                                                                    "
        "                     This is made by:                                                                           "
        "                                                                                                                "
        "                                                                                      - [A]bu ";
  v7[0] = 8;
  __vbaVarDup(v16, v7);
  v15[0] = v10;
  v14 = v13;
  ((void (__stdcall *)(_DWORD *, _DWORD, _DWORD *))rtcMsgBox)(v16, 0, v15);
  v15[0] = v10;
  v14 = v13;
  ((void (__cdecl *)(int, _DWORD *, _DWORD *))__vbaFreeVarList)(4, v16, v15);
  v17 = 0;
  v16[1] = &loc_4029C4;
  (*(void (__stdcall **)(int))(*(_DWORD *)v18 + 8))(v18);
  return v17;
}
// 402957: bad sp value at call
// 402969: bad sp value at call
// 401018: using guessed type int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401030: using guessed type int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401094: using guessed type int __fastcall __vbaVarDup(_DWORD, _DWORD);
// 4010C8: using guessed type int dword_4010C8[3];
// 401C48: using guessed type wchar_t aCrackMe[9];
// 401D14: using guessed type wchar_t aFindTheRealSer[432];

// nfuncs=49 queued=5 decompiled=5 lumina nreq=0 worse=0 better=0
// ALL OK, 5 function(s) have been successfully decompiled
