/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn start(); // weak
__int64 sub_2015C0(void); // weak
__int64 __fastcall sub_202650(__int64 a1, unsigned __int64 a2, __int64 a3);
// Display *XOpenDisplay(const char *);
// int XQueryPointer(Display *, Window, Window *, Window *, int *, int *, int *, int *, unsigned int *);
// __int64 __fastcall XRRQueryExtension(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall XRRQueryVersion(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall XRRGetMonitors(_QWORD, _QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall XRRFreeMonitors(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); weak
// int XCloseDisplay(Display *);
__int64 __fastcall sub_202A00(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD); // weak

//-------------------------------------------------------------------------
// Data declarations

char aSerial[9] = "Serial: "; // weak
char aCroakCorrectSe[24] = "Croak! Correct serial.\n"; // weak
char aSimpleFrogName[19] = "Simple Frog\nName: "; // weak
char aWrongSerial[15] = "Wrong serial.\n"; // weak
__int128 xmmword_200590 = 0x9896800000000000000000LL; // weak
__int64 qword_204B80; // weak
__int16 word_204B90[]; // weak
__int16 word_204B92[]; // weak
__int16 word_204B94[]; // weak
char byte_204B96[]; // weak
char byte_204B97[]; // weak
char byte_204B98[327672]; // weak


//----- (00000000002015A0) ----------------------------------------------------
void __noreturn start()
{
  sys_exit_group(sub_2015C0());
  BUG();
}
// 2015A0: using guessed type void __noreturn start();
// 2015C0: using guessed type __int64 sub_2015C0(void);

//----- (00000000002015C0) ----------------------------------------------------
__int64 sub_2015C0()
{
  unsigned __int64 v0; // r8
  unsigned int v1; // edi
  __int64 v2; // rax
  __int64 v3; // r8
  bool v4; // r9
  bool v5; // cl
  __int64 v6; // rcx
  char *v7; // rsi
  size_t v8; // rdx
  __int64 v9; // rax
  __int64 v10; // r8
  unsigned int v11; // r14d
  Display *v12; // rax
  unsigned __int64 v13; // rbp
  unsigned __int64 v14; // r12
  unsigned __int64 v15; // r13
  Display *v16; // r14
  unsigned __int64 v17; // rbp
  __int64 v18; // rbx
  __int64 v19; // r13
  int v20; // r8d
  unsigned __int64 v21; // r11
  __int64 v22; // rcx
  unsigned __int64 v23; // rcx
  __int64 v24; // rcx
  int v25; // ecx
  unsigned __int64 v26; // rbx
  unsigned __int64 v27; // rax
  unsigned __int64 v28; // rcx
  __int64 v29; // rax
  __int64 v30; // rdx
  __int64 v31; // rsi
  __int64 v32; // rcx
  __int64 v33; // r15
  Screen *screens; // rcx
  __int64 v36; // rax
  unsigned __int64 v37; // rax
  bool v38; // zf
  __int64 v39; // rsi
  unsigned __int64 v40; // rcx
  unsigned __int8 *v41; // rdx
  unsigned __int8 i; // r8
  unsigned __int64 v43; // rcx
  unsigned __int64 v44; // r9
  __int64 v45; // rcx
  char v46; // dl
  __int64 v47; // rdx
  unsigned __int64 v48; // rdi
  __m128i si128; // xmm1
  __int64 v50; // rdx
  char v51; // di
  int v52; // edi
  __int64 v53; // rdx
  __time_t v54; // rcx
  __time_t v55; // r10
  unsigned __int64 v56; // rbx
  __int64 v57; // rcx
  __int64 v58; // rax
  __int64 v59; // rdx
  __int64 v60; // rdi
  unsigned __int64 v61; // r9
  unsigned __int64 v62; // r10
  unsigned __int64 v63; // r9
  __int64 v64; // r10
  __int64 v65; // r14
  __int64 v66; // r14
  unsigned __int64 v67; // rax
  unsigned __int64 v68; // rbx
  unsigned __int64 v69; // r8
  __int64 j; // r9
  unsigned __int64 v71; // r11
  unsigned __int64 v72; // rdi
  __int64 v73; // r12
  unsigned __int64 v74; // rcx
  unsigned __int64 v75; // r14
  unsigned __int64 v76; // r13
  unsigned __int64 v77; // rsi
  unsigned __int64 v78; // rbx
  unsigned __int64 v79; // rbp
  unsigned __int64 v80; // rdi
  unsigned __int64 v81; // r8
  unsigned int v82; // edi
  __int64 v83; // rax
  __int64 v84; // r8
  bool v85; // r9
  bool v86; // cl
  __int64 v87; // rcx
  char *p_tp; // rsi
  size_t v89; // rdx
  __int64 v90; // rax
  __int64 v91; // r8
  __int64 v92; // rax
  int v93; // eax
  __int64 k; // rsi
  int v95; // r8d
  char v96; // r9
  int v97; // edi
  int v98; // edi
  unsigned __int8 v99; // r8
  int v100; // r8d
  unsigned __int8 v101; // r9
  bool v102; // bp
  __int64 v103; // rsi
  __int64 v104; // rcx
  char *v105; // rdx
  int v106; // eax
  unsigned __int64 v107; // r15
  unsigned __int8 v108; // r10
  unsigned __int8 v109; // r11
  unsigned __int8 v110; // bl
  __int64 v111; // rdi
  unsigned __int64 v112; // rsi
  __m128i v113; // xmm0
  __m128i v114; // xmm1
  int v115; // ecx
  _BOOL8 v116; // rdx
  unsigned __int64 v117; // r8
  unsigned int v118; // edi
  __int64 v119; // rax
  __int64 v120; // r8
  bool v121; // r9
  bool v122; // cl
  __int64 v123; // rcx
  unsigned __int64 v124; // r8
  unsigned int v125; // edi
  __int64 v126; // rax
  __int64 v127; // r8
  bool v128; // r9
  bool v129; // cl
  __int64 v130; // rcx
  unsigned __int8 v131; // [rsp+Fh] [rbp-7A9h]
  __int64 v132; // [rsp+10h] [rbp-7A8h]
  int v133; // [rsp+10h] [rbp-7A8h]
  unsigned __int64 v134; // [rsp+10h] [rbp-7A8h]
  unsigned __int64 v135; // [rsp+10h] [rbp-7A8h]
  int v136; // [rsp+18h] [rbp-7A0h]
  unsigned __int64 v137; // [rsp+18h] [rbp-7A0h]
  unsigned int v138; // [rsp+24h] [rbp-794h] BYREF
  __int64 v139; // [rsp+28h] [rbp-790h] BYREF
  Window v140[2]; // [rsp+30h] [rbp-788h] BYREF
  __m128i v141; // [rsp+40h] [rbp-778h]
  int v142; // [rsp+58h] [rbp-760h] BYREF
  int v143; // [rsp+5Ch] [rbp-75Ch] BYREF
  struct timespec rmtp; // [rsp+60h] [rbp-758h] BYREF
  __m128i v145; // [rsp+70h] [rbp-748h] BYREF
  __time_t tv_sec; // [rsp+80h] [rbp-738h]
  Window root; // [rsp+88h] [rbp-730h]
  struct timespec v148; // [rsp+90h] [rbp-728h] BYREF
  struct timespec rqtp; // [rsp+A0h] [rbp-718h] BYREF
  struct timespec buf[48]; // [rsp+F0h] [rbp-6C8h] BYREF
  unsigned __int8 v151; // [rsp+3F0h] [rbp-3C8h] BYREF
  _BYTE v152[143]; // [rsp+3F1h] [rbp-3C7h] BYREF
  struct timespec tp; // [rsp+480h] [rbp-338h] BYREF

  v0 = 0;
  v1 = 1;
  do
  {
    v2 = sys_write(v1, &aSimpleFrogName[v0], 18 - v0);
    v5 = v2 <= 0;
    if ( v2 == -4 )
      v5 = v4;
    if ( v5 )
      return 1;
    v6 = 0;
    if ( v2 > 0 )
      v6 = v2;
    v0 = v6 + v3;
  }
  while ( v0 < 0x12 );
  v7 = (char *)buf;
  v8 = 1;
  while ( 1 )
  {
    do
    {
      LOBYTE(buf[0].tv_sec) = 0;
      v9 = sys_read(0, v7, v8);
    }
    while ( v9 == -4 );
    if ( v9 == 0 )
      break;
    if ( v9 < 0 )
      return 1;
    if ( LOBYTE(buf[0].tv_sec) != 13 )
    {
      if ( LOBYTE(buf[0].tv_sec) == 10 )
        break;
      if ( (unsigned __int64)(v10 + 1) <= 0x80 )
        v152[v10 - 1] = buf[0].tv_sec;
    }
  }
  v152[v10 - 1] = 0;
  v11 = 1;
  if ( v151 != 0 )
  {
    v131 = v151;
    LODWORD(v132) = 0;
    v12 = XOpenDisplay(nullptr);
    if ( v12 != nullptr )
    {
      v13 = 0xBF58476D1CE4E5B9LL;
      v14 = 0x9E3779B97F4A7C15LL;
      v15 = 0x94D049BB133111EBLL;
      v16 = v12;
      root = v12->screens[(__int64)v12->default_screen].root;
      rqtp = (struct timespec)_mm_loadu_si128((const __m128i *)&xmmword_200590);
      if ( sys_clock_gettime(1, buf) < 0 )
      {
        v26 = 0xEE18D70B34696718LL;
        v136 = 0;
      }
      else
      {
        tp = (struct timespec)_mm_loadu_si128((const __m128i *)buf);
        v17 = 0x53494D504C454652LL;
        v132 = 0;
        v136 = 0;
        v18 = 0;
        v19 = 0;
        while ( 1 )
        {
          v140[0] = 0;
          v148.tv_sec = 0;
          v139 = 0;
          v143 = 0;
          v142 = 0;
          v138 = 0;
          XQueryPointer(v16, root, v140, (Window *)&v148, (int *)&v139 + 1, (int *)&v139, &v143, &v142, &v138);
          if ( sys_clock_gettime(1, &tp) < 0 )
            break;
          v21 = __ROL8__(
                  1000000000 * (tp.tv_sec - buf[0].tv_sec) + tp.tv_nsec - buf[0].tv_nsec,
                  11 * (unsigned __int8)v18 + 5)
              ^ v139
              ^ __ROL8__(v19 ^ v139, 7 * (unsigned __int8)v18 + 3)
              ^ ((unsigned __int64)v138 << 17)
              ^ (0x9E3779B97F4A7C15LL * (unsigned int)v18);
          v22 = __ROL8__(v17, 19);
          v23 = 0x94D049BB133111EBLL
              * ((0xBF58476D1CE4E5B9LL * ((v21 + v22) ^ ((v21 + v22) >> 30)))
               ^ ((0xBF58476D1CE4E5B9LL * ((v21 + v22) ^ ((v21 + v22) >> 30))) >> 27));
          v17 = 0xD6E8FEB86659FD93LL * __ROL8__(v23 ^ v17 ^ (v23 >> 31), 23);
          v24 = v132;
          if ( v20 != 0 )
            v24 = HIDWORD(v139);
          v132 = v24;
          v25 = v136;
          if ( v20 != 0 )
            v25 = v139;
          v136 = v25;
          if ( v20 != 0 )
            v19 = v139;
          v18 = (unsigned int)(v18 + 1);
          if ( 1000000000 * (tp.tv_sec - buf[0].tv_sec) + tp.tv_nsec - buf[0].tv_nsec > 1499999999 )
            break;
          rmtp = 0;
          if ( sys_nanosleep(&rqtp, &rmtp) == -4 )
          {
            while ( sys_nanosleep(&rmtp, &rmtp) == -4 )
              ;
          }
        }
        v27 = v17 ^ v19 ^ (v18 << 32) ^ ((v17 ^ v19 ^ (v18 << 32)) >> 30);
        v13 = 0xBF58476D1CE4E5B9LL;
        v15 = 0x94D049BB133111EBLL;
        v28 = 0x94D049BB133111EBLL * ((0xBF58476D1CE4E5B9LL * v27) ^ ((0xBF58476D1CE4E5B9LL * v27) >> 27));
        v26 = v28 ^ (v28 >> 31);
        v14 = 0x9E3779B97F4A7C15LL;
      }
      if ( sys_clock_gettime(0, &v148) < 0 )
      {
        XCloseDisplay(v16);
        return 1;
      }
      tv_sec = v148.tv_sec;
      LODWORD(buf[0].tv_sec) = 0;
      LODWORD(tp.tv_sec) = 0;
      if ( (unsigned int)XRRQueryExtension(v16, buf, &tp) != 0 )
      {
        LODWORD(rqtp.tv_sec) = 0;
        LODWORD(rmtp.tv_sec) = 0;
        if ( (unsigned int)XRRQueryVersion(v16, &rqtp, &rmtp) != 0
          && (SLODWORD(rqtp.tv_sec) > 1 || LODWORD(rqtp.tv_sec) == 1 && SLODWORD(rmtp.tv_sec) >= 5) )
        {
          LODWORD(v140[0]) = 0;
          v29 = XRRGetMonitors(v16, root, 1, v140);
          if ( v29 != 0 )
          {
            v32 = SLODWORD(v140[0]);
            if ( SLODWORD(v140[0]) > 0 )
            {
              v32 = 56LL * SLODWORD(v140[0]);
              v30 = 0;
              while ( 1 )
              {
                v31 = *(unsigned int *)(v29 + v30 + 20);
                if ( (int)v132 >= (int)v31 )
                {
                  v31 = (unsigned int)(*(_DWORD *)(v29 + v30 + 28) + v31);
                  if ( (int)v132 < (int)v31 )
                  {
                    v31 = *(unsigned int *)(v29 + v30 + 24);
                    if ( v136 >= (int)v31 )
                    {
                      v33 = *(unsigned int *)(v29 + v30 + 28);
                      v31 = (unsigned int)(*(_DWORD *)(v29 + v30 + 32) + v31);
                      if ( v136 < (int)v31 )
                        break;
                    }
                  }
                }
                v30 += 56;
                if ( v32 == v30 )
                  goto LABEL_53;
              }
              v133 = *(_DWORD *)(v29 + v30 + 32);
              XRRFreeMonitors(v29, v31, v30, v32, (unsigned int)v136);
LABEL_55:
              XCloseDisplay(v16);
              v37 = -1;
              do
                v38 = v152[v37++] == 0;
              while ( !v38 );
              v39 = 127;
              if ( v37 < 0x7F )
                v39 = v37;
              v40 = 0x14650FB0739D0383LL;
              v41 = v152;
              for ( i = v131; i != 0; i = *v41++ )
                v40 = 0x100000001B3LL * (i ^ v40);
              v43 = 0x94D049BB133111EBLL
                  * ((0xBF58476D1CE4E5B9LL * (v40 ^ (v40 >> 30))) ^ ((0xBF58476D1CE4E5B9LL * (v40 ^ (v40 >> 30))) >> 27));
              v44 = v43 ^ (v43 >> 31);
              if ( v37 != 0 )
              {
                if ( v37 < 4 )
                {
                  v45 = 0;
LABEL_77:
                  v53 = 127;
                  if ( v37 < 0x7F )
                    v53 = v37;
                  do
                  {
                    *((_BYTE *)&buf[0].tv_sec + v45) = v152[v45 - 1];
                    ++v45;
                  }
                  while ( v53 != v45 );
                  goto LABEL_80;
                }
                if ( v37 >= 0x20 )
                {
                  v45 = v39 & 0x60;
                  v46 = 127;
                  if ( v37 < 0x7F )
                    v46 = v37;
                  v47 = v46 & 0x60;
                  v48 = 0;
                  do
                  {
                    si128 = _mm_load_si128((const __m128i *)&v152[v48 + 15]);
                    buf[v48 / 0x10] = (struct timespec)_mm_load_si128((const __m128i *)&v152[v48 - 1]);
                    buf[v48 / 0x10 + 1] = (struct timespec)si128;
                    v48 += 32LL;
                  }
                  while ( v47 != v48 );
                  if ( v37 == v45 )
                    goto LABEL_80;
                  if ( (v39 & 0x1C) == 0 )
                    goto LABEL_77;
                }
                else
                {
                  v45 = 0;
                }
                v50 = v45;
                v45 = v39 & 0x7C;
                v51 = 127;
                if ( v37 < 0x7F )
                  v51 = v37;
                v52 = v51 & 0x7C;
                do
                {
                  *(_DWORD *)((char *)&buf[0].tv_sec + v50) = *(_DWORD *)&v152[v50 - 1];
                  v50 += 4;
                }
                while ( v52 != v50 );
                if ( v37 != v45 )
                  goto LABEL_77;
              }
LABEL_80:
              *((_BYTE *)&buf[0].tv_sec + v39) = 0;
              *((_BYTE *)&buf[0].tv_sec + v39 + 1) = v26;
              *((_BYTE *)&buf[0].tv_sec + v39 + 2) = BYTE1(v26);
              *((_BYTE *)&buf[0].tv_sec + v39 + 3) = BYTE2(v26);
              *((_BYTE *)&buf[0].tv_sec + v39 + 4) = BYTE3(v26);
              *((_BYTE *)&buf[0].tv_sec + v39 + 5) = BYTE4(v26);
              *((_BYTE *)&buf[0].tv_sec + v39 + 6) = BYTE5(v26);
              *((_BYTE *)&buf[0].tv_sec + v39 + 7) = BYTE6(v26);
              *((_BYTE *)&buf[0].tv_nsec + v39) = HIBYTE(v26);
              v54 = tv_sec;
              *((_BYTE *)&buf[0].tv_nsec + v39 + 1) = tv_sec;
              *((_BYTE *)&buf[0].tv_nsec + v39 + 2) = BYTE1(v54);
              *((_BYTE *)&buf[0].tv_nsec + v39 + 3) = BYTE2(v54);
              *((_BYTE *)&buf[0].tv_nsec + v39 + 4) = BYTE3(v54);
              *((_BYTE *)&buf[0].tv_nsec + v39 + 5) = BYTE4(v54);
              *((_BYTE *)&buf[0].tv_nsec + v39 + 6) = BYTE5(v54);
              *((_BYTE *)&buf[0].tv_nsec + v39 + 7) = BYTE6(v54);
              v55 = v54;
              *((_BYTE *)&buf[1].tv_sec + v39) = HIBYTE(v54);
              *((_BYTE *)&buf[1].tv_sec + v39 + 1) = v33;
              *((_BYTE *)&buf[1].tv_sec + v39 + 2) = BYTE1(v33);
              *((_BYTE *)&buf[1].tv_sec + v39 + 3) = BYTE2(v33);
              *((_BYTE *)&buf[1].tv_sec + v39 + 4) = BYTE3(v33);
              LODWORD(v54) = v133;
              *((_BYTE *)&buf[1].tv_sec + v39 + 5) = v133;
              *((_BYTE *)&buf[1].tv_sec + v39 + 6) = BYTE1(v133);
              *((_BYTE *)&buf[1].tv_sec + v39 + 7) = BYTE2(v133);
              *((_BYTE *)&buf[1].tv_nsec + v39) = HIBYTE(v133);
              v134 = v26;
              v56 = __ROL8__(v55, 17) ^ (v33 << 32) ^ (unsigned int)v54 ^ v26 ^ __ROL8__(v44, 31);
              v137 = v44;
              v57 = __ROL8__(v134, 29) + __ROL8__(v55, 43) + v44 + 0x53696D706C654672LL;
              v58 = 5;
              v59 = 9;
              v60 = 0;
              do
              {
                v61 = v56 + __ROL8__(v57, v58);
                v62 = (0xD1342543DE82EF95LL * v61) ^ v57;
                v63 = 0x94D049BB133111EBLL
                    * ((0xBF58476D1CE4E5B9LL * (v60 ^ v61 ^ ((v60 ^ v61) >> 30)))
                     ^ ((0xBF58476D1CE4E5B9LL * (v60 ^ v61 ^ ((v60 ^ v61) >> 30))) >> 27));
                v56 = v63 ^ (v63 >> 31);
                v64 = __ROL8__(v62, v59);
                v57 = v64;
                v58 += 7;
                v59 += 11;
                v60 -= 0x61C8864680B583EBLL;
              }
              while ( v58 != 117 );
              *((_BYTE *)&buf[1].tv_nsec + v39 + 1) = v56;
              *((_BYTE *)&buf[1].tv_nsec + v39 + 2) = BYTE1(v56);
              *((_BYTE *)&buf[1].tv_nsec + v39 + 3) = BYTE2(v56);
              *((_BYTE *)&buf[1].tv_nsec + v39 + 4) = ((unsigned int)v63 ^ (unsigned int)(v63 >> 31)) >> 24;
              *((_BYTE *)&buf[1].tv_nsec + v39 + 5) = BYTE4(v56);
              *((_BYTE *)&buf[1].tv_nsec + v39 + 6) = BYTE5(v63);
              *((_BYTE *)&buf[1].tv_nsec + v39 + 7) = BYTE6(v63);
              *((_BYTE *)&buf[2].tv_sec + v39) = HIBYTE(v63);
              *((_BYTE *)&buf[2].tv_sec + v39 + 1) = v64;
              *((_BYTE *)&buf[2].tv_sec + v39 + 2) = BYTE1(v64);
              *((_BYTE *)&buf[2].tv_sec + v39 + 3) = BYTE2(v64);
              *((_BYTE *)&buf[2].tv_sec + v39 + 4) = BYTE3(v64);
              *((_BYTE *)&buf[2].tv_sec + v39 + 5) = BYTE4(v64);
              *((_BYTE *)&buf[2].tv_sec + v39 + 6) = BYTE5(v64);
              *((_BYTE *)&buf[2].tv_sec + v39 + 7) = BYTE6(v64);
              *((_BYTE *)&buf[2].tv_nsec + v39) = HIBYTE(v64);
              v65 = v64;
              sub_202A00(buf, v39 + 41, &rmtp, v64, 0xD1342543DE82EF95LL);
              v66 = __ROL8__(v65, 23);
              v67 = 0x94D049BB133111EBLL
                  * ((0xBF58476D1CE4E5B9LL
                    * (v56
                     ^ v66
                     ^ v137
                     ^ v134
                     ^ tv_sec
                     ^ 0x5341542D46524F47LL
                     ^ ((v56 ^ v66 ^ v137 ^ v134 ^ tv_sec ^ 0x5341542D46524F47LL) >> 30)))
                   ^ ((0xBF58476D1CE4E5B9LL
                     * (v56
                      ^ v66
                      ^ v137
                      ^ v134
                      ^ tv_sec
                      ^ 0x5341542D46524F47LL
                      ^ ((v56 ^ v66 ^ v137 ^ v134 ^ tv_sec ^ 0x5341542D46524F47LL) >> 30))) >> 27));
              v68 = v67 ^ (v67 >> 31);
              sub_202650((__int64)&rmtp, v68, (__int64)buf);
              v135 = v68;
              v69 = v68 ^ 0x3343415553454652LL;
              for ( j = 0; j != 0x8000; ++j )
              {
                v71 = v14;
                v72 = v15
                    * ((v13 * ((v69 + v14) ^ ((v69 + v14) >> 30))) ^ ((v13 * ((v69 + v14) ^ ((v69 + v14) >> 30))) >> 27));
                v73 = 2 * j;
                v74 = (v72 ^ (v72 >> 31)) - 3 * (((v72 ^ (v72 >> 31)) / 3) & 0x7FFFFFFFFFFFFF00LL);
                word_204B90[(unsigned __int64)(5 * v73) / 2] = v74;
                v75 = v15;
                v76 = v15
                    * ((v13 * ((v69 + 0x3C6EF372FE94F82ALL) ^ ((v69 + 0x3C6EF372FE94F82ALL) >> 30)))
                     ^ ((v13 * ((v69 + 0x3C6EF372FE94F82ALL) ^ ((v69 + 0x3C6EF372FE94F82ALL) >> 30))) >> 27));
                byte_204B96[5 * v73] = (v72 & 0x20000000000LL) != 0;
                v77 = (v76 ^ (v76 >> 31)) - 3 * (((v76 ^ (v76 >> 31)) / 3) & 0x7FFFFFFFFFFFFF00LL);
                word_204B92[(unsigned __int64)(5 * v73) / 2] = v77;
                v78 = v13;
                v79 = v75
                    * ((v13 * ((v69 - 0x255992D382208BC1LL) ^ ((v69 - 0x255992D382208BC1LL) >> 30)))
                     ^ ((v13 * ((v69 - 0x255992D382208BC1LL) ^ ((v69 - 0x255992D382208BC1LL) >> 30))) >> 27));
                byte_204B97[5 * v73] = (v76 & 0x20000000000LL) != 0;
                v80 = (v79 ^ (v79 >> 31)) - 3 * (((v79 ^ (v79 >> 31)) / 3) & 0x7FFFFFFFFFFFFF00LL);
                word_204B94[(unsigned __int64)(5 * v73) / 2] = v80;
                byte_204B98[5 * v73] = (v79 & 0x20000000000LL) != 0;
                if ( v77 == v74 )
                {
                  LOWORD(v77) = v74 + 1;
                  if ( v74 >= 0x2FF )
                    LOWORD(v77) = v74 - 767;
                  word_204B92[5 * j] = v77;
                }
                v13 = v78;
                v15 = v75;
                if ( v80 == v74 || (_WORD)v77 == (_WORD)v80 )
                {
                  do
                  {
                    do
                      LOWORD(v80) = (unsigned __int16)(v80 + 17) % 3u;
                    while ( (_WORD)v80 == (_WORD)v74 );
                  }
                  while ( (_WORD)v80 == (_WORD)v77 );
                  word_204B94[5 * j] = v80;
                }
                v69 += 0x78DDE6E5FD29F054LL;
                *((_BYTE *)&word_204B90[5 * j + 3]
                + ((v75 * ((v78 * (v69 ^ (v69 >> 30))) ^ ((v78 * (v69 ^ (v69 >> 30))) >> 27)))
                 ^ ((v75 * ((v78 * (v69 ^ (v69 >> 30))) ^ ((v78 * (v69 ^ (v69 >> 30))) >> 27))) >> 31))
                % 3) = *((_BYTE *)&buf[0].tv_sec
                       + (unsigned __int16)word_204B90[5 * j
                                                     + ((v75
                                                       * ((v78 * (v69 ^ (v69 >> 30)))
                                                        ^ ((v78 * (v69 ^ (v69 >> 30))) >> 27)))
                                                      ^ ((v75
                                                        * ((v78 * (v69 ^ (v69 >> 30)))
                                                         ^ ((v78 * (v69 ^ (v69 >> 30))) >> 27))) >> 31))
                                                     % 3])
                     ^ 1;
                v14 = v71;
              }
              v81 = 0;
              v82 = 1;
              while ( 1 )
              {
                v83 = sys_write(v82, &aSerial[v81], 8 - v81);
                v86 = v83 <= 0;
                if ( v83 == -4 )
                  v86 = v85;
                if ( v86 )
                  return 1;
                v87 = 0;
                if ( v83 > 0 )
                  v87 = v83;
                v81 = v87 + v84;
                if ( v81 >= 8 )
                {
                  p_tp = (char *)&tp;
                  v89 = 1;
                  while ( 1 )
                  {
                    do
                    {
                      LOBYTE(tp.tv_sec) = 0;
                      v90 = sys_read(0, p_tp, v89);
                    }
                    while ( v90 == -4 );
                    if ( v90 == 0 )
                      break;
                    if ( v90 < 0 )
                      return 1;
                    if ( LOBYTE(tp.tv_sec) != 13 )
                    {
                      if ( LOBYTE(tp.tv_sec) == 10 )
                        break;
                      if ( (unsigned __int64)(v91 + 1) <= 0x41 )
                        *((_BYTE *)&rqtp.tv_sec + v91) = tp.tv_sec;
                    }
                  }
                  *((_BYTE *)&rqtp.tv_sec + v91) = 0;
                  v92 = 0;
                  do
                    v38 = *((_BYTE *)&rqtp.tv_sec + v92++) == 0;
                  while ( !v38 );
                  if ( v92 == 65 )
                  {
                    v93 = 1;
                    for ( k = 0; k != 32; ++k )
                    {
                      v97 = *((unsigned __int8 *)&rqtp.tv_sec + 2 * k);
                      if ( (unsigned __int8)(v97 - 48) > 9u )
                      {
                        if ( (unsigned __int8)(v97 - 97) > 5u )
                        {
                          v99 = v97 - 65;
                          v98 = v97 - 55;
                          if ( v99 >= 6u )
                            v98 = -1;
                        }
                        else
                        {
                          v98 = v97 - 87;
                        }
                      }
                      else
                      {
                        v98 = v97 - 48;
                      }
                      v100 = *((unsigned __int8 *)&rqtp.tv_sec + 2 * k + 1);
                      if ( (unsigned __int8)(v100 - 48) <= 9u )
                      {
                        v95 = v100 - 48;
                      }
                      else if ( (unsigned __int8)(v100 - 97) > 5u )
                      {
                        v101 = v100 - 65;
                        v95 = v100 - 55;
                        if ( v101 >= 6u )
                          v95 = -1;
                      }
                      else
                      {
                        v95 = v100 - 87;
                      }
                      v96 = v95 | (16 * v98);
                      if ( (v95 | v98) < 0 )
                      {
                        v96 = 0;
                        v93 = 0;
                      }
                      *((_BYTE *)v140 + k) = v96;
                    }
                    v102 = v93 != 0;
                  }
                  else
                  {
                    *(_OWORD *)v140 = 0;
                    v141 = 0;
                    v102 = false;
                  }
                  sub_202650((__int64)v140, v135, (__int64)&tp);
                  v103 = 0x46524F472D534154LL;
                  v104 = 0;
                  v105 = byte_204B98;
                  v106 = 0;
                  v107 = v78;
                  do
                  {
                    v108 = *((_BYTE *)&tp.tv_sec + *((unsigned __int16 *)v105 - 4)) ^ *(v105 - 2);
                    v109 = *((_BYTE *)&tp.tv_sec + *((unsigned __int16 *)v105 - 3)) ^ *(v105 - 1);
                    v110 = *((_BYTE *)&tp.tv_sec + *((unsigned __int16 *)v105 - 2)) ^ *v105;
                    v106 |= (unsigned __int8)(v110 | v108 | v109) ^ 1;
                    v111 = __ROL8__(
                             (4 * (unsigned int)v110)
                           ^ (2 * (unsigned int)v109)
                           ^ (v108 | (unsigned __int64)(*((unsigned __int16 *)v105 - 4) << 8))
                           | ((unsigned __int64)*((unsigned __int16 *)v105 - 3) << 24)
                           | ((unsigned __int64)*((unsigned __int16 *)v105 - 2) << 40),
                             v104);
                    v112 = v107 * ((v14 + (v103 ^ v111)) ^ ((v14 + (v103 ^ v111)) >> 30));
                    v103 = (v75 * (v112 ^ (v112 >> 27))) ^ ((v75 * (v112 ^ (v112 >> 27))) >> 31);
                    ++v104;
                    v105 += 10;
                  }
                  while ( v104 != 0x8000 );
                  qword_204B80 ^= v103;
                  v113 = _mm_unpacklo_epi16(
                           _mm_unpacklo_epi8(
                             _mm_or_si128(
                               _mm_cvtsi32_si128(
                                 HIDWORD(v140[0]) ^ HIDWORD(rmtp.tv_sec)
                               | HIDWORD(v140[1]) ^ HIDWORD(rmtp.tv_nsec)
                               | v141.m128i_i32[1] ^ v145.m128i_i32[1]
                               | (unsigned int)(v141.m128i_i32[3] ^ v145.m128i_i32[3])),
                               _mm_or_si128(
                                 _mm_or_si128(
                                   _mm_cvtsi32_si128(v141.m128i_i32[2] ^ v145.m128i_i32[2]),
                                   _mm_xor_si128(_mm_load_si128(&v145), v141)),
                                 _mm_or_si128(
                                   (__m128i)(v140[1] ^ rmtp.tv_nsec),
                                   _mm_xor_si128(_mm_load_si128((const __m128i *)&rmtp), *(__m128i *)v140)))),
                             (__m128i)0LL),
                           (__m128i)0LL);
                  v114 = _mm_or_si128(_mm_shuffle_epi32(v113, 238), v113);
                  v115 = _mm_cvtsi128_si32(_mm_or_si128(_mm_shuffle_epi32(v114, 85), v114));
                  v116 = v106 == 0;
                  qword_204B80 ^= (v115 == 0) + 2 * v116;
                  if ( !v116 || !v102 || v115 != 0 )
                  {
                    v124 = 0;
                    v125 = 1;
                    do
                    {
                      v126 = sys_write(v125, &aWrongSerial[v124], 14 - v124);
                      v129 = v126 <= 0;
                      if ( v126 == -4 )
                        v129 = v128;
                      v11 = 1;
                      if ( v129 )
                        break;
                      v130 = 0;
                      if ( v126 > 0 )
                        v130 = v126;
                      v124 = v130 + v127;
                    }
                    while ( v124 < 0xE );
                  }
                  else
                  {
                    v117 = 0;
                    v118 = 1;
                    do
                    {
                      v119 = sys_write(v118, &aCroakCorrectSe[v117], 23 - v117);
                      v122 = v119 <= 0;
                      if ( v119 == -4 )
                        v122 = v121;
                      v11 = 0;
                      if ( v122 )
                        break;
                      v123 = 0;
                      if ( v119 > 0 )
                        v123 = v119;
                      v117 = v123 + v120;
                    }
                    while ( v117 < 0x17 );
                  }
                  return v11;
                }
              }
            }
LABEL_53:
            XRRFreeMonitors(v29, v31, v30, v32, (unsigned int)v136);
          }
        }
      }
      screens = v16->screens;
      v36 = (__int64)v16->default_screen << 7;
      v33 = *(unsigned int *)((char *)&screens->width + v36);
      v133 = *(int *)((char *)&screens->height + v36);
      goto LABEL_55;
    }
  }
  return v11;
}
// 2015F4: variable 'v1' is possibly undefined
// 201602: variable 'v4' is possibly undefined
// 20161B: variable 'v3' is possibly undefined
// 20164C: variable 'v7' is possibly undefined
// 20164C: variable 'v8' is possibly undefined
// 201671: variable 'v10' is possibly undefined
// 20190D: variable 'v20' is possibly undefined
// 201B3E: variable 'v31' is possibly undefined
// 201B3E: variable 'v30' is possibly undefined
// 202254: variable 'v82' is possibly undefined
// 202262: variable 'v85' is possibly undefined
// 20227B: variable 'v84' is possibly undefined
// 2022AC: variable 'p_tp' is possibly undefined
// 2022AC: variable 'v89' is possibly undefined
// 2022D1: variable 'v91' is possibly undefined
// 2025B4: variable 'v118' is possibly undefined
// 2025C2: variable 'v121' is possibly undefined
// 2025DE: variable 'v120' is possibly undefined
// 202614: variable 'v125' is possibly undefined
// 202622: variable 'v128' is possibly undefined
// 202641: variable 'v127' is possibly undefined
// 200590: using guessed type __int128 xmmword_200590;
// 2015C0: using guessed type __int64 sub_2015C0();
// 2029B0: using guessed type __int64 __fastcall XRRQueryExtension(_QWORD, _QWORD, _QWORD);
// 2029C0: using guessed type __int64 __fastcall XRRQueryVersion(_QWORD, _QWORD, _QWORD);
// 2029D0: using guessed type __int64 __fastcall XRRGetMonitors(_QWORD, _QWORD, _QWORD, _QWORD);
// 2029E0: using guessed type __int64 __fastcall XRRFreeMonitors(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 202A00: using guessed type __int64 __fastcall sub_202A00(_QWORD, _QWORD, _QWORD, _QWORD, _QWORD);
// 204B80: using guessed type __int64 qword_204B80;
// 204B90: using guessed type __int16 word_204B90[];
// 204B92: using guessed type __int16 word_204B92[];
// 204B94: using guessed type __int16 word_204B94[];

//----- (0000000000202650) ----------------------------------------------------
__int64 __fastcall sub_202650(__int64 a1, unsigned __int64 a2, __int64 a3)
{
  unsigned __int64 *v3; // rax
  __int64 v4; // rcx
  __int64 v5; // r8
  unsigned __int64 v6; // rdx
  unsigned __int64 v7; // rdx
  __int64 v8; // r9
  __int64 v9; // rax
  __int64 v10; // rdi
  __int64 v11; // r8
  unsigned __int64 v12; // rbx
  __int64 v13; // rdx
  __int64 v14; // rbp
  __int64 v15; // r13
  __int64 v16; // r14
  unsigned __int64 v17; // r13
  __int64 v18; // r11
  __int64 v19; // r13
  unsigned __int64 v20; // r13
  __int64 result; // rax
  __int64 v22; // rdi
  __int64 v23; // r8
  __int64 v24; // r9
  unsigned __int64 v25; // r14
  __int64 v26; // r10
  unsigned __int64 v27; // r15
  __int64 v28; // r12
  __int64 v29; // rdx
  __int64 v30; // rbp
  __int64 v31; // r13
  unsigned __int64 v32; // r13
  unsigned __int64 v33; // rbp
  unsigned __int8 v34; // cf
  _QWORD v35[8]; // [rsp+0h] [rbp-78h] BYREF
  __int64 v36; // [rsp+40h] [rbp-38h]

  v36 = a3;
  v3 = v35;
  v4 = 23;
  v5 = 0;
  do
  {
    v6 = (*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 23) & 0x1F))
        | (unsigned __int64)(*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 12) & 0x1F)) << 8)
        | (*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 1) & 0x1F)) << 16)
        | (*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 22) & 0x1F)) << 24)
        | ((unsigned __int64)*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 11) & 0x1F)) << 32)
        | ((unsigned __int64)*(unsigned __int8 *)(a1 + (v4 & 0x1F)) << 40)
        | ((unsigned __int64)*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 21) & 0x1F)) << 48)
        | ((unsigned __int64)*(unsigned __int8 *)(a1 + (((_BYTE)v4 - 10) & 0x1F)) << 56))
       ^ a2
       ^ v5;
    v7 = 0x94D049BB133111EBLL
       * ((0xBF58476D1CE4E5B9LL * (v6 ^ (v6 >> 30))) ^ ((0xBF58476D1CE4E5B9LL * (v6 ^ (v6 >> 30))) >> 27));
    *v3 = v7 ^ (v7 >> 31);
    v5 -= 0x61C8864680B583EBLL;
    ++v3;
    v4 += 5;
  }
  while ( v4 != 63 );
  v8 = 5;
  v9 = 23;
  v10 = 17;
  v11 = 11;
  v12 = 0;
  do
  {
    v13 = ((_BYTE)v8 - 5) & 7;
    v14 = ((_BYTE)v8 - 4) & 7;
    v15 = v35[v13] + __ROL8__(a2 ^ v35[v14] ^ (v8 - 5), v11);
    v16 = ((_BYTE)v8 - 2) & 7;
    v35[v13] = v15;
    v17 = v35[v16] ^ (0xD1342543DE82EF95LL * v15);
    v35[v16] = v17;
    v18 = v8 & 7;
    v19 = v35[v18] + __ROL8__(v35[v13] + v17, v10);
    v35[v18] = v19;
    v20 = 0xBF58476D1CE4E5B9LL * (v19 ^ v12 ^ v35[v16] ^ ((v19 ^ v12 ^ v35[v16]) >> 30));
    v35[v14] ^= (0x94D049BB133111EBLL * (v20 ^ (v20 >> 27))) ^ ((0x94D049BB133111EBLL * (v20 ^ (v20 >> 27))) >> 31);
    v35[v13] = __ROL8__(v35[v13] ^ v35[v18], v9);
    v35[v16] += 0xA0761D6478BD642FLL * v35[v14];
    ++v8;
    v9 += 17;
    v10 += 13;
    v11 += 7;
    v12 += 0x100000000LL;
  }
  while ( v8 != 101 );
  result = 1;
  v22 = 13;
  v23 = 5;
  v24 = 0;
  v25 = 0;
  v26 = v36;
  do
  {
    v27 = v25 & 7;
    v28 = ((_BYTE)v25 + 2) & 7;
    v29 = v35[v27];
    v30 = __ROL8__(v35[v28], v23);
    v31 = __ROL8__(v35[((_BYTE)v25 + 5) & 7], v22);
    v32 = 0x8EBC6AF09C88C6E3LL
        * (((v24 ^ v30 ^ v29 ^ v31) + (a2 ^ v35[((_BYTE)v25 - 1) & 7]))
         ^ (((v24 ^ v30 ^ v29 ^ v31) + (a2 ^ v35[((_BYTE)v25 - 1) & 7])) >> 23));
    v33 = v32 ^ __ROL8__(v32, 29);
    v34 = _bittest64((const __int64 *)&v33, v25);
    *(_BYTE *)(v26 + v25) = v34;
    v35[v27] = v29 ^ __ROL8__(v25 + v34 + v33, result);
    v35[v28] += 0x589965CC75374CC3LL * v33;
    ++v25;
    result += 11;
    v24 -= 0x18FC812E5F4BD725LL;
    v22 += 7;
    v23 += 3;
  }
  while ( v25 != 768 );
  return result;
}

// nfuncs=19 queued=3 decompiled=3 lumina nreq=0 worse=0 better=0
// ALL OK, 3 function(s) have been successfully decompiled
