;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 93862A67DA543C331AC03D60DCAAC424A199B1C55D954B10D9FBC46A31EAE1F6
; Input MD5    : 80D85D8A340F40C02EA40A03BFDAAC23
; Input CRC32  : 359F7F89
; Compiler     : GNU C++

; File Name   : /home/petik/Downloads/virusshare/timotei/timotei-crackme-01
; Format      : ELF64 for x86-64 (Executable)
; Imagebase   : 400000
;
; Source File : 'timo#1_final.asm'

.686p
.mmx
.model flat
.intel_syntax noprefix


; Segment type: Pure data
; Segment permissions: Read
LOAD segment mempage public 'DATA' use64
assume cs:LOAD
;org 400000h
dword_400000 dd 464C457Fh ; File format: \x7FELF
db 2                    ; File class: 64-bit
db 1                    ; Data encoding: little-endian
db 1                    ; File version
db 0                    ; OS/ABI: UNIX System V ABI
db 0                    ; ABI Version
db 7 dup(0)             ; Padding
dw 2                    ; File type: Executable
dw 3Eh                  ; Machine: x86-64
dd 1                    ; File version
dq offset _start        ; Entry point
dq 40h                  ; PHT file offset
dq 24E8h                ; SHT file offset
dd 0                    ; Processor-specific flags
dw 40h                  ; ELF header size
dw 38h                  ; PHT entry size
dw 3                    ; Number of entries in PHT
dw 40h                  ; SHT entry size
dw 6                    ; Number of entries in SHT
dw 5                    ; SHT entry index for string table
; ELF64 Program Header
; PHT Entry 0
dd 1                    ; Type: LOAD
dd 4                    ; Flags
dq 0                    ; File offset
dq offset dword_400000  ; Virtual address
dq 400000h              ; Physical address
dq 0E8h                 ; Size in file image
dq 0E8h                 ; Size in memory image
dq 1000h                ; Alignment
; PHT Entry 1
dd 1                    ; Type: LOAD
dd 5                    ; Flags
dq 1000h                ; File offset
dq offset _start        ; Virtual address
dq 401000h              ; Physical address
dq 162h                 ; Size in file image
dq 162h                 ; Size in memory image
dq 1000h                ; Alignment
; PHT Entry 2
dd 1                    ; Type: LOAD
dd 6                    ; Flags
dq 2000h                ; File offset
dq offset Credit        ; Virtual address
dq 402000h              ; Physical address
dq 1B1h                 ; Size in file image
dq 1B1h                 ; Size in memory image
dq 1000h                ; Alignment
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing


; Attributes: noreturn

public _start
_start proc near
mov     eax, 1
mov     edi, 1          ; fd
mov     esi, offset message ; buf
mov     edx, 24h ; '$'  ; count
syscall                 ; LINUX - sys_write
mov     eax, 0
mov     edi, 0          ; fd
mov     esi, offset buffer ; buf
mov     edx, 0Ah        ; count
syscall                 ; LINUX - sys_read
cmp     byte_4020E7[eax], 0Ah
jz      short _garbage_end
mov     edi, 0          ; fd
mov     rsi, offset dummy ; buf
mov     edx, 1          ; count

_garbage:
mov     eax, 0
syscall                 ; LINUX - sys_read
cmp     dummy, 0Ah
jz      short _garbage_end
jmp     short _garbage

_garbage_end:
mov     edi, offset buffer
sub     ecx, ecx
sub     al, al
not     ecx
cld
repne scasb
not     ecx
dec     ecx
mov     eax, ecx
cmp     eax, 3
jle     out
dec     eax
xor     ebx, ebx
mov     edx, 539h
mov     ecx, offset buffer
mov     esi, ecx

__:
mov     bl, [ecx+1]
add     edx, ebx
inc     ecx
dec     eax
jnz     short __
add     edx, edx
mov     eax, edx
xor     edx, edx
mov     ecx, 11h
div     ecx
add     dl, 30h ; '0'
mov     al, [esi]
sub     dl, al
test    dl, dl
jz      short go_on
jmp     out

go_on:
mov     eax, 1
mov     edi, 1          ; fd
mov     esi, offset message2 ; buf
mov     edx, 21h ; '!'  ; count
syscall                 ; LINUX - sys_write
mov     eax, 0
mov     edi, 0          ; fd
mov     esi, offset buffer2 ; buf
mov     edx, 0Ah        ; count
syscall                 ; LINUX - sys_read
cmp     byte ptr [eax+40214Bh], 0Ah
jz      short _garbage_end2
mov     edi, 0          ; fd
mov     rsi, offset dummy ; buf
mov     edx, 1          ; count

_garbage2:
mov     eax, 0
syscall                 ; LINUX - sys_read
cmp     dummy, 0Ah
jz      short _garbage_end2
jmp     short _garbage2

_garbage_end2:
mov     esi, offset message2_help ; "No need to patch or bruteforce, explore"...
mov     esi, offset buffer2
mov     ecx, 4
mov     eax, 811C9DC5h
mov     edi, 1000193h
xor     ebx, ebx

nextbyte:
mul     edi
mov     bl, [esi]
xor     eax, ebx
inc     esi
dec     ecx
jnz     short nextbyte
cmp     eax, 86CFDCF8h
jnz     short out
mov     esi, offset good ; ".:Good, that's all for history lesson t"...
jmp     short $+2

goodway:
mov     eax, 1
mov     edi, 1          ; fd
mov     edx, 2Fh ; '/'  ; count
syscall                 ; LINUX - sys_write

out:
mov     eax, 3Ch ; '<'
xor     rdi, rdi        ; error_code
syscall                 ; LINUX - sys_exit
_start endp

_text ends


; Segment type: Pure data
; Segment permissions: Read/Write
_data segment dword public 'DATA' use64
assume cs:_data
;org 402000h
Credit db '._:timotei crackme#1:_...thanks Grb'
db 'avaCigla for beta testing!',0
; char message
message db '.'
db  3Ah ; :
db  6Bh ; k
db  6Eh ; n
db  6Fh ; o
db  63h ; c
db  6Bh ; k
db  2Ch ; ,
db  6Bh ; k
db  6Eh ; n
db  6Fh ; o
db  63h ; c
db  6Bh ; k
db  2Eh ; .
db  2Eh ; .
db  2Eh ; .
db  79h ; y
db  6Fh ; o
db  75h ; u
db  72h ; r
db  20h
db  70h ; p
db  69h ; i
db  6Eh ; n
db  20h
db  70h ; p
db  6Ch ; l
db  65h ; e
db  61h ; a
db  73h ; s
db  65h ; e
db  2Eh ; .
db  2Eh ; .
db  2Eh ; .
db  3Ah ; :
db  20h
db  0Ah
; char message2
message2 db '.'
db  3Ah ; :
db  57h ; W
db  68h ; h
db  65h ; e
db  72h ; r
db  65h ; e
db  20h
db  64h ; d
db  69h ; i
db  64h ; d
db  20h
db  2Bh ; +
db  46h ; F
db  72h ; r
db  61h ; a
db  76h ; v
db  69h ; i
db  61h ; a
db  20h
db  74h ; t
db  61h ; a
db  75h ; u
db  67h ; g
db  68h ; h
db  74h ; t
db  20h
db  75h ; u
db  73h ; s
db  3Fh ; ?
db  20h
db  3Ah ; :
db  20h
db  0Ah
message2_help db 'No need to patch or bruteforce, exp'
db 'lore the web...',0
db  0Ah
; char good[46]
good db '.:Good, that',27h,'s all for histor'
db 'y lesson today:-)'
byte_4020E7 db 0Ah
; char buffer[100]
buffer db 64h dup(0)
; char buffer2[100]
buffer2 db 64h dup(0)
; char dummy
dummy db 0
_data ends


end _start
