import sys

KEY = 0xCDC40493
# generated by crackme from password 'bruceschneier'

def error():
	print "error!"
	sys.exit(1)
	

with open("crackme", "r+b") as f:
	last_dword = 0
	pos = -1
	while True:
		tmp = f.read(1)
		if not tmp:
			break
		x = ord(tmp)
		last_dword = (((last_dword >> 8) & 0xFFFFFF) | ((x & 0xFF) << 24))
		if last_dword == 0x12345678:
			if pos != -1:
				print "dword not unique!"
				error()
			pos = f.tell()
	if pos == -1:
		error()

	f.seek(pos)

	count = 0
	last_dword = 0
	while True:
		tmp = f.read(1)
		if not tmp:
			break
		x = ord(tmp)
		last_dword = (((last_dword >> 8) & 0xFFFFFF) | ((x & 0xFF) << 24))
		count += 1
		if count == 4:
			count = 0
			if last_dword == 0:
				break
			print "encrypt: ",hex(last_dword),"->",hex(last_dword ^KEY)
			last_dword = last_dword ^ KEY
			f.seek(f.tell() - 4)
			b = [0,0,0,0]
			for j in range(0,4):
				y = last_dword & 0xFF
				last_dword >>= 8
				b[j] = y
			f.write(bytearray(b))


	f.close()


print "finished."
