/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void __fastcall _mingw_invalidParameterHandler(const wchar_t *a1, const wchar_t *a2, const wchar_t *a3);
__int64 pre_c_init(); // weak
__int64 pre_cpp_init(); // weak
__int64 WinMainCRTStartup(); // weak
__int64 mainCRTStartup(); // weak
__int64 _tmainCRTStartup();
_BOOL8 check_managed_app();
__int64 *__fastcall duplicate_ppstrings(int a1, __int64 *a2);
int __cdecl atexit(void (__cdecl *)());
__int64 __fastcall weak___register_frame_info_hmod_libgcc(); // weak
__int64 weak___deregister_frame_info_hmod_libgcc(); // weak
int _gcc_register_frame();
int _gcc_deregister_frame();
int __fastcall main(int argc, const char **argv, const char **envp);
void __fastcall _do_global_dtors();
int _do_global_ctors();
int _main();
__int64 setargv();
__int64 __fastcall TlsCallback_0(__int64 a1, int a2);
__int64 _tlregdtor(); // weak
__int64 __fastcall _dyn_tls_dtor(__int64 a1, unsigned int a2);
int __cdecl matherr(struct _exception *Except);
void __cdecl fpreset();
void __noreturn _report_error(const char *a1, ...);
unsigned __int64 __fastcall mark_section_writable(const void *a1);
__int64 restore_modified_sections();
void *__fastcall _write_memory(void *a1, const void *a2, size_t a3);
_DWORD *__fastcall do_pseudo_reloc(_DWORD *a1, unsigned __int64 a2, __int64 a3);
__int64 pei386_runtime_relocator();
__int64 (__fastcall *__fastcall _mingw_raise_matherr(int a1, __int64 a2, double a3, double a4, __int64 a5))(_QWORD);
void __fastcall _mingw_setusermatherr(__int64 (__fastcall *a1)(_QWORD));
__int64 __fastcall __w64_mingwthr_add_key_dtor(int a1, __int64 a2);
__int64 __fastcall __w64_mingwthr_remove_key_dtor(int a1);
void _mingwthr_run_key_dtors();
__int64 __fastcall _mingw_TLScallback(__int64 a1, unsigned int a2);
_BOOL8 __fastcall ValidateImageBase(__int64 a1);
__int64 __fastcall FindPESection(__int64 a1, unsigned __int64 a2);
char *__fastcall FindPESectionByName(const char *a1);
__int64 __fastcall _mingw_GetSectionForAddress(__int64 a1);
__int64 _mingw_GetSectionCount();
__int64 __fastcall FindPESectionExec(__int64 a1);
unsigned __int64 GetPEImageBase();
_BOOL8 __fastcall IsNonwritableInCurrentImage(__int64 a1);
__int64 __fastcall _mingw_enum_import_library_names(int a1);
int __cdecl vfprintf(FILE *const Stream, const char *const Format, va_list ArgList);
int scanf(const char *const Format, ...);
int printf(const char *const Format, ...);
int fprintf(FILE *const Stream, const char *const Format, ...);
__int64 __fastcall _getmainargs(int *a1, char ***a2, char ***a3, int a4, int *a5);
__int64 __fastcall _wgetmainargs(int *a1, wchar_t ***a2, wchar_t ***a3, int a4, int *a5);
_onexit_t __cdecl onexit(_onexit_t Func);
int __cdecl at_quick_exit(void (__cdecl *)());
void __fastcall __noreturn amsg_exit(int a1);
__int64 get_output_format(); // weak
void __cdecl tzset_0();
void __cdecl tzset();
__int64 _ms_fwprintf(FILE *a1, const wchar_t *a2, ...);
// FILE *__cdecl _acrt_iob_func_0(unsigned int Ix);
// int *__cdecl _daylight_0();
// int *__cdecl _p___argc();
// char ***__cdecl _p___argv();
// wchar_t ***__cdecl _p___wargv();
// int *__cdecl _p__commode();
// char ***__cdecl _p__environ();
// int *__cdecl _p__fmode();
// wchar_t ***__cdecl _p__wenviron_0();
// void __cdecl _setusermatherr(_UserMathErrorFunctionPointer UserMathErrorFunction);
// int __cdecl _stdio_common_vfprintf(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// int __cdecl _stdio_common_vfscanf(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list Arglist);
// int __cdecl _stdio_common_vfwprintf_0(unsigned __int64 Options, FILE *Stream, const wchar_t *Format, _locale_t Locale, va_list ArgList);
// int *__cdecl _timezone();
// char **__cdecl _tzname_0();
// void __cdecl cexit_0();
// errno_t __cdecl configure_narrow_argv_0(_crt_argv_mode mode);
// errno_t __cdecl configure_wide_argv(_crt_argv_mode mode);
// int __cdecl crt_at_quick_exit_0(_PVFV Function);
// int __cdecl crt_atexit(_PVFV Function);
// void __cdecl __noreturn exit(int Code);
// int __cdecl initialize_narrow_environment();
// int __cdecl initialize_wide_environment();
// void __cdecl initterm(_PVFV *First, _PVFV *Last);
// void __cdecl _set_app_type(_crt_app_type Type);
// _invalid_parameter_handler __cdecl set_invalid_parameter_handler_0(_invalid_parameter_handler Handler);
// int __cdecl set_new_mode_0(int NewMode);
// void __cdecl __noreturn abort();
// void *__cdecl calloc(size_t Count, size_t Size);
// void __cdecl __noreturn exit(int Code);
// void __cdecl free(void *Block);
// size_t __cdecl fwrite(const void *Buffer, size_t ElementSize, size_t ElementCount, FILE *Stream);
// void *__cdecl malloc_0(size_t Size);
// void *__cdecl memcpy_0(void *, const void *Src, size_t Size);
// size_t __cdecl strlen(const char *Str);
// int __cdecl strncmp_0(const char *Str1, const char *Str2, size_t MaxCount);
// LPSTR __stdcall GetCommandLineA();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN gnu_exception_handler; // weak
__int64 _CTOR_LIST__[] = { -1LL }; // weak
__int64 (__fastcall *_data_start__)(_QWORD) = NULL; // weak
_UNKNOWN m; // weak
_UNKNOWN filename; // weak
__int64 (*p_0)[36] = &qword_1400034E0; // weak
_UNKNOWN dowildcard; // weak
_UNKNOWN CRT_MT; // weak
_UNKNOWN MINGW_INSTALL_DEBUG_MATHERR; // weak
_UNKNOWN *__initenv = &local__initenv; // weak
char *tzname[2] = { &initial_tznames, &initial_timezone };
int timezone = 1073758800;
int daylight = 1073758804;
_DWORD __RUNTIME_PSEUDO_RELOC_LIST__[64] =
{
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
}; // weak
_UNKNOWN _EH_FRAME_BEGIN__; // weak
_UNKNOWN _mingw_module_is_dll; // weak
int argc; // idb
char **argv; // idb
char **envp; // idb
int argret; // weak
int mainret; // idb
int managedapp; // weak
int has_cctor; // weak
int startinfo; // weak
__int64 hmod_libgcc; // weak
_UNKNOWN obj; // weak
_UNKNOWN t; // weak
_UNKNOWN _2; // weak
_UNKNOWN o; // weak
_UNKNOWN _4; // weak
_UNKNOWN _5; // weak
_UNKNOWN k; // weak
_UNKNOWN _6; // weak
char _7; // weak
int initialized; // weak
_UNKNOWN newmode; // weak
_UNKNOWN _mingw_initltsdrot_force; // weak
_UNKNOWN _mingw_initltsdyn_force; // weak
_UNKNOWN _mingw_initltssuo_force; // weak
int commode;
_UNKNOWN _mingw_app_type; // weak
__int64 the_secs; // weak
int maxSections; // weak
int was_init_0; // weak
__int64 (__fastcall *stUserMathErr)(_QWORD); // weak
int fmode;
__int64 _mingw_oldexcpt_handler; // weak
struct _RTL_CRITICAL_SECTION _mingwthr_cs; // idb
int _mingwthr_cs_init; // weak
__int64 key_dtor_list; // weak
_UNKNOWN _native_startup_state; // weak
signed __int64 _native_startup_lock; // weak
// extern void (__stdcall *DeleteCriticalSection)(LPCRITICAL_SECTION lpCriticalSection);
// extern void (__stdcall *EnterCriticalSection)(LPCRITICAL_SECTION lpCriticalSection);
// extern BOOL (__stdcall *FreeLibrary)(HMODULE hLibModule);
// extern DWORD (__stdcall *GetLastError)();
// extern HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName);
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern void (__stdcall *InitializeCriticalSection)(LPCRITICAL_SECTION lpCriticalSection);
// extern void (__stdcall *LeaveCriticalSection)(LPCRITICAL_SECTION lpCriticalSection);
// extern HMODULE (__stdcall *LoadLibraryA)(LPCSTR lpLibFileName);
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern LPVOID (__stdcall *TlsGetValue)(DWORD dwTlsIndex);
// extern BOOL (__stdcall *VirtualProtect)(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect);
// extern SIZE_T (__stdcall *VirtualQuery)(LPCVOID lpAddress, PMEMORY_BASIC_INFORMATION lpBuffer, SIZE_T dwLength);
// extern void (__cdecl *_tzset)();
_PVFV __crt_xc_start__ = NULL; // weak
_PVFV _xc_z = NULL; // weak
_PVFV __crt_xi_start__ = NULL; // weak
_PVFV _xi_z = NULL; // weak
_UNKNOWN _xd_z; // weak


//----- (0000000140001000) ----------------------------------------------------
void __fastcall _mingw_invalidParameterHandler(const wchar_t *a1, const wchar_t *a2, const wchar_t *a3)
{
  ;
}

//----- (0000000140001017) ----------------------------------------------------
__int64 pre_c_init()
{
  managedapp = check_managed_app();
  if ( _mingw_app_type != 0 )
    _set_app_type(_crt_gui_app);
  else
    _set_app_type(_crt_console_app);
  *_p__fmode() = fmode;
  *_p__commode() = commode;
  setargv();
  if ( MINGW_INSTALL_DEBUG_MATHERR == 1 )
    _mingw_setusermatherr((__int64 (__fastcall *)(_QWORD))matherr);
  return 0;
}
// 140001017: using guessed type __int64 pre_c_init();
// 140009020: using guessed type int managedapp;

//----- (000000014000109A) ----------------------------------------------------
__int64 pre_cpp_init()
{
  __int64 result; // rax

  startinfo = newmode;
  result = _getmainargs(&argc, &argv, &envp, dowildcard, &startinfo);
  argret = result;
  return result;
}
// 14000109A: using guessed type __int64 pre_cpp_init();
// 140009018: using guessed type int argret;
// 140009028: using guessed type int startinfo;

//----- (00000001400010F6) ----------------------------------------------------
__int64 WinMainCRTStartup()
{
  _mingw_app_type = 1;
  return (unsigned int)_tmainCRTStartup();
}
// 1400010F6: using guessed type __int64 WinMainCRTStartup();

//----- (0000000140001125) ----------------------------------------------------
__int64 mainCRTStartup()
{
  _mingw_app_type = 0;
  return (unsigned int)_tmainCRTStartup();
}
// 140001125: using guessed type __int64 mainCRTStartup();

//----- (0000000140001154) ----------------------------------------------------
__int64 _tmainCRTStartup()
{
  PVOID StackBase; // [rsp+58h] [rbp-18h]
  signed __int64 v2; // [rsp+60h] [rbp-10h]
  int v3; // [rsp+6Ch] [rbp-4h]

  StackBase = NtCurrentTeb()->NtTib.StackBase;
  v3 = 0;
  while ( 1 )
  {
    v2 = _InterlockedCompareExchange64(&_native_startup_lock, (signed __int64)StackBase, 0);
    if ( v2 == 0 )
      break;
    if ( (PVOID)v2 == StackBase )
    {
      v3 = 1;
      break;
    }
    Sleep(0x3E8u);
  }
  if ( _native_startup_state == 1 )
    amsg_exit(31);
  if ( _native_startup_state != 0 )
  {
    has_cctor = 1;
  }
  else
  {
    _native_startup_state = 1;
    initterm(&__crt_xi_start__, &_xi_z);
  }
  if ( _native_startup_state == 1 )
  {
    initterm(&__crt_xc_start__, &_xc_z);
    _native_startup_state = 2;
  }
  if ( v3 == 0 )
    _InterlockedExchange64(&_native_startup_lock, 0);
  if ( TlsCallback_0 != nullptr )
    TlsCallback_0(0, 2);
  pei386_runtime_relocator();
  _mingw_oldexcpt_handler = (__int64)SetUnhandledExceptionFilter((LPTOP_LEVEL_EXCEPTION_FILTER)&gnu_exception_handler);
  set_invalid_parameter_handler_0((_invalid_parameter_handler)_mingw_invalidParameterHandler);
  fpreset();
  duplicate_ppstrings(argc, (__int64 *)&argv);
  _main();
  *(_QWORD *)__initenv = envp;
  mainret = main(argc, (const char **)argv, (const char **)envp);
  if ( managedapp == 0 )
    exit(mainret);
  if ( has_cctor == 0 )
    cexit_0();
  return (unsigned int)mainret;
}
// 140004210: using guessed type _UNKNOWN *__initenv;
// 140009020: using guessed type int managedapp;
// 140009024: using guessed type int has_cctor;
// 140009140: using guessed type __int64 _mingw_oldexcpt_handler;
// 1400091E8: using guessed type signed __int64 _native_startup_lock;
// 14000B000: using guessed type _PVFV __crt_xc_start__;
// 14000B010: using guessed type _PVFV _xc_z;
// 14000B018: using guessed type _PVFV __crt_xi_start__;
// 14000B028: using guessed type _PVFV _xi_z;

//----- (0000000140001378) ----------------------------------------------------
_BOOL8 check_managed_app()
{
  int v1; // eax

  _mingw_initltsdrot_force = 1;
  _mingw_initltsdyn_force = 1;
  _mingw_initltssuo_force = 1;
  if ( MEMORY[0x140000000] != 23117 )
    return false;
  if ( *(_DWORD *)(MEMORY[0x14000003C] + 0x140000000LL) != 17744 )
    return false;
  v1 = *(unsigned __int16 *)(MEMORY[0x14000003C] + 0x140000018LL);
  if ( v1 == 267 )
  {
    return *(_DWORD *)(MEMORY[0x14000003C] + 0x140000074LL) > 0xEu
        && *(_DWORD *)(MEMORY[0x14000003C] + 0x1400000E8LL) != 0;
  }
  else if ( v1 == 523 )
  {
    return *(_DWORD *)(MEMORY[0x14000003C] + 0x140000084LL) > 0xEu
        && *(_DWORD *)(MEMORY[0x14000003C] + 0x1400000F8LL) != 0;
  }
  else
  {
    return false;
  }
}

//----- (000000014000147C) ----------------------------------------------------
__int64 *__fastcall duplicate_ppstrings(int a1, __int64 *a2)
{
  size_t Size; // [rsp+20h] [rbp-20h]
  __int64 v4; // [rsp+28h] [rbp-18h]
  _QWORD *v5; // [rsp+30h] [rbp-10h]
  int i; // [rsp+3Ch] [rbp-4h]

  v5 = malloc_0(8LL * (a1 + 1));
  v4 = *a2;
  for ( i = 0; i < a1; ++i )
  {
    Size = strlen(*(const char **)(8LL * i + v4)) + 1;
    v5[i] = malloc_0(Size);
    memcpy_0((void *)v5[i], *(const void **)(8LL * i + v4), Size);
  }
  v5[i] = 0;
  *a2 = (__int64)v5;
  return a2;
}

//----- (0000000140001583) ----------------------------------------------------
int __cdecl atexit(void (__cdecl *a1)())
{
  if ( onexit((_onexit_t)a1) != nullptr )
    return 0;
  else
    return -1;
}

//----- (00000001400015D0) ----------------------------------------------------
__int64 weak___deregister_frame_info_hmod_libgcc()
{
  return 0;
}
// 1400015D0: using guessed type __int64 weak___deregister_frame_info_hmod_libgcc();

//----- (00000001400015E0) ----------------------------------------------------
int _gcc_register_frame()
{
  HMODULE ModuleHandleA; // rbx
  FARPROC ProcAddress; // rsi

  ModuleHandleA = GetModuleHandleA("libgcc_s_dw2-1.dll");
  if ( ModuleHandleA != nullptr )
  {
    hmod_libgcc = (__int64)LoadLibraryA("libgcc_s_dw2-1.dll");
    ProcAddress = GetProcAddress(ModuleHandleA, "__register_frame_info");
    _data_start__ = (__int64 (__fastcall *)(_QWORD))GetProcAddress(ModuleHandleA, "__deregister_frame_info");
    if ( ProcAddress != nullptr )
      ((void (__fastcall *)(void *, void *))ProcAddress)(&_EH_FRAME_BEGIN__, &obj);
  }
  else
  {
    _data_start__ = (__int64 (__fastcall *)(_QWORD))weak___deregister_frame_info_hmod_libgcc;
    ((void (__fastcall *)(void *, void *))weak___register_frame_info_hmod_libgcc)(&_EH_FRAME_BEGIN__, &obj);
  }
  return atexit((void (__cdecl *)())_gcc_deregister_frame);
}
// 1400015C0: using guessed type __int64 __fastcall weak___register_frame_info_hmod_libgcc();
// 1400015D0: using guessed type __int64 weak___deregister_frame_info_hmod_libgcc();
// 140004000: using guessed type __int64 (__fastcall *_data_start__)(_QWORD);
// 140009040: using guessed type __int64 hmod_libgcc;

//----- (0000000140001690) ----------------------------------------------------
int _gcc_deregister_frame()
{
  int result; // eax

  result = (int)_data_start__;
  if ( _data_start__ != nullptr )
    result = _data_start__(&_EH_FRAME_BEGIN__);
  if ( hmod_libgcc != 0 )
    return FreeLibrary((HMODULE)hmod_libgcc);
  return result;
}
// 140004000: using guessed type __int64 (__fastcall *_data_start__)(_QWORD);
// 140009040: using guessed type __int64 hmod_libgcc;

//----- (00000001400016D0) ----------------------------------------------------
int __fastcall main(int argc, const char **argv, const char **envp)
{
  LPSTR i; // rax
  __int64 v4; // rdi
  bool v5; // zf
  __int64 v6; // r15
  __int64 v7; // r12
  char *v8; // rbx
  _BYTE *v9; // rsi
  __int64 v10; // rcx
  __int64 v11; // r8
  __int64 v13; // [rsp+8h] [rbp+8h]

  t = 114;
  _2 = 113;
  o = 102;
  _4 = 118;
  _5 = 97;
  k = 98;
  _6 = 101;
  if ( v13 != 2 )
    goto vicroty_yorale;
  for ( i = GetCommandLineA(); *i != 32; ++i )
    ;
  do
    ++i;
  while ( *i == 32 );
  v4 = (__int64)i;
  v6 = 0;
  v5 = true;
  v7 = 17;
  v8 = (char *)&filename;
  v9 = &m;
  v10 = 1;
  do
  {
    if ( v10 == 0 )
      break;
    v5 = *v9++ == *(_BYTE *)v4++;
    --v10;
  }
  while ( v5 );
  if ( v5 )
  {
    printf("Please input the password character by character separated by newlines.\n");
    while ( 1 )
    {
      while ( 1 )
      {
        --v8;
        if ( ++v6 > v7 )
          break;
        if ( *v8 >= 65 )
        {
          scanf("%s", &_7);
          if ( *v8 != _7 )
            v4 = 1;
        }
      }
      if ( v4 != 1 )
      {
        if ( v11 == 1 )
          break;
        if ( v7 < 17 )
        {
          printf("You did the thing no way!!! P.S. Modifying the program to output this message doesn't count.\n");
          return 0;
        }
      }
      v11 = 1;
      if ( v7 == 16 )
        break;
      v6 = 0;
      v8 = &_7;
      v7 = 16;
    }
    printf("Incorrect password.\n");
    return 0;
  }
  else
  {
vicroty_yorale:
    printf(
      "Hello, this is one of my first projects in assembly! Try to find the second command line argument when decompiling"
      " it to continue.\n");
    return 0;
  }
}
// 1400016D0: could not find valid save-restore pair for rbp
// 140001818: variable 'v11' is possibly undefined
// 1400090B0: using guessed type char _7;

//----- (00000001400018B0) ----------------------------------------------------
void __fastcall _do_global_dtors()
{
  while ( (*p_0)[0] != 0 )
  {
    ((void (*)(void))(*p_0)[0])();
    p_0 = (__int64 (*)[36])((char *)p_0 + 8);
  }
}
// 140004170: using guessed type __int64 (*p_0)[36];

//----- (00000001400018EF) ----------------------------------------------------
int _do_global_ctors()
{
  int j; // [rsp+28h] [rbp-8h]
  int i; // [rsp+2Ch] [rbp-4h]

  for ( i = 0; _CTOR_LIST__[i + 1] != 0; ++i )
    ;
  for ( j = i; j != 0; --j )
    ((void (*)(void))_CTOR_LIST__[j])();
  return atexit(_do_global_dtors);
}
// 1400034C0: using guessed type __int64 _CTOR_LIST__[];

//----- (0000000140001967) ----------------------------------------------------
int _main()
{
  int result; // eax

  result = initialized;
  if ( initialized == 0 )
  {
    initialized = 1;
    return _do_global_ctors();
  }
  return result;
}
// 1400090C0: using guessed type int initialized;

//----- (0000000140001990) ----------------------------------------------------
__int64 setargv()
{
  return 0;
}

//----- (00000001400019A0) ----------------------------------------------------
// Alternative name is '__dyn_tls_init'
__int64 __fastcall TlsCallback_0(__int64 a1, int a2)
{
  void (**i)(void); // [rsp+28h] [rbp-8h]

  if ( CRT_MT != 2 )
    CRT_MT = 2;
  if ( a2 == 2 )
  {
    for ( i = (void (**)(void))&_xd_z; i != (void (**)(void))&_xd_z; ++i )
    {
      if ( *i != nullptr )
        (*i)();
    }
    return 1;
  }
  else
  {
    if ( a2 == 1 )
      _mingw_TLScallback(a1, 1u);
    return 1;
  }
}

//----- (0000000140001A43) ----------------------------------------------------
__int64 _tlregdtor()
{
  return 0;
}
// 140001A43: using guessed type __int64 _tlregdtor();

//----- (0000000140001A60) ----------------------------------------------------
// Alternative name is 'TlsCallback_1'
__int64 __fastcall _dyn_tls_dtor(__int64 a1, unsigned int a2)
{
  if ( a2 != 3 && a2 != 0 )
    return 1;
  _mingw_TLScallback(a1, a2);
  return 1;
}

//----- (0000000140001AB0) ----------------------------------------------------
int __cdecl matherr(struct _exception *Except)
{
  double retval; // xmm8_8
  double arg2; // xmm7_8
  double arg1; // xmm6_8
  char *name; // rbx
  FILE *v5; // rax
  const char *v7; // [rsp+48h] [rbp-8h]

  switch ( Except->type )
  {
    case 1:
      v7 = "Argument domain error (DOMAIN)";
      break;
    case 2:
      v7 = "Argument singularity (SIGN)";
      break;
    case 3:
      v7 = "Overflow range error (OVERFLOW)";
      break;
    case 4:
      v7 = "The result is too small to be represented (UNDERFLOW)";
      break;
    case 5:
      v7 = "Total loss of significance (TLOSS)";
      break;
    case 6:
      v7 = "Partial loss of significance (PLOSS)";
      break;
    default:
      v7 = "Unknown error";
      break;
  }
  retval = Except->retval;
  arg2 = Except->arg2;
  arg1 = Except->arg1;
  name = Except->name;
  v5 = _acrt_iob_func_0(2u);
  fprintf(v5, "_matherr(): %s in %s(%g, %g)  (retval=%g)\n", v7, name, arg1, arg2, retval);
  return 0;
}

//----- (0000000140001BD0) ----------------------------------------------------
void __cdecl fpreset()
{
  __asm { fninit }
}

//----- (0000000140001BE0) ----------------------------------------------------
void __noreturn _report_error(const char *a1, ...)
{
  FILE *v1; // rax
  FILE *v2; // rax
  va_list va; // [rsp+58h] [rbp+28h] BYREF

  va_start(va, a1);
  v1 = _acrt_iob_func_0(2u);
  fwrite("Mingw-w64 runtime failure:\n", 1u, 0x1Bu, v1);
  v2 = _acrt_iob_func_0(2u);
  vfprintf(v2, a1, va);
  abort();
}

//----- (0000000140001C50) ----------------------------------------------------
unsigned __int64 __fastcall mark_section_writable(const void *a1)
{
  unsigned __int64 result; // rax
  DWORD LastError; // eax
  struct _MEMORY_BASIC_INFORMATION Buffer; // [rsp+20h] [rbp-40h] BYREF
  __int64 SectionForAddress; // [rsp+50h] [rbp-10h]
  DWORD flNewProtect; // [rsp+58h] [rbp-8h]
  int i; // [rsp+5Ch] [rbp-4h]

  for ( i = 0; i < maxSections; ++i )
  {
    if ( (unsigned __int64)a1 >= *(_QWORD *)(the_secs + 40LL * i + 24) )
    {
      result = *(_QWORD *)(the_secs + 40LL * i + 24) + *(unsigned int *)(*(_QWORD *)(the_secs + 40LL * i + 32) + 8LL);
      if ( (unsigned __int64)a1 < result )
        return result;
    }
  }
  SectionForAddress = _mingw_GetSectionForAddress((__int64)a1);
  if ( SectionForAddress == 0 )
    _report_error("Address %p has no image-section", a1);
  *(_QWORD *)(the_secs + 40LL * i + 32) = SectionForAddress;
  *(_DWORD *)(the_secs + 40LL * i) = 0;
  *(_QWORD *)(the_secs + 40LL * i + 24) = GetPEImageBase() + *(unsigned int *)(SectionForAddress + 12);
  if ( VirtualQuery(*(LPCVOID *)(the_secs + 40LL * i + 24), &Buffer, 0x30u) == 0 )
    _report_error(
      "  VirtualQuery failed for %d bytes at address %p",
      *(_DWORD *)(SectionForAddress + 8),
      *(const void **)(the_secs + 40LL * i + 24));
  if ( Buffer.Protect != 64 && Buffer.Protect != 4 && Buffer.Protect != 128 && Buffer.Protect != 8 )
  {
    if ( Buffer.Protect == 2 )
      flNewProtect = 4;
    else
      flNewProtect = 64;
    *(_QWORD *)(the_secs + 40LL * i + 8) = Buffer.BaseAddress;
    *(_QWORD *)(the_secs + 40LL * i + 16) = Buffer.RegionSize;
    if ( !VirtualProtect(Buffer.BaseAddress, Buffer.RegionSize, flNewProtect, (PDWORD)(the_secs + 40LL * i)) )
    {
      LastError = GetLastError();
      _report_error("  VirtualProtect failed with code 0x%x", LastError);
    }
  }
  return (unsigned int)++maxSections;
}
// 140009110: using guessed type __int64 the_secs;
// 140009118: using guessed type int maxSections;

//----- (0000000140001F2F) ----------------------------------------------------
__int64 restore_modified_sections()
{
  __int64 result; // rax
  DWORD flOldProtect; // [rsp+28h] [rbp-8h] BYREF
  int i; // [rsp+2Ch] [rbp-4h]

  for ( i = 0; ; ++i )
  {
    result = (unsigned int)maxSections;
    if ( i >= maxSections )
      break;
    if ( *(_DWORD *)(the_secs + 40LL * i) != 0 )
      VirtualProtect(
        *(LPVOID *)(the_secs + 40LL * i + 8),
        *(_QWORD *)(the_secs + 40LL * i + 16),
        *(_DWORD *)(the_secs + 40LL * i),
        &flOldProtect);
  }
  return result;
}
// 140009110: using guessed type __int64 the_secs;
// 140009118: using guessed type int maxSections;

//----- (0000000140002007) ----------------------------------------------------
void *__fastcall _write_memory(void *a1, const void *a2, size_t a3)
{
  void *result; // rax

  if ( a3 != 0 )
  {
    mark_section_writable(a1);
    return memcpy_0(a1, a2, a3);
  }
  return result;
}

//----- (000000014000204E) ----------------------------------------------------
_DWORD *__fastcall do_pseudo_reloc(_DWORD *a1, unsigned __int64 a2, __int64 a3)
{
  _DWORD *result; // rax
  unsigned int v4; // eax
  unsigned int v5; // eax
  int v6; // [rsp+34h] [rbp-4Ch] BYREF
  signed __int64 v7; // [rsp+38h] [rbp-48h] BYREF
  __int64 v8; // [rsp+40h] [rbp-40h]
  __int64 v9; // [rsp+48h] [rbp-38h]
  unsigned int v10; // [rsp+54h] [rbp-2Ch]
  const void **v11; // [rsp+58h] [rbp-28h]
  __int64 v12; // [rsp+60h] [rbp-20h]
  _DWORD *i; // [rsp+68h] [rbp-18h]
  unsigned int *j; // [rsp+70h] [rbp-10h]
  _DWORD *v15; // [rsp+78h] [rbp-8h]

  v12 = a2 - (_QWORD)a1;
  result = a1;
  v15 = a1;
  if ( (__int64)(a2 - (_QWORD)a1) > 7 )
  {
    if ( v12 > 11 && *v15 == 0 && v15[1] == 0 && v15[2] == 0 )
      v15 += 3;
    if ( *v15 != 0 || v15[1] != 0 )
    {
      for ( i = v15; ; i += 2 )
      {
        result = i;
        if ( (unsigned __int64)i >= a2 )
          break;
        v12 = (unsigned int)i[1] + a3;
        v6 = *(_DWORD *)v12 + *i;
        _write_memory((void *)v12, &v6, 4u);
      }
    }
    else
    {
      if ( v15[2] != 1 )
        _report_error("  Unknown pseudo relocation protocol version %d.\n", v15[2]);
      for ( j = v15 + 3; ; j += 3 )
      {
        result = j;
        if ( (unsigned __int64)j >= a2 )
          break;
        v12 = j[1] + a3;
        v11 = (const void **)(*j + a3);
        v11 = (const void **)*v11;
        v4 = (unsigned __int8)j[2];
        if ( v4 == 64 )
        {
          v7 = *(_QWORD *)v12;
        }
        else
        {
          if ( v4 > 0x40 )
            goto LABEL_30;
          if ( v4 == 32 )
          {
            v7 = *(unsigned int *)v12;
            if ( (int)v7 < 0 )
              v7 |= 0xFFFFFFFF00000000uLL;
          }
          else
          {
            if ( v4 > 0x20 )
              goto LABEL_30;
            if ( v4 == 8 )
            {
              v7 = *(unsigned __int8 *)v12;
              if ( (v7 & 0x80) != 0 )
                v7 |= 0xFFFFFFFFFFFFFF00uLL;
            }
            else
            {
              if ( v4 != 16 )
              {
LABEL_30:
                v7 = 0;
                _report_error("  Unknown pseudo relocation bit size %d.\n", (unsigned __int8)j[2]);
              }
              v7 = *(unsigned __int16 *)v12;
              if ( (v7 & 0x8000) != 0 )
                v7 |= 0xFFFFFFFFFFFF0000uLL;
            }
          }
        }
        v7 -= a3 + *j;
        v7 += (signed __int64)v11;
        v10 = (unsigned __int8)j[2];
        if ( v10 <= 0x3F )
        {
          v9 = (1LL << v10) - 1;
          v8 = -1LL << ((unsigned __int8)v10 - 1);
          if ( v9 < v7 || v8 > v7 )
            _report_error(
              "%d bit pseudo relocation at %p out of range, targeting %p, yielding the value %p.\n",
              v10,
              (const void *)v12,
              v11,
              (const void *)v7);
        }
        v5 = (unsigned __int8)j[2];
        if ( v5 == 64 )
        {
          _write_memory((void *)v12, &v7, 8u);
        }
        else if ( v5 <= 0x40 )
        {
          if ( v5 == 32 )
          {
            _write_memory((void *)v12, &v7, 4u);
          }
          else if ( v5 <= 0x20 )
          {
            if ( v5 == 8 )
            {
              _write_memory((void *)v12, &v7, 1u);
            }
            else if ( v5 == 16 )
            {
              _write_memory((void *)v12, &v7, 2u);
            }
          }
        }
      }
    }
  }
  return result;
}

//----- (00000001400023D8) ----------------------------------------------------
__int64 pei386_runtime_relocator()
{
  __int64 result; // rax
  void *v1; // rsp
  char v2; // [rsp+20h] [rbp-10h] BYREF
  int SectionCount; // [rsp+2Ch] [rbp-4h]

  result = (unsigned int)was_init_0;
  if ( was_init_0 == 0 )
  {
    was_init_0 = 1;
    SectionCount = _mingw_GetSectionCount();
    v1 = alloca(16 * ((unsigned __int64)(40LL * SectionCount + 15) >> 4));
    the_secs = (__int64)&v2;
    maxSections = 0;
    do_pseudo_reloc(__RUNTIME_PSEUDO_RELOC_LIST__, (unsigned __int64)__RUNTIME_PSEUDO_RELOC_LIST__, 0x140000000LL);
    return restore_modified_sections();
  }
  return result;
}
// 140005F00: using guessed type _DWORD __RUNTIME_PSEUDO_RELOC_LIST__[64];
// 140009110: using guessed type __int64 the_secs;
// 140009118: using guessed type int maxSections;
// 14000911C: using guessed type int was_init_0;

//----- (0000000140002480) ----------------------------------------------------
__int64 (__fastcall *__fastcall _mingw_raise_matherr(int a1, __int64 a2, double a3, double a4, __int64 a5))(_QWORD)
{
  __int64 (__fastcall *result)(_QWORD); // rax
  int v6; // [rsp+20h] [rbp-30h] BYREF
  __int64 v7; // [rsp+28h] [rbp-28h]
  double v8; // [rsp+30h] [rbp-20h]
  double v9; // [rsp+38h] [rbp-18h]
  __int64 v10; // [rsp+40h] [rbp-10h]

  result = stUserMathErr;
  if ( stUserMathErr != nullptr )
  {
    v6 = a1;
    v7 = a2;
    v8 = a3;
    v9 = a4;
    v10 = a5;
    return (__int64 (__fastcall *)(_QWORD))stUserMathErr(&v6);
  }
  return result;
}
// 140009120: using guessed type __int64 (__fastcall *stUserMathErr)(_QWORD);

//----- (00000001400024EA) ----------------------------------------------------
void __fastcall _mingw_setusermatherr(__int64 (__fastcall *a1)(_QWORD))
{
  stUserMathErr = a1;
  _setusermatherr((_UserMathErrorFunctionPointer)a1);
}
// 140009120: using guessed type __int64 (__fastcall *stUserMathErr)(_QWORD);

//----- (0000000140002750) ----------------------------------------------------
__int64 __fastcall __w64_mingwthr_add_key_dtor(int a1, __int64 a2)
{
  _QWORD *v3; // [rsp+28h] [rbp-8h]

  if ( _mingwthr_cs_init == 0 )
    return 0;
  v3 = calloc(1u, 0x18u);
  if ( v3 == nullptr )
    return 0xFFFFFFFFLL;
  *(_DWORD *)v3 = a1;
  v3[1] = a2;
  EnterCriticalSection(&_mingwthr_cs);
  v3[2] = key_dtor_list;
  key_dtor_list = (__int64)v3;
  LeaveCriticalSection(&_mingwthr_cs);
  return 0;
}
// 140009188: using guessed type int _mingwthr_cs_init;
// 140009190: using guessed type __int64 key_dtor_list;

//----- (00000001400027F1) ----------------------------------------------------
__int64 __fastcall __w64_mingwthr_remove_key_dtor(int a1)
{
  _QWORD *Block; // [rsp+20h] [rbp-10h]
  _QWORD *v3; // [rsp+28h] [rbp-8h]

  if ( _mingwthr_cs_init == 0 )
    return 0;
  EnterCriticalSection(&_mingwthr_cs);
  v3 = nullptr;
  for ( Block = (_QWORD *)key_dtor_list; Block != nullptr; Block = (_QWORD *)Block[2] )
  {
    if ( a1 == *(_DWORD *)Block )
    {
      if ( v3 != nullptr )
        v3[2] = Block[2];
      else
        key_dtor_list = Block[2];
      free(Block);
      break;
    }
    v3 = Block;
  }
  LeaveCriticalSection(&_mingwthr_cs);
  return 0;
}
// 140009188: using guessed type int _mingwthr_cs_init;
// 140009190: using guessed type __int64 key_dtor_list;

//----- (00000001400028B2) ----------------------------------------------------
void _mingwthr_run_key_dtors()
{
  LPVOID Value; // [rsp+20h] [rbp-10h]
  __int64 i; // [rsp+28h] [rbp-8h]

  if ( _mingwthr_cs_init != 0 )
  {
    EnterCriticalSection(&_mingwthr_cs);
    for ( i = key_dtor_list; i != 0; i = *(_QWORD *)(i + 16) )
    {
      Value = TlsGetValue(*(_DWORD *)i);
      if ( GetLastError() == 0 && Value != nullptr )
        (*(void (__fastcall **)(LPVOID))(i + 8))(Value);
    }
    LeaveCriticalSection(&_mingwthr_cs);
  }
}
// 140009188: using guessed type int _mingwthr_cs_init;
// 140009190: using guessed type __int64 key_dtor_list;

//----- (0000000140002951) ----------------------------------------------------
__int64 __fastcall _mingw_TLScallback(__int64 a1, unsigned int a2)
{
  _QWORD *v3; // [rsp+20h] [rbp-10h]
  _QWORD *Block; // [rsp+28h] [rbp-8h]

  if ( a2 == 3 )
  {
    _mingwthr_run_key_dtors();
  }
  else if ( a2 <= 3 )
  {
    if ( a2 == 2 )
    {
      fpreset();
    }
    else if ( a2 != 0 )
    {
      if ( _mingwthr_cs_init == 0 )
        InitializeCriticalSection(&_mingwthr_cs);
      _mingwthr_cs_init = 1;
    }
    else
    {
      _mingwthr_run_key_dtors();
      if ( _mingwthr_cs_init == 1 )
      {
        for ( Block = (_QWORD *)key_dtor_list; Block != nullptr; Block = v3 )
        {
          v3 = (_QWORD *)Block[2];
          free(Block);
        }
        key_dtor_list = 0;
        _mingwthr_cs_init = 0;
        DeleteCriticalSection(&_mingwthr_cs);
      }
    }
  }
  return 1;
}
// 140002986: conditional instruction was optimized away because edx.4<2u
// 140002996: conditional instruction was optimized away because edx.4==1
// 140009188: using guessed type int _mingwthr_cs_init;
// 140009190: using guessed type __int64 key_dtor_list;

//----- (0000000140002A50) ----------------------------------------------------
_BOOL8 __fastcall ValidateImageBase(__int64 a1)
{
  __int64 v2; // [rsp+10h] [rbp-10h]

  if ( *(_WORD *)a1 != 23117 )
    return false;
  v2 = *(int *)(a1 + 60) + a1;
  return *(_DWORD *)v2 == 17744 && *(_WORD *)(v2 + 24) == 523;
}

//----- (0000000140002ACC) ----------------------------------------------------
__int64 __fastcall FindPESection(__int64 a1, unsigned __int64 a2)
{
  __int64 v3; // [rsp+8h] [rbp-18h]
  unsigned int v4; // [rsp+14h] [rbp-Ch]
  __int64 v5; // [rsp+18h] [rbp-8h]

  v3 = *(int *)(a1 + 60) + a1;
  v4 = 0;
  v5 = *(unsigned __int16 *)(v3 + 20) + v3 + 24;
  while ( v4 < *(unsigned __int16 *)(v3 + 6) )
  {
    if ( a2 >= *(unsigned int *)(v5 + 12) && a2 < (unsigned int)(*(_DWORD *)(v5 + 12) + *(_DWORD *)(v5 + 8)) )
      return v5;
    ++v4;
    v5 += 40;
  }
  return 0;
}

//----- (0000000140002B65) ----------------------------------------------------
char *__fastcall FindPESectionByName(const char *a1)
{
  __int64 v2; // [rsp+20h] [rbp-20h]
  unsigned int v3; // [rsp+34h] [rbp-Ch]
  char *Str1; // [rsp+38h] [rbp-8h]

  if ( strlen(a1) > 8 )
    return nullptr;
  if ( !ValidateImageBase(0x140000000LL) )
    return nullptr;
  v2 = MEMORY[0x14000003C] + 0x140000000LL;
  v3 = 0;
  Str1 = (char *)(*(unsigned __int16 *)(MEMORY[0x14000003C] + 0x140000014LL) + v2 + 24);
  while ( v3 < *(unsigned __int16 *)(v2 + 6) )
  {
    if ( strncmp_0(Str1, a1, 8u) == 0 )
      return Str1;
    ++v3;
    Str1 += 40;
  }
  return nullptr;
}

//----- (0000000140002C2B) ----------------------------------------------------
__int64 __fastcall _mingw_GetSectionForAddress(__int64 a1)
{
  if ( ValidateImageBase(0x140000000LL) )
    return FindPESection(0x140000000LL, a1 - 0x140000000LL);
  else
    return 0;
}

//----- (0000000140002C7B) ----------------------------------------------------
__int64 _mingw_GetSectionCount()
{
  if ( ValidateImageBase(0x140000000LL) )
    return *(unsigned __int16 *)(MEMORY[0x14000003C] + 0x140000006LL);
  else
    return 0;
}

//----- (0000000140002CCB) ----------------------------------------------------
__int64 __fastcall FindPESectionExec(__int64 a1)
{
  unsigned int v2; // [rsp+34h] [rbp-Ch]
  __int64 v3; // [rsp+38h] [rbp-8h]

  if ( !ValidateImageBase(0x140000000LL) )
    return 0;
  v2 = 0;
  v3 = *(unsigned __int16 *)(MEMORY[0x14000003C] + 0x140000014LL) + MEMORY[0x14000003C] + 0x140000000LL + 24;
  while ( v2 < *(unsigned __int16 *)(MEMORY[0x14000003C] + 0x140000006LL) )
  {
    if ( (*(_DWORD *)(v3 + 36) & 0x20000000) != 0 )
    {
      if ( a1 == 0 )
        return v3;
      --a1;
    }
    ++v2;
    v3 += 40;
  }
  return 0;
}

//----- (0000000140002D77) ----------------------------------------------------
unsigned __int64 GetPEImageBase()
{
  if ( ValidateImageBase(0x140000000LL) )
    return 0x140000000uLL;
  else
    return 0;
}

//----- (0000000140002DAB) ----------------------------------------------------
_BOOL8 __fastcall IsNonwritableInCurrentImage(__int64 a1)
{
  __int64 PESection; // [rsp+28h] [rbp-18h]

  if ( !ValidateImageBase(0x140000000LL) )
    return false;
  PESection = FindPESection(0x140000000LL, a1 - 0x140000000LL);
  return PESection != 0 && *(_DWORD *)(PESection + 36) >= 0;
}

//----- (0000000140002E1C) ----------------------------------------------------
__int64 __fastcall _mingw_enum_import_library_names(int a1)
{
  unsigned int v2; // [rsp+34h] [rbp-1Ch]
  __int64 v3; // [rsp+48h] [rbp-8h]

  if ( !ValidateImageBase(0x140000000LL) )
    return 0;
  v2 = *(_DWORD *)(MEMORY[0x14000003C] + 0x140000090LL);
  if ( v2 == 0 )
    return 0;
  if ( FindPESection(0x140000000LL, v2) == 0 )
    return 0;
  v3 = v2 + 0x140000000LL;
  if ( v3 == 0 )
    return 0;
  while ( *(_DWORD *)(v3 + 4) != 0 || *(_DWORD *)(v3 + 12) != 0 )
  {
    if ( a1 <= 0 )
      return *(unsigned int *)(v3 + 12) + 0x140000000LL;
    --a1;
    v3 += 20;
  }
  return 0;
}

//----- (0000000140002F40) ----------------------------------------------------
int __cdecl vfprintf(FILE *const Stream, const char *const Format, va_list ArgList)
{
  return _stdio_common_vfprintf(0, Stream, Format, nullptr, ArgList);
}

//----- (0000000140002F90) ----------------------------------------------------
int scanf(const char *const Format, ...)
{
  FILE *v1; // rax
  va_list va; // [rsp+68h] [rbp+28h] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func_0(0);
  return _stdio_common_vfscanf(0, v1, Format, nullptr, va);
}

//----- (0000000140002FF0) ----------------------------------------------------
int printf(const char *const Format, ...)
{
  FILE *v1; // rax
  va_list va; // [rsp+68h] [rbp+28h] BYREF

  va_start(va, Format);
  v1 = _acrt_iob_func_0(1u);
  return _stdio_common_vfprintf(0, v1, Format, nullptr, va);
}

//----- (0000000140003050) ----------------------------------------------------
int fprintf(FILE *const Stream, const char *const Format, ...)
{
  va_list va; // [rsp+60h] [rbp+20h] BYREF

  va_start(va, Format);
  return _stdio_common_vfprintf(0, Stream, Format, nullptr, va);
}

//----- (00000001400030B0) ----------------------------------------------------
__int64 __fastcall _getmainargs(int *a1, char ***a2, char ***a3, int a4, int *a5)
{
  _crt_argv_mode v5; // eax

  initialize_narrow_environment();
  if ( a4 != 0 )
    v5 = _crt_argv_expanded_arguments;
  else
    v5 = _crt_argv_unexpanded_arguments;
  configure_narrow_argv_0(v5);
  *a1 = *_p___argc();
  *a2 = *_p___argv();
  *a3 = *_p__environ();
  if ( a5 != nullptr )
    set_new_mode_0(*a5);
  return 0;
}

//----- (0000000140003130) ----------------------------------------------------
__int64 __fastcall _wgetmainargs(int *a1, wchar_t ***a2, wchar_t ***a3, int a4, int *a5)
{
  _crt_argv_mode v5; // eax

  initialize_wide_environment();
  if ( a4 != 0 )
    v5 = _crt_argv_expanded_arguments;
  else
    v5 = _crt_argv_unexpanded_arguments;
  configure_wide_argv(v5);
  *a1 = *_p___argc();
  *a2 = *_p___wargv();
  *a3 = *_p__wenviron_0();
  if ( a5 != nullptr )
    set_new_mode_0(*a5);
  return 0;
}

//----- (00000001400031B0) ----------------------------------------------------
_onexit_t __cdecl onexit(_onexit_t Func)
{
  if ( crt_atexit((_PVFV)Func) != 0 )
    return nullptr;
  else
    return Func;
}

//----- (00000001400031DD) ----------------------------------------------------
int __cdecl at_quick_exit(void (__cdecl *a1)())
{
  if ( _mingw_module_is_dll != 0 )
    return 0;
  else
    return crt_at_quick_exit_0(a1);
}

//----- (0000000140003210) ----------------------------------------------------
void __fastcall __noreturn amsg_exit(int a1)
{
  FILE *v1; // rax

  v1 = _acrt_iob_func_0(2u);
  fprintf(v1, "runtime error %d\n", a1);
  exit(255);
}

//----- (0000000140003248) ----------------------------------------------------
__int64 get_output_format()
{
  return 0;
}
// 140003248: using guessed type __int64 get_output_format();

//----- (0000000140003253) ----------------------------------------------------
void __cdecl tzset_0()
{
  _tzset();
  tzname[0] = (char *)_tzname_0();
  *(_QWORD *)&timezone = _timezone();
  *(_QWORD *)&daylight = _daylight_0();
}

//----- (0000000140003292) ----------------------------------------------------
void __cdecl tzset()
{
  tzset_0();
}

//----- (00000001400032A6) ----------------------------------------------------
__int64 _ms_fwprintf(FILE *a1, const wchar_t *a2, ...)
{
  va_list va; // [rsp+60h] [rbp+20h] BYREF

  va_start(va, a2);
  return (unsigned int)_stdio_common_vfwprintf_0(4u, a1, a2, nullptr, va);
}

// nfuncs=112 queued=56 decompiled=56 lumina nreq=0 worse=0 better=0
// ALL OK, 56 function(s) have been successfully decompiled
