;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |                      License info: 14-0000-FFFF-88                      |
; |                       ntkey <admin@hex-rays.com>                        |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : FAA6A550B98DD15B81CD0BFE5BF9B9E545AC6A2C791F07BBA97BA7C7B4D87425
; Input MD5    : 721963C3A5C01F3433EA1C0F6CCC0E33
; Input CRC32  : E564BE29
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Documents/crackme-writeups/authors/sallos/6883d23c8fac2855fe6fb09e/original/escapematrix.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 6883D108 (Fri Jul 25 18:46:32 2025 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 000004BE (   1214.)
; Section size in file          : 00000600 (   1536.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment para public 'CODE' use32
                assume cs:_text
                ;org 401000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

; =============== S U B R O U T I N E =======================================

; Attributes: noreturn

                public start
start           proc near
                push    0               ; lpModuleName
                call    GetModuleHandleA
                mov     hInstance, eax
                call    InitCommonControls
                push    0               ; dwInitParam
                push    offset DialogFunc ; lpDialogFunc
                push    0               ; hWndParent
                push    65h ; 'e'       ; lpTemplateName
                push    hInstance       ; hInstance
                call    DialogBoxParamA
                push    0               ; uExitCode
                call    ExitProcess
start           endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

; INT_PTR __stdcall DialogFunc(HWND, UINT, WPARAM, LPARAM)
DialogFunc      proc near               ; DATA XREF: start+13↑o

hDlg            = dword ptr  8
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                mov     eax, [ebp+arg_4]
                cmp     eax, 110h
                jnz     loc_401150
                push    40h ; '@'
                push    offset String
                call    RtlZeroMemory
                push    3E9h            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    0               ; lParam
                push    0               ; wParam
                push    31h ; '1'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                or      eax, eax
                jz      loc_4012CA
                push    offset pv       ; pv
                push    3Ch ; '<'       ; c
                push    eax             ; h
                call    GetObjectA
                mov     pv.lfHeight, 0FFFFFFF0h
                push    offset pv       ; lplf
                call    CreateFontIndirectA
                mov     wParam, eax
                push    6Eh ; 'n'       ; dwBytes
                push    0               ; uFlags
                call    GlobalAlloc
                mov     hMem, eax
                mov     dword ptr [eax], 53E24B7Dh
                push    3E9h            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    1               ; lParam
                push    wParam          ; wParam
                push    30h ; '0'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                push    3EDh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    1               ; lParam
                push    wParam          ; wParam
                push    30h ; '0'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                push    3EAh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    1               ; lParam
                push    wParam          ; wParam
                push    30h ; '0'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                push    3EBh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    1               ; lParam
                push    wParam          ; wParam
                push    30h ; '0'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                push    3ECh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    1               ; lParam
                push    wParam          ; wParam
                push    30h ; '0'       ; Msg
                push    eax             ; hWnd
                call    SendMessageA
                push    4               ; dwBytes
                push    0               ; uFlags
                call    GlobalAlloc
                mov     dword_403170, eax
                mov     dword ptr [eax], 1AFB0261h
                jmp     loc_4012CA
; ---------------------------------------------------------------------------

loc_401150:                             ; CODE XREF: DialogFunc+B↑j
                cmp     eax, 111h
                jnz     loc_40129A
                mov     esi, 16EE4E13h
                push    esi
                mov     esi, 17AF4F72h
                push    esi
                lea     ebx, loc_40129F
                add     ebx, 13228F73h
                mov     edx, [ebp+arg_8]
                movzx   eax, dx
                shr     edx, 10h
                or      edx, edx
                jnz     loc_4012CA
                sub     ebx, offset loc_40129F
                cmp     eax, 3EAh
                jnz     short loc_4011B4
                push    16h             ; int
                push    offset Caption  ; lpCaption
                push    3Ch ; '<'       ; int
                push    offset Text     ; lpText
                push    [ebp+hDlg]      ; hWnd
                call    sub_4012D3
                jmp     loc_40129F
; ---------------------------------------------------------------------------
                jmp     loc_401298
; ---------------------------------------------------------------------------

loc_4011B4:                             ; CODE XREF: DialogFunc+161↑j
                cmp     eax, 3EBh
                jnz     loc_401298
                push    3EAh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    0               ; bEnable
                push    eax             ; hWnd
                call    EnableWindow
                mov     edi, esp
                push    3Fh ; '?'       ; cchMax
                push    offset String   ; lpString
                push    3ECh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItemTextA
                push    offset String   ; lpString
                call    lstrlenA
                push    eax
                push    offset String
                push    [ebp+hDlg]
                call    sub_401349
                or      eax, eax
                jnz     short loc_401223
                push    1Bh             ; int
                push    offset byte_4030A1 ; lpCaption
                push    60h ; '`'       ; int
                push    offset dword_4030BC ; lpText
                push    [ebp+hDlg]      ; hWnd
                call    sub_4012D3
                jmp     short loc_40129F
; ---------------------------------------------------------------------------
                jmp     short loc_401298
; ---------------------------------------------------------------------------

loc_401223:                             ; CODE XREF: DialogFunc+1D6↑j
                push    3EDh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    GetDlgItem
                push    5               ; nCmdShow
                push    eax             ; hWnd
                call    ShowWindow
                xor     eax, eax
                mov     al, byte_40311C
                and     al, 1
                cmp     eax, 1
                jnz     short loc_401270
                push    24h ; '$'       ; int
                push    offset word_403056 ; lpString
                push    3E9h            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    sub_401420
                push    23h ; '#'       ; int
                push    offset word_40307A ; lpString
                push    3EDh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    sub_401420
                jmp     short loc_401298
; ---------------------------------------------------------------------------

loc_401270:                             ; CODE XREF: DialogFunc+216↑j
                push    19h             ; int
                push    offset byte_40311D ; lpString
                push    3E9h            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    sub_401420
                push    2Ch ; ','       ; int
                push    offset word_403136 ; lpString
                push    3EDh            ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    sub_401420

loc_401298:                             ; CODE XREF: DialogFunc+181↑j
                                        ; DialogFunc+18B↑j ...
                jmp     short loc_4012CA
; ---------------------------------------------------------------------------

loc_40129A:                             ; CODE XREF: DialogFunc+127↑j
                cmp     eax, 10h
                jnz     short loc_4012C1

loc_40129F:                             ; CODE XREF: DialogFunc+17C↑j
                                        ; DialogFunc+1F1↑j
                                        ; DATA XREF: ...
                push    hMem            ; hMem
                call    GlobalFree
                push    dword_403170    ; hMem
                call    GlobalFree
                push    0               ; nResult
                push    [ebp+hDlg]      ; hDlg
                call    EndDialog
                jmp     short loc_4012CA
; ---------------------------------------------------------------------------

loc_4012C1:                             ; CODE XREF: DialogFunc+26F↑j
                mov     eax, 0
                leave
                retn    10h
; ---------------------------------------------------------------------------

loc_4012CA:                             ; CODE XREF: DialogFunc+38↑j
                                        ; DialogFunc+11D↑j ...
                mov     eax, 1
                leave
                retn    10h
DialogFunc      endp ; sp-analysis failed


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

; int __stdcall sub_4012D3(HWND hWnd, LPCSTR lpText, int, LPCSTR lpCaption, int)
sub_4012D3      proc near               ; CODE XREF: DialogFunc+177↑p
                                        ; DialogFunc+1EC↑p

hWnd            = dword ptr  8
lpText          = dword ptr  0Ch
arg_8           = dword ptr  10h
lpCaption       = dword ptr  14h
arg_10          = dword ptr  18h

                push    ebp
                mov     ebp, esp
                push    ebx
                push    esi
                push    edi
                push    [ebp+arg_8]
                push    [ebp+lpText]
                call    sub_40131C
                push    [ebp+arg_10]
                push    [ebp+lpCaption]
                call    sub_40131C
                push    0               ; uType
                push    [ebp+lpCaption] ; lpCaption
                push    [ebp+lpText]    ; lpText
                push    [ebp+hWnd]      ; hWnd
                call    MessageBoxA
                push    [ebp+arg_8]
                push    [ebp+lpText]
                call    sub_40131C
                push    [ebp+arg_10]
                push    [ebp+lpCaption]
                call    sub_40131C
                pop     edi
                pop     esi
                pop     ebx
                leave
                retn    14h
sub_4012D3      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_40131C      proc near               ; CODE XREF: sub_4012D3+C↑p
                                        ; sub_4012D3+17↑p ...

var_4           = dword ptr -4
arg_0           = dword ptr  8
arg_4           = dword ptr  0Ch

                push    ebp
                mov     ebp, esp
                push    ebx
                mov     edi, [ebp+arg_0]
                mov     esi, [ebp+arg_0]
                mov     ecx, [ebp+arg_4]
                xor     eax, eax
                jmp     short loc_401336
; ---------------------------------------------------------------------------

loc_40132D:                             ; CODE XREF: sub_40131C+24↓j
                dec     ecx
                cmp     ecx, 0
                jz      short loc_401344
                mov     ebx, [esp+4+var_4]

loc_401336:                             ; CODE XREF: sub_40131C+F↑j
                                        ; sub_40131C+26↓j
                lodsb
                xor     al, bl
                shr     ebx, 8
                stosb
                cmp     ebx, 0
                jz      short loc_40132D
                loop    loc_401336

loc_401344:                             ; CODE XREF: sub_40131C+15↑j
                pop     ebx
                leave
                retn    8
sub_40131C      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

sub_401349      proc near               ; CODE XREF: DialogFunc+1CF↑p

var_C           = dword ptr -0Ch
var_8           = dword ptr -8
var_4           = dword ptr -4
arg_4           = dword ptr  0Ch
arg_8           = dword ptr  10h

                push    ebp
                mov     ebp, esp
                add     esp, 0FFFFFFF8h
                push    ebx
                xor     eax, eax
                mov     [ebp+var_4], eax
                mov     esi, [ebp+arg_4]
                mov     eax, dword_403000
                mov     [ebp+var_8], eax

loc_401360:                             ; CODE XREF: sub_401349+B1↓j
                xor     ecx, ecx
                mov     ecx, 4
                xor     eax, eax

loc_401369:                             ; CODE XREF: sub_401349+2B↓j
                lodsb
                xor     al, bl
                shr     ebx, 8
                shl     edx, 8
                mov     dl, al
                loop    loc_401369
                mov     eax, [ebp+var_4]
                or      eax, eax
                jnz     short loc_40138F
                mov     eax, [ebp+var_8]
                mov     ecx, hMem
                mov     ecx, [ecx]
                mov     [ebp+var_8], ecx
                xor     ecx, ecx
                jmp     short loc_4013EC
; ---------------------------------------------------------------------------

loc_40138F:                             ; CODE XREF: sub_401349+32↑j
                cmp     eax, 1
                jnz     short loc_4013A2
                mov     eax, [ebp+var_8]
                mov     ecx, edi
                mov     ecx, [ecx]
                mov     [ebp+var_8], ecx
                xor     ecx, ecx
                jmp     short loc_4013EC
; ---------------------------------------------------------------------------

loc_4013A2:                             ; CODE XREF: sub_401349+49↑j
                cmp     eax, 2
                jnz     short loc_4013B7
                mov     eax, [ebp+var_8]
                mov     ecx, dword_40309D
                mov     [ebp+var_8], ecx
                xor     ecx, ecx
                jmp     short loc_4013EC
; ---------------------------------------------------------------------------

loc_4013B7:                             ; CODE XREF: sub_401349+5C↑j
                cmp     eax, 3
                jnz     short loc_4013CE
                mov     eax, [ebp+var_8]
                mov     ecx, dword_403170
                mov     ecx, [ecx]
                mov     [ebp+var_8], ecx
                xor     ecx, ecx
                jmp     short loc_4013EC
; ---------------------------------------------------------------------------

loc_4013CE:                             ; CODE XREF: sub_401349+71↑j
                cmp     eax, 4
                jnz     short loc_4013E2
                mov     eax, [ebp+var_8]
                lea     ecx, [edi-4]
                mov     ecx, [ecx]
                mov     [ebp+var_8], ecx
                xor     ecx, ecx
                jmp     short loc_4013EC
; ---------------------------------------------------------------------------

loc_4013E2:                             ; CODE XREF: sub_401349+88↑j
                mov     ecx, 17h
                cmp     ecx, [ebp+arg_8]
                jz      short loc_401409

loc_4013EC:                             ; CODE XREF: sub_401349+44↑j
                                        ; sub_401349+57↑j ...
                xor     edx, eax
                mov     ebx, [esp+0Ch+var_C]
                mov     ecx, [ebp+var_4]
                lea     ecx, [ecx+1]
                mov     [ebp+var_4], ecx
                jz      loc_401360
                xor     eax, eax
                mov     eax, 1
                jmp     short loc_40140B
; ---------------------------------------------------------------------------

loc_401409:                             ; CODE XREF: sub_401349+A1↑j
                xor     eax, eax

loc_40140B:                             ; CODE XREF: sub_401349+BE↑j
                xor     edx, edx
                mov     dl, byte_40311C
                inc     dl
                mov     byte_40311C, dl
                pop     ebx
                leave
                retn    0Ch
sub_401349      endp


; =============== S U B R O U T I N E =======================================

; Attributes: bp-based frame

; int __stdcall sub_401420(HWND hDlg, int nIDDlgItem, LPCSTR lpString, int)
sub_401420      proc near               ; CODE XREF: DialogFunc+227↑p
                                        ; DialogFunc+23B↑p ...

hDlg            = dword ptr  8
nIDDlgItem      = dword ptr  0Ch
lpString        = dword ptr  10h
arg_C           = dword ptr  14h

                push    ebp
                mov     ebp, esp
                push    ebx
                push    esi
                push    edi
                push    [ebp+arg_C]
                push    [ebp+lpString]
                call    sub_40131C
                push    [ebp+lpString]  ; lpString
                push    [ebp+nIDDlgItem] ; nIDDlgItem
                push    [ebp+hDlg]      ; hDlg
                call    SetDlgItemTextA
                push    [ebp+arg_C]
                push    [ebp+lpString]
                call    sub_40131C
                pop     edi
                pop     esi
                pop     ebx
                leave
                retn    10h
sub_401420      endp

; ---------------------------------------------------------------------------
                align 2
; [00000006 BYTES: COLLAPSED FUNCTION CreateFontIndirectA]
; [00000006 BYTES: COLLAPSED FUNCTION GetObjectA]
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION GetModuleHandleA]
; [00000006 BYTES: COLLAPSED FUNCTION GlobalAlloc]
; [00000006 BYTES: COLLAPSED FUNCTION GlobalFree]
; [00000006 BYTES: COLLAPSED FUNCTION RtlZeroMemory]
; [00000006 BYTES: COLLAPSED FUNCTION lstrlenA]
; [00000006 BYTES: COLLAPSED FUNCTION DialogBoxParamA]
; [00000006 BYTES: COLLAPSED FUNCTION EnableWindow]
; [00000006 BYTES: COLLAPSED FUNCTION EndDialog]
; [00000006 BYTES: COLLAPSED FUNCTION GetDlgItem]
; [00000006 BYTES: COLLAPSED FUNCTION GetDlgItemTextA]
; [00000006 BYTES: COLLAPSED FUNCTION MessageBoxA]
; [00000006 BYTES: COLLAPSED FUNCTION SendMessageA]
; [00000006 BYTES: COLLAPSED FUNCTION SetDlgItemTextA]
; [00000006 BYTES: COLLAPSED FUNCTION ShowWindow]
; [00000006 BYTES: COLLAPSED FUNCTION InitCommonControls]
                align 200h
                dd 280h dup(?)
_text           ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 00000266 (    614.)
; Section size in file          : 00000400 (   1024.)
; Offset to raw data for section: 00000A00
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from KERNEL32.dll
;
; ===========================================================================

; Segment type: Externs
; _idata
; int (__stdcall *lstrlenA)(LPCSTR lpString)
                extrn __imp_lstrlenA:dword ; DATA XREF: lstrlenA↑r
                                        ; .rdata:0040207C↓o
                                        ; KERNEL32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
                extrn __imp_ExitProcess:dword ; DATA XREF: ExitProcess↑r
                                        ; KERNEL32
; HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName)
                extrn __imp_GetModuleHandleA:dword ; DATA XREF: GetModuleHandleA↑r
                                        ; KERNEL32
                extrn __imp_RtlZeroMemory:dword ; DATA XREF: RtlZeroMemory↑r
                                        ; KERNEL32
; HGLOBAL (__stdcall *GlobalFree)(HGLOBAL hMem)
                extrn __imp_GlobalFree:dword ; DATA XREF: GlobalFree↑r
                                        ; KERNEL32
; HGLOBAL (__stdcall *GlobalAlloc)(UINT uFlags, SIZE_T dwBytes)
                extrn __imp_GlobalAlloc:dword ; DATA XREF: GlobalAlloc↑r
                                        ; KERNEL32

;
; Imports from comctl32.dll
;
; void (__stdcall *InitCommonControls)()
                extrn __imp_InitCommonControls:dword
                                        ; DATA XREF: InitCommonControls↑r
                                        ; .rdata:004020A4↓o
                                        ; comctl32

;
; Imports from gdi32.dll
;
; int (__stdcall *GetObjectA)(HANDLE h, int c, LPVOID pv)
                extrn __imp_GetObjectA:dword ; DATA XREF: GetObjectA↑r
                                        ; .rdata:00402068↓o
                                        ; gdi32
; HFONT (__stdcall *CreateFontIndirectA)(const LOGFONTA *lplf)
                extrn __imp_CreateFontIndirectA:dword
                                        ; DATA XREF: CreateFontIndirectA↑r
                                        ; gdi32

;
; Imports from user32.dll
;
; BOOL (__stdcall *EnableWindow)(HWND hWnd, BOOL bEnable)
                extrn __imp_EnableWindow:dword ; DATA XREF: EnableWindow↑r
                                        ; .rdata:00402090↓o
                                        ; user32
; BOOL (__stdcall *EndDialog)(HWND hDlg, INT_PTR nResult)
                extrn __imp_EndDialog:dword ; DATA XREF: EndDialog↑r
                                        ; user32
; HWND (__stdcall *GetDlgItem)(HWND hDlg, int nIDDlgItem)
                extrn __imp_GetDlgItem:dword ; DATA XREF: GetDlgItem↑r
                                        ; user32
; UINT (__stdcall *GetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax)
                extrn __imp_GetDlgItemTextA:dword ; DATA XREF: GetDlgItemTextA↑r
                                        ; user32
; int (__stdcall *MessageBoxA)(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType)
                extrn __imp_MessageBoxA:dword ; DATA XREF: MessageBoxA↑r
                                        ; user32
; LRESULT (__stdcall *SendMessageA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
                extrn __imp_SendMessageA:dword ; DATA XREF: SendMessageA↑r
                                        ; user32
; BOOL (__stdcall *SetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPCSTR lpString)
                extrn __imp_SetDlgItemTextA:dword ; DATA XREF: SetDlgItemTextA↑r
                                        ; user32
; BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow)
                extrn __imp_ShowWindow:dword ; DATA XREF: ShowWindow↑r
                                        ; user32
; INT_PTR (__stdcall *DialogBoxParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam)
                extrn __imp_DialogBoxParamA:dword ; DATA XREF: DialogBoxParamA↑r
                                        ; user32


; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_rdata          segment para public 'DATA' use32
                assume cs:_rdata
                ;org 402058h
__IMPORT_DESCRIPTOR_gdi32 dd rva off_4020E0 ; Import Name Table
                dd 0                    ; Time stamp
                dd 0                    ; Forwarder Chain
                dd rva aGdi32Dll        ; DLL Name
                dd rva __imp_GetObjectA ; Import Address Table
__IMPORT_DESCRIPTOR_KERNEL32 dd rva off_4020BC ; Import Name Table
                dd 0                    ; Time stamp
                dd 0                    ; Forwarder Chain
                dd rva aKernel32Dll     ; DLL Name
                dd rva __imp_lstrlenA   ; Import Address Table
__IMPORT_DESCRIPTOR_user32 dd rva off_4020EC ; Import Name Table
                dd 0                    ; Time stamp
                dd 0                    ; Forwarder Chain
                dd rva aUser32Dll       ; DLL Name
                dd rva __imp_EnableWindow ; Import Address Table
__IMPORT_DESCRIPTOR_comctl32 dd rva off_4020D8 ; Import Name Table
                dd 0                    ; Time stamp
                dd 0                    ; Forwarder Chain
                dd rva aComctl32Dll     ; DLL Name
                dd rva __imp_InitCommonControls ; Import Address Table
                dd 5 dup(0)
;
; Import names for KERNEL32.dll
;
off_4020BC      dd rva word_402190      ; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_KERNEL32↑o
                dd rva word_402142
                dd rva word_402150
                dd rva word_402180
                dd rva word_402172
                dd rva word_402164
                dd 0
;
; Import names for comctl32.dll
;
off_4020D8      dd rva word_402242      ; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_comctl32↑o
                dd 0
;
; Import names for gdi32.dll
;
off_4020E0      dd rva word_40212A      ; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_gdi32↑o
                dd rva word_402114
                dd 0
;
; Import names for user32.dll
;
off_4020EC      dd rva word_4021BC      ; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_user32↑o
                dd rva word_4021CC
                dd rva word_4021D8
                dd rva word_4021E6
                dd rva word_4021F8
                dd rva word_402206
                dd rva word_402216
                dd rva word_402228
                dd rva word_4021AA
                dd 0
word_402114     dw 2Fh                  ; DATA XREF: .rdata:004020E4↑o
                db 'CreateFontIndirectA',0
word_40212A     dw 0CDh                 ; DATA XREF: .rdata:off_4020E0↑o
                db 'GetObjectA',0
                align 4
aGdi32Dll       db 'gdi32.dll',0        ; DATA XREF: .rdata:00402064↑o
word_402142     dw 119h                 ; DATA XREF: .rdata:004020C0↑o
                db 'ExitProcess',0
word_402150     dw 215h                 ; DATA XREF: .rdata:004020C4↑o
                db 'GetModuleHandleA',0
                align 4
word_402164     dw 2B3h                 ; DATA XREF: .rdata:004020D0↑o
                db 'GlobalAlloc',0
word_402172     dw 2BAh                 ; DATA XREF: .rdata:004020CC↑o
                db 'GlobalFree',0
                align 10h
word_402180     dw 419h                 ; DATA XREF: .rdata:004020C8↑o
                db 'RtlZeroMemory',0
word_402190     dw 54Dh                 ; DATA XREF: .rdata:off_4020BC↑o
                db 'lstrlenA',0
                align 4
aKernel32Dll    db 'KERNEL32.dll',0     ; DATA XREF: .rdata:00402078↑o
                align 2
word_4021AA     dw 8Ah                  ; DATA XREF: .rdata:0040210C↑o
                db 'DialogBoxParamA',0
word_4021BC     dw 0ABh                 ; DATA XREF: .rdata:off_4020EC↑o
                db 'EnableWindow',0
                align 4
word_4021CC     dw 0ADh                 ; DATA XREF: .rdata:004020F0↑o
                db 'EndDialog',0
word_4021D8     dw 0F2h                 ; DATA XREF: .rdata:004020F4↑o
                db 'GetDlgItem',0
                align 2
word_4021E6     dw 0F4h                 ; DATA XREF: .rdata:004020F8↑o
                db 'GetDlgItemTextA',0
word_4021F8     dw 19Dh                 ; DATA XREF: .rdata:004020FC↑o
                db 'MessageBoxA',0
word_402206     dw 1E2h                 ; DATA XREF: .rdata:00402100↑o
                db 'SendMessageA',0
                align 2
word_402216     dw 1F8h                 ; DATA XREF: .rdata:00402104↑o
                db 'SetDlgItemTextA',0
word_402228     dw 22Dh                 ; DATA XREF: .rdata:00402108↑o
                db 'ShowWindow',0
                align 2
aUser32Dll      db 'user32.dll',0       ; DATA XREF: .rdata:0040208C↑o
                align 2
word_402242     dw 3Eh                  ; DATA XREF: .rdata:off_4020D8↑o
                db 'InitCommonControls',0
                align 4
aComctl32Dll    db 'comctl32.dll',0     ; DATA XREF: .rdata:004020A0↑o
                align 1000h
_rdata          ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 000001F0 (    496.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000E00
; Flags C0000040: Data Readable Writable
; Alignment     : default
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment para public 'DATA' use32
                assume cs:_data
                ;org 403000h
dword_403000    dd 2AE05761h            ; DATA XREF: sub_401349+F↑r
; CHAR Caption[]
Caption         dd 3347E727h, 6156EE3Eh, 7B02F71Ah, 6A02FC12h, 3D0CFA1Ch
                                        ; DATA XREF: DialogFunc+165↑o
                db 5Dh, 8Fh
; CHAR Text[]
Text            dw 0EA3Dh               ; DATA XREF: DialogFunc+16F↑o
                dd 0FC533F4Dh, 0EA1D7C4Dh, 0FD1C3350h, 0FB127F02h, 0F6536147h
                dd 0FD54664Dh, 0E0143347h, 0AF147D4Bh, 0FD537C56h, 0E61F7247h
                dd 0AF5F7658h, 0FB006648h, 0AF007202h, 0E617336Bh
                db 46h, 13h
; CHAR word_403056[]
word_403056     dw 0AF3Ah               ; DATA XREF: DialogFunc+21A↑o
                dd 0E1177A46h, 0FC536705h, 0E6536A43h, 0E0043356h, 0AF177F57h
                dd 0EA537640h, 0A30A6043h, 0E0165D02h
                db 0Ch, 13h
; CHAR word_40307A[]
word_40307A     dw 0AF3Ah               ; DATA XREF: DialogFunc+22E↑o
                dd 0FB006648h, 0E6126002h, 0FB1A3346h, 0FA1C6402h, 0ED53774Eh
                dd 0E7073347h, 0FD073347h, 0A11B6757h
                db 22h
dword_40309D    dd 18EA5133h            ; DATA XREF: sub_401349+61↑r
; CHAR byte_4030A1[]
byte_4030A1     db 24h, 0EAh, 4Eh       ; DATA XREF: DialogFunc+1DA↑o
                dd 47E21C70h, 2E00733h, 2EA1B67h, 4EEE1661h, 50E00433h
                dd 22A1177Fh
; CHAR dword_4030BC[]
dword_4030BC    dd 3457E02Ah, 6102E31Fh, 7E47E216h, 3350EA11h, 3357E00Ah
                                        ; DATA XREF: DialogFunc+1E4↑o
                dd 344CE017h, 7640AF07h, 6547E61Fh, 7D4BAF16h, 6A4CEE53h
                dd 3344E053h, 604BE707h, 6743E953h, 6141AF16h, 330CFF12h
                dd 3457E02Ah, 7A02EA01h, 7C41AF1Dh, 7C50FB1Dh, 754DAF1Fh
                dd 664DF653h, 644DAF01h, 7A4EAF1Dh, 130CEA15h
byte_40311C     db 0                    ; DATA XREF: DialogFunc+20C↑r
                                        ; sub_401349+C4↑r ...
; CHAR byte_40311D[]
byte_40311D     db 2Ah, 0E0h, 57h       ; DATA XREF: DialogFunc+244↑o
                dd 2EA0134h, 56FC1275h, 56AF0176h, 2E1127Bh, 51E61B67h
                db 3Dh, 73h
; CHAR word_403136[]
word_403136     dw 0E037h               ; DATA XREF: DialogFunc+258↑o
                dd 0AF07344Ch, 0E11A7B56h, 0E00A3349h, 0FD123357h, 0E4533F47h
                dd 0AF047C4Ch, 0AF067C5Bh, 0A166143h, 0E21C5002h, 0E11C3347h
                dd 130Ch
; HINSTANCE hInstance
hInstance       dd 0                    ; DATA XREF: start+7↑w start+1C↑r
; WPARAM wParam
wParam          dd 0                    ; DATA XREF: DialogFunc+5F↑w
                                        ; DialogFunc+87↑r ...
; HGLOBAL hMem
hMem            dd 0                    ; DATA XREF: DialogFunc+6D↑w
                                        ; DialogFunc:loc_40129F↑r ...
; HGLOBAL dword_403170
dword_403170    dd 0                    ; DATA XREF: DialogFunc+112↑w
                                        ; DialogFunc+27C↑r ...
; CHAR String[64]
String          db 40h dup(0)           ; DATA XREF: DialogFunc+13↑o
                                        ; DialogFunc+1AA↑o ...
; LOGFONTA pv
pv              LOGFONTA <0>            ; DATA XREF: DialogFunc+3E↑o
                                        ; DialogFunc+4B↑w ...
                align 1000h
_data           ends


                end start
