;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : E851D0C3426F6CC558FD0ADAB5A7BAB84EAB69603EE21B418DADCEAA210C16DE
; Input MD5    : 3EE57072020F7B5666B4A9FAD51269F8
; Input CRC32  : 9CC776E5
; Compiler     : GNU C++

; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-02/timotei-crackme-02
; Format      : ELF64 for x86-64 (Executable)
; Imagebase   : 400000
;

.686p
.mmx
.model flat
.intel_syntax noprefix


; Segment type: Pure data
; Segment permissions: Read
LOAD segment mempage public 'DATA' use64
assume cs:LOAD
;org 400000h
dword_400000 dd 464C457Fh ; File format: \x7FELF
db 2                    ; File class: 64-bit
db 1                    ; Data encoding: little-endian
db 1                    ; File version
db 0                    ; OS/ABI: UNIX System V ABI
db 0                    ; ABI Version
db 7 dup(0)             ; Padding
dw 2                    ; File type: Executable
dw 3Eh                  ; Machine: x86-64
dd 1                    ; File version
dq offset start         ; Entry point
dq 40h                  ; PHT file offset
dq 2140h                ; SHT file offset
dd 0                    ; Processor-specific flags
dw 40h                  ; ELF header size
dw 38h                  ; PHT entry size
dw 3                    ; Number of entries in PHT
dw 40h                  ; SHT entry size
dw 4                    ; Number of entries in SHT
dw 3                    ; SHT entry index for string table
; ELF64 Program Header
; PHT Entry 0
dd 1                    ; Type: LOAD
dd 4                    ; Flags
dq 0                    ; File offset
dq offset dword_400000  ; Virtual address
dq 400000h              ; Physical address
dq 0E8h                 ; Size in file image
dq 0E8h                 ; Size in memory image
dq 1000h                ; Alignment
; PHT Entry 1
dd 1                    ; Type: LOAD
dd 5                    ; Flags
dq 1000h                ; File offset
dq offset start         ; Virtual address
dq 401000h              ; Physical address
dq 73h                  ; Size in file image
dq 73h                  ; Size in memory image
dq 1000h                ; Alignment
; PHT Entry 2
dd 1                    ; Type: LOAD
dd 6                    ; Flags
dq 2000h                ; File offset
dq offset aTimoteiCrackme ; Virtual address
dq 402000h              ; Physical address
dq 125h                 ; Size in file image
dq 125h                 ; Size in memory image
dq 1000h                ; Alignment
LOAD ends


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use64
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing



public start
start proc near

arg_8= qword ptr  10h

cmp     byte ptr [rsp+0], 2
jnz     short loc_401069
mov     rdi, [rsp+arg_8]
sub     ecx, ecx
sub     al, al
not     ecx
cld
repne scasb
not     ecx
dec     ecx
cmp     ecx, 3
jle     short loc_401069
sub     rbx, rbx
sub     rdi, rdi
mov     rax, [rsp+arg_8]

loc_401028:
mov     bl, [rax]
rol     rbx, 8
inc     rax
dec     ecx
jnz     short loc_401028
add     rbx, 0AFDCh
mov     di, bx

loc_40103F:
mov     rax, offset loc_40103F
add     rax, rdi
jmp     rax
mov     eax, 1
mov     edi, 1          ; fd
mov     rsi, offset buf ; buf
mov     edx, 2Fh ; '/'  ; count
syscall                 ; LINUX - sys_write

loc_401069:
mov     eax, 3Ch ; '<'
xor     rdi, rdi        ; error_code
syscall                 ; LINUX - sys_exit
start endp

_text ends


; Segment type: Pure data
; Segment permissions: Read/Write
_data segment dword public 'DATA' use64
assume cs:_data
;org 402000h
aTimoteiCrackme db '._:timotei crackme#2:_:.',0
aGreetzFlyOutTo db ':.greetz fly out to jeffli6789 & Bi'
db 'naryNewbie..',0
; char buf[21]
buf db '_.:pass accepted:._',0Ah,0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
_data ends


end start
