/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall start(); // weak
void sub_4001B4();
void sub_4001B8();
void sub_4001BC();
void sub_4001C0();
void sub_4001C4();
void sub_4001C8();
void sub_4001CC();
void sub_4001D0();
void sub_4001D4();
void sub_4001D8();
void sub_4001DC();
void sub_4001E0();
void sub_4001E4();
void sub_4001E8();
void sub_4001EC();
void sub_4001F0();

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *funcs_400176[8])() =
{
  &sub_4001B4,
  &sub_4001B8,
  &sub_4001BC,
  &sub_4001C0,
  &sub_4001C4,
  &sub_4001C8,
  &sub_4001CC,
  &sub_4001D0
}; // weak
__int64 (__fastcall *funcs_4001A8[8])() =
{
  &sub_4001D4,
  &sub_4001D8,
  &sub_4001DC,
  &sub_4001E0,
  &sub_4001E4,
  &sub_4001E8,
  &sub_4001EC,
  &sub_4001F0
}; // weak
int dword_6008E8 = 0; // weak
int dword_6008EC = 35651618; // weak
int dword_6008F0 = 834666506; // weak
int dword_6008F4 = 834666513; // weak
int dword_6008F8 = 622854151; // weak
int dword_6008FC = 35651652; // weak
int dword_600900 = 536870920; // weak


//----- (00000000004000B0) ----------------------------------------------------
__int64 __fastcall start()
{
  int v0; // r12d
  int v1; // r13d
  __int64 v2; // r15
  int v3; // ecx
  unsigned int v4; // eax
  __int64 v5; // rbx
  unsigned int v6; // eax
  __int64 v7; // rcx
  unsigned int v8; // et2
  __int64 v10; // rdx
  __int64 v11; // rcx
  __int64 v12; // rdi
  __int64 v13; // rsi
  __int64 v14; // r8
  __int64 v15; // r9
  __int64 v16; // r10
  __int64 v17; // r11
  signed __int64 v18; // rax
  __int64 v19; // rax
  __int64 v20; // rbp
  int v21; // edi
  char v22[16]; // [rsp+0h] [rbp-58h] BYREF
  __int64 v23; // [rsp+10h] [rbp-48h] BYREF
  __int64 v24; // [rsp+18h] [rbp-40h]
  __int64 v25; // [rsp+20h] [rbp-38h]
  __int64 v26; // [rsp+28h] [rbp-30h]
  __int64 v27; // [rsp+30h] [rbp-28h]
  __int64 v28; // [rsp+38h] [rbp-20h]
  __int64 v29; // [rsp+40h] [rbp-18h]
  __int64 v30; // [rsp+48h] [rbp-10h]
  __int64 v31; // [rsp+50h] [rbp-8h]

  v3 = 0;
  while ( 2 )
  {
    v4 = HIWORD(*(_DWORD *)(unsigned int)((_DWORD)&dword_6008E8 + 4 * v3));
    v31 = v4;
    v19 = v4 & 7;
    v20 = (unsigned int)v19;
    if ( (_DWORD)v19 != 0 )
      funcs_400176[v19]();
    v5 = BYTE1(v31);
    funcs_400176[(unsigned __int8)v31 >> 5]();
    v18 = v31;
    switch ( v5 )
    {
      case 0LL:
      case 2LL:
      case 5LL:
      case 6LL:
      case 7LL:
      case 8LL:
      case 9LL:
      case 10LL:
      case 11LL:
      case 12LL:
      case 13LL:
      case 14LL:
      case 15LL:
      case 16LL:
      case 17LL:
      case 18LL:
      case 21LL:
      case 22LL:
      case 23LL:
      case 24LL:
      case 27LL:
      case 28LL:
      case 29LL:
      case 30LL:
      case 31LL:
      case 32LL:
      case 33LL:
      case 34LL:
      case 35LL:
      case 36LL:
      case 37LL:
      case 38LL:
      case 39LL:
      case 40LL:
      case 41LL:
      case 42LL:
      case 43LL:
      case 44LL:
      case 45LL:
      case 46LL:
      case 47LL:
      case 48LL:
      case 55LL:
      case 56LL:
      case 57LL:
      case 58LL:
      case 59LL:
      case 60LL:
      case 61LL:
      case 62LL:
      case 63LL:
      case 64LL:
      case 65LL:
      case 66LL:
      case 67LL:
      case 68LL:
      case 69LL:
      case 70LL:
      case 71LL:
      case 72LL:
      case 73LL:
      case 74LL:
      case 75LL:
      case 76LL:
      case 77LL:
      case 78LL:
      case 79LL:
      case 80LL:
      case 81LL:
      case 82LL:
      case 83LL:
      case 84LL:
      case 85LL:
      case 86LL:
      case 87LL:
      case 88LL:
      case 89LL:
      case 90LL:
      case 91LL:
      case 92LL:
      case 93LL:
      case 94LL:
      case 95LL:
      case 96LL:
      case 97LL:
      case 98LL:
      case 99LL:
      case 100LL:
      case 101LL:
      case 102LL:
      case 103LL:
      case 104LL:
      case 105LL:
      case 106LL:
      case 107LL:
      case 108LL:
      case 109LL:
      case 110LL:
      case 111LL:
        goto LABEL_12;
      case 1LL:
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008E8 + 4 * v10) = v12;
        goto LABEL_12;
      case 3LL:
        if ( v10 == 6 )
        {
          v30 = v11;
          v29 = v13;
          v28 = v14;
          v27 = v15;
          v26 = v16;
          v25 = v17;
          v24 = v2;
          v23 = 0;
          sys_read(0, (char *)&v23, 1u);
          v2 = v24;
          LOBYTE(v18) = v31;
        }
        goto LABEL_12;
      case 4LL:
        if ( v10 != 0 )
        {
          if ( v10 == 7 )
          {
            v30 = v11;
            v29 = v13;
            v28 = v14;
            v27 = v15;
            v26 = v16;
            v25 = v17;
            v24 = v2;
            v23 = v12;
            sys_write(1u, (const char *)&v23, 1u);
            v2 = v24;
            LOBYTE(v18) = v31;
          }
LABEL_12:
          funcs_4001A8[(unsigned __int8)v18 >> 5]();
          continue;
        }
        v31 = 4194921;
LABEL_6:
        v31 = v18;
        v30 = v11;
        v29 = v13;
        v28 = v14;
        v27 = v15;
        v26 = v16;
        v25 = v17;
        v24 = v2;
        v23 = v12;
        v6 = v12;
        v7 = 9;
        do
        {
          v8 = v6 % 0xA;
          v6 /= 0xAu;
          v22[v7] = v8 + 48;
          v7 = (unsigned int)(v7 - 1);
        }
        while ( v6 != 0 );
        sys_write(1u, &v22[v7 + 1], (unsigned int)(9 - v7));
        return v31;
      case 19LL:
        LOBYTE(v18) = v31;
        goto LABEL_12;
      case 20LL:
        LOBYTE(v18) = v31;
        goto LABEL_12;
      case 25LL:
        v31 = v11;
        goto LABEL_12;
      case 26LL:
        v31 = v11;
        goto LABEL_12;
      case 49LL:
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008EC + 4 * v12) = v11;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008F0 + 4 * v12) = v2;
        v2 = (unsigned int)(v12 + 2);
        goto LABEL_12;
      case 50LL:
        v2 = *(unsigned int *)(unsigned int)((_DWORD)&dword_6008F0 + 4 * (v12 - 2));
        goto LABEL_12;
      case 51LL:
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008E8 + 4 * (v12 + 1)) = v10;
        goto LABEL_12;
      case 52LL:
        v31 = v12;
        if ( v20 != 0 )
          funcs_4001A8[v20]();
        goto LABEL_12;
      case 53LL:
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008EC + 4 * v12) = v14;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008F0 + 4 * v12) = v15;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008F4 + 4 * v12) = v16;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008F8 + 4 * v12) = v17;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_6008FC + 4 * v12) = v0;
        *(_DWORD *)(unsigned int)((_DWORD)&dword_600900 + 4 * v12) = v1;
        goto LABEL_12;
      case 54LL:
        v21 = v12 - 6;
        v0 = *(_DWORD *)(unsigned int)((_DWORD)&dword_6008FC + 4 * v21);
        v1 = *(_DWORD *)(unsigned int)((_DWORD)&dword_600900 + 4 * v21);
        goto LABEL_12;
      case 112LL:
        if ( (_DWORD)v10 != 11 )
          goto LABEL_12;
        v18 = sys_exit(0);
        goto LABEL_6;
    }
  }
}
// 4000C0: variable 'v3' is possibly undefined
// 400117: variable 'v11' is possibly undefined
// 400118: variable 'v13' is possibly undefined
// 400119: variable 'v14' is possibly undefined
// 40011B: variable 'v15' is possibly undefined
// 40011D: variable 'v16' is possibly undefined
// 40011F: variable 'v17' is possibly undefined
// 400121: variable 'v2' is possibly undefined
// 400123: variable 'v12' is possibly undefined
// 4001A2: variable 'v18' is possibly undefined
// 4001F9: variable 'v10' is possibly undefined
// 400475: variable 'v0' is possibly undefined
// 40047E: variable 'v1' is possibly undefined
// 4000B0: using guessed type __int64 __fastcall start();
// 600868: using guessed type __int64 (__fastcall *funcs_400176[8])();
// 6008A8: using guessed type __int64 (__fastcall *funcs_4001A8[8])();
// 6008E8: using guessed type int dword_6008E8;
// 6008EC: using guessed type int dword_6008EC;
// 6008F0: using guessed type int dword_6008F0;
// 6008F4: using guessed type int dword_6008F4;
// 6008F8: using guessed type int dword_6008F8;
// 6008FC: using guessed type int dword_6008FC;
// 600900: using guessed type int dword_600900;

//----- (00000000004001B4) ----------------------------------------------------
void sub_4001B4()
{
  ;
}

//----- (00000000004001B8) ----------------------------------------------------
void sub_4001B8()
{
  ;
}

//----- (00000000004001BC) ----------------------------------------------------
void sub_4001BC()
{
  ;
}

//----- (00000000004001C0) ----------------------------------------------------
void sub_4001C0()
{
  ;
}

//----- (00000000004001C4) ----------------------------------------------------
void sub_4001C4()
{
  ;
}

//----- (00000000004001C8) ----------------------------------------------------
void sub_4001C8()
{
  ;
}

//----- (00000000004001CC) ----------------------------------------------------
void sub_4001CC()
{
  ;
}

//----- (00000000004001D0) ----------------------------------------------------
void sub_4001D0()
{
  ;
}

//----- (00000000004001D4) ----------------------------------------------------
void sub_4001D4()
{
  ;
}

//----- (00000000004001D8) ----------------------------------------------------
void sub_4001D8()
{
  ;
}

//----- (00000000004001DC) ----------------------------------------------------
void sub_4001DC()
{
  ;
}

//----- (00000000004001E0) ----------------------------------------------------
void sub_4001E0()
{
  ;
}

//----- (00000000004001E4) ----------------------------------------------------
void sub_4001E4()
{
  ;
}

//----- (00000000004001E8) ----------------------------------------------------
void sub_4001E8()
{
  ;
}

//----- (00000000004001EC) ----------------------------------------------------
void sub_4001EC()
{
  ;
}

//----- (00000000004001F0) ----------------------------------------------------
void sub_4001F0()
{
  ;
}

// nfuncs=17 queued=17 decompiled=17 lumina nreq=0 worse=0 better=0
// ALL OK, 17 function(s) have been successfully decompiled
