/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

int __fastcall sub_40129C(_DWORD, _DWORD); // weak
int __stdcall sub_401320(_DWORD); // weak
// int __usercall sub_401D64@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4);
// int __usercall sub_401D71@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4);
int __stdcall sub_401D7E(int a1);
int __cdecl sub_40200C(int a1);
int __cdecl sub_4020A8(int a1);
int __cdecl sub_402138(int a1);
int __cdecl sub_40218C(int a1);
int __cdecl sub_4021D0(int a1);
int __cdecl sub_402214(int a1);
int __cdecl sub_40225C(int a1);
int __cdecl sub_4022F4(int a1);
int __cdecl sub_402350(int a1);
int __cdecl sub_402474(int a1);
int __cdecl sub_4024BC(int a1);
int __cdecl sub_402510(int a1);
// int __usercall sub_402FD0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4);
// int __userpurge sub_403212@<eax>(int a1@<ebp>, int a2);
// int __usercall sub_403240@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4);
// int __userpurge sub_403313@<eax>(int a1@<ebp>, int a2);
int __stdcall sub_403340(int a1);
int __cdecl sub_4033B0(_DWORD *a1);
int sub_403980(void); // weak
int __stdcall sub_404720(int *a1);
// int __usercall sub_404810@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4, int a5);
// int __usercall sub_4049D0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4, int a5);
// int __usercall sub_404C70@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, _DWORD *a4);
_DWORD sub_404E70(); // weak
// int __usercall sub_4050E0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
// int __usercall sub_4051E0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
_DWORD sub_405350(); // weak
// int __usercall sub_405E40@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
// int __usercall sub_405F70@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
// int __usercall sub_406550@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>);
int sub_4068B0(void); // weak

//-------------------------------------------------------------------------
// Data declarations

int (__stdcall *dword_401000)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x104014; // weak
int (__stdcall *dword_401004)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x10401C; // weak
int (__fastcall *dword_401010)(_DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD))0x104034; // weak
int (__fastcall *dword_401014)(_DWORD, _DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD, _DWORD))0x10403C; // weak
int (__thiscall *dword_401018)(_DWORD) = (int (__thiscall *)(_DWORD))0x104044; // weak
int (__cdecl *dword_40101C)(_DWORD) = (int (__cdecl *)(_DWORD))0x10404C; // weak
int (__cdecl *dword_401020)(_DWORD) = (int (__cdecl *)(_DWORD))0x104054; // weak
int (*dword_401024)(void) = (int (*)(void))0x10405C; // weak
int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x104064; // weak
int (__stdcall *dword_401034)(_DWORD) = (int (__stdcall *)(_DWORD))0x10407C; // weak
int dword_40103C = 1065100; // weak
int (__stdcall *dword_401040)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x104094; // weak
int (__stdcall *dword_401044)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x10409C; // weak
int (__stdcall *dword_401048)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x1040A4; // weak
int (*dword_40104C)(void) = (int (*)(void))0x1040AC; // weak
int (__stdcall *dword_401050)(_DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD))0x1040B4; // weak
int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x1040CC; // weak
int (__stdcall *dword_401068)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x1040E4; // weak
int (__stdcall *dword_40106C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x1040EC; // weak
int (__stdcall *dword_401078)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x104104; // weak
int (__stdcall *dword_40107C)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x10410C; // weak
int (__stdcall *dword_401080)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x104114; // weak
int (__stdcall *dword_401084)(_DWORD) = (int (__stdcall *)(_DWORD))0x10411C; // weak
int (__cdecl *dword_401090)(_DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD))0x104134; // weak
int (__cdecl *dword_401094)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x10413C; // weak
int (*dword_4010A0)(void) = (int (*)(void))0x104154; // weak
int (__stdcall *dword_4010A4)(_DWORD) = (int (__stdcall *)(_DWORD))0x10415C; // weak
int (__cdecl *dword_4010A8)(_DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD))0x104164; // weak
int (__thiscall *dword_4010B0)(_DWORD) = (int (__thiscall *)(_DWORD))0x104174; // weak
int (__stdcall *dword_4010BC)(_DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))0x10418C; // weak
int (__stdcall *dword_4010D4)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x1041BC; // weak
int (__cdecl *dword_4010E0)(_DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD))0x1041D4; // weak
int (__stdcall *dword_4010E8)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD))0x1041E4; // weak
int (__stdcall *dword_4010EC)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x1041EC; // weak
int (__cdecl *dword_4010F0)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x1041F4; // weak
int (*dword_401100)(void) = (int (*)(void))0x104214; // weak
int (__cdecl *dword_401104)(_DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD))0x10421C; // weak
int (__fastcall *dword_401114)(_DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD))0x10423C; // weak
int (__cdecl *dword_401118)(_DWORD, _DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD, _DWORD))0x104244; // weak
int (__cdecl *dword_40111C)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x10424C; // weak
double (__stdcall *dword_401124)(_DWORD, _DWORD, _DWORD, _DWORD) = (double (__stdcall *)(_DWORD, _DWORD, _DWORD, _DWORD))0x10425C; // weak
int (__cdecl *dword_401130)(_DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD))0x104274; // weak
int (__cdecl *dword_401134)(_DWORD) = (int (__cdecl *)(_DWORD))0x10427C; // weak
int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x104284; // weak
int (__stdcall *dword_40113C)(_DWORD, _DWORD) = (int (__stdcall *)(_DWORD, _DWORD))0x10428C; // weak
int (__fastcall *dword_401140)(_DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD))0x104294; // weak
double (__stdcall *dword_401144)(_DWORD, _DWORD) = (double (__stdcall *)(_DWORD, _DWORD))0x10429C; // weak
int (__fastcall *dword_401148)(_DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD))0x1042A4; // weak
int (*dword_40114C)(void) = (int (*)(void))0x1042AC; // weak
int (__cdecl *dword_401150)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x1042B4; // weak
int (__fastcall *dword_401158)(_DWORD, _DWORD) = (int (__fastcall *)(_DWORD, _DWORD))0x1042C4; // weak
int (__cdecl *dword_40115C)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x1042CC; // weak
int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD) = (int (__cdecl *)(_DWORD, _DWORD, _DWORD))0x1042EC; // weak
int (__thiscall *dword_401174)(_DWORD, _DWORD) = (int (__thiscall *)(_DWORD, _DWORD))0x1042FC; // weak
int (__thiscall *dword_40117C)(_DWORD) = (int (__thiscall *)(_DWORD))0x10430C; // weak
int (__stdcall *dword_401180)(_DWORD) = (int (__stdcall *)(_DWORD))0x104314; // weak
int dword_401188[4] = { 524295, 4207045, 4207112, 4207052 }; // weak
int dword_401198[4] = { 524295, 4207352, 4207369, 4207359 }; // weak
int dword_4011A8[2] = { 524417, 4207505 }; // weak
int dword_4011B0[2] = { 524302, 0 }; // weak
int dword_4011D0[3] = { 262148, 0, 0 }; // weak
int dword_4011E0[2] = { 262150, 0 }; // weak
int dword_4011F0[2] = { 262150, 0 }; // weak
int dword_401200[2] = { 262150, 0 }; // weak
int dword_401228[2] = { 262150, 0 }; // weak
int dword_401238[2] = { 524302, 0 }; // weak
int dword_401260[2] = { 524302, 0 }; // weak
int dword_401270[2] = { 262150, 0 }; // weak
int dword_401280[2] = { 524302, 0 }; // weak
_UNKNOWN sub_401296; // weak
char *off_401FF4[2] = { "comctl32", "InitCommonControls" }; // weak
char *off_402090 = "kernel32"; // weak
int dword_4020D0[5] = { 866995937, 298804889, -1442837321, -1814863872, 6 }; // weak
int dword_4020E4[2] = { 7930106, 75 }; // weak
int dword_4020EC[7] = { 36438038, 65536, 872677672, 537526308, 2371627, 260, 7 }; // weak
char *off_402120 = "user32"; // weak
char *off_402174 = "kernel32"; // weak
char *off_4021B8 = "kernel32"; // weak
char *off_4021FC = "user32.dll"; // weak
char *off_402244 = "user32"; // weak
char *off_4022DC = "kernel32"; // weak
char *off_402338[2] = { "kernel32", "WriteProcessMemory" }; // weak
char *off_40245C = "kernel32"; // weak
char *off_4024A4 = "kernel32"; // weak
char *off_4024F8[2] = { "kernel32", "CreateToolhelp32Snapshot" }; // weak
int dword_4025CC[5] = { 3801338, 4784238, 7143459, 55, 0 }; // weak
int dword_4025E0 = 0; // weak
wchar_t aAbcdefghijklmn[92] = L"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789(),./:[]<>*&!$|\\?@# ;'~}{-=+_"; // weak
wchar_t aX5stuLmzycde01[92] = L"X5STU,.LMZYcde012tu89()\\?@#xvwI/:[]EFjklAP<nomQRVW34KJfghBGHaNOibCD>*&!$|67ypqrsz;-+_' =~}{"; // weak
wchar_t asc_402B58[5] = L"\\\\.\\"; // weak
wchar_t aFailedShutdown[16] = L"Failed shutdown"; // weak
int dword_402B8C[2] = { 54, 26 }; // weak
_UNKNOWN loc_40395B; // weak
_UNKNOWN loc_4049BB; // weak
_UNKNOWN loc_404C5B; // weak
_UNKNOWN loc_404E5C; // weak
_UNKNOWN loc_4051CB; // weak
_UNKNOWN loc_405316; // weak
_UNKNOWN loc_405F40; // weak
_UNKNOWN loc_40653A; // weak
_UNKNOWN loc_406874; // weak
int dword_407044 = 0; // weak
int dword_407060 = 0; // weak
int dword_40706C = 0; // weak
int dword_407070 = 0; // weak
int dword_407078 = 0; // weak
int dword_40707C = 0; // weak
int dword_407080[5] = { 0, 0, 0, 0, 0 }; // weak
int dword_407094[8] = { 0, 0, 0, 0, 0, 0, 0, 0 }; // weak
int dword_4070B4 = 0; // weak
__int16 word_4070C0 = 0; // weak
int (*dword_407430)(void) = NULL; // weak
int (*dword_407448)(void) = NULL; // weak
int (*dword_407454)(void) = NULL; // weak
int (*dword_407460)(void) = NULL; // weak
int (*dword_40746C)(void) = NULL; // weak
int (*dword_407478)(void) = NULL; // weak
int (*dword_407484)(void) = NULL; // weak
int (*dword_40749C)(void) = NULL; // weak
int (*dword_4074A8)(void) = NULL; // weak
int (*dword_4074D8)(void) = NULL; // weak
int (*dword_4074E4)(void) = NULL; // weak
int (*dword_4074F0)(void) = NULL; // weak


//----- (00401D64) --------------------------------------------------------
int __usercall sub_401D64@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4)
{
  return sub_402FD0(a1, a2, a3, a4 - 55);
}

//----- (00401D71) --------------------------------------------------------
int __usercall sub_401D71@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4)
{
  return sub_403240(a1, a2, a3, a4 - 59);
}

//----- (00401D7E) --------------------------------------------------------
int __stdcall sub_401D7E(int a1)
{
  return sub_403340(a1 - 59);
}

//----- (0040200C) --------------------------------------------------------
int __cdecl sub_40200C(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407430 != nullptr )
    return dword_407430();
  v2 = (int (__stdcall *)(int))sub_401320(off_401FF4);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 401FF4: using guessed type char *off_401FF4[2];
// 407430: using guessed type int (*dword_407430)(void);

//----- (004020A8) --------------------------------------------------------
int __cdecl sub_4020A8(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407448 != nullptr )
    return dword_407448();
  v2 = (int (__stdcall *)(int))sub_401320(&off_402090);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 402090: using guessed type char *off_402090;
// 407448: using guessed type int (*dword_407448)(void);

//----- (00402138) --------------------------------------------------------
int __cdecl sub_402138(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407454 != nullptr )
    return dword_407454();
  v2 = (int (__stdcall *)(int))sub_401320(&off_402120);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 402120: using guessed type char *off_402120;
// 407454: using guessed type int (*dword_407454)(void);

//----- (0040218C) --------------------------------------------------------
int __cdecl sub_40218C(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407460 != nullptr )
    return dword_407460();
  v2 = (int (__stdcall *)(int))sub_401320(&off_402174);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 402174: using guessed type char *off_402174;
// 407460: using guessed type int (*dword_407460)(void);

//----- (004021D0) --------------------------------------------------------
int __cdecl sub_4021D0(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_40746C != nullptr )
    return dword_40746C();
  v2 = (int (__stdcall *)(int))sub_401320(&off_4021B8);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 4021B8: using guessed type char *off_4021B8;
// 40746C: using guessed type int (*dword_40746C)(void);

//----- (00402214) --------------------------------------------------------
int __cdecl sub_402214(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407478 != nullptr )
    return dword_407478();
  v2 = (int (__stdcall *)(int))sub_401320(&off_4021FC);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 4021FC: using guessed type char *off_4021FC;
// 407478: using guessed type int (*dword_407478)(void);

//----- (0040225C) --------------------------------------------------------
int __cdecl sub_40225C(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_407484 != nullptr )
    return dword_407484();
  v2 = (int (__stdcall *)(int))sub_401320(&off_402244);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 402244: using guessed type char *off_402244;
// 407484: using guessed type int (*dword_407484)(void);

//----- (004022F4) --------------------------------------------------------
int __cdecl sub_4022F4(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_40749C != nullptr )
    return dword_40749C();
  v2 = (int (__stdcall *)(int))sub_401320(&off_4022DC);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 4022DC: using guessed type char *off_4022DC;
// 40749C: using guessed type int (*dword_40749C)(void);

//----- (00402350) --------------------------------------------------------
int __cdecl sub_402350(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_4074A8 != nullptr )
    return dword_4074A8();
  v2 = (int (__stdcall *)(int))sub_401320(off_402338);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 402338: using guessed type char *off_402338[2];
// 4074A8: using guessed type int (*dword_4074A8)(void);

//----- (00402474) --------------------------------------------------------
int __cdecl sub_402474(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_4074D8 != nullptr )
    return dword_4074D8();
  v2 = (int (__stdcall *)(int))sub_401320(&off_40245C);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 40245C: using guessed type char *off_40245C;
// 4074D8: using guessed type int (*dword_4074D8)(void);

//----- (004024BC) --------------------------------------------------------
int __cdecl sub_4024BC(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_4074E4 != nullptr )
    return dword_4074E4();
  v2 = (int (__stdcall *)(int))sub_401320(&off_4024A4);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 4024A4: using guessed type char *off_4024A4;
// 4074E4: using guessed type int (*dword_4074E4)(void);

//----- (00402510) --------------------------------------------------------
int __cdecl sub_402510(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_4074F0 != nullptr )
    return dword_4074F0();
  v2 = (int (__stdcall *)(int))sub_401320(off_4024F8);
  return v2(a1);
}
// 401320: using guessed type int __stdcall sub_401320(_DWORD);
// 4024F8: using guessed type char *off_4024F8[2];
// 4074F0: using guessed type int (*dword_4074F0)(void);

//----- (00402FD0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_402FD0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4)
{
  unsigned int v4; // esi
  int v5; // eax
  int v6; // esi
  int v7; // eax
  void (__fastcall *v8)(int (__userpurge **)@<eax>(int@<ebp>, int), int *); // edi
  int v9; // eax
  void (__fastcall *v10)(int *, int, int (__userpurge *)@<eax>(int@<ebp>, int)); // ebx
  int v11; // eax
  int v12; // eax
  int v13; // esi
  int v14; // eax
  int v16; // [esp-44h] [ebp-C8h] BYREF
  int v17; // [esp-40h] [ebp-C4h]
  int v18; // [esp-38h] [ebp-BCh]
  int v19; // [esp-34h] [ebp-B8h]
  int v20; // [esp-30h] [ebp-B4h]
  int v21; // [esp-2Ch] [ebp-B0h]
  int v22; // [esp-28h] [ebp-ACh]
  int v23; // [esp-24h] [ebp-A8h]
  int v24; // [esp-20h] [ebp-A4h]
  int v25; // [esp-1Ch] [ebp-A0h]
  int v26; // [esp-18h] [ebp-9Ch]
  int v27; // [esp-14h] [ebp-98h]
  int v28; // [esp-10h] [ebp-94h]
  int v29; // [esp-Ch] [ebp-90h]
  int v30; // [esp-8h] [ebp-8Ch]
  int v31; // [esp-4h] [ebp-88h]
  _DWORD v32[2]; // [esp+0h] [ebp-84h] BYREF
  int *v33; // [esp+8h] [ebp-7Ch]
  int v34; // [esp+Ch] [ebp-78h]
  _DWORD v35[2]; // [esp+10h] [ebp-74h] BYREF
  int v36; // [esp+18h] [ebp-6Ch]
  int v37; // [esp+1Ch] [ebp-68h]
  _DWORD v38[2]; // [esp+20h] [ebp-64h] BYREF
  int v39; // [esp+28h] [ebp-5Ch]
  int v40; // [esp+2Ch] [ebp-58h]
  _DWORD v41[4]; // [esp+30h] [ebp-54h] BYREF
  _DWORD v42[2]; // [esp+40h] [ebp-44h] BYREF
  int v43; // [esp+48h] [ebp-3Ch]
  int v44; // [esp+4Ch] [ebp-38h]
  int v45; // [esp+50h] [ebp-34h] BYREF
  int v46; // [esp+54h] [ebp-30h] BYREF
  int v47; // [esp+58h] [ebp-2Ch] BYREF
  int (__userpurge *v48)@<eax>(int@<ebp>, int); // [esp+5Ch] [ebp-28h] BYREF
  _DWORD v49[4]; // [esp+60h] [ebp-24h] BYREF
  struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList; // [esp+70h] [ebp-14h]
  _DWORD *v51; // [esp+74h] [ebp-10h]
  int *v52; // [esp+78h] [ebp-Ch]
  int *v53; // [esp+7Ch] [ebp-8h]
  int (__userpurge *v54)@<eax>(int@<ebp>, int); // [esp+80h] [ebp-4h]

  v51 = &sub_401296;
  ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
  v17 = a3;
  v52 = &v16;
  v53 = dword_401188;
  v54 = (int (__userpurge *)@<eax>(int@<ebp>, int))(a4 & 1);
  v4 = a4 & 0xFFFFFFFE;
  (*(void (__stdcall **)(unsigned int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, _DWORD, _DWORD, int *, int, _DWORD, _DWORD, int, int, _DWORD, _DWORD, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int, int, int, int, int, int (__userpurge *)@<eax>(int@<ebp>, int), _DWORD, _DWORD, _DWORD, _DWORD, struct _EXCEPTION_REGISTRATION_RECORD *, void *))(*(_DWORD *)v4 + 4))(
    v4,
    a2,
    v17,
    a1,
    v18,
    v19,
    v20,
    v21,
    v22,
    v23,
    v24,
    v25,
    v26,
    v27,
    v28,
    v29,
    v30,
    v31,
    v32[0],
    v32[1],
    v33,
    v34,
    v35[0],
    v35[1],
    v36,
    v37,
    v38[0],
    v38[1],
    v39,
    v40,
    v41[0],
    v41[1],
    v41[2],
    v41[3],
    v42[0],
    v42[1],
    v43,
    v44,
    v45,
    v46,
    v47,
    v48,
    v49[0],
    v49[1],
    v49[2],
    v49[3],
    ExceptionList,
    &sub_401296);
  v49[0] = 0;
  v48 = nullptr;
  v47 = 0;
  v46 = 0;
  v45 = 0;
  v42[0] = 0;
  v41[0] = 0;
  v38[0] = 0;
  v35[0] = 0;
  v33 = nullptr;
  v32[0] = 32770;
  if ( (unsigned __int16)dword_401130(v32, v49) != 0 )
    dword_401024();
  sub_4020A8(1000);
  dword_40104C();
  v5 = (*(int (__stdcall **)(unsigned int))(*(_DWORD *)v4 + 768))(v4);
  v6 = dword_401068(&v45, v5);
  v7 = (*(int (__stdcall **)(int, int (__userpurge **)@<eax>(int@<ebp>, int)))(*(_DWORD *)v6 + 160))(v6, &v48);
  __asm { fnclex }
  if ( v7 < 0 )
    dword_401050(v7, v6, dword_4020D0, 160);
  v8 = (void (__fastcall *)(int (__userpurge **)@<eax>(int@<ebp>, int), int *))dword_401114;
  dword_401114(&v47, dword_4020E4);
  v54 = v48;
  v9 = sub_4033B0(&v47);
  v10 = (void (__fastcall *)(int *, int, int (__userpurge *)@<eax>(int@<ebp>, int)))dword_401158;
  v11 = dword_401158(&v46, v9);
  v12 = dword_4010A4(v11);
  v54 = (int (__userpurge *)@<eax>(int@<ebp>, int))&v46;
  v13 = -(v12 == 0);
  dword_40111C(3, &v47, &v48);
  dword_40117C(&v45);
  if ( (_WORD)v13 != 0 )
  {
    v8(&v48, dword_4025CC);
    v14 = sub_4033B0(&v48);
    v10(&v47, v14, v54);
    v36 = -2147352572;
    v39 = -2147352572;
    v35[0] = 10;
    v38[0] = 10;
    v33 = &dword_4025E0;
    v32[0] = 8;
    dword_401140(v41, v32);
    v43 = v47;
    v47 = 0;
    v42[0] = 8;
    dword_40106C(v42, 64, v41, v38, v35);
    dword_40111C(2, &v48, &v47);
    v51 = v35;
    ExceptionList = (struct _EXCEPTION_REGISTRATION_RECORD *)v38;
    dword_401028(4, v42, v41);
    dword_401024();
  }
  else
  {
    sub_4068B0();
  }
  v54 = sub_403212;
  return dword_401018(v49);
}
// 40304E: bad sp value at call
// 40307D: bad sp value at call
// 40308C: bad sp value at call
// 4030B8: bad sp value at call
// 4030C2: bad sp value at call
// 4030D2: bad sp value at call
// 4030F2: bad sp value at call
// 4030FE: bad sp value at call
// 403115: bad sp value at call
// 40311B: bad sp value at call
// 403125: bad sp value at call
// 403158: bad sp value at call
// 403180: bad sp value at call
// 403190: bad sp value at call
// 4031A8: bad sp value at call
// 40320B: bad sp value at call
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401024: using guessed type int (*dword_401024)(void);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 401050: using guessed type int (__stdcall *dword_401050)(_DWORD, _DWORD, _DWORD, _DWORD);
// 401068: using guessed type int (__stdcall *dword_401068)(_DWORD, _DWORD);
// 40106C: using guessed type int (__stdcall *dword_40106C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 4010A4: using guessed type int (__stdcall *dword_4010A4)(_DWORD);
// 401114: using guessed type int (__fastcall *dword_401114)(_DWORD, _DWORD);
// 40111C: using guessed type int (__cdecl *dword_40111C)(_DWORD, _DWORD, _DWORD);
// 401130: using guessed type int (__cdecl *dword_401130)(_DWORD, _DWORD);
// 401140: using guessed type int (__fastcall *dword_401140)(_DWORD, _DWORD);
// 401158: using guessed type int (__fastcall *dword_401158)(_DWORD, _DWORD);
// 40117C: using guessed type int (__thiscall *dword_40117C)(_DWORD);
// 401188: using guessed type int dword_401188[4];
// 4020D0: using guessed type int dword_4020D0[5];
// 4020E4: using guessed type int dword_4020E4[2];
// 4025CC: using guessed type int dword_4025CC[5];
// 4025E0: using guessed type int dword_4025E0;
// 4068B0: using guessed type int sub_4068B0(void);

//----- (00403212) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __userpurge sub_403212@<eax>(int a1@<ebp>, int a2)
{
  (*(void (__cdecl **)(_DWORD))(**(_DWORD **)(a1 + 8) + 8))(*(_DWORD *)(a1 + 8));
  return *(_DWORD *)(a1 - 4);
}
// 40322E: positive sp value C has been found
// 403212: could not find valid save-restore pair for ebx
// 403212: could not find valid save-restore pair for edi
// 403212: could not find valid save-restore pair for esi

//----- (00403240) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_403240@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4)
{
  int v4; // eax
  unsigned __int16 (__stdcall *v5)(_DWORD *, _DWORD *); // edi
  _DWORD v7[5]; // [esp-14h] [ebp-58h] BYREF
  _DWORD v8[2]; // [esp+0h] [ebp-44h] BYREF
  int v9; // [esp+8h] [ebp-3Ch]
  int v10; // [esp+Ch] [ebp-38h]
  int v11; // [esp+10h] [ebp-34h]
  int v12; // [esp+14h] [ebp-30h]
  int v13; // [esp+18h] [ebp-2Ch]
  int v14; // [esp+1Ch] [ebp-28h]
  _DWORD v15[4]; // [esp+20h] [ebp-24h] BYREF
  struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList; // [esp+30h] [ebp-14h]
  void *v17; // [esp+34h] [ebp-10h]
  _DWORD *v18; // [esp+38h] [ebp-Ch]
  int *v19; // [esp+3Ch] [ebp-8h]
  int (__userpurge *v20)@<eax>(int@<ebp>, int); // [esp+40h] [ebp-4h]

  v17 = &sub_401296;
  ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
  v18 = v7;
  v19 = dword_401198;
  v4 = a4;
  v20 = (int (__userpurge *)@<eax>(int@<ebp>, int))(a4 & 1);
  LOBYTE(v4) = a4 & 0xFE;
  (*(void (__stdcall **)(int, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, int, int, int, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, struct _EXCEPTION_REGISTRATION_RECORD *, void *))(*(_DWORD *)v4 + 4))(
    v4,
    a2,
    a3,
    a1,
    v7[3],
    v7[4],
    v8[0],
    v8[1],
    v9,
    v10,
    v11,
    v12,
    v13,
    v14,
    v15[0],
    v15[1],
    v15[2],
    v15[3],
    ExceptionList,
    &sub_401296);
  v5 = (unsigned __int16 (__stdcall *)(_DWORD *, _DWORD *))dword_401130;
  v15[0] = 0;
  v11 = 0;
  v9 = 0;
  v8[0] = 32770;
  if ( (unsigned __int16)dword_401130(v8, v15) != 0 )
  {
    dword_401024();
  }
  else
  {
    sub_4020A8(2000);
    dword_40104C();
  }
  v9 = 0;
  v8[0] = 32770;
  if ( v5(v8, v15) != 0 )
    dword_401024();
  word_4070C0 = 0;
  dword_407078 = 0;
  dword_40707C = 0;
  sub_403980();
  v20 = sub_403313;
  return dword_401018(v15);
}
// 4032A3: bad sp value at call
// 4032D0: bad sp value at call
// 40330C: bad sp value at call
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401024: using guessed type int (*dword_401024)(void);
// 40104C: using guessed type int (*dword_40104C)(void);
// 401130: using guessed type int (__cdecl *dword_401130)(_DWORD, _DWORD);
// 401198: using guessed type int dword_401198[4];
// 403980: using guessed type int sub_403980(void);
// 407078: using guessed type int dword_407078;
// 40707C: using guessed type int dword_40707C;
// 4070C0: using guessed type __int16 word_4070C0;

//----- (00403313) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __userpurge sub_403313@<eax>(int a1@<ebp>, int a2)
{
  (*(void (__cdecl **)(_DWORD))(**(_DWORD **)(a1 + 8) + 8))(*(_DWORD *)(a1 + 8));
  return *(_DWORD *)(a1 - 4);
}
// 40332F: positive sp value C has been found
// 403313: could not find valid save-restore pair for ebx
// 403313: could not find valid save-restore pair for edi
// 403313: could not find valid save-restore pair for esi

//----- (00403340) --------------------------------------------------------
int __stdcall sub_403340(int a1)
{
  int v1; // eax
  int v3[9]; // [esp-8h] [ebp-28h] BYREF
  int v4; // [esp+1Ch] [ebp-4h]
  int v5; // [esp+28h] [ebp+8h]

  v3[7] = (int)v3;
  v3[8] = (int)dword_4011A8;
  v1 = a1;
  v4 = a1 & 1;
  LOBYTE(v1) = a1 & 0xFE;
  v5 = v1;
  (*(void (__stdcall **)(int, int, int))(*(_DWORD *)v1 + 4))(v1, v3[0], v3[1]);
  sub_40200C(v3[2]);
  dword_40104C();
  v4 = 0;
  (*(void (__stdcall **)(int))(*(_DWORD *)v5 + 8))(v5);
  return v4;
}
// 40104C: using guessed type int (*dword_40104C)(void);
// 4011A8: using guessed type int dword_4011A8[2];

//----- (004033B0) --------------------------------------------------------
int __cdecl sub_4033B0(_DWORD *a1)
{
  unsigned int v1; // edi
  int v2; // ecx
  void (__fastcall *v3)(int *, wchar_t *); // edi
  int v4; // eax
  int v5; // ecx
  int v6; // eax
  bool v7; // of
  int v8; // eax
  int v9; // eax
  void (__fastcall *v10)(int *, int); // edi
  int v11; // edx
  int j; // eax
  int v13; // eax
  int v14; // eax
  int v15; // edx
  int v16; // eax
  int v17; // eax
  int v18; // eax
  int v19; // eax
  int v20; // eax
  void (__fastcall *v21)(int *, int); // edi
  int v22; // eax
  int i; // eax
  int v24; // eax
  int v25; // eax
  int v26; // edx
  int v27; // eax
  int v28; // eax
  int v29; // eax
  int v30; // eax
  void (__thiscall *v31)(int *); // esi
  void (__thiscall *v32)(_DWORD *); // edi
  void *v34; // [esp-8Ch] [ebp-1A0h]
  int v35; // [esp-24h] [ebp-138h] BYREF
  _DWORD v36[4]; // [esp+0h] [ebp-114h] BYREF
  _DWORD v37[4]; // [esp+10h] [ebp-104h] BYREF
  _DWORD v38[4]; // [esp+20h] [ebp-F4h] BYREF
  _DWORD v39[4]; // [esp+30h] [ebp-E4h] BYREF
  int v40; // [esp+40h] [ebp-D4h]
  _DWORD v41[2]; // [esp+44h] [ebp-D0h] BYREF
  int v42; // [esp+4Ch] [ebp-C8h]
  _DWORD v43[2]; // [esp+54h] [ebp-C0h] BYREF
  int v44; // [esp+5Ch] [ebp-B8h]
  _DWORD v45[2]; // [esp+64h] [ebp-B0h] BYREF
  int *v46; // [esp+6Ch] [ebp-A8h]
  _DWORD v47[2]; // [esp+74h] [ebp-A0h] BYREF
  int v48; // [esp+7Ch] [ebp-98h]
  _DWORD v49[4]; // [esp+84h] [ebp-90h] BYREF
  _DWORD v50[4]; // [esp+94h] [ebp-80h] BYREF
  _DWORD v51[2]; // [esp+A4h] [ebp-70h] BYREF
  int v52; // [esp+ACh] [ebp-68h]
  _DWORD v53[2]; // [esp+B4h] [ebp-60h] BYREF
  int v54; // [esp+BCh] [ebp-58h]
  int v55; // [esp+C4h] [ebp-50h] BYREF
  int v56; // [esp+C8h] [ebp-4Ch] BYREF
  int v57; // [esp+CCh] [ebp-48h] BYREF
  int v58; // [esp+D0h] [ebp-44h] BYREF
  _DWORD v59[4]; // [esp+D4h] [ebp-40h] BYREF
  int v60; // [esp+E4h] [ebp-30h] BYREF
  int v61; // [esp+E8h] [ebp-2Ch] BYREF
  _DWORD v62[4]; // [esp+ECh] [ebp-28h] BYREF
  _DWORD v63[5]; // [esp+FCh] [ebp-18h] BYREF

  v63[3] = &v35;
  v63[4] = dword_4011B0;
  v63[0] = 0;
  v62[0] = 0;
  v61 = 0;
  v60 = 0;
  v59[0] = 0;
  v58 = 0;
  v57 = 0;
  v56 = 0;
  v55 = 0;
  v53[0] = 0;
  v51[0] = 0;
  v50[0] = 0;
  v49[0] = 0;
  v45[0] = 0;
  v43[0] = 0;
  v41[0] = 0;
  v39[0] = 0;
  v38[0] = 0;
  v37[0] = 0;
  v36[0] = 0;
  v48 = 0;
  v47[0] = 32770;
  if ( (unsigned __int16)dword_401130(v47, v59) != 0 )
    dword_401024();
  v1 = dword_401134(dword_407094);
  if ( v1 >= 0xFA1 )
    dword_4010A0();
  v2 = dword_4070B4 + 4 * v1;
  v3 = (void (__fastcall *)(int *, wchar_t *))dword_401114;
  dword_401114(v2, *a1);
  v48 = 1;
  v47[0] = 2;
  v4 = dword_401138(v53, v47, dword_407094);
  dword_401010(dword_407094, v4);
  v3(&v60, aAbcdefghijklmn);
  v3(&v61, aX5stuLmzycde01);
  v48 = (int)a1;
  v47[0] = 16392;
  dword_401150(v53, v47, 1);
  dword_4010E0(v51, 250);
  v40 = dword_4010A8(v51, v53);
  dword_401028(2, v53, v51);
  if ( (_WORD)v40 == 0 )
  {
    dword_4010E0(v53, 250);
    v20 = dword_40101C(v53);
    v21 = (void (__fastcall *)(int *, int))dword_401158;
    dword_401158(v63, v20);
    dword_401018(v53);
    v22 = *a1;
    v48 = 1;
    v47[0] = 2;
    v46 = (int *)dword_401020(v22);
    v45[0] = 3;
    v44 = 1;
    v43[0] = 2;
    for ( i = dword_40105C(v62, v37, v36, v43, v45, v47); i != 0; i = dword_40116C(v62, v37, v36) )
    {
      v54 = 1;
      v53[0] = 2;
      v24 = dword_401134(v62);
      v25 = dword_401090(*a1, v24);
      v21(&v55, v25);
      v26 = v55;
      v42 = v63[0];
      v46 = &v61;
      v41[0] = 8;
      v52 = 1;
      v51[0] = 2;
      v55 = 0;
      v45[0] = 16392;
      v27 = ((int (__fastcall *)(int *, int, int, int, _DWORD *))v21)(&v56, v26, v60, 1, v51);
      v28 = dword_401104(0, v27);
      dword_401094(v50, v45, v28);
      v29 = dword_4010F0(v49, v50, v41);
      v30 = dword_40101C(v29);
      v21(v63, v30);
      dword_40111C(2, &v56, &v55);
      dword_401028(4, v53, v51);
    }
    dword_401114(&v58, v63[0]);
    goto LABEL_15;
  }
  v3(&v57, (wchar_t *)&dword_4025E0);
  v5 = *a1;
  v48 = (int)a1;
  v47[0] = 16392;
  v6 = dword_401020(v5);
  v7 = __OFSUB__(v6, 1);
  v8 = v6 - 1;
  if ( !v7 )
  {
    dword_40115C(v53, v47, v8);
    v9 = dword_40101C(v53);
    v10 = (void (__fastcall *)(int *, int))dword_401158;
    dword_401158(a1, v9);
    dword_401018(v53);
    v11 = *a1;
    v48 = 1;
    v47[0] = 2;
    v46 = (int *)dword_401020(v11);
    v45[0] = 3;
    v44 = 1;
    v43[0] = 2;
    for ( j = dword_40105C(v62, v39, v38, v43, v45, v47); j != 0; j = dword_40116C(v62, v39, v38) )
    {
      v54 = 1;
      v53[0] = 2;
      v13 = dword_401134(v62);
      v14 = dword_401090(*a1, v13);
      v10(&v55, v14);
      v15 = v55;
      v42 = v57;
      v46 = &v60;
      v41[0] = 8;
      v52 = 1;
      v51[0] = 2;
      v55 = 0;
      v45[0] = 16392;
      v16 = ((int (__fastcall *)(int *, int, int, int, _DWORD *))v10)(&v56, v15, v61, 1, v51);
      v17 = dword_401104(0, v16);
      dword_401094(v50, v45, v17);
      v18 = dword_4010F0(v49, v50, v41);
      v19 = dword_40101C(v18);
      v10(&v57, v19);
      dword_40111C(2, &v56, &v55);
      dword_401028(4, v53, v51);
    }
    dword_401114(&v58, v57);
    v34 = &loc_40395B;
LABEL_15:
    dword_401028(4, v39, v38);
    v31 = (void (__thiscall *)(int *))dword_401174;
    dword_401174(v63, v34);
    v32 = (void (__thiscall *)(_DWORD *))dword_401018;
    dword_401018(v62);
    v31(&v61);
    v31(&v60);
    v32(v59);
    return ((int (__thiscall *)(int *))v31)(&v57);
  }
  dword_401100();
  return sub_403980();
}
// 403939: variable 'v34' is possibly undefined
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 40101C: using guessed type int (__cdecl *dword_40101C)(_DWORD);
// 401020: using guessed type int (__cdecl *dword_401020)(_DWORD);
// 401024: using guessed type int (*dword_401024)(void);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401090: using guessed type int (__cdecl *dword_401090)(_DWORD, _DWORD);
// 401094: using guessed type int (__cdecl *dword_401094)(_DWORD, _DWORD, _DWORD);
// 4010A0: using guessed type int (*dword_4010A0)(void);
// 4010A8: using guessed type int (__cdecl *dword_4010A8)(_DWORD, _DWORD);
// 4010E0: using guessed type int (__cdecl *dword_4010E0)(_DWORD, _DWORD);
// 4010F0: using guessed type int (__cdecl *dword_4010F0)(_DWORD, _DWORD, _DWORD);
// 401100: using guessed type int (*dword_401100)(void);
// 401104: using guessed type int (__cdecl *dword_401104)(_DWORD, _DWORD);
// 401114: using guessed type int (__fastcall *dword_401114)(_DWORD, _DWORD);
// 40111C: using guessed type int (__cdecl *dword_40111C)(_DWORD, _DWORD, _DWORD);
// 401130: using guessed type int (__cdecl *dword_401130)(_DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 401138: using guessed type int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD);
// 401150: using guessed type int (__cdecl *dword_401150)(_DWORD, _DWORD, _DWORD);
// 401158: using guessed type int (__fastcall *dword_401158)(_DWORD, _DWORD);
// 40115C: using guessed type int (__cdecl *dword_40115C)(_DWORD, _DWORD, _DWORD);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 401174: using guessed type int (__thiscall *dword_401174)(_DWORD, _DWORD);
// 4011B0: using guessed type int dword_4011B0[2];
// 4025E0: using guessed type int dword_4025E0;
// 402770: using guessed type wchar_t aAbcdefghijklmn[92];
// 40282C: using guessed type wchar_t aX5stuLmzycde01[92];
// 403980: using guessed type int sub_403980(void);
// 407094: using guessed type int dword_407094[8];
// 4070B4: using guessed type int dword_4070B4;

//----- (00403980) --------------------------------------------------------
#error "403D4B: call analysis failed (funcsize=967)"

//----- (00404720) --------------------------------------------------------
int __stdcall sub_404720(int *a1)
{
  int v1; // eax
  int v2; // eax
  int v3; // eax
  int v4; // eax
  void (*v5)(void); // ebx
  int v6; // esi
  int result; // eax
  int v8; // esi
  int v9; // [esp-38h] [ebp-54h]
  _DWORD v10[6]; // [esp-18h] [ebp-34h] BYREF
  int v11; // [esp+0h] [ebp-1Ch] BYREF
  int v12; // [esp+4h] [ebp-18h] BYREF
  _DWORD v13[5]; // [esp+8h] [ebp-14h] BYREF

  v13[3] = v10;
  v13[4] = dword_4011D0;
  v9 = *a1;
  v13[0] = 0;
  v12 = 0;
  v11 = 0;
  v1 = dword_401044(v9, asc_402B58, -1073741824, 3, &v11, 3, 128, 0, v10[0], v10[1], v10[2], v10[3], v10[4], v10[5]);
  v2 = dword_401158(v13, v1);
  v3 = dword_40113C(&v12, v2);
  v4 = sub_40218C(v3);
  v5 = (void (*)(void))dword_40104C;
  v6 = v4;
  dword_40104C();
  result = dword_40111C(2, v13, &v12);
  if ( v6 != -1 )
  {
    v8 = sub_4021D0(dword_40706C);
    v5();
    dword_407070 = v8;
    return dword_401024();
  }
  return result;
}
// 401024: using guessed type int (*dword_401024)(void);
// 401044: using guessed type int (__stdcall *dword_401044)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 40111C: using guessed type int (__cdecl *dword_40111C)(_DWORD, _DWORD, _DWORD);
// 40113C: using guessed type int (__stdcall *dword_40113C)(_DWORD, _DWORD);
// 401158: using guessed type int (__fastcall *dword_401158)(_DWORD, _DWORD);
// 4011D0: using guessed type int dword_4011D0[3];
// 402B58: using guessed type wchar_t asc_402B58[5];
// 40706C: using guessed type int dword_40706C;
// 407070: using guessed type int dword_407070;

//----- (00404810) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_404810@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4, int a5)
{
  int v5; // eax
  void (__stdcall *v6)(_DWORD *, _DWORD *); // edi
  unsigned int v7; // esi
  __int16 v8; // si
  unsigned int v9; // esi
  _DWORD v11[5]; // [esp-14h] [ebp-C0h] BYREF
  _DWORD v12[4]; // [esp+0h] [ebp-ACh] BYREF
  _DWORD v13[6]; // [esp+10h] [ebp-9Ch] BYREF
  int v14; // [esp+28h] [ebp-84h] BYREF
  _DWORD v15[4]; // [esp+2Ch] [ebp-80h] BYREF
  _DWORD v16[2]; // [esp+3Ch] [ebp-70h] BYREF
  int v17; // [esp+44h] [ebp-68h]
  _DWORD v18[2]; // [esp+4Ch] [ebp-60h] BYREF
  int v19; // [esp+54h] [ebp-58h]
  int v20; // [esp+5Ch] [ebp-50h]
  _DWORD v21[4]; // [esp+6Ch] [ebp-40h] BYREF
  _DWORD v22[4]; // [esp+7Ch] [ebp-30h] BYREF
  _DWORD v23[7]; // [esp+8Ch] [ebp-20h] BYREF
  int *v24; // [esp+A8h] [ebp-4h]

  v23[5] = &sub_401296;
  v23[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v11[2] = a1;
  v11[1] = a3;
  v11[0] = a2;
  v23[6] = v11;
  v24 = dword_4011E0;
  v18[0] = 2;
  v16[0] = 2;
  v15[0] = 2;
  v23[0] = 0;
  v22[0] = 0;
  v21[0] = 0;
  v20 = 0;
  v14 = 0;
  v13[0] = 0;
  v12[0] = 0;
  v19 = 1;
  v17 = 256;
  v15[2] = 0;
  v5 = dword_40105C(v23, v13, v12, v15, v16, v18);
  v6 = (void (__stdcall *)(_DWORD *, _DWORD *))dword_40103C;
  while ( v5 != 0 )
  {
    v19 = a4;
    v18[0] = 16392;
    v6(v22, v18);
    v7 = dword_401134(v23);
    if ( v7 >= 0x101 )
      dword_4010A0();
    v16[0] = 16392;
    v17 = dword_407044 + 4 * v7;
    ((void (__cdecl *)(_DWORD *, _DWORD *))v6)(v21, v16);
    v8 = dword_4010A8(v21, v22);
    dword_401028(2, v22, v21);
    if ( v8 != 0 )
    {
      v9 = dword_401134(v23);
      if ( v9 >= 0x101 )
        dword_4010A0();
      v24 = (int *)a5;
      v14 = *(__int16 *)(dword_407060 + 2 * v9);
      sub_4049D0(16392, (int)v6, v9, (int)&v14, a5);
    }
    v5 = dword_40116C(v23, v13, v12);
  }
  v24 = (int *)&loc_4049BB;
  dword_401028(2, v13, v12);
  return dword_401018(v23);
}
// 4048C3: bad sp value at call
// 4048C9: bad sp value at call
// 4048F6: bad sp value at call
// 404900: bad sp value at call
// 404912: bad sp value at call
// 404924: bad sp value at call
// 404955: bad sp value at call
// 40496C: bad sp value at call
// 4049A8: bad sp value at call
// 4049B4: bad sp value at call
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 40103C: using guessed type int dword_40103C;
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 4010A0: using guessed type int (*dword_4010A0)(void);
// 4010A8: using guessed type int (__cdecl *dword_4010A8)(_DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 4011E0: using guessed type int dword_4011E0[2];
// 407044: using guessed type int dword_407044;
// 407060: using guessed type int dword_407060;

//----- (004049D0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_4049D0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4, int a5)
{
  int v5; // eax
  __int16 v6; // di
  int v7; // eax
  int v8; // eax
  void (__thiscall *v9)(_DWORD *); // edi
  int (__stdcall *v10)(int *, int, int); // ebx
  int v11; // eax
  int v12; // esi
  int v13; // eax
  int v14; // eax
  int v15; // eax
  int (__thiscall *v16)(_DWORD *); // esi
  _DWORD v18[5]; // [esp-14h] [ebp-F4h] BYREF
  _DWORD v19[4]; // [esp+0h] [ebp-E0h] BYREF
  _DWORD v20[5]; // [esp+10h] [ebp-D0h] BYREF
  int v21; // [esp+24h] [ebp-BCh] BYREF
  _DWORD v22[4]; // [esp+38h] [ebp-A8h] BYREF
  _DWORD v23[4]; // [esp+48h] [ebp-98h] BYREF
  _DWORD v24[2]; // [esp+58h] [ebp-88h] BYREF
  int v25; // [esp+60h] [ebp-80h]
  _DWORD v26[4]; // [esp+68h] [ebp-78h] BYREF
  _DWORD v27[4]; // [esp+78h] [ebp-68h] BYREF
  _DWORD v28[4]; // [esp+88h] [ebp-58h] BYREF
  _DWORD v29[4]; // [esp+98h] [ebp-48h] BYREF
  _DWORD v30[2]; // [esp+A8h] [ebp-38h] BYREF
  _DWORD v31[4]; // [esp+B0h] [ebp-30h] BYREF
  _DWORD v32[6]; // [esp+C0h] [ebp-20h] BYREF
  int v33; // [esp+D8h] [ebp-8h]
  int *v34; // [esp+DCh] [ebp-4h]
  int savedregs; // [esp+E0h] [ebp+0h]

  v32[5] = &sub_401296;
  v32[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v18[2] = a1;
  v18[1] = a3;
  v18[0] = a2;
  v33 = (int)v18;
  v34 = dword_4011F0;
  v32[0] = 0;
  v31[0] = 0;
  v30[0] = 0;
  v29[0] = 0;
  v28[0] = 0;
  v27[0] = 0;
  v26[0] = 0;
  v24[0] = 0;
  v23[0] = 0;
  v22[0] = 0;
  v21 = 0;
  v20[0] = 0;
  v19[0] = 0;
  sub_405E40(a1, a2, 0);
  v5 = dword_401118(v28, v29, v29, a4);
  v6 = dword_401084(v5);
  dword_401018(v29);
  if ( v6 != 0 )
  {
    v26[2] = -2147352572;
    v27[2] = -2147352572;
    v28[2] = -2147352572;
    v26[0] = 10;
    v27[0] = 10;
    v28[0] = 10;
    v25 = (int)aFailedShutdown;
    v24[0] = 8;
    dword_401140(v29, v24);
    dword_40106C(v29, 0, v28, v27, v26);
    v34 = v26;
    v33 = (int)v27;
    dword_401028(4, v29, v28);
  }
  v24[0] = 2;
  v22[0] = 2;
  v25 = 48;
  v22[2] = 20000;
  v7 = dword_401014(v23, a5, v24);
  v8 = dword_40105C(v31, v20, v19, v22, v7, savedregs);
  v9 = (void (__thiscall *)(_DWORD *))dword_401174;
  v10 = (int (__stdcall *)(int *, int, int))dword_401134;
  while ( v8 != 0 )
  {
    dword_40107C(v29, v31);
    v11 = dword_4010EC(v30, v29);
    dword_401180(v11);
    v12 = dword_40114C();
    v9(v30);
    dword_401018(v29);
    v13 = ((int (__stdcall *)(_DWORD *))v10)(v32);
    v34 = &v21;
    v33 = 1;
    v21 = v13;
    v14 = dword_40113C(v30, dword_402B8C);
    v15 = v10(dword_407080, v12, v14);
    sub_402350(v15);
    dword_40104C();
    v25 = v21;
    v24[0] = 3;
    dword_401148(v32, v24);
    v9(v30);
    v8 = dword_40116C(v31, v20, v19);
  }
  word_4070C0 = -1;
  v34 = (int *)&loc_404C5B;
  dword_401028(2, v20, v19);
  v16 = (int (__thiscall *)(_DWORD *))dword_401018;
  dword_401018(v32);
  return v16(v31);
}
// 404A4C: bad sp value at call
// 404A5E: bad sp value at call
// 404A9F: bad sp value at call
// 404AB6: bad sp value at call
// 404ACE: bad sp value at call
// 404B09: bad sp value at call
// 404B29: bad sp value at call
// 404B4B: bad sp value at call
// 404B59: bad sp value at call
// 404B71: bad sp value at call
// 404B76: bad sp value at call
// 404B80: bad sp value at call
// 404B9A: bad sp value at call
// 404BD1: bad sp value at call
// 404BDA: bad sp value at call
// 404BEE: bad sp value at call
// 404C41: bad sp value at call
// 404C53: bad sp value at call
// 404C58: bad sp value at call
// 401014: using guessed type int (__fastcall *dword_401014)(_DWORD, _DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 40106C: using guessed type int (__stdcall *dword_40106C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 40107C: using guessed type int (__stdcall *dword_40107C)(_DWORD, _DWORD);
// 401084: using guessed type int (__stdcall *dword_401084)(_DWORD);
// 4010EC: using guessed type int (__stdcall *dword_4010EC)(_DWORD, _DWORD);
// 401118: using guessed type int (__cdecl *dword_401118)(_DWORD, _DWORD, _DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 40113C: using guessed type int (__stdcall *dword_40113C)(_DWORD, _DWORD);
// 401140: using guessed type int (__fastcall *dword_401140)(_DWORD, _DWORD);
// 401148: using guessed type int (__fastcall *dword_401148)(_DWORD, _DWORD);
// 40114C: using guessed type int (*dword_40114C)(void);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 401174: using guessed type int (__thiscall *dword_401174)(_DWORD, _DWORD);
// 401180: using guessed type int (__stdcall *dword_401180)(_DWORD);
// 4011F0: using guessed type int dword_4011F0[2];
// 402B68: using guessed type wchar_t aFailedShutdown[16];
// 402B8C: using guessed type int dword_402B8C[2];
// 407080: using guessed type int dword_407080[5];
// 4070C0: using guessed type __int16 word_4070C0;

//----- (00404C70) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_404C70@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, _DWORD *a4)
{
  int v4; // eax
  int v5; // eax
  void (*v6)(void); // ebx
  int v7; // edi
  int v8; // eax
  int (__cdecl *v9)(_DWORD); // edi
  int v10; // eax
  int v11; // eax
  int v12; // eax
  int (__thiscall *v13)(_DWORD *); // esi
  _DWORD v15[5]; // [esp-14h] [ebp-B0h] BYREF
  _DWORD v16[4]; // [esp+0h] [ebp-9Ch] BYREF
  _DWORD v17[5]; // [esp+10h] [ebp-8Ch] BYREF
  int v18; // [esp+24h] [ebp-78h] BYREF
  _DWORD v19[4]; // [esp+28h] [ebp-74h] BYREF
  _DWORD v20[4]; // [esp+38h] [ebp-64h] BYREF
  _DWORD v21[2]; // [esp+48h] [ebp-54h] BYREF
  int v22; // [esp+50h] [ebp-4Ch]
  int v23; // [esp+58h] [ebp-44h]
  int v24; // [esp+68h] [ebp-34h] BYREF
  _DWORD v25[4]; // [esp+6Ch] [ebp-30h] BYREF
  _DWORD v26[7]; // [esp+7Ch] [ebp-20h] BYREF
  int *v27; // [esp+98h] [ebp-4h]
  int savedregs; // [esp+9Ch] [ebp+0h]

  v26[5] = &sub_401296;
  v26[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v15[2] = a1;
  v15[1] = a3;
  v15[0] = a2;
  v26[6] = v15;
  v27 = dword_401200;
  v4 = *a4;
  v26[0] = 0;
  v25[0] = 0;
  v24 = 0;
  v23 = 0;
  v21[0] = 0;
  v20[0] = 0;
  v19[0] = 0;
  v18 = 0;
  v17[0] = 0;
  v16[0] = 0;
  v27 = (int *)dword_40113C(&v24, v4);
  v5 = sub_402214(0);
  v6 = (void (*)(void))dword_40104C;
  v18 = v5;
  dword_40104C();
  dword_4010D4(a4, v24);
  v22 = v18;
  v21[0] = 3;
  dword_401010(v25, v21);
  dword_401174(&v24, savedregs);
  v27 = (int *)dword_40113C(&v24, *a4);
  v18 = sub_402214(0);
  v6();
  dword_4010D4(a4, v24);
  v7 = -(v18 > 0);
  dword_401174(&v24, savedregs);
  if ( (_WORD)v7 != 0 )
  {
    v21[0] = 2;
    v20[0] = 2;
    v19[0] = 2;
    v22 = 1;
    v20[2] = 255;
    v19[2] = 0;
    v8 = dword_40105C(v26, v17, v16, v19, v20, v21);
    v9 = dword_401134;
    while ( v8 != 0 )
    {
      v18 = 0;
      v10 = ((int (__stdcall *)(_DWORD *, _DWORD, int *))v9)(v26, 0, &v18);
      v11 = ((int (__stdcall *)(_DWORD *, int))v9)(v25, v10);
      sub_40225C(v11);
      v6();
      v22 = 16;
      v21[0] = 32770;
      if ( (unsigned __int16)dword_401000(v21, v26) != 0 )
      {
        v18 = 0;
        v12 = ((int (__stdcall *)(_DWORD *, int, _DWORD, int *))v9)(v25, 16, 0, &v18);
        sub_40225C(v12);
        v6();
      }
      v8 = dword_40116C(v26, v17, v16);
    }
    dword_401024();
  }
  v27 = (int *)&loc_404E5C;
  dword_401028(2, v17, v16);
  v13 = (int (__thiscall *)(_DWORD *))dword_401018;
  dword_401018(v26);
  return v13(v25);
}
// 404D02: bad sp value at call
// 404D0B: bad sp value at call
// 404D18: bad sp value at call
// 404D46: bad sp value at call
// 404D92: bad sp value at call
// 404DAE: bad sp value at call
// 404DB5: bad sp value at call
// 404DD5: bad sp value at call
// 404DEE: bad sp value at call
// 404E0A: bad sp value at call
// 404E42: bad sp value at call
// 404E54: bad sp value at call
// 404E59: bad sp value at call
// 401000: using guessed type int (__stdcall *dword_401000)(_DWORD, _DWORD);
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401024: using guessed type int (*dword_401024)(void);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 4010D4: using guessed type int (__stdcall *dword_4010D4)(_DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 40113C: using guessed type int (__stdcall *dword_40113C)(_DWORD, _DWORD);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 401174: using guessed type int (__thiscall *dword_401174)(_DWORD, _DWORD);
// 401200: using guessed type int dword_401200[2];

//----- (00404E70) --------------------------------------------------------
#error "40500A: call analysis failed (funcsize=145)"

//----- (004050E0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_4050E0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  void (__fastcall *v3)(_DWORD *, _DWORD *); // esi
  int v4; // eax
  int v5; // eax
  void (__thiscall *v6)(_DWORD *); // esi
  _DWORD v8[4]; // [esp-10h] [ebp-70h] BYREF
  _DWORD v9[4]; // [esp+0h] [ebp-60h] BYREF
  _DWORD v10[4]; // [esp+10h] [ebp-50h] BYREF
  _DWORD v11[4]; // [esp+20h] [ebp-40h] BYREF
  _DWORD v12[4]; // [esp+30h] [ebp-30h] BYREF
  _DWORD v13[4]; // [esp+40h] [ebp-20h] BYREF
  struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList; // [esp+50h] [ebp-10h]
  void *v15; // [esp+54h] [ebp-Ch]
  _DWORD *v16; // [esp+58h] [ebp-8h]
  int *v17; // [esp+5Ch] [ebp-4h]
  void *savedregs; // [esp+60h] [ebp+0h]

  v15 = &sub_401296;
  ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
  v16 = v8;
  v17 = dword_401228;
  ((void (__stdcall *)(int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, struct _EXCEPTION_REGISTRATION_RECORD *, void *))dword_401078)(
    a2,
    a3,
    a1,
    v8[3],
    0,
    v9[1],
    v9[2],
    v9[3],
    0,
    v10[1],
    v10[2],
    v10[3],
    0,
    v11[1],
    v11[2],
    v11[3],
    0,
    v12[1],
    v12[2],
    v12[3],
    0,
    v13[1],
    v13[2],
    v13[3],
    ExceptionList,
    &sub_401296);
  dword_401144(0, 1089470464);
  v3 = (void (__fastcall *)(_DWORD *, _DWORD *))dword_401010;
  dword_401010(v12, v9);
  dword_401124(0, 1076887552, 0, 0x40000000);
  v3(v11, v9);
  v4 = dword_401004(v10, v11, v12);
  v3(v13, (_DWORD *)v4);
  v5 = dword_401138(v10, v13, v11);
  v3(v12, (_DWORD *)v5);
  dword_401148(v13, v11);
  savedregs = &loc_4051CB;
  v6 = (void (__thiscall *)(_DWORD *))dword_401018;
  dword_401018(v13);
  v6(v12);
  return ((int (__thiscall *)(_DWORD *))v6)(v11);
}
// 405143: bad sp value at call
// 405163: bad sp value at call
// 405171: bad sp value at call
// 40517C: bad sp value at call
// 40518A: bad sp value at call
// 405195: bad sp value at call
// 40519D: bad sp value at call
// 4051BE: bad sp value at call
// 4051C3: bad sp value at call
// 4051C8: bad sp value at call
// 401004: using guessed type int (__stdcall *dword_401004)(_DWORD, _DWORD, _DWORD);
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401078: using guessed type int (__stdcall *dword_401078)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401124: using guessed type double (__stdcall *dword_401124)(_DWORD, _DWORD, _DWORD, _DWORD);
// 401138: using guessed type int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD);
// 401144: using guessed type double (__stdcall *dword_401144)(_DWORD, _DWORD);
// 401148: using guessed type int (__fastcall *dword_401148)(_DWORD, _DWORD);
// 401228: using guessed type int dword_401228[2];

//----- (004051E0) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_4051E0@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  void (__fastcall *v3)(_DWORD *, _DWORD *); // esi
  int (__stdcall *v4)(_DWORD *, _DWORD *, _DWORD *); // edi
  int v5; // eax
  int v6; // eax
  int v7; // eax
  void (__thiscall *v8)(_DWORD *); // esi
  _DWORD v10[5]; // [esp-14h] [ebp-98h] BYREF
  _DWORD v11[4]; // [esp+0h] [ebp-84h] BYREF
  _DWORD v12[4]; // [esp+10h] [ebp-74h] BYREF
  _DWORD v13[4]; // [esp+20h] [ebp-64h] BYREF
  _DWORD v14[4]; // [esp+30h] [ebp-54h] BYREF
  _DWORD v15[8]; // [esp+40h] [ebp-44h] BYREF
  _DWORD v16[8]; // [esp+60h] [ebp-24h] BYREF
  void *savedregs; // [esp+84h] [ebp+0h]

  v16[5] = &sub_401296;
  v16[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v16[6] = v10;
  v16[7] = dword_401238;
  v16[0] = 0;
  dword_401078(
    a2,
    a3,
    a1,
    v10[3],
    v10[4],
    0,
    v11[1],
    v11[2],
    v11[3],
    0,
    v12[1],
    v12[2],
    v12[3],
    0,
    v13[1],
    v13[2],
    v13[3],
    0,
    v14[1],
    v14[2],
    v14[3],
    0,
    v15[1],
    v15[2],
    v15[3],
    0,
    v15[5],
    v15[6],
    v15[7]);
  dword_401144(0, 1081081856);
  v3 = (void (__fastcall *)(_DWORD *, _DWORD *))dword_401010;
  dword_401010(v15, v11);
  dword_401124(0, 1075838976, 0, 0x40000000);
  v3(v14, v11);
  v4 = (int (__stdcall *)(_DWORD *, _DWORD *, _DWORD *))dword_401138;
  v5 = dword_401138(v13, v11, v15);
  v3(v16, (_DWORD *)v5);
  v6 = v4(v13, v14, v15);
  v7 = v4(v12, v16, (_DWORD *)v6);
  v3(v15, (_DWORD *)v7);
  dword_401018(v13);
  savedregs = &loc_405316;
  v8 = (void (__thiscall *)(_DWORD *))dword_401018;
  dword_401018(v16);
  v8(v15);
  return ((int (__thiscall *)(_DWORD *))v8)(v14);
}
// 405252: bad sp value at call
// 405278: bad sp value at call
// 4052A3: bad sp value at call
// 4052AA: bad sp value at call
// 4052B8: bad sp value at call
// 4052C3: bad sp value at call
// 4052CA: bad sp value at call
// 4052CF: bad sp value at call
// 405309: bad sp value at call
// 40530E: bad sp value at call
// 405313: bad sp value at call
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401078: using guessed type int (__stdcall *dword_401078)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401124: using guessed type double (__stdcall *dword_401124)(_DWORD, _DWORD, _DWORD, _DWORD);
// 401138: using guessed type int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD);
// 401144: using guessed type double (__stdcall *dword_401144)(_DWORD, _DWORD);
// 401238: using guessed type int dword_401238[2];

//----- (00405350) --------------------------------------------------------
#error "405943: call analysis failed (funcsize=606)"

//----- (00405E40) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_405E40@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  int (__fastcall *v3)(_DWORD, _DWORD); // edi
  _DWORD v5[6]; // [esp-18h] [ebp-6Ch] BYREF
  _DWORD v6[2]; // [esp+0h] [ebp-54h] BYREF
  int v7; // [esp+8h] [ebp-4Ch]
  int v8; // [esp+10h] [ebp-44h]
  _DWORD v9[4]; // [esp+20h] [ebp-34h] BYREF
  _DWORD v10[8]; // [esp+30h] [ebp-24h] BYREF
  void *savedregs; // [esp+54h] [ebp+0h]

  v10[5] = &sub_401296;
  v10[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v5[2] = a1;
  v5[1] = a3;
  v5[0] = a2;
  v10[6] = v5;
  v10[7] = dword_401260;
  v10[0] = 0;
  v9[0] = 0;
  v8 = 0;
  v6[0] = 0;
  sub_4022F4(2035711);
  dword_40104C();
  v3 = dword_401010;
  dword_401010(v9, v6);
  v7 = 0;
  v6[0] = 32770;
  if ( (unsigned __int16)dword_4010A8(v6, v9) != 0 )
  {
    ((void (__fastcall *)(_DWORD *, _DWORD *, void *))v3)(v10, v6, savedregs);
    v7 = 0;
    v6[0] = 2;
    v3(dword_407080, v6);
  }
  else
  {
    v7 = -1;
    v6[0] = 11;
    ((void (__fastcall *)(_DWORD *, _DWORD *, void *))v3)(v10, v6, savedregs);
    dword_401148(dword_407080, v9);
  }
  savedregs = &loc_405F40;
  return dword_401018(v9);
}
// 405EA6: bad sp value at call
// 405EBA: bad sp value at call
// 405ED5: bad sp value at call
// 405EE9: bad sp value at call
// 405F06: bad sp value at call
// 405F10: bad sp value at call
// 405F39: bad sp value at call
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 4010A8: using guessed type int (__cdecl *dword_4010A8)(_DWORD, _DWORD);
// 401148: using guessed type int (__fastcall *dword_401148)(_DWORD, _DWORD);
// 401260: using guessed type int dword_401260[2];
// 407080: using guessed type int dword_407080[5];

//----- (00405F70) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_405F70@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  int v3; // eax
  int (__stdcall *v4)(_DWORD *); // esi
  unsigned int v5; // edi
  int (__stdcall *v6)(int, _DWORD *); // ebx
  int v7; // eax
  int v8; // eax
  int v9; // eax
  int v10; // eax
  unsigned int v11; // edi
  int v12; // eax
  int v13; // eax
  unsigned int v14; // edi
  int v15; // eax
  int v16; // eax
  int v17; // eax
  int v18; // eax
  int v19; // eax
  unsigned int v20; // edi
  int v21; // eax
  int v22; // eax
  _DWORD v24[5]; // [esp-14h] [ebp-568h] BYREF
  _BYTE v25[296]; // [esp+0h] [ebp-554h] BYREF
  _BYTE v26[296]; // [esp+128h] [ebp-42Ch] BYREF
  _DWORD v27[4]; // [esp+250h] [ebp-304h] BYREF
  _DWORD v28[5]; // [esp+260h] [ebp-2F4h] BYREF
  int v29; // [esp+274h] [ebp-2E0h]
  int v30; // [esp+278h] [ebp-2DCh]
  _DWORD v31[4]; // [esp+27Ch] [ebp-2D8h] BYREF
  _DWORD v32[2]; // [esp+28Ch] [ebp-2C8h] BYREF
  int v33; // [esp+294h] [ebp-2C0h]
  _DWORD v34[2]; // [esp+29Ch] [ebp-2B8h] BYREF
  int v35; // [esp+2A4h] [ebp-2B0h]
  _DWORD v36[4]; // [esp+2ACh] [ebp-2A8h] BYREF
  _DWORD v37[4]; // [esp+2BCh] [ebp-298h] BYREF
  _DWORD v38[4]; // [esp+2CCh] [ebp-288h] BYREF
  _DWORD v39[2]; // [esp+2DCh] [ebp-278h] BYREF
  int v40; // [esp+2E4h] [ebp-270h]
  _DWORD v41[4]; // [esp+2ECh] [ebp-268h] BYREF
  int v42; // [esp+2FCh] [ebp-258h] BYREF
  int v43; // [esp+300h] [ebp-254h] BYREF
  _DWORD v44[140]; // [esp+304h] [ebp-250h] BYREF
  _DWORD v45[4]; // [esp+534h] [ebp-20h] BYREF
  struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList; // [esp+544h] [ebp-10h]
  void *v47; // [esp+548h] [ebp-Ch]
  _DWORD *v48; // [esp+54Ch] [ebp-8h]
  int *v49; // [esp+550h] [ebp-4h]

  v47 = &sub_401296;
  ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
  v24[2] = a1;
  v24[1] = a3;
  v24[0] = a2;
  v48 = v24;
  v49 = dword_401270;
  memset(v44, 0, 0x22Cu);
  memset(v26, 0, sizeof(v26));
  memset(v25, 0, sizeof(v25));
  v45[0] = 0;
  v43 = 0;
  v42 = 0;
  v41[0] = 0;
  v39[0] = 0;
  v38[0] = 0;
  v37[0] = 0;
  v36[0] = 0;
  v34[0] = 0;
  v32[0] = 0;
  v31[0] = 0;
  v28[0] = 0;
  v27[0] = 0;
  v44[0] = 296;
  v30 = 0;
  v29 = sub_402510(2);
  dword_40104C();
  v35 = 1;
  v34[0] = 2;
  v33 = 256;
  v32[0] = 2;
  v31[2] = 0;
  v31[0] = 2;
  v3 = dword_40105C(v45, v28, v27, v31, v32, v34);
  v4 = (int (__stdcall *)(_DWORD *))dword_401134;
  while ( v3 != 0 )
  {
    v5 = v4(v45);
    if ( v5 >= 0x101 )
      dword_4010A0();
    dword_401114(dword_407044 + 4 * v5, &dword_4025E0);
    v3 = dword_40116C(v45, v28, v27);
  }
  dword_401010(v45, v34);
  v49 = (int *)dword_4010BC(dword_4020EC, v26, v44);
  sub_402474(v29);
  dword_40104C();
  dword_401040(dword_4020EC, v44, v26);
  v6 = (int (__stdcall *)(int, _DWORD *))dword_401080;
  v40 = dword_401080(260, &v44[9]);
  v39[0] = 8;
  dword_4010E0(v41, 0);
  v35 = 1;
  v34[0] = 2;
  v7 = v6(260, &v44[9]);
  dword_401158(&v43, v7);
  v33 = (int)&v43;
  v32[0] = 16392;
  v8 = dword_4010E8(v38, 0, v41, v39, 1);
  v9 = dword_401004(v37, v34, v8);
  v10 = v4((_DWORD *)v9);
  dword_401150(v36, v32, v10);
  dword_401048(260, &v44[9], v43);
  v11 = v4(v45);
  if ( v11 >= 0x101 )
    dword_4010A0();
  v12 = dword_40101C(v36);
  v13 = dword_401158(&v42, v12);
  dword_401114(dword_407044 + 4 * v11, v13);
  dword_40111C(2, &v43, &v42);
  ExceptionList = (struct _EXCEPTION_REGISTRATION_RECORD *)v36;
  v45[3] = v38;
  dword_401028(4, v41, v39);
  v14 = v4(v45);
  if ( v14 >= 0x101 )
LABEL_9:
    dword_4010A0();
  while ( 1 )
  {
    *(_WORD *)(dword_407060 + 2 * v14) = dword_4010B0(v44[2]);
    v49 = (int *)dword_4010BC(dword_4020EC, v25, v44);
    v30 = sub_4024BC(v29);
    dword_40104C();
    dword_401040(dword_4020EC, v44, v25);
    if ( v30 == 0 )
      break;
    v15 = dword_401138(v41, v34, v45);
    dword_401010(v45, v15);
    v40 = v6(260, &v44[9]);
    v39[0] = 8;
    dword_4010E0(v41, 0);
    v35 = 1;
    v34[0] = 2;
    v16 = v6(260, &v44[9]);
    dword_401158(&v43, v16);
    v33 = (int)&v43;
    v32[0] = 16392;
    v17 = dword_4010E8(v38, 0, v41, v39, 1);
    v18 = dword_401004(v37, v34, v17);
    v19 = v4((_DWORD *)v18);
    dword_401150(v36, v32, v19);
    dword_401048(260, &v44[9], v43);
    v20 = v4(v45);
    if ( v20 >= 0x101 )
      dword_4010A0();
    v21 = dword_40101C(v36);
    v22 = dword_401158(&v42, v21);
    dword_401114(dword_407044 + 4 * v20, v22);
    dword_40111C(2, &v43, &v42);
    ExceptionList = (struct _EXCEPTION_REGISTRATION_RECORD *)v36;
    v45[3] = v38;
    dword_401028(4, v41, v39);
    v14 = v4(v45);
    if ( v14 >= 0x101 )
      goto LABEL_9;
  }
  v49 = (int *)&loc_40653A;
  dword_401028(2, v28, v27);
  return dword_401018(v45);
}
// 406093: bad sp value at call
// 4060A7: bad sp value at call
// 4060DE: bad sp value at call
// 406100: bad sp value at call
// 406119: bad sp value at call
// 406145: bad sp value at call
// 40615D: bad sp value at call
// 406178: bad sp value at call
// 40619A: bad sp value at call
// 4061A4: bad sp value at call
// 4061D9: bad sp value at call
// 4061EE: bad sp value at call
// 406206: bad sp value at call
// 40621F: bad sp value at call
// 406229: bad sp value at call
// 406242: bad sp value at call
// 406250: bad sp value at call
// 406276: bad sp value at call
// 40629A: bad sp value at call
// 4062A7: bad sp value at call
// 4062E2: bad sp value at call
// 406314: bad sp value at call
// 40634F: bad sp value at call
// 40635A: bad sp value at call
// 40636C: bad sp value at call
// 406387: bad sp value at call
// 4063A9: bad sp value at call
// 4063B3: bad sp value at call
// 4063E8: bad sp value at call
// 4063FD: bad sp value at call
// 406415: bad sp value at call
// 40642E: bad sp value at call
// 406438: bad sp value at call
// 406451: bad sp value at call
// 40645F: bad sp value at call
// 406485: bad sp value at call
// 4064A9: bad sp value at call
// 4064B6: bad sp value at call
// 406527: bad sp value at call
// 406533: bad sp value at call
// 401004: using guessed type int (__stdcall *dword_401004)(_DWORD, _DWORD, _DWORD);
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 40101C: using guessed type int (__cdecl *dword_40101C)(_DWORD);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 401040: using guessed type int (__stdcall *dword_401040)(_DWORD, _DWORD, _DWORD);
// 401048: using guessed type int (__stdcall *dword_401048)(_DWORD, _DWORD, _DWORD);
// 40104C: using guessed type int (*dword_40104C)(void);
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401080: using guessed type int (__stdcall *dword_401080)(_DWORD, _DWORD);
// 4010A0: using guessed type int (*dword_4010A0)(void);
// 4010B0: using guessed type int (__thiscall *dword_4010B0)(_DWORD);
// 4010BC: using guessed type int (__stdcall *dword_4010BC)(_DWORD, _DWORD, _DWORD);
// 4010E0: using guessed type int (__cdecl *dword_4010E0)(_DWORD, _DWORD);
// 4010E8: using guessed type int (__stdcall *dword_4010E8)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401114: using guessed type int (__fastcall *dword_401114)(_DWORD, _DWORD);
// 40111C: using guessed type int (__cdecl *dword_40111C)(_DWORD, _DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 401138: using guessed type int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD);
// 401150: using guessed type int (__cdecl *dword_401150)(_DWORD, _DWORD, _DWORD);
// 401158: using guessed type int (__fastcall *dword_401158)(_DWORD, _DWORD);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 401270: using guessed type int dword_401270[2];
// 4020EC: using guessed type int dword_4020EC[7];
// 4025E0: using guessed type int dword_4025E0;
// 407044: using guessed type int dword_407044;
// 407060: using guessed type int dword_407060;

//----- (00406550) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_406550@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>)
{
  int v3; // eax
  int (__stdcall *v4)(_DWORD *); // edi
  unsigned int v5; // esi
  int i; // eax
  int v7; // eax
  int v8; // eax
  int v9; // eax
  void (__fastcall *v10)(_DWORD *, int); // esi
  int v11; // eax
  void (__thiscall *v12)(_DWORD *); // esi
  _DWORD v14[7]; // [esp-1Ch] [ebp-118h] BYREF
  _DWORD v15[4]; // [esp+0h] [ebp-FCh] BYREF
  _DWORD v16[4]; // [esp+10h] [ebp-ECh] BYREF
  _DWORD v17[4]; // [esp+20h] [ebp-DCh] BYREF
  _DWORD v18[5]; // [esp+30h] [ebp-CCh] BYREF
  _DWORD v19[2]; // [esp+44h] [ebp-B8h] BYREF
  int v20; // [esp+4Ch] [ebp-B0h]
  _DWORD v21[2]; // [esp+54h] [ebp-A8h] BYREF
  int v22; // [esp+5Ch] [ebp-A0h]
  _DWORD v23[2]; // [esp+64h] [ebp-98h] BYREF
  int v24; // [esp+6Ch] [ebp-90h]
  _DWORD v25[4]; // [esp+74h] [ebp-88h] BYREF
  _DWORD v26[4]; // [esp+84h] [ebp-78h] BYREF
  _DWORD v27[4]; // [esp+94h] [ebp-68h] BYREF
  int v28; // [esp+A4h] [ebp-58h] BYREF
  int v29; // [esp+A8h] [ebp-54h] BYREF
  _DWORD v30[4]; // [esp+B8h] [ebp-44h] BYREF
  _DWORD v31[4]; // [esp+C8h] [ebp-34h] BYREF
  _DWORD v32[7]; // [esp+D8h] [ebp-24h] BYREF
  int *v33; // [esp+F4h] [ebp-8h]
  _DWORD *v34; // [esp+F8h] [ebp-4h]
  void *savedregs; // [esp+FCh] [ebp+0h]

  v32[5] = &sub_401296;
  v32[4] = NtCurrentTeb()->NtTib.ExceptionList;
  v14[2] = a1;
  v14[1] = a3;
  v14[0] = a2;
  v32[6] = v14;
  v33 = dword_401280;
  v32[0] = 0;
  v31[0] = 0;
  v30[0] = 0;
  v29 = 0;
  v28 = 0;
  v27[0] = 0;
  v26[0] = 0;
  v25[0] = 0;
  v18[0] = 0;
  v17[0] = 0;
  v16[0] = 0;
  v15[0] = 0;
  v24 = 1;
  v23[0] = 2;
  v22 = 4000;
  v21[0] = 2;
  v20 = 0;
  v19[0] = 2;
  v3 = dword_40105C(v31, v18, v17, v19, v21, v23);
  v4 = (int (__stdcall *)(_DWORD *))dword_401134;
  while ( v3 != 0 )
  {
    v24 = 1;
    v23[0] = 2;
    v5 = v4(v31);
    if ( v5 >= 0xFA1 )
      dword_4010A0();
    v22 = dword_401020(*(_DWORD *)(dword_4070B4 + 4 * v5));
    v21[0] = 3;
    v20 = 1;
    v19[0] = 2;
    for ( i = dword_40105C(v32, v16, v15, v19, v21, v23); i != 0; i = dword_40116C(v32, v16, v15) )
    {
      v27[2] = 1;
      v27[0] = 2;
      if ( (unsigned int)v4(v31) >= 0xFA1 )
        dword_4010A0();
      v7 = ((int (__stdcall *)(_DWORD *, _DWORD *))v4)(v32, v27);
      dword_401094(v26, v23, v7);
      v8 = dword_4010EC(&v28, v26);
      LOWORD(v20) = dword_401034(v8);
      v19[0] = 2;
      v9 = dword_401138(v25, v19, v30);
      v10 = (void (__fastcall *)(_DWORD *, int))dword_401010;
      dword_401010(v30, v9);
      dword_401174(&v28, savedregs);
      dword_401028(2, v27, v26);
      v24 = 30000;
      v23[0] = 32770;
      if ( (unsigned __int16)dword_401000(v23, v30) != 0 )
      {
        v24 = 30000;
        v23[0] = 2;
        v11 = dword_401004(v27, v23, v30);
        v10(v30, v11);
      }
    }
    v3 = dword_40116C(v31, v18, v17);
  }
  dword_401148(&v29, v30);
  savedregs = &loc_406874;
  v34 = v15;
  v33 = v16;
  dword_401028(4, v18, v17);
  v12 = (void (__thiscall *)(_DWORD *))dword_401018;
  dword_401018(v32);
  v12(v31);
  return ((int (__thiscall *)(_DWORD *))v12)(v30);
}
// 406631: bad sp value at call
// 40669A: bad sp value at call
// 4066B6: bad sp value at call
// 4066E9: bad sp value at call
// 4066F7: bad sp value at call
// 406705: bad sp value at call
// 406731: bad sp value at call
// 406742: bad sp value at call
// 406747: bad sp value at call
// 406756: bad sp value at call
// 40677E: bad sp value at call
// 4067A8: bad sp value at call
// 4067B3: bad sp value at call
// 4067C7: bad sp value at call
// 4067E4: bad sp value at call
// 4067F7: bad sp value at call
// 406855: bad sp value at call
// 406867: bad sp value at call
// 40686C: bad sp value at call
// 406871: bad sp value at call
// 401000: using guessed type int (__stdcall *dword_401000)(_DWORD, _DWORD);
// 401004: using guessed type int (__stdcall *dword_401004)(_DWORD, _DWORD, _DWORD);
// 401010: using guessed type int (__fastcall *dword_401010)(_DWORD, _DWORD);
// 401018: using guessed type int (__thiscall *dword_401018)(_DWORD);
// 401020: using guessed type int (__cdecl *dword_401020)(_DWORD);
// 401028: using guessed type int (__cdecl *dword_401028)(_DWORD, _DWORD, _DWORD);
// 401034: using guessed type int (__stdcall *dword_401034)(_DWORD);
// 40105C: using guessed type int (__cdecl *dword_40105C)(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401094: using guessed type int (__cdecl *dword_401094)(_DWORD, _DWORD, _DWORD);
// 4010A0: using guessed type int (*dword_4010A0)(void);
// 4010EC: using guessed type int (__stdcall *dword_4010EC)(_DWORD, _DWORD);
// 401134: using guessed type int (__cdecl *dword_401134)(_DWORD);
// 401138: using guessed type int (__cdecl *dword_401138)(_DWORD, _DWORD, _DWORD);
// 401148: using guessed type int (__fastcall *dword_401148)(_DWORD, _DWORD);
// 40116C: using guessed type int (__cdecl *dword_40116C)(_DWORD, _DWORD, _DWORD);
// 401174: using guessed type int (__thiscall *dword_401174)(_DWORD, _DWORD);
// 401280: using guessed type int dword_401280[2];
// 4070B4: using guessed type int dword_4070B4;

// nfuncs=132 queued=33 decompiled=33 lumina nreq=0 worse=0 better=0
#error "There were 3 decompilation failure(s) on 33 function(s)"
