/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void start();

//-------------------------------------------------------------------------
// Data declarations

int (**off_40CFDC)[9216] = &off_40CFC0; // weak


//----- (00400154) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void start()
{
  int v0; // ebx
  unsigned int v1; // ebp
  _BYTE *v2; // edi
  _BYTE *v3; // esi
  unsigned int v4; // eax
  int v5; // edx
  int v6; // ecx
  unsigned int v7; // ecx
  int v8; // eax
  char v9; // tt
  int v10; // eax
  int v11; // edx
  int v12; // ecx
  bool v13; // cf
  unsigned int v14; // eax
  _DWORD *v15; // esi
  _DWORD *v16; // eax
  int *v17; // esi
  _DWORD *v18; // edi
  int v19; // eax
  int v20; // ebp
  _DWORD v21[6]; // [esp-20h] [ebp-20h] BYREF
  _BYTE *v22; // [esp-8h] [ebp-8h]
  _BYTE *v23; // [esp-4h] [ebp-4h]

  _InterlockedExchange((volatile __int32 *)&off_40CFDC, (__int32)v21);
  v0 = v21[3];
  v1 = v21[5];
  v2 = v22;
  v3 = v23;
  v23 = (_BYTE *)v21[5];
LABEL_2:
  *v2++ = *v3++;
  while ( 1 )
  {
    (*(void (__cdecl **)(_BYTE *))v0)(v23);
    if ( !v13 )
      goto LABEL_2;
    (*(void (__thiscall **)(_DWORD))v0)(0);
    if ( !v13 )
      break;
    v4 = (*(int (**)(void))v0)();
    if ( !v13 )
    {
      LOBYTE(v4) = *v3++;
      v13 = v4 & 1;
      v14 = v4 >> 1;
      if ( v14 == 0 )
      {
        v15 = v23;
        while ( 1 )
        {
          v16 = (_DWORD *)*v15;
          v17 = v15 + 1;
          v18 = v16;
          v19 = *v17;
          v15 = v17 + 1;
          v20 = (*(int (__cdecl **)(int))(v0 + 16))(v19);
          while ( *v18 + 1 >= 0 )
          {
            if ( *v18 == -1 )
              __asm { jmp     dword ptr [ebx+0Ch] }
            *v18 = (*(int (__cdecl **)(int, int))(v0 + 20))(v20, *v18 + 1);
            ++v18;
          }
        }
      }
      v7 = v6 + v13 + v6;
LABEL_17:
      ++v7;
LABEL_18:
      ++v7;
      goto LABEL_19;
    }
    BYTE1(v5) = 0x80;
    v7 = v6 + 1;
    do
    {
      v8 = (*(int (__fastcall **)(unsigned int, int))v0)(v7, v5);
      v9 = v13 + v8;
      v13 = __CFADD__(v13, (_BYTE)v8) | __CFADD__((_BYTE)v8, v13 + v8);
      LOBYTE(v8) = v8 + v9;
    }
    while ( !v13 );
    if ( (_BYTE)v8 != 0 )
    {
LABEL_21:
      v22 = v3;
      qmemcpy(v2, &v2[-v8], v7);
      v2 += v7;
      v3 = v22;
    }
    else
    {
      *v2++ = 0;
    }
  }
  v10 = (*(int (**)(void))(v0 + 8))();
  v13 = __CFADD__(BYTE1(v11), BYTE1(v11));
  BYTE1(v11) *= 2;
  if ( v12 == v13 + 1 )
  {
    (*(void (__fastcall **)(_DWORD, int))(v0 + 4))(0, v11);
  }
  else
  {
    ++v3;
    v14 = (*(int (__fastcall **)(int, int))(v0 + 4))(v10, v11);
    if ( v14 >= *(_DWORD *)(v0 - 8) )
      goto LABEL_17;
    if ( BYTE1(v14) >= 5u )
      goto LABEL_18;
    if ( v14 <= 0x7F )
      goto LABEL_17;
LABEL_19:
    v1 = v14;
  }
  v8 = v1;
  goto LABEL_21;
}
// 40015B: positive sp value 20 has been found
// 400162: variable 'v13' is possibly undefined
// 400172: variable 'v6' is possibly undefined
// 400175: variable 'v7' is possibly undefined
// 400175: variable 'v5' is possibly undefined
// 400183: variable 'v11' is possibly undefined
// 400185: variable 'v12' is possibly undefined
// 40CFDC: using guessed type int (**off_40CFDC)[9216];

// nfuncs=1 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
