;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 45B99BFFDB6F2F99B3B571F395A71D92106B5DB95E8541E10F91989EB1C96E58
; Input MD5    : F86DB33AEFB6C60EC1E4E35D4BE3CC2C
; Input CRC32  : 7465883E
; Compiler     : Visual C++ (guessed)

; ---------------------------------------------------------------------------
; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-07/timotei-crackme-07.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 64764BA0 (Tue May 30 19:16:48 2023 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 000000B8 (    184.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

                .686p
                .mmx
                .model flat

; ===========================================================================

; Segment type: Pure code
; Segment permissions: Read/Execute
_text           segment para public 'CODE' use32
                assume cs:_text
                ;org 401000h
                assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing

                public start
start:                                  ; DATA XREF: .text:0040100C↓o
                push    offset unk_403102
                push    40h ; '@'
                push    3E8h
                push    offset start
                call    VirtualProtect
                push    0FFFFFFF5h
                call    GetStdHandle
                mov     dword_4030FE, eax
                push    0FFFFFFF6h
                call    GetStdHandle
                mov     dword_4030FA, eax
                push    0
                push    0
                push    1Ah
                push    offset aEnterThePassw0 ; "_.: eNter tHe pAsSw0rD : "
                push    dword_4030FE
                call    WriteConsoleA
                push    0
                push    offset unk_403092
                push    64h ; 'd'
                push    offset dword_40302E
                push    dword_4030FA
                call    ReadConsoleA
                mov     eax, dword_40302E
                xor     ds:dword_40106B, eax
; ---------------------------------------------------------------------------
dword_40106B    dd 9090469Fh            ; DATA XREF: .text:00401065↑w
; ---------------------------------------------------------------------------
                xor     al, 0Ch
                sub     al, 22h ; '"'
                xor     al, 38h
                push    0
                call    ExitProcess
; ---------------------------------------------------------------------------
                push    0
                push    0
                push    14h
                push    offset aL0ginAccepted ; "_.: l0gIn aCcEpTeD "
                push    dword_4030FE
                call    WriteConsoleA
                push    0
                call    ExitProcess
; ---------------------------------------------------------------------------
                align 2
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION GetStdHandle]
; [00000006 BYTES: COLLAPSED FUNCTION ReadConsoleA]
; [00000006 BYTES: COLLAPSED FUNCTION VirtualProtect]
; [00000006 BYTES: COLLAPSED FUNCTION WriteConsoleA]
                align 200h
                dd 380h dup(?)
_text           ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 000000B6 (    182.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000600
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from kernel32.dll
;
; ===========================================================================

; Segment type: Externs
; _idata
; HANDLE (__stdcall *GetStdHandle)(DWORD nStdHandle)
                extrn __imp_GetStdHandle:dword ; DATA XREF: GetStdHandle↑r
                                        ; .rdata:00402028↓o
                                        ; kernel32
; BOOL (__stdcall *ReadConsoleA)(HANDLE hConsoleInput, LPVOID lpBuffer, DWORD nNumberOfCharsToRead, LPDWORD lpNumberOfCharsRead, PCONSOLE_READCONSOLE_CONTROL pInputControl)
                extrn __imp_ReadConsoleA:dword ; DATA XREF: ReadConsoleA↑r
                                        ; kernel32
; BOOL (__stdcall *VirtualProtect)(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect)
                extrn __imp_VirtualProtect:dword ; DATA XREF: VirtualProtect↑r
                                        ; kernel32
; BOOL (__stdcall *WriteConsoleA)(HANDLE hConsoleOutput, const void *lpBuffer, DWORD nNumberOfCharsToWrite, LPDWORD lpNumberOfCharsWritten, LPVOID lpReserved)
                extrn __imp_WriteConsoleA:dword ; DATA XREF: WriteConsoleA↑r
                                        ; kernel32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
                extrn __imp_ExitProcess:dword ; DATA XREF: ExitProcess↑r
                                        ; kernel32


; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read
_rdata          segment para public 'DATA' use32
                assume cs:_rdata
                ;org 402018h
__IMPORT_DESCRIPTOR_kernel32 dd rva off_402040 ; Import Name Table
                dd 0                    ; Time stamp
                dd 0                    ; Forwarder Chain
                dd rva aKernel32Dll     ; DLL Name
                dd rva __imp_GetStdHandle ; Import Address Table
                align 20h
;
; Import names for kernel32.dll
;
off_402040      dd rva word_402066      ; DATA XREF: .rdata:__IMPORT_DESCRIPTOR_kernel32↑o
                dd rva word_402076
                dd rva word_402086
                dd rva word_402098
                dd rva word_402058
                dd 0
word_402058     dw 9Bh                  ; DATA XREF: .rdata:00402050↑o
                db 'ExitProcess',0
word_402066     dw 16Ah                 ; DATA XREF: .rdata:off_402040↑o
                db 'GetStdHandle',0
                align 2
word_402076     dw 233h                 ; DATA XREF: .rdata:00402044↑o
                db 'ReadConsoleA',0
                align 2
word_402086     dw 2DEh                 ; DATA XREF: .rdata:00402048↑o
                db 'VirtualProtect',0
                align 4
word_402098     dw 2EEh                 ; DATA XREF: .rdata:0040204C↑o
                db 'WriteConsoleA',0
aKernel32Dll    db 'kernel32.dll',0     ; DATA XREF: .rdata:00402024↑o
                align 1000h
_rdata          ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 00000106 (    262.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000800
; Flags C0000040: Data Readable Writable
; Alignment     : default
; ===========================================================================

; Segment type: Pure data
; Segment permissions: Read/Write
_data           segment para public 'DATA' use32
                assume cs:_data
                ;org 403000h
aEnterThePassw0 db '_.: eNter tHe pAsSw0rD : ',0 ; DATA XREF: .text:00401034↑o
aL0ginAccepted  db '_.: l0gIn aCcEpTeD ',0 ; DATA XREF: .text:00401082↑o
dword_40302E    dd 0                    ; DATA XREF: .text:00401050↑o
                                        ; .text:00401060↑r
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
unk_403092      db    0                 ; DATA XREF: .text:00401046↑o
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
dword_4030FA    dd 0                    ; DATA XREF: .text:00401029↑w
                                        ; .text:00401055↑r
dword_4030FE    dd 0                    ; DATA XREF: .text:0040101D↑w
                                        ; .text:00401039↑r ...
unk_403102      db    0                 ; DATA XREF: .text:start↑o
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                db    0
                align 1000h
_data           ends


                end start
