/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

// int __stdcall __vbaStrI2(_DWORD); weak
// int __fastcall __vbaVarMove(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __thiscall __vbaFreeVar(_DWORD); weak
// int __stdcall __vbaLenBstr(_DWORD); weak
// void __stdcall __noreturn __vbaEnd(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall rtcAnsiValueBstr(_DWORD); weak
// int __stdcall __vbaStrCat(_DWORD, _DWORD); weak
// int __vbaSetSystemError(void); weak
// int __stdcall __vbaHresultCheckObj(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaAryDestruct(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __vbaExitProc(void); weak
// double __stdcall rtcRandomNext(_DWORD); weak
// int __thiscall __vbaI4Abs(_DWORD); weak
// int __stdcall rtcRandomize(_DWORD); weak
// int __stdcall __vbaOnError(_DWORD); weak
// int __stdcall __vbaObjSet(_DWORD, _DWORD); weak
// int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int rtcDoEvents(void); weak
// int __stdcall __vbaErase(_DWORD, _DWORD); weak
// void __noreturn __vbaGenerateBoundsError(void); weak
// int __stdcall __vbaStrCmp(_DWORD, _DWORD); weak
// int __stdcall __vbaAryConstruct2(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __thiscall __vbaI2I4(_DWORD); weak
// int __cdecl __vbaRedim(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall rtcStrReverse(_DWORD); weak
// void __fastcall __noreturn __vbaErrorOverflow(_DWORD, _DWORD); weak
// double __stdcall __vbaR8Str(_DWORD); weak
// int __fastcall __vbaStrCopy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaI4Str(_DWORD); weak
// int __cdecl __vbaFreeStrList(_DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaVarTstNe(_DWORD, _DWORD); weak
// int __stdcall __vbaStrToAnsi(_DWORD, _DWORD); weak
// int __fastcall __vbaVarDup(_DWORD, _DWORD); weak
// int __fastcall __vbaVarCopy(_DWORD, _DWORD, _DWORD); weak
// int __usercall __vbaFpI4@<eax>(double@<st0>); weak
// int __fastcall __vbaStrMove(_DWORD, _DWORD); weak
// int __stdcall rtcRightCharVar(_DWORD, _DWORD, _DWORD); weak
// int __usercall __vbaR8IntI4@<eax>(double@<st0>); weak
// double __vbaFPInt(void); weak
// int __thiscall __vbaFreeStr(_DWORD, _DWORD); weak
// int __thiscall __vbaFreeObj(_DWORD); weak
// void __stdcall __noreturn _vbaFPException(_DWORD, _DWORD); weak
// double __stdcall adj_fdiv_m64(_DWORD, _DWORD); weak
// int __stdcall DllFunctionCall(_DWORD); weak
int __cdecl sub_11001E5C(int a1);
int __cdecl sub_110020F8(int a1);
int __cdecl sub_11002688(int a1);
int __cdecl sub_11002710(int a1);
int __cdecl sub_11002754(int a1);
int __cdecl sub_11002788(int a1);
int __cdecl sub_110027D4(int a1);
int __cdecl sub_11002834(int a1);
int __cdecl sub_11002880(int a1);
int __cdecl sub_110028CC(int a1);
int __cdecl sub_11002910(int a1);
int __cdecl sub_11002944(int a1);
int __cdecl sub_11002990(int a1);
_DWORD __cdecl sub_11002C10(_DWORD); // weak
// int __userpurge sub_110031A1@<eax>(int a1@<ebp>, int a2);
_DWORD __cdecl sub_110031D0(_DWORD, _DWORD, __int16); // weak
int sub_11003770();
int __stdcall sub_11003D90(_WORD *a1);
int __stdcall sub_11004470(int *a1, int *a2, int *a3, int *a4, int *a5, int *a6, int *a7, int *a8);
int __cdecl sub_11004650(int a1, int a2);
int __stdcall sub_110048E0(int a1, int a2);
int __stdcall sub_11004950(int a1, int a2, __int16 a3);
void sub_11005638();
// int __usercall sub_11005650@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4);
void __cdecl __noreturn sub_11005750(int a1);

//-------------------------------------------------------------------------
// Data declarations

int dword_110011C0[2] = { 262150, 0 }; // weak
int dword_11001220[2] = { 524302, 0 }; // weak
int dword_11001230[3] = { 262148, 0, 0 }; // weak
// extern _UNKNOWN _vbaExceptHandler; weak
char *off_110020E0[2] = { "kernel32", "GetTickCount" }; // weak
int dword_1100224C[4] = { 9568257, 4, 0, 0 }; // weak
char *off_11002670 = "kernel32"; // weak
char *off_110026F8 = "kernel32"; // weak
char *off_1100273C = "kernel32"; // weak
char *off_11002770[2] = { "kernel32", "CreateEventA" }; // weak
char *off_110027BC[2] = { "kernel32", "ContinueDebugEvent" }; // weak
char *off_1100281C[2] = { "kernel32.dll", "WaitForDebugEvent" }; // weak
char *off_11002868[2] = { "kernel32", "DebugActiveProcess" }; // weak
char *off_110028B4 = "kernel32"; // weak
char *off_110028F8 = "kernel32"; // weak
char *off_1100292C = "kernel32"; // weak
char *off_11002978[2] = { "kernel32", "WaitForSingleObject" }; // weak
int dword_11002A48[4] = { 92, 1651924831, 1684948321, 0 }; // weak
_UNKNOWN loc_110048C2; // weak
_UNKNOWN loc_11005730; // weak
int dword_11006034 = 0; // weak
int dword_11006050 = 0; // weak
int dword_1100606C = 0; // weak
int dword_11006078 = 0; // weak
int dword_1100607C = 0; // weak
int dword_11006080 = 0; // weak
int (*dword_11006400)(void) = NULL; // weak
int (*dword_1100640C)(void) = NULL; // weak
int (*dword_11006424)(void) = NULL; // weak
int (*dword_11006430)(void) = NULL; // weak
int (*dword_1100643C)(void) = NULL; // weak
int (*dword_11006448)(void) = NULL; // weak
int (*dword_11006454)(void) = NULL; // weak
int (*dword_11006460)(void) = NULL; // weak
int (*dword_1100646C)(void) = NULL; // weak
int (*dword_11006478)(void) = NULL; // weak
int (*dword_11006484)(void) = NULL; // weak
int (*dword_11006490)(void) = NULL; // weak


//----- (11001E5C) --------------------------------------------------------
int __cdecl sub_11001E5C(int a1)
{
  return sub_11002C10(a1 - 59);
}
// 11002C10: using guessed type _DWORD __cdecl sub_11002C10(_DWORD);

//----- (110020F8) --------------------------------------------------------
int __cdecl sub_110020F8(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006400 != nullptr )
    return dword_11006400();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_110020E0);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 110020E0: using guessed type char *off_110020E0[2];
// 11006400: using guessed type int (*dword_11006400)(void);

//----- (11002688) --------------------------------------------------------
int __cdecl sub_11002688(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_1100640C != nullptr )
    return dword_1100640C();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_11002670);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 11002670: using guessed type char *off_11002670;
// 1100640C: using guessed type int (*dword_1100640C)(void);

//----- (11002710) --------------------------------------------------------
int __cdecl sub_11002710(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006424 != nullptr )
    return dword_11006424();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_110026F8);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 110026F8: using guessed type char *off_110026F8;
// 11006424: using guessed type int (*dword_11006424)(void);

//----- (11002754) --------------------------------------------------------
int __cdecl sub_11002754(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006430 != nullptr )
    return dword_11006430();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_1100273C);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 1100273C: using guessed type char *off_1100273C;
// 11006430: using guessed type int (*dword_11006430)(void);

//----- (11002788) --------------------------------------------------------
int __cdecl sub_11002788(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_1100643C != nullptr )
    return dword_1100643C();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_11002770);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 11002770: using guessed type char *off_11002770[2];
// 1100643C: using guessed type int (*dword_1100643C)(void);

//----- (110027D4) --------------------------------------------------------
int __cdecl sub_110027D4(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006448 != nullptr )
    return dword_11006448();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_110027BC);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 110027BC: using guessed type char *off_110027BC[2];
// 11006448: using guessed type int (*dword_11006448)(void);

//----- (11002834) --------------------------------------------------------
int __cdecl sub_11002834(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006454 != nullptr )
    return dword_11006454();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_1100281C);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 1100281C: using guessed type char *off_1100281C[2];
// 11006454: using guessed type int (*dword_11006454)(void);

//----- (11002880) --------------------------------------------------------
int __cdecl sub_11002880(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006460 != nullptr )
    return dword_11006460();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_11002868);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 11002868: using guessed type char *off_11002868[2];
// 11006460: using guessed type int (*dword_11006460)(void);

//----- (110028CC) --------------------------------------------------------
int __cdecl sub_110028CC(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_1100646C != nullptr )
    return dword_1100646C();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_110028B4);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 110028B4: using guessed type char *off_110028B4;
// 1100646C: using guessed type int (*dword_1100646C)(void);

//----- (11002910) --------------------------------------------------------
int __cdecl sub_11002910(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006478 != nullptr )
    return dword_11006478();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_110028F8);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 110028F8: using guessed type char *off_110028F8;
// 11006478: using guessed type int (*dword_11006478)(void);

//----- (11002944) --------------------------------------------------------
int __cdecl sub_11002944(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006484 != nullptr )
    return dword_11006484();
  v2 = (int (__stdcall *)(int))DllFunctionCall(&off_1100292C);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 1100292C: using guessed type char *off_1100292C;
// 11006484: using guessed type int (*dword_11006484)(void);

//----- (11002990) --------------------------------------------------------
int __cdecl sub_11002990(int a1)
{
  int (__stdcall *v2)(int); // eax

  if ( dword_11006490 != nullptr )
    return dword_11006490();
  v2 = (int (__stdcall *)(int))DllFunctionCall(off_11002978);
  return v2(a1);
}
// 110012D0: using guessed type int __stdcall DllFunctionCall(_DWORD);
// 11002978: using guessed type char *off_11002978[2];
// 11006490: using guessed type int (*dword_11006490)(void);

//----- (11002C10) --------------------------------------------------------
#error "1100319A: call analysis failed (funcsize=409)"

//----- (110031A1) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __userpurge sub_110031A1@<eax>(int a1@<ebp>, int a2)
{
  (*(void (__cdecl **)(_DWORD))(**(_DWORD **)(a1 + 8) + 8))(*(_DWORD *)(a1 + 8));
  return *(_DWORD *)(a1 - 4);
}
// 110031BD: positive sp value C has been found
// 110031A1: could not find valid save-restore pair for ebx
// 110031A1: could not find valid save-restore pair for edi
// 110031A1: could not find valid save-restore pair for esi

//----- (110031D0) --------------------------------------------------------
#error "1100372D: call analysis failed (funcsize=253)"

//----- (11003770) --------------------------------------------------------
int sub_11003770()
{
  __int16 v0; // si
  int v1; // ebp
  int v2; // eax
  int v3; // edx
  int v4; // ecx
  int v5; // eax
  unsigned int v6; // edi
  int v7; // eax
  int v8; // edi
  int v9; // eax
  unsigned int v10; // edi
  int v11; // ebp
  int v12; // eax
  bool v13; // of
  int v14; // eax
  unsigned int v15; // edi
  int v16; // eax
  int v17; // edi
  int v18; // eax
  unsigned int v19; // edi
  __int16 v20; // ax
  int v21; // edi
  __int16 v22; // ax
  int v23; // ebp
  int v24; // eax
  unsigned int v25; // edi
  int v26; // eax
  int v27; // edi
  int v28; // eax
  unsigned int v29; // edi
  __int16 v30; // ax
  int v31; // edi
  __int16 v32; // ax
  int v33; // ebp
  int v34; // eax
  unsigned int v35; // edi
  int v36; // eax
  int v37; // edi
  int v38; // eax
  unsigned int v39; // edi
  __int16 v40; // ax

  dword_11006080 = sub_110048E0(dword_11006080, 1);
  dword_1100607C = sub_110048E0(dword_1100607C, dword_11006080);
  v0 = 0;
  do
  {
    if ( (unsigned int)v0 >= 0x101 )
      __vbaGenerateBoundsError();
    v1 = *(_DWORD *)(dword_11006050 + 4 * v0);
    v2 = sub_11004950(dword_11006078, 13, -1);
    LOWORD(v4) = v0 + 128;
    if ( __OFADD__(128, v0) )
      goto LABEL_61;
    dword_11006078 ^= v2;
    dword_11006078 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * (unsigned __int8)(v0 + 0x80)), dword_11006078);
    v5 = sub_11004950(v1, 2, 0);
    v6 = __vbaI4Abs(v5) % 256;
    if ( v6 >= 0x101 )
      __vbaGenerateBoundsError();
    v7 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v6), dword_11006078);
    v8 = sub_110048E0(v7, dword_1100607C);
    if ( (unsigned int)v0 >= 0x101 )
      __vbaGenerateBoundsError();
    *(_DWORD *)(dword_11006050 + 4 * v0) = v8;
    v9 = sub_11004950(v8, 10, 0);
    v10 = __vbaI4Abs(v9) % 256;
    if ( v10 >= 0x101 )
      __vbaGenerateBoundsError();
    dword_1100607C = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v10), v1);
    if ( (unsigned int)v0 >= 0x101 )
      __vbaGenerateBoundsError();
    v4 = dword_1100607C;
    LOWORD(v3) = v0 + 1;
    *(_DWORD *)(dword_11006034 + 4 * v0) = dword_1100607C;
    if ( __OFADD__(1, v0) )
      goto LABEL_61;
    if ( (unsigned int)(__int16)v3 >= 0x101 )
      __vbaGenerateBoundsError();
    v11 = *(_DWORD *)(dword_11006050 + 4 * (__int16)v3);
    v12 = sub_11004950(dword_11006078, 6, 0);
    LOWORD(v3) = v0 + 128;
    if ( __OFADD__(128, v0) )
      goto LABEL_61;
    v13 = __OFADD__(1, (_WORD)v3);
    LOWORD(v3) = v0 + 129;
    dword_11006078 ^= v12;
    if ( v13 )
      goto LABEL_61;
    dword_11006078 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * (unsigned __int8)v3), dword_11006078);
    v14 = sub_11004950(v11, 2, 0);
    v15 = __vbaI4Abs(v14) % 256;
    if ( v15 >= 0x101 )
      __vbaGenerateBoundsError();
    v16 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v15), dword_11006078);
    v17 = sub_110048E0(v16, dword_1100607C);
    LOWORD(v3) = v0 + 1;
    if ( __OFADD__(1, v0) )
      goto LABEL_61;
    if ( (unsigned int)(__int16)v3 >= 0x101 )
      __vbaGenerateBoundsError();
    *(_DWORD *)(dword_11006050 + 4 * (__int16)v3) = v17;
    v18 = sub_11004950(v17, 10, 0);
    v19 = __vbaI4Abs(v18) % 256;
    if ( v19 >= 0x101 )
      __vbaGenerateBoundsError();
    dword_1100607C = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v19), v11);
    v20 = v0 + 1;
    if ( __OFADD__(1, v0) )
      goto LABEL_61;
    v21 = v20;
    if ( (unsigned int)v20 >= 0x101 )
      __vbaGenerateBoundsError();
    v4 = dword_11006034;
    v3 = dword_1100607C;
    v22 = v0 + 2;
    *(_DWORD *)(dword_11006034 + 4 * v21) = dword_1100607C;
    if ( __OFADD__(2, v0) )
      goto LABEL_61;
    if ( (unsigned int)v22 >= 0x101 )
      __vbaGenerateBoundsError();
    v23 = *(_DWORD *)(dword_11006050 + 4 * v22);
    dword_11006078 ^= sub_11004950(dword_11006078, 2, -1);
    if ( __OFADD__(128, v0) || __OFADD__(2, v0 + 128) )
      goto LABEL_61;
    dword_11006078 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * (unsigned __int8)(v0 - 126)), dword_11006078);
    v24 = sub_11004950(v23, 2, 0);
    v25 = __vbaI4Abs(v24) % 256;
    if ( v25 >= 0x101 )
      __vbaGenerateBoundsError();
    v26 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v25), dword_11006078);
    v27 = sub_110048E0(v26, dword_1100607C);
    LOWORD(v3) = v0 + 2;
    if ( __OFADD__(2, v0) )
      goto LABEL_61;
    if ( (unsigned int)(__int16)v3 >= 0x101 )
      __vbaGenerateBoundsError();
    *(_DWORD *)(dword_11006050 + 4 * (__int16)v3) = v27;
    v28 = sub_11004950(v27, 10, 0);
    v29 = __vbaI4Abs(v28) % 256;
    if ( v29 >= 0x101 )
      __vbaGenerateBoundsError();
    dword_1100607C = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v29), v23);
    v30 = v0 + 2;
    if ( __OFADD__(2, v0) )
      goto LABEL_61;
    v31 = v30;
    if ( (unsigned int)v30 >= 0x101 )
      __vbaGenerateBoundsError();
    v4 = dword_11006034;
    v3 = dword_1100607C;
    v32 = v0 + 3;
    *(_DWORD *)(dword_11006034 + 4 * v31) = dword_1100607C;
    if ( __OFADD__(3, v0) )
      goto LABEL_61;
    if ( (unsigned int)v32 >= 0x101 )
      __vbaGenerateBoundsError();
    v33 = *(_DWORD *)(dword_11006050 + 4 * v32);
    dword_11006078 ^= sub_11004950(dword_11006078, 16, 0);
    if ( __OFADD__(128, v0) || __OFADD__(3, v0 + 128) )
      goto LABEL_61;
    dword_11006078 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * (unsigned __int8)(v0 - 125)), dword_11006078);
    v34 = sub_11004950(v33, 2, 0);
    v35 = __vbaI4Abs(v34) % 256;
    if ( v35 >= 0x101 )
      __vbaGenerateBoundsError();
    v36 = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v35), dword_11006078);
    v37 = sub_110048E0(v36, dword_1100607C);
    LOWORD(v3) = v0 + 3;
    if ( __OFADD__(3, v0) )
      goto LABEL_61;
    if ( (unsigned int)(__int16)v3 >= 0x101 )
      __vbaGenerateBoundsError();
    *(_DWORD *)(dword_11006050 + 4 * (__int16)v3) = v37;
    v38 = sub_11004950(v37, 10, 0);
    v39 = __vbaI4Abs(v38) % 256;
    if ( v39 >= 0x101 )
      __vbaGenerateBoundsError();
    dword_1100607C = sub_110048E0(*(_DWORD *)(dword_11006050 + 4 * v39), v33);
    v40 = v0 + 3;
    if ( __OFADD__(3, v0) )
      goto LABEL_61;
    if ( (unsigned int)v40 >= 0x101 )
      __vbaGenerateBoundsError();
    v4 = dword_11006034;
    v3 = dword_1100607C;
    v13 = __OFADD__(4, v0);
    v0 += 4;
    if ( v13 )
LABEL_61:
      __vbaErrorOverflow(v4, v3);
    *(_DWORD *)(dword_11006034 + 4 * v40) = dword_1100607C;
  }
  while ( v0 <= 252 );
  return 0;
}
// 110037F8: conditional instruction was optimized away because edi.4<100u
// 1100395E: conditional instruction was optimized away because edi.4<100u
// 11003AE5: conditional instruction was optimized away because edi.4<100u
// 11003C62: conditional instruction was optimized away because edi.4<100u
// 11003D8A: variable 'v4' is possibly undefined
// 11003D8A: variable 'v3' is possibly undefined
// 11001060: using guessed type int __thiscall __vbaI4Abs(_DWORD);
// 11001094: using guessed type void __noreturn __vbaGenerateBoundsError(void);
// 110010E8: using guessed type void __fastcall __noreturn __vbaErrorOverflow(_DWORD, _DWORD);
// 11006034: using guessed type int dword_11006034;
// 11006050: using guessed type int dword_11006050;
// 11006078: using guessed type int dword_11006078;
// 1100607C: using guessed type int dword_1100607C;
// 11006080: using guessed type int dword_11006080;

//----- (11003D90) --------------------------------------------------------
int __stdcall sub_11003D90(_WORD *a1)
{
  bool v1; // zf
  __int16 v2; // si
  int v3; // edx
  int v4; // ecx
  bool v5; // of
  __int16 v6; // si
  int v7; // eax
  __int16 v8; // ax
  int v9; // eax
  int v10; // eax
  __int16 v11; // ax
  int v12; // eax
  int v13; // eax
  int v14; // edi
  int v15; // edi
  int v16; // edi
  int v17; // edi
  int v18; // edi
  int v19; // edi
  __int16 v20; // si
  int v21; // eax
  int v22; // eax
  __int16 v23; // ax
  int v24; // eax
  int v25; // eax
  __int16 v26; // ax
  int v27; // eax
  __int16 v28; // ax
  int v29; // edi
  __int16 v30; // ax
  int v31; // edi
  __int16 v32; // ax
  int v33; // edi
  __int16 v34; // ax
  int v35; // edi
  __int16 v36; // ax
  int v37; // edi
  __int16 v38; // ax
  int v39; // edi
  __int16 v40; // ax
  int v42; // [esp+0h] [ebp-30h]
  int v43; // [esp+4h] [ebp-2Ch]
  int v44; // [esp+10h] [ebp-20h] BYREF
  int v45; // [esp+14h] [ebp-1Ch] BYREF
  int v46; // [esp+18h] [ebp-18h] BYREF
  int v47; // [esp+1Ch] [ebp-14h] BYREF
  int v48; // [esp+20h] [ebp-10h] BYREF
  int v49; // [esp+24h] [ebp-Ch] BYREF
  int v50; // [esp+28h] [ebp-8h] BYREF
  int v51; // [esp+2Ch] [ebp-4h] BYREF

  v1 = *a1 == 0;
  v45 = 0;
  v48 = 0;
  v51 = 0;
  v46 = 0;
  v49 = 0;
  v44 = 0;
  v47 = 0;
  v50 = 0;
  if ( !v1 )
    sub_11004650(v42, v43);
  v2 = 0;
  v44 = -1640531527;
  v45 = -1640531527;
  v46 = -1640531527;
  v47 = -1640531527;
  v48 = -1640531527;
  v49 = -1640531527;
  v50 = -1640531527;
  v51 = -1640531527;
  do
  {
    sub_11004470(&v44, &v45, &v46, &v47, &v48, &v49, &v50, &v51);
    v5 = __OFADD__(1, v2++);
    if ( v5 )
      goto LABEL_108;
  }
  while ( v2 <= 3 );
  v6 = 0;
  do
  {
    if ( *a1 != 0 )
    {
      if ( (unsigned int)v6 >= 0x101 )
        __vbaGenerateBoundsError();
      v7 = sub_110048E0(v44, *(_DWORD *)(dword_11006034 + 4 * v6));
      LOWORD(v3) = v6 + 1;
      v44 = v7;
      if ( __OFADD__(1, v6) )
        goto LABEL_108;
      if ( (unsigned int)(__int16)v3 >= 0x101 )
        __vbaGenerateBoundsError();
      v45 = sub_110048E0(v45, *(_DWORD *)(dword_11006034 + 4 * (__int16)v3));
      v8 = v6 + 2;
      if ( __OFADD__(2, v6) )
        goto LABEL_108;
      if ( (unsigned int)v8 >= 0x101 )
        __vbaGenerateBoundsError();
      v9 = sub_110048E0(v46, *(_DWORD *)(dword_11006034 + 4 * v8));
      LOWORD(v4) = v6 + 3;
      v46 = v9;
      if ( __OFADD__(3, v6) )
        goto LABEL_108;
      if ( (unsigned int)(__int16)v4 >= 0x101 )
        __vbaGenerateBoundsError();
      v10 = sub_110048E0(v47, *(_DWORD *)(dword_11006034 + 4 * (__int16)v4));
      LOWORD(v3) = v6 + 4;
      v47 = v10;
      if ( __OFADD__(4, v6) )
        goto LABEL_108;
      if ( (unsigned int)(__int16)v3 >= 0x101 )
        __vbaGenerateBoundsError();
      v48 = sub_110048E0(v48, *(_DWORD *)(dword_11006034 + 4 * (__int16)v3));
      v11 = v6 + 5;
      if ( __OFADD__(5, v6) )
        goto LABEL_108;
      if ( (unsigned int)v11 >= 0x101 )
        __vbaGenerateBoundsError();
      v12 = sub_110048E0(v49, *(_DWORD *)(dword_11006034 + 4 * v11));
      LOWORD(v4) = v6 + 6;
      v49 = v12;
      if ( __OFADD__(6, v6) )
        goto LABEL_108;
      if ( (unsigned int)(__int16)v4 >= 0x101 )
        __vbaGenerateBoundsError();
      v13 = sub_110048E0(v50, *(_DWORD *)(dword_11006034 + 4 * (__int16)v4));
      LOWORD(v3) = v6 + 7;
      v50 = v13;
      if ( __OFADD__(7, v6) )
        goto LABEL_108;
      if ( (unsigned int)(__int16)v3 >= 0x101 )
        __vbaGenerateBoundsError();
      v51 = sub_110048E0(v51, *(_DWORD *)(dword_11006034 + 4 * (__int16)v3));
    }
    sub_11004470(&v44, &v45, &v46, &v47, &v48, &v49, &v50, &v51);
    if ( (unsigned int)v6 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v44;
    LOWORD(v4) = v6 + 1;
    *(_DWORD *)(dword_11006050 + 4 * v6) = v44;
    if ( __OFADD__(1, v6) )
      goto LABEL_108;
    v14 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v45;
    LOWORD(v4) = v6 + 2;
    *(_DWORD *)(dword_11006050 + 4 * v14) = v45;
    if ( __OFADD__(2, v6) )
      goto LABEL_108;
    v15 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v46;
    LOWORD(v4) = v6 + 3;
    *(_DWORD *)(dword_11006050 + 4 * v15) = v46;
    if ( __OFADD__(3, v6) )
      goto LABEL_108;
    v16 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v47;
    LOWORD(v4) = v6 + 4;
    *(_DWORD *)(dword_11006050 + 4 * v16) = v47;
    if ( __OFADD__(4, v6) )
      goto LABEL_108;
    v17 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v48;
    LOWORD(v4) = v6 + 5;
    *(_DWORD *)(dword_11006050 + 4 * v17) = v48;
    if ( __OFADD__(5, v6) )
      goto LABEL_108;
    v18 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v49;
    LOWORD(v4) = v6 + 6;
    *(_DWORD *)(dword_11006050 + 4 * v18) = v49;
    if ( __OFADD__(6, v6) )
      goto LABEL_108;
    v19 = (__int16)v4;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v50;
    LOWORD(v4) = v6 + 7;
    *(_DWORD *)(dword_11006050 + 4 * v19) = v50;
    if ( __OFADD__(7, v6) )
      goto LABEL_108;
    if ( (unsigned int)(__int16)v4 >= 0x101 )
      __vbaGenerateBoundsError();
    v3 = v51;
    v5 = __OFADD__(8, v6);
    v6 += 8;
    if ( v5 )
      goto LABEL_108;
    *(_DWORD *)(dword_11006050 + 4 * (__int16)v4) = v51;
  }
  while ( v6 <= 248 );
  if ( *a1 != 0 )
  {
    v20 = 0;
    while ( 1 )
    {
      if ( (unsigned int)v20 >= 0x101 )
        __vbaGenerateBoundsError();
      v21 = sub_110048E0(v44, *(_DWORD *)(dword_11006050 + 4 * v20));
      LOWORD(v4) = v20 + 1;
      v44 = v21;
      if ( __OFADD__(1, v20) )
        break;
      if ( (unsigned int)(__int16)v4 >= 0x101 )
        __vbaGenerateBoundsError();
      v22 = sub_110048E0(v45, *(_DWORD *)(dword_11006050 + 4 * (__int16)v4));
      LOWORD(v3) = v20 + 2;
      v45 = v22;
      if ( __OFADD__(2, v20) )
        break;
      if ( (unsigned int)(__int16)v3 >= 0x101 )
        __vbaGenerateBoundsError();
      v46 = sub_110048E0(v46, *(_DWORD *)(dword_11006050 + 4 * (__int16)v3));
      v23 = v20 + 3;
      if ( __OFADD__(3, v20) )
        break;
      if ( (unsigned int)v23 >= 0x101 )
        __vbaGenerateBoundsError();
      v24 = sub_110048E0(v47, *(_DWORD *)(dword_11006050 + 4 * v23));
      LOWORD(v4) = v20 + 4;
      v47 = v24;
      if ( __OFADD__(4, v20) )
        break;
      if ( (unsigned int)(__int16)v4 >= 0x101 )
        __vbaGenerateBoundsError();
      v25 = sub_110048E0(v48, *(_DWORD *)(dword_11006050 + 4 * (__int16)v4));
      LOWORD(v3) = v20 + 5;
      v48 = v25;
      if ( __OFADD__(5, v20) )
        break;
      if ( (unsigned int)(__int16)v3 >= 0x101 )
        __vbaGenerateBoundsError();
      v49 = sub_110048E0(v49, *(_DWORD *)(dword_11006050 + 4 * (__int16)v3));
      v26 = v20 + 6;
      if ( __OFADD__(6, v20) )
        break;
      if ( (unsigned int)v26 >= 0x101 )
        __vbaGenerateBoundsError();
      v27 = sub_110048E0(v50, *(_DWORD *)(dword_11006050 + 4 * v26));
      LOWORD(v4) = v20 + 7;
      v50 = v27;
      if ( __OFADD__(7, v20) )
        break;
      if ( (unsigned int)(__int16)v4 >= 0x101 )
        __vbaGenerateBoundsError();
      v51 = sub_110048E0(v51, *(_DWORD *)(dword_11006050 + 4 * (__int16)v4));
      sub_11004470(&v44, &v45, &v46, &v47, &v48, &v49, &v50, &v51);
      if ( (unsigned int)v20 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v44;
      v28 = v20 + 1;
      *(_DWORD *)(dword_11006050 + 4 * v20) = v44;
      if ( __OFADD__(1, v20) )
        break;
      v29 = v28;
      if ( (unsigned int)v28 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v45;
      v30 = v20 + 2;
      *(_DWORD *)(dword_11006050 + 4 * v29) = v45;
      if ( __OFADD__(2, v20) )
        break;
      v31 = v30;
      if ( (unsigned int)v30 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v46;
      v32 = v20 + 3;
      *(_DWORD *)(dword_11006050 + 4 * v31) = v46;
      if ( __OFADD__(3, v20) )
        break;
      v33 = v32;
      if ( (unsigned int)v32 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v47;
      v34 = v20 + 4;
      *(_DWORD *)(dword_11006050 + 4 * v33) = v47;
      if ( __OFADD__(4, v20) )
        break;
      v35 = v34;
      if ( (unsigned int)v34 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v48;
      v36 = v20 + 5;
      *(_DWORD *)(dword_11006050 + 4 * v35) = v48;
      if ( __OFADD__(5, v20) )
        break;
      v37 = v36;
      if ( (unsigned int)v36 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v49;
      v38 = v20 + 6;
      *(_DWORD *)(dword_11006050 + 4 * v37) = v49;
      if ( __OFADD__(6, v20) )
        break;
      v39 = v38;
      if ( (unsigned int)v38 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v50;
      v40 = v20 + 7;
      *(_DWORD *)(dword_11006050 + 4 * v39) = v50;
      if ( __OFADD__(7, v20) )
        break;
      if ( (unsigned int)v40 >= 0x101 )
        __vbaGenerateBoundsError();
      v3 = dword_11006050;
      v4 = v51;
      v5 = __OFADD__(8, v20);
      v20 += 8;
      if ( v5 )
        break;
      *(_DWORD *)(dword_11006050 + 4 * v40) = v51;
      if ( v20 > 248 )
        return sub_11003770();
    }
LABEL_108:
    __vbaErrorOverflow(v4, v3);
  }
  return sub_11003770();
}
// 11003DC3: variable 'v42' is possibly undefined
// 11003DC3: variable 'v43' is possibly undefined
// 1100445D: variable 'v4' is possibly undefined
// 1100445D: variable 'v3' is possibly undefined
// 11001094: using guessed type void __noreturn __vbaGenerateBoundsError(void);
// 110010E8: using guessed type void __fastcall __noreturn __vbaErrorOverflow(_DWORD, _DWORD);
// 11006034: using guessed type int dword_11006034;
// 11006050: using guessed type int dword_11006050;

//----- (11004470) --------------------------------------------------------
int __stdcall sub_11004470(int *a1, int *a2, int *a3, int *a4, int *a5, int *a6, int *a7, int *a8)
{
  int v8; // ebp
  int v9; // ecx
  int v10; // edx
  int v11; // edx
  int v12; // edx
  int v13; // edx
  int v14; // edx
  int v15; // ecx
  int result; // eax

  v8 = sub_11004950(*a2, 11, -1) ^ *a1;
  *a1 = v8;
  *a4 = sub_110048E0(*a4, v8);
  *a2 = sub_110048E0(*a2, *a3);
  v9 = sub_11004950(*a3, 2, 0) ^ *a2;
  *a2 = v9;
  *a5 = sub_110048E0(*a5, v9);
  *a3 = sub_110048E0(*a3, *a4);
  v10 = sub_11004950(*a4, 8, -1) ^ *a3;
  *a3 = v10;
  *a6 = sub_110048E0(*a6, v10);
  *a4 = sub_110048E0(*a4, *a5);
  v11 = sub_11004950(*a5, 16, 0) ^ *a4;
  *a4 = v11;
  *a7 = sub_110048E0(*a7, v11);
  *a5 = sub_110048E0(*a5, *a6);
  v12 = sub_11004950(*a6, 10, -1) ^ *a5;
  *a5 = v12;
  *a8 = sub_110048E0(*a8, v12);
  *a6 = sub_110048E0(*a6, *a7);
  v13 = sub_11004950(*a7, 4, 0) ^ *a6;
  *a6 = v13;
  *a1 = sub_110048E0(*a1, v13);
  *a7 = sub_110048E0(*a7, *a8);
  v14 = sub_11004950(*a8, 8, -1) ^ *a7;
  *a7 = v14;
  *a2 = sub_110048E0(*a2, v14);
  *a8 = sub_110048E0(*a8, *a1);
  v15 = sub_11004950(*a1, 9, 0) ^ *a8;
  *a8 = v15;
  *a3 = sub_110048E0(*a3, v15);
  result = sub_110048E0(*a1, *a2);
  *a1 = result;
  return result;
}

//----- (11004650) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __cdecl sub_11004650(int a1, int a2)
{
  int v2; // edx
  _DWORD *v3; // ecx
  __int16 v4; // si
  int v5; // edi
  int v6; // eax
  int v7; // eax
  char v8; // fps
  double v9; // st7
  unsigned int v10; // edi
  char v11; // fps
  double v12; // st7
  char v13; // fps
  double v14; // st7
  unsigned int v15; // edi
  char v16; // fps
  double v17; // st7
  char v18; // fps
  double v19; // st7
  unsigned int v20; // edi
  _DWORD v22[7]; // [esp-1Ch] [ebp-78h] BYREF
  int v23[5]; // [esp+0h] [ebp-5Ch] BYREF
  _DWORD v24[2]; // [esp+14h] [ebp-48h] BYREF
  int v25; // [esp+1Ch] [ebp-40h]
  int v26; // [esp+20h] [ebp-3Ch]
  int v27; // [esp+24h] [ebp-38h]
  int v28; // [esp+28h] [ebp-34h]
  int v29; // [esp+2Ch] [ebp-30h]
  int v30; // [esp+30h] [ebp-2Ch]
  _DWORD v31[3]; // [esp+34h] [ebp-28h] BYREF
  _DWORD *v32; // [esp+40h] [ebp-1Ch]
  int v33; // [esp+44h] [ebp-18h]
  int v34; // [esp+48h] [ebp-14h]
  int v35; // [esp+4Ch] [ebp-10h]
  int v36; // [esp+50h] [ebp-Ch]
  _DWORD *v37; // [esp+54h] [ebp-8h]
  int *v38; // [esp+58h] [ebp-4h]
  int savedregs; // [esp+5Ch] [ebp+0h]

  v37 = v22;
  v38 = dword_110011C0;
  ((void (__stdcall *)(_DWORD *, int *, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int, int, int, int, _DWORD, _DWORD, int, int, int, int, int, int))__vbaAryConstruct2)(
    v31,
    dword_1100224C,
    3,
    v22[0],
    v22[1],
    v22[2],
    v22[3],
    v22[4],
    v22[5],
    v22[6],
    0,
    v23[1],
    v23[2],
    v23[3],
    v23[4],
    0,
    v24[1],
    v25,
    v26,
    v27,
    v28,
    v29,
    v30);
  __vbaErase(0, v23);
  v23[0] = sub_110020F8((int)v32);
  __vbaSetSystemError();
  v3 = v32;
  v4 = 1;
  *v32 = v23[0];
  while ( v4 <= 30 )
  {
    LOWORD(v2) = v4 - 1;
    if ( __OFSUB__(v4, 1) )
      goto LABEL_23;
    if ( (unsigned int)(__int16)v2 >= 0x1F )
      __vbaGenerateBoundsError();
    v31[2] = -1;
    v31[1] = 7;
    v5 = v32[(__int16)v2];
    v6 = sub_11004950(v5, 7, -1);
    v23[0] = v6;
    if ( (unsigned int)v4 >= 0x1F )
      __vbaGenerateBoundsError();
    v7 = sub_110048E0(v5 ^ v6, v5);
    v3 = v32;
    v32[v4] = v7;
    if ( __OFADD__(v4, 1) )
LABEL_23:
      __vbaErrorOverflow(v3, v2);
    ++v4;
  }
  rtcDoEvents();
  v25 = -1;
  v24[0] = 2;
  rtcRandomNext(v24);
  __vbaFreeVar(v24);
  v23[0] = sub_110020F8((int)v32);
  __vbaSetSystemError();
  sub_110048E0(v32[3], v23[0]);
  rtcRandomize(v24);
  __vbaFreeVar(v24);
  v25 = -2147352572;
  v24[0] = 10;
  v9 = rtcRandomNext(v24) * 9.0;
  if ( (v8 & 0xD) == 0 )
  {
    v10 = __vbaR8IntI4(v9);
    if ( v10 >= 0x1F )
      __vbaGenerateBoundsError();
    dword_11006078 = v32[v10];
    __vbaFreeVar(v24);
    v25 = -2147352572;
    v24[0] = 10;
    v12 = rtcRandomNext(v24) * 10.0;
    if ( (v11 & 0xD) == 0 )
    {
      __vbaFPInt();
      v14 = v12 + 9.0;
      if ( (v13 & 0xD) == 0 )
      {
        v15 = __vbaFpI4(v14);
        if ( v15 >= 0x1F )
          __vbaGenerateBoundsError();
        dword_1100607C = v32[v15];
        __vbaFreeVar(v24);
        v25 = -2147352572;
        v24[0] = 10;
        v17 = rtcRandomNext(v24) * 20.0;
        if ( (v16 & 0xD) == 0 )
        {
          __vbaFPInt();
          v19 = v17 + 9.0;
          if ( (v18 & 0xD) == 0 )
          {
            v20 = __vbaFpI4(v19);
            if ( v20 >= 0x1F )
              __vbaGenerateBoundsError();
            dword_11006080 = v32[v20];
            __vbaFreeVar(v24);
            __vbaErase(0, v23);
            v23[0] = (int)v31;
            return __vbaAryDestruct(0, v23, &loc_110048C2, v33, v34, v35, v36, v37, v38, savedregs);
          }
        }
      }
    }
  }
  _vbaFPException(a1, a2);
}
// 1100469D: bad sp value at call
// 11004740: bad sp value at call
// 11004752: bad sp value at call
// 11004780: bad sp value at call
// 11004789: bad sp value at call
// 1100479E: bad sp value at call
// 110047D5: bad sp value at call
// 110047E5: bad sp value at call
// 11004834: bad sp value at call
// 11004848: bad sp value at call
// 11004889: bad sp value at call
// 11004897: bad sp value at call
// 110048BB: bad sp value at call
// 110048D8: variable 'v2' is possibly undefined
// 11001014: using guessed type int __thiscall __vbaFreeVar(_DWORD);
// 11001044: using guessed type int __vbaSetSystemError(void);
// 11001054: using guessed type int __stdcall __vbaAryDestruct(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 1100105C: using guessed type double __stdcall rtcRandomNext(_DWORD);
// 11001064: using guessed type int __stdcall rtcRandomize(_DWORD);
// 1100107C: using guessed type int rtcDoEvents(void);
// 11001088: using guessed type int __stdcall __vbaErase(_DWORD, _DWORD);
// 11001094: using guessed type void __noreturn __vbaGenerateBoundsError(void);
// 110010A0: using guessed type int __stdcall __vbaAryConstruct2(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 110010E8: using guessed type void __fastcall __noreturn __vbaErrorOverflow(_DWORD, _DWORD);
// 11001134: using guessed type int __usercall __vbaFpI4@<eax>(double@<st0>);
// 11001148: using guessed type int __usercall __vbaR8IntI4@<eax>(double@<st0>);
// 11001158: using guessed type double __vbaFPInt(void);
// 110011C0: using guessed type int dword_110011C0[2];
// 1100124C: using guessed type void __stdcall __noreturn _vbaFPException(_DWORD, _DWORD);
// 1100224C: using guessed type int dword_1100224C[4];
// 11006078: using guessed type int dword_11006078;
// 1100607C: using guessed type int dword_1100607C;
// 11006080: using guessed type int dword_11006080;

//----- (110048E0) --------------------------------------------------------
int __stdcall sub_110048E0(int a1, int a2)
{
  __asm
  {
    fild    [esp+10h+arg_0]
    fstp    [esp+10h+var_10]
    fild    [esp+10h+arg_4]
    fstp    [esp+10h+var_8]
    fld     [esp+10h+var_10]
    fadd    [esp+10h+var_8]
    fstp    [esp+10h+var_10]
    fnstsw  ax
  }
  if ( (_AX & 0xD) != 0 )
    goto LABEL_8;
  __asm
  {
    fld     [esp+10h+var_10]
    fcomp   ds:dbl_110011D8
    fld     [esp+10h+var_10]
    fnstsw  ax
  }
  if ( (_AX & 0x100) != 0 )
  {
    __asm { fadd    ds:dbl_110011D0 }
    goto LABEL_6;
  }
  __asm
  {
    fcomp   ds:dbl_110011A8
    fld     [esp+10h+var_10]
    fnstsw  ax
  }
  if ( (_AX & 0x4100) == 0 )
  {
    __asm { fsub    ds:dbl_110011D0 }
LABEL_6:
    __asm { fnstsw  ax }
    if ( (_AX & 0xD) == 0 )
      return __vbaFpI4();
LABEL_8:
    _vbaFPException(a1, a2);
  }
  return __vbaFpI4();
}
// 110048E3: inconsistent fpu stack
// 11001134: using guessed type int __vbaFpI4(void);
// 1100124C: using guessed type void __stdcall __noreturn _vbaFPException(_DWORD, _DWORD);

//----- (11004950) --------------------------------------------------------
int __stdcall sub_11004950(int a1, int a2, __int16 a3)
{
  int result; // eax
  unsigned int v4; // esi
  int v5; // esi
  unsigned int v6; // ebp
  bool v7; // of
  int v8; // esi
  unsigned int v9; // ebx
  unsigned int v10; // ebp
  int v11; // esi
  int v12; // esi

  result = 0;
  if ( a2 < 32 )
  {
    if ( a2 == 0 )
      return a1;
    v4 = 31 - a2;
    if ( __OFSUB__(31, a2) )
      goto LABEL_23;
    if ( v4 >= 0x20 )
      __vbaGenerateBoundsError();
    v5 = *(_DWORD *)(dword_1100606C + 4 * v4);
    if ( a3 != 0 )
    {
      v6 = a1 & v5 & 0x80000000;
      v7 = __OFSUB__(v5, 1);
      v8 = v5 - 1;
      if ( !v7 )
      {
        v9 = v8 & a1;
        if ( (unsigned int)a2 >= 0x20 )
          __vbaGenerateBoundsError();
        if ( is_mul_ok(v9, *(_DWORD *)(dword_1100606C + 4 * a2)) )
          return v6 | (v9 * *(_DWORD *)(dword_1100606C + 4 * a2));
      }
LABEL_23:
      __vbaErrorOverflow();
    }
    v10 = 31 - a2;
    if ( __OFSUB__(31, a2) )
      goto LABEL_23;
    if ( v10 >= 0x20 )
      __vbaGenerateBoundsError();
    if ( a2 < 31 )
    {
      if ( (unsigned int)a2 >= 0x20 )
        __vbaGenerateBoundsError();
      v11 = *(_DWORD *)(dword_1100606C + 4 * a2);
      v7 = __OFSUB__(v11, 1);
      v12 = v11 - 1;
      if ( v7 )
        goto LABEL_23;
      v5 = ~v12;
    }
    return (a1 < 0 ? *(_DWORD *)(dword_1100606C + 4 * v10) : 0)
         | ((v5 & 0x7FFFFFFF & a1) / *(_DWORD *)(dword_1100606C + 4 * a2));
  }
  return result;
}
// 11004A3A: conditional instruction was optimized away because %arg_4.4 is in (1..1F)
// 11001094: using guessed type void __noreturn __vbaGenerateBoundsError(void);
// 110010E8: using guessed type void __noreturn __vbaErrorOverflow(void);
// 1100606C: using guessed type int dword_1100606C;

//----- (11005638) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void sub_11005638()
{
  ;
}
// 11005648: positive sp value 10 has been found

//----- (11005650) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __usercall sub_11005650@<eax>(int a1@<ebx>, int a2@<edi>, int a3@<esi>, int a4)
{
  __int16 v4; // di
  int v5; // eax
  _DWORD v7[6]; // [esp-18h] [ebp-74h] BYREF
  _DWORD v8[2]; // [esp+0h] [ebp-5Ch] BYREF
  int *v9; // [esp+8h] [ebp-54h]
  int v10; // [esp+Ch] [ebp-50h]
  _DWORD v11[2]; // [esp+10h] [ebp-4Ch] BYREF
  int *v12; // [esp+18h] [ebp-44h]
  int v13; // [esp+1Ch] [ebp-40h]
  int v14; // [esp+24h] [ebp-38h]
  int v15; // [esp+28h] [ebp-34h]
  int v16; // [esp+2Ch] [ebp-30h]
  _DWORD v17[4]; // [esp+30h] [ebp-2Ch] BYREF
  int v18; // [esp+40h] [ebp-1Ch] BYREF
  _DWORD v19[5]; // [esp+44h] [ebp-18h] BYREF

  v19[2] = &_vbaExceptHandler;
  v19[1] = NtCurrentTeb()->NtTib.ExceptionList;
  v19[3] = v7;
  v19[4] = dword_11001220;
  v19[0] = 0;
  v18 = 0;
  ((void (__fastcall *)(int *, int, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int *, int, _DWORD, _DWORD, int *, int, _DWORD, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD))__vbaStrCopy)(
    &v18,
    a4,
    a2,
    a3,
    a1,
    v7[3],
    v7[4],
    v7[5],
    0,
    v8[1],
    v9,
    v10,
    0,
    v11[1],
    v12,
    v13,
    0,
    v14,
    v15,
    v16,
    0,
    v17[1],
    v17[2],
    v17[3]);
  v12 = &v18;
  v11[0] = 16392;
  rtcRightCharVar(v17, v11, 1);
  v9 = dword_11002A48;
  v8[0] = 32776;
  v4 = __vbaVarTstNe(v8, v17);
  __vbaFreeVar(v17);
  if ( v4 != 0 )
  {
    v5 = __vbaStrCat(dword_11002A48, v18);
    __vbaStrMove(v19, v5);
  }
  return __vbaFreeStr(&v18, &loc_11005730);
}
// 110056B0: bad sp value at call
// 110056CC: bad sp value at call
// 110056D7: bad sp value at call
// 110056F6: bad sp value at call
// 11005729: bad sp value at call
// 11001014: using guessed type int __thiscall __vbaFreeVar(_DWORD);
// 1100103C: using guessed type int __stdcall __vbaStrCat(_DWORD, _DWORD);
// 110010FC: using guessed type int __fastcall __vbaStrCopy(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 1100111C: using guessed type int __stdcall __vbaVarTstNe(_DWORD, _DWORD);
// 11001140: using guessed type int __fastcall __vbaStrMove(_DWORD, _DWORD);
// 11001144: using guessed type int __stdcall rtcRightCharVar(_DWORD, _DWORD, _DWORD);
// 11001160: using guessed type int __thiscall __vbaFreeStr(_DWORD, _DWORD);
// 11001220: using guessed type int dword_11001220[2];
// 11002A48: using guessed type int dword_11002A48[4];

//----- (11005750) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
void __cdecl __noreturn sub_11005750(int a1)
{
  int v1; // edi
  int v2; // edi
  int v3; // [esp-18h] [ebp-94h] BYREF
  _DWORD v4[2]; // [esp+0h] [ebp-7Ch] BYREF
  int v5[29]; // [esp+8h] [ebp-74h] BYREF

  v5[27] = (int)&v3;
  v5[28] = (int)dword_11001230;
  v4[0] = 0;
  memset(v5, 0, 0x60u);
  sub_11002880(a1);
  __vbaSetSystemError();
  v5[21] = __vbaStrToAnsi(v4, L"GO!");
  v5[20] = 0;
  v1 = sub_11002754(2031619);
  __vbaSetSystemError();
  __vbaFreeStr(v4, v5[22]);
  sub_11002688(v1);
  __vbaSetSystemError();
  while ( 1 )
  {
    v5[21] = -1;
    sub_11002834((int)v5);
    __vbaSetSystemError();
    if ( v5[0] == 5 )
      break;
    v5[21] = 65538;
    v5[20] = v5[2];
    sub_110027D4(v5[1]);
    __vbaSetSystemError();
  }
  v5[21] = v5[1];
  v5[20] = 0;
  v2 = sub_11002910(2035711);
  __vbaSetSystemError();
  v5[18] = 0;
  sub_110028CC(v2);
  __vbaSetSystemError();
  sub_11002710(v2);
  __vbaSetSystemError();
  __vbaEnd(v5[16], v5[17], v5[18], v5[19], v5[20], v5[21]);
}
// 110057A2: bad sp value at call
// 110057BC: bad sp value at call
// 110057D6: bad sp value at call
// 1100101C: using guessed type void __stdcall __noreturn __vbaEnd(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 11001044: using guessed type int __vbaSetSystemError(void);
// 11001128: using guessed type int __stdcall __vbaStrToAnsi(_DWORD, _DWORD);
// 11001160: using guessed type int __thiscall __vbaFreeStr(_DWORD, _DWORD);
// 11001230: using guessed type int[3];
// 11002A30: using guessed type wchar_t aGo[4];

// nfuncs=115 queued=25 decompiled=25 lumina nreq=0 worse=0 better=0
#error "There were 2 decompilation failure(s) on 25 function(s)"
