/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int __cdecl sub_401000(int a1, int a2, _DWORD *a3);
void __noreturn start(); // weak
INT_PTR __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4); // idb
char __stdcall sub_40131C(unsigned int a1, int a2);
_BYTE *__stdcall sub_401350(char *a1, char *a2, _BYTE *a3);
int __stdcall sub_4014A0(int a1);
int __fastcall sub_4014D0(int a1, int a2, _BYTE *a3);
// INT_PTR __stdcall DialogBoxParamA(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// BOOL __stdcall EndDialog(HWND hDlg, INT_PTR nResult);
// UINT __stdcall GetDlgItemTextA(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// void __stdcall __noreturn ExitProcess(UINT uExitCode);
// HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName);
// void __stdcall InitCommonControls();

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_40112C; // weak
_UNKNOWN loc_40116A; // weak
_UNKNOWN loc_4011F8; // weak
int dword_401360[64] =
{
  50462976,
  117835012,
  185207048,
  252579084,
  319951120,
  387323156,
  454695192,
  522067228,
  589439264,
  656811300,
  724183336,
  791555372,
  858927408,
  926299444,
  993671480,
  1061043516,
  1667391808,
  1734763876,
  1802135912,
  1869507948,
  1936879984,
  2004252020,
  1534753144,
  1600019804,
  1667391840,
  1734763876,
  1802135912,
  1869507948,
  1936879984,
  2004252020,
  2071624056,
  2138996092,
  -2088599168,
  -2021227132,
  -1953855096,
  -1886483060,
  -1819111024,
  -1751738988,
  -1684366952,
  -1616995172,
  -1549622880,
  -1482250844,
  -1414878808,
  -1347572308,
  -1280134736,
  -1212762700,
  -1145390664,
  -1078018628,
  -1010646592,
  -943274556,
  -875902520,
  -808530484,
  -741158448,
  -673786412,
  -606414376,
  -539042340,
  -471670304,
  -404298268,
  -336926232,
  -269554196,
  -202182160,
  -134810124,
  -67438088,
  -66052
}; // weak
int dword_403000 = 0; // weak
int dword_403004 = 0; // weak
int dword_403008 = 0; // weak
HINSTANCE hInstance = NULL; // idb
CHAR Text[] = "Username requires min 5 chars"; // idb
CHAR Caption[] = "Error"; // idb
CHAR aRegcodeRequire[] = "RegCode requires 8 chars"; // idb
CHAR aError_0[] = "Error"; // idb
CHAR aRegcodeIsCorre[] = "RegCode is correct"; // idb
CHAR aWellDone[] = "Well Done"; // idb


//----- (00401000) --------------------------------------------------------
int __cdecl sub_401000(int a1, int a2, _DWORD *a3)
{
  a3[46] = dword_403008;
  a3[49] = dword_403000;
  a3[45] = dword_403004;
  return 0;
}
// 403000: using guessed type int dword_403000;
// 403004: using guessed type int dword_403004;
// 403008: using guessed type int dword_403008;

//----- (00401031) --------------------------------------------------------
void __noreturn start()
{
  hInstance = GetModuleHandleA(nullptr);
  InitCommonControls();
  DialogBoxParamA(hInstance, (LPCSTR)0x65, nullptr, DialogFunc, 0);
  ExitProcess(0);
}
// 401031: using guessed type void __noreturn start();

//----- (0040105F) --------------------------------------------------------
INT_PTR __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4)
{
  int v4; // edx
  int v5; // ecx
  int v6; // edx
  int v7; // ecx
  int v8; // eax
  unsigned int v9; // ebx
  unsigned int v10; // ecx
  bool v11; // cf
  struct _EXCEPTION_REGISTRATION_RECORD *ExceptionList; // [esp-8h] [ebp-224h] BYREF
  int (__cdecl *v14)(int, int, _DWORD *); // [esp-4h] [ebp-220h]
  char v15; // [esp+3h] [ebp-219h]
  int v16; // [esp+4h] [ebp-218h]
  unsigned int v17; // [esp+8h] [ebp-214h]
  unsigned int v18; // [esp+Ch] [ebp-210h]
  CHAR v19[255]; // [esp+1Eh] [ebp-1FEh] BYREF
  CHAR String[255]; // [esp+11Dh] [ebp-FFh] BYREF
  int savedregs; // [esp+21Ch] [ebp+0h] BYREF

  if ( a2 != 272 )
  {
    if ( a2 == 273 )
    {
      if ( a3 == 1002 )
      {
        GetDlgItemTextA(hDlg, 1005, String, 255);
        GetDlgItemTextA(hDlg, 1001, v19, 255);
        sub_4014A0((int)v19);
        v17 = sub_4014D0(v5, v4, String);
        if ( v17 < 5 )
        {
          MessageBoxA(hDlg, Text, Caption, 0);
          return 0;
        }
        v16 = sub_4014D0(v7, v6, v19);
        if ( v16 != 8 )
        {
          MessageBoxA(hDlg, aRegcodeRequire, aError_0, 0);
          return 0;
        }
        dword_403008 = (int)&loc_40112C;
        dword_403004 = (int)&savedregs;
        v14 = sub_401000;
        ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
        dword_403000 = (int)&ExceptionList;
        dword_403008 = (int)&loc_40116A;
        dword_403004 = (int)&savedregs;
        v14 = sub_401000;
        ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
        dword_403000 = (int)&ExceptionList;
        v8 = 0;
        v9 = 0;
        v18 = 0;
        v15 = 0;
        v10 = (unsigned __int8)String[0];
        do
        {
          LOBYTE(v8) = v10;
          v9 = v8 + _byteswap_ulong(v9);
          ++v15;
          v14 = (int (__cdecl *)(int, int, _DWORD *))v10;
          LOBYTE(v10) = v15;
          v11 = v10 < v17;
          v10 = (unsigned int)v14 + 1;
        }
        while ( v11 );
        dword_403008 = (int)&loc_4011F8;
        dword_403004 = (int)&savedregs;
        v14 = sub_401000;
        ExceptionList = NtCurrentTeb()->NtTib.ExceptionList;
        dword_403000 = (int)&ExceptionList;
        v18 = v9;
        if ( v9 == 0 )
        {
          MessageBoxA(hDlg, aRegcodeIsCorre, aWellDone, 0);
          return 0;
        }
      }
    }
    else
    {
      if ( a2 != 16 )
        return 0;
      EndDialog(hDlg, 0);
    }
  }
  return 1;
}
// 4011E2: conditional instruction was optimized away because ebx.4==0
// 4010D4: variable 'v5' is possibly undefined
// 4010D4: variable 'v4' is possibly undefined
// 4010EF: variable 'v7' is possibly undefined
// 4010EF: variable 'v6' is possibly undefined
// 403000: using guessed type int dword_403000;
// 403004: using guessed type int dword_403004;
// 403008: using guessed type int dword_403008;

//----- (0040131C) --------------------------------------------------------
char __stdcall sub_40131C(unsigned int a1, int a2)
{
  int v3; // ecx
  char result; // al

  v3 = 7;
  *(_BYTE *)(a2 + 8) = 0;
  do
  {
    _AL = (a1 & 0xF) - (((a1 & 0xF) < 0xA) + 105);
    __asm { das }
    *(_BYTE *)(v3 + a2) = result;
    a1 >>= 4;
    --v3;
  }
  while ( v3 >= 0 );
  return result;
}

//----- (00401350) --------------------------------------------------------
_BYTE *__stdcall sub_401350(char *a1, char *a2, _BYTE *a3)
{
  char *v4; // esi
  char v8; // ah
  _BYTE *v11; // esi

  _EBX = dword_401360;
  v4 = a1;
  do
  {
    _AL = *v4++;
    __asm { xlat }
    v8 = _AL;
    _AL = *a2++;
    __asm { xlat }
  }
  while ( v8 == _AL && (int)v4 < (int)&a3[(int)a1] );
  v11 = (_BYTE *)(v4 - a1);
  if ( v11 == a3 )
    return nullptr;
  else
    return v11;
}
// 401360: using guessed type int dword_401360[64];

//----- (004014A0) --------------------------------------------------------
int __stdcall sub_4014A0(int a1)
{
  _BYTE *v1; // eax

  v1 = (_BYTE *)(a1 - 1);
  while ( *++v1 != 0 )
  {
    if ( *v1 >= 0x41u && *v1 <= 0x5Au )
      *v1 += 32;
  }
  return a1;
}

//----- (004014D0) --------------------------------------------------------
int __fastcall sub_4014D0(int a1, int a2, _BYTE *a3)
{
  int v3; // ecx
  _BYTE *v4; // esi
  unsigned __int8 v6; // al

  v3 = 0;
  v4 = a3 - 1;
  do
  {
    do
      ++v4;
    while ( *v4 == 32 );
  }
  while ( *v4 == 9 );
  if ( *v4 != 0 )
  {
    while ( 1 )
    {
      v6 = v4[v3];
      a3[v3++] = v6;
      if ( v6 == 0 )
        break;
      if ( v6 >= 0x21u )
        a2 = v3;
    }
    a3[a2] = 0;
    return a2;
  }
  else
  {
    *a3 = 0;
    return 0;
  }
}

// nfuncs=14 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
