/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_F20();
// _QWORD std::ios_base::Init::Init(std::ios_base::Init *__hidden this); idb
// void *malloc(size_t size);
// int sigfillset(sigset_t *set);
// int __cxa_atexit(void (*lpfunc)(void *), void *obj, void *lpdso_handle);
// void free(void *ptr);
// int sigaction(int sig, const struct sigaction *act, struct sigaction *oact);
// int sigaltstack(const struct sigaltstack *ss, struct sigaltstack *oss);
// int _cxa_finalize(void *);
int sub_102E();
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)());
__int64 (**sub_1090())(void);
__int64 sub_10D0(void); // weak
__int64 (**sub_1120())(void);
__int64 sub_1160(); // weak
void __fastcall __noreturn sub_1190(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall sub_1946(__int64 a1, __int64 a2, __int64 a3);
bool sub_1965();
char sub_19C6();
void init(); // idb
void fini(); // idb
void term_proc();
// int _libc_start_main(int (*main)(int, char **, char **), int argc, char **ubp_av, void (*init)(), void (*fini)(), void (*rtld_fini)(), void *stack_end);
// void std::ios_base::Init::~Init(std::ios_base::Init *__hidden this); idb
// int __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak
// __int64 Jv_RegisterClasses(void); weak
// __int64 ITM_deregisterTMCloneTable(void); weak
// __int64 ITM_registerTMCloneTable(void); weak

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN main;
__int64 (__fastcall *funcs_1F39[2])() = { &sub_1160, &sub_102E }; // weak
__int64 (__fastcall *off_202D88)() = &sub_1120; // weak
_UNKNOWN unk_202D90; // weak
void *off_203068 = &off_203068; // idb
char byte_203880; // weak
_UNKNOWN unk_203881; // weak
_UNKNOWN unk_203887; // weak


//----- (0000000000000F00) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ != nullptr )
    return (__int64 (**)(void))_gmon_start__();
  return result;
}
// 2038E0: using guessed type __int64 _gmon_start__(void);

//----- (0000000000000F20) ----------------------------------------------------
void sub_F20()
{
  JUMPOUT(0);
}
// F26: control flows out of bounds to 0

//----- (0000000000000FC0) ----------------------------------------------------
__int64 __fastcall main(int a1, char **a2, char **a3)
{
  char v5; // al
  unsigned int v6; // edx
  bool v7; // al

  v5 = sub_19C6();
  v6 = 1;
  if ( v5 != 0 )
  {
    v7 = sub_1965();
    v6 = 2;
    if ( v7 )
      sub_1190(a1, a2, 2);
  }
  return v6;
}
// 1190: using guessed type void __fastcall __noreturn sub_1190(_QWORD, _QWORD, _QWORD);

//----- (000000000000102E) ----------------------------------------------------
int sub_102E()
{
  std::ios_base::Init::Init((std::ios_base::Init *)&unk_203881);
  return __cxa_atexit((void (*)(void *))&std::ios_base::Init::~Init, &unk_203881, &off_203068);
}

//----- (0000000000001060) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)())
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main((int (*)(int, char **, char **))main, v4, &retaddr, init, fini, a3, &v5);
  __halt();
}
// 1066: positive sp value 8 has been found
// 106D: variable 'v3' is possibly undefined

//----- (0000000000001090) ----------------------------------------------------
__int64 (**sub_1090())(void)
{
  __int64 (**result)(void); // rax

  result = (__int64 (**)(void))(&unk_203887 - (_UNKNOWN *)&byte_203880);
  if ( (unsigned __int64)(&unk_203887 - (_UNKNOWN *)&byte_203880) > 0xE )
  {
    result = &ITM_deregisterTMCloneTable;
    if ( &ITM_deregisterTMCloneTable != nullptr )
      return (__int64 (**)(void))ITM_deregisterTMCloneTable();
  }
  return result;
}
// 203880: using guessed type char byte_203880;
// 2038F0: using guessed type __int64 ITM_deregisterTMCloneTable(void);

//----- (00000000000010D0) ----------------------------------------------------
__int64 sub_10D0()
{
  return 0;
}
// 10D0: using guessed type __int64 sub_10D0();
// 2038F8: using guessed type __int64 ITM_registerTMCloneTable(void);

//----- (0000000000001120) ----------------------------------------------------
__int64 (**sub_1120())(void)
{
  __int64 (**result)(void); // rax

  if ( byte_203880 == 0 )
  {
    if ( &__cxa_finalize != nullptr )
      _cxa_finalize(off_203068);
    result = sub_1090();
    byte_203880 = 1;
  }
  return result;
}
// 203880: using guessed type char byte_203880;

//----- (0000000000001160) ----------------------------------------------------
__int64 sub_1160()
{
  if ( unk_202D90 != 0 && &Jv_RegisterClasses != nullptr )
    Jv_RegisterClasses();
  return sub_10D0();
}
// 10D0: using guessed type __int64 sub_10D0(void);
// 1160: using guessed type __int64 sub_1160();
// 2038E8: using guessed type __int64 Jv_RegisterClasses(void);

//----- (0000000000001946) ----------------------------------------------------
__int64 __fastcall sub_1946(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 v3; // rax
  __int64 v4; // rsi
  __int64 v5; // rdi
  __int64 result; // rax
  __int64 v7; // rax
  __int64 v8; // rcx
  __int64 v9; // rdi
  __int128 v10; // rtt
  __int64 v11; // rdx
  __int64 v12; // rdx
  __int64 v13; // rdx
  __int64 *v14; // rax
  __int64 v15; // rdx
  __int64 *v16; // rax
  __int64 v17; // rdx
  __int64 *v18; // rax
  __int64 v19; // rdx

  v3 = *(_QWORD *)(a3 + 168);
  v4 = a3 + 40;
  v5 = v3 + 2;
  result = v3 + 14;
  *(_QWORD *)(a3 + 168) = result;
  switch ( *(_BYTE *)(v5 + 8) )
  {
    case 0:
      return result;
    case 1:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
             + *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 2:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
             - *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 3:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11))
             * *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 4:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
             / *(__int64 *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 5:
      v7 = *(unsigned __int8 *)(v5 + 10);
      v8 = *(unsigned __int8 *)(v5 + 9);
      v9 = *(unsigned __int8 *)(v5 + 11);
      v10 = *(__int64 *)(v4 + 8 * v7);
      result = *(_QWORD *)(v4 + 8 * v7) / *(__int64 *)(v4 + 8 * v9);
      *(_QWORD *)(v4 + 8 * v8) = v10 % *(__int64 *)(v4 + 8 * v9);
      break;
    case 6:
      result = *(__int64 *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) >> *(_QWORD *)(v4
                                                                                   + 8LL * *(unsigned __int8 *)(v5 + 11));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 7:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) << *(_QWORD *)(v4
                                                                                  + 8LL * *(unsigned __int8 *)(v5 + 11));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 8:
      result = -*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 9:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)v5;
      break;
    case 0xA:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(unsigned __int8 *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
                                                        + *(_QWORD *)v5);
      break;
    case 0xB:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(char *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5);
      break;
    case 0xC:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(unsigned __int16 *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
                                                         + *(_QWORD *)v5);
      break;
    case 0xD:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(__int16 *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5);
      break;
    case 0xE:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(unsigned int *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10))
                                                     + *(_QWORD *)v5);
      break;
    case 0xF:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(int *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5);
      break;
    case 0x10:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5);
      break;
    case 0x11:
      result = *(_QWORD *)v5;
      *(_BYTE *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x12:
      result = *(_QWORD *)v5;
      *(_WORD *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x13:
      result = *(_QWORD *)v5;
      *(_DWORD *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x14:
      result = *(_QWORD *)v5;
      *(_QWORD *)(*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x15:
      v11 = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      result = *(_QWORD *)(v4 + 120);
      *(_QWORD *)(v4 + 120) = result - 8;
      *(_QWORD *)(result - 8) = v11;
      break;
    case 0x16:
      result = *(_QWORD *)(a3 + 160);
      v12 = *(_QWORD *)v5;
      *(_QWORD *)(v4 + 120) = result - 8;
      *(_QWORD *)(result - 8) = v12;
      break;
    case 0x17:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(a3 + 40 + 8 * result) = **(_QWORD **)(a3 + 160);
      *(_QWORD *)(a3 + 160) += 8LL;
      break;
    case 0x18:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      break;
    case 0x19:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11))
             | *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x1A:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11))
             & *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x1B:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11))
             ^ *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x1C:
      result = ~*(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x1D:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) < *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x1E:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) <= *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x1F:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) > *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x20:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) >= *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x21:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) == *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x22:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) != *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 11));
      break;
    case 0x23:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) == *(_QWORD *)v5;
      break;
    case 0x24:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) != *(_QWORD *)v5;
      break;
    case 0x25:
      result = *(unsigned __int8 *)(v5 + 9);
      *(_QWORD *)(v4 + 8 * result) = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) == 0;
      break;
    case 0x26:
      result = *(unsigned __int8 *)(v5 + 10);
      if ( *(_QWORD *)(v4 + 8 * result) == 0 )
      {
        result = *(_QWORD *)v5;
        *(_QWORD *)(a3 + 168) = *(_QWORD *)v5;
      }
      break;
    case 0x27:
      result = *(unsigned __int8 *)(v5 + 10);
      if ( *(_QWORD *)(v4 + 8 * result) != 0 )
      {
        result = *(_QWORD *)v5;
        *(_QWORD *)(a3 + 168) = *(_QWORD *)v5;
      }
      break;
    case 0x28:
      result = *(_QWORD *)(a3 + 160);
      v13 = *(_QWORD *)v5;
      *(_QWORD *)(v4 + 120) = result - 8;
      *(_QWORD *)(result - 8) = *(_QWORD *)(v4 + 128);
      *(_QWORD *)(v4 + 128) = v13;
      break;
    case 0x29:
      v14 = *(__int64 **)(a3 + 160);
      v15 = *v14;
      result = (__int64)(v14 + 1);
      *(_QWORD *)(v4 + 120) = result;
      *(_QWORD *)(v4 + 128) = v15;
      break;
    case 0x2A:
      result = *(unsigned __int8 *)(v5 + 10);
      if ( *(_QWORD *)(v4 + 8 * result) != 0 )
      {
        v16 = *(__int64 **)(a3 + 160);
        v17 = *v16;
        result = (__int64)(v16 + 1);
        *(_QWORD *)(v4 + 120) = result;
        *(_QWORD *)(v4 + 128) = v17;
      }
      break;
    case 0x2B:
      result = *(unsigned __int8 *)(v5 + 10);
      if ( *(_QWORD *)(v4 + 8 * result) == 0 )
      {
        v18 = *(__int64 **)(a3 + 160);
        v19 = *v18;
        result = (__int64)(v18 + 1);
        *(_QWORD *)(v4 + 120) = result;
        *(_QWORD *)(v4 + 128) = v19;
      }
      break;
    case 0x2C:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) + *(_QWORD *)v5;
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x2D:
      result = *(__int64 *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) >> *(_QWORD *)v5;
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x2E:
      result = *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10)) << *(_QWORD *)v5;
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x2F:
      result = *(_QWORD *)v5 | *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x30:
      result = *(_QWORD *)v5 & *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
    case 0x31:
      result = *(_QWORD *)v5 ^ *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 10));
      *(_QWORD *)(v4 + 8LL * *(unsigned __int8 *)(v5 + 9)) = result;
      break;
  }
  return result;
}

//----- (0000000000001965) ----------------------------------------------------
bool sub_1965()
{
  __int64 v0; // rcx
  struct sigaction *p_act; // rdi
  int v2; // eax
  char v3; // dl
  struct sigaction act; // [rsp+8h] [rbp-A0h] BYREF

  v0 = 38;
  p_act = &act;
  while ( v0 != 0 )
  {
    LODWORD(p_act->sa_handler) = 0;
    p_act = (struct sigaction *)((char *)p_act + 4);
    --v0;
  }
  act.sa_flags = 134217732;
  act.sa_handler = (__sighandler_t)sub_1946;
  v2 = sigfillset(&act.sa_mask);
  v3 = 0;
  if ( v2 == 0 )
    return sigaction(4, &act, nullptr) == 0;
  return v3;
}

//----- (00000000000019C6) ----------------------------------------------------
char sub_19C6()
{
  void *v0; // rax
  char v1; // dl
  struct sigaltstack *v2; // rdi
  void *v3; // rbx
  __int64 i; // rcx
  int v5; // eax
  struct sigaltstack v7; // [rsp+8h] [rbp-20h] BYREF

  v0 = malloc(0x2000u);
  v1 = 0;
  if ( v0 != nullptr )
  {
    v2 = &v7;
    v3 = v0;
    for ( i = 6; i != 0; --i )
    {
      LODWORD(v2->ss_sp) = 0;
      v2 = (struct sigaltstack *)((char *)v2 + 4);
    }
    v7.ss_size = 0x2000;
    v7.ss_sp = v0;
    v5 = sigaltstack(&v7, nullptr);
    v1 = 1;
    if ( v5 != 0 )
    {
      free(v3);
      return 0;
    }
  }
  return v1;
}

//----- (0000000000001EF0) ----------------------------------------------------
void init()
{
  signed __int64 v0; // rbp
  __int64 i; // rbx

  v0 = &off_202D88 - funcs_1F39;
  init_proc();
  if ( v0 != 0 )
  {
    for ( i = 0; i != v0; ++i )
      funcs_1F39[i]();
  }
}
// 202D78: using guessed type __int64 (__fastcall *funcs_1F39[2])();
// 202D88: using guessed type __int64 (__fastcall *off_202D88)();

//----- (0000000000001F64) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=40 queued=14 decompiled=14 lumina nreq=0 worse=0 better=0
// ALL OK, 14 function(s) have been successfully decompiled
