/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall start(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, int a7, _BYTE *a8);

//-------------------------------------------------------------------------
// Data declarations

_UNKNOWN loc_40103F; // weak


//----- (0000000000401000) ----------------------------------------------------
__int64 __fastcall start(__int64 a1, __int64 a2, __int64 a3, __int64 a4, __int64 a5, __int64 a6, int a7, _BYTE *a8)
{
  _BYTE *v8; // rdi
  __int64 v9; // rcx
  bool v10; // zf
  __int64 v11; // rbx
  __int64 v12; // rdi
  _BYTE *v13; // rax
  _UNKNOWN *retaddr; // [rsp+0h] [rbp+0h]

  if ( (_BYTE)retaddr == 2 )
  {
    v8 = a8;
    v9 = 0xFFFFFFFFLL;
    do
    {
      if ( v9 == 0 )
        break;
      v10 = *v8++ == 0;
      --v9;
    }
    while ( !v10 );
    LODWORD(v9) = -(int)v9 - 2;
    if ( (int)v9 > 3 )
    {
      v11 = 0;
      v12 = 0;
      v13 = a8;
      do
      {
        LOBYTE(v11) = *v13;
        v11 = __ROL8__(v11, 8);
        ++v13;
        v9 = (unsigned int)(v9 - 1);
      }
      while ( (_DWORD)v9 != 0 );
      LOWORD(v12) = v11 - 20516;
      return ((__int64 (__fastcall *)(__int64, __int64, __int64, __int64))((char *)&loc_40103F + v12))(v12, a2, a3, v9);
    }
  }
  sys_exit(0);
}

// nfuncs=1 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
