/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __noreturn start(); // weak
INT_PTR __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4); // idb
char __stdcall sub_4012D8(char *a1, int *a2);
int __stdcall sub_4012FE(char *a1, char *a2);
unsigned int __stdcall sub_401327(char *a1, char *a2, char *a3);
int __stdcall sub_40137D(char *a1);
int __stdcall sub_40139D(LPCSTR lpFileName); // idb
int __stdcall sub_401409(_BYTE *a1);
char __stdcall sub_40146B(char *a1);
char __stdcall sub_401490(char *lpText, char *lpCaption);
char __stdcall sub_4014CC(LPSTR lpFilename);
// BOOLEAN __stdcall GetUserNameExA(EXTENDED_NAME_FORMAT NameFormat, LPSTR lpNameBuffer, PULONG nSize);
// HFONT __stdcall CreateFontIndirectA(const LOGFONTA *lplf);
// int __stdcall GetObjectA(HANDLE h, int c, LPVOID pv);
// BOOL __stdcall CloseHandle(HANDLE hObject);
// HANDLE __stdcall CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// void __stdcall __noreturn ExitProcess(UINT uExitCode);
// BOOL __stdcall FreeLibrary(HMODULE hLibModule);
// HANDLE __stdcall GetCurrentProcess();
// HMODULE __stdcall GetModuleHandleA(LPCSTR lpModuleName);
// FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName);
// HGLOBAL __stdcall GlobalAlloc(UINT uFlags, SIZE_T dwBytes);
// HGLOBAL __stdcall GlobalFree(HGLOBAL hMem);
// HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName);
// BOOL __stdcall ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// int __stdcall RtlZeroMemory(_DWORD, _DWORD); weak
// DWORD __stdcall SetFilePointer(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// DWORD __stdcall GetModuleFileNameA(HMODULE hModule, LPSTR lpFilename, DWORD nSize);
// INT_PTR __stdcall DialogBoxParamA(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam);
// BOOL __stdcall EndDialog(HWND hDlg, INT_PTR nResult);
// HWND __stdcall GetDlgItem(HWND hDlg, int nIDDlgItem);
// UINT __stdcall GetDlgItemTextA(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax);
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);
// LRESULT __stdcall SendMessageA(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// void __stdcall InitCommonControls();

//-------------------------------------------------------------------------
// Data declarations

int dword_403000 = 0; // weak
char aKeyLicense[12] = "key.license"; // weak
CHAR aVpffVv[7] = "vPFF@VV"; // idb
CHAR aFjkbwdqpidqljk[16] = "fJKBWDQPIDQLJKV\t"; // idb
CHAR aWwjw[5] = "`WWJW"; // idb
CHAR aLksdila[7] = "lKSDILA"; // idb
CHAR aLksdila_0[7] = "lKSDILA"; // idb
HINSTANCE hInstance = NULL; // idb
WPARAM wParam = 0u; // idb
HMODULE hModule = NULL; // idb
int (__stdcall *dword_403094)(_DWORD, _DWORD) = NULL; // weak
LOGFONTA pv = { 0, 0, 0, 0, 0, 0u, 0u, 0u, 0u, 0u, 0u, 0u, 0u, "" }; // idb
CHAR NameBuffer[256] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb
HGLOBAL lpFileName = NULL; // idb
CHAR Filename[40] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0'
}; // idb


//----- (00401000) --------------------------------------------------------
void __noreturn start()
{
  hInstance = GetModuleHandleA(nullptr);
  InitCommonControls();
  DialogBoxParamA(hInstance, (LPCSTR)0x65, nullptr, DialogFunc, 0);
  ExitProcess(0);
}
// 401000: using guessed type void __noreturn start();

//----- (0040102E) --------------------------------------------------------
INT_PTR __stdcall DialogFunc(HWND hDlg, UINT a2, WPARAM a3, LPARAM a4)
{
  HMODULE LibraryA; // eax
  BOOL (__stdcall *CheckRemoteDebuggerPresent)(HANDLE, PBOOL); // eax
  HANDLE CurrentProcess; // eax
  HWND DlgItem; // eax
  void *v8; // eax
  HWND v9; // eax
  HWND v10; // eax
  HWND v11; // eax
  CHAR String[255]; // [esp+5h] [ebp-103h] BYREF
  ULONG nSize; // [esp+104h] [ebp-4h] BYREF

  switch ( a2 )
  {
    case 0x110u:
      LibraryA = LoadLibraryA("kernel32.dll");
      if ( LibraryA != nullptr )
      {
        hModule = LibraryA;
        CheckRemoteDebuggerPresent = (BOOL (__stdcall *)(HANDLE, PBOOL))GetProcAddress(
                                                                          LibraryA,
                                                                          "CheckRemoteDebuggerPresent");
        if ( CheckRemoteDebuggerPresent != nullptr )
        {
          dword_403094 = (int (__stdcall *)(_DWORD, _DWORD))CheckRemoteDebuggerPresent;
          CurrentProcess = GetCurrentProcess();
          dword_403094(CurrentProcess, &dword_403000);
        }
      }
      if ( dword_403000 != 0 )
      {
        MessageBoxA(hDlg, "Oh, No", "Please try again!", 0);
        SendMessageA(hDlg, 0x10u, 0, 0);
      }
      else
      {
        DlgItem = GetDlgItem(hDlg, 1002);
        if ( SendMessageA(DlgItem, 0x31u, 0, 0) != 0 )
        {
          lpFileName = GlobalAlloc(0, 0x500u);
          RtlZeroMemory(lpFileName, 1280);
          v8 = (void *)RtlZeroMemory(Filename, 1024);
          GetObjectA(v8, 60, &pv);
          pv.lfHeight = -16;
          wParam = (WPARAM)CreateFontIndirectA(&pv);
          v9 = GetDlgItem(hDlg, 1001);
          SendMessageA(v9, 0x30u, wParam, 1);
          v10 = GetDlgItem(hDlg, 1002);
          SendMessageA(v10, 0x30u, wParam, 1);
          v11 = GetDlgItem(hDlg, 1003);
          SendMessageA(v11, 0x30u, wParam, 1);
          sub_4014CC(Filename);
          sub_401327(Filename, aKeyLicense, (char *)lpFileName);
        }
      }
      break;
    case 0x111u:
      if ( HIWORD(a3) == 0 && (unsigned __int16)a3 == 1001 )
      {
        nSize = 255;
        RtlZeroMemory(NameBuffer, 255);
        RtlZeroMemory(String, 255);
        GetUserNameExA(NameSamCompatible, NameBuffer, &nSize);
        sub_4012D8(NameBuffer, (int *)&nSize);
        GetDlgItemTextA(hDlg, 1003, String, 255);
        if ( sub_4012FE(String, NameBuffer) != 0 )
        {
          sub_401490(aLksdila_0, aWwjw);
        }
        else if ( sub_40139D((LPCSTR)lpFileName) != 0 )
        {
          sub_401490(aLksdila, aWwjw);
        }
        else
        {
          sub_401490(aFjkbwdqpidqljk, aVpffVv);
        }
        SendMessageA(hDlg, 0x10u, 0, 0);
      }
      break;
    case 0x10u:
      FreeLibrary(hModule);
      GlobalFree(lpFileName);
      EndDialog(hDlg, 0);
      break;
    default:
      return 0;
  }
  return 1;
}
// 401548: using guessed type int __stdcall RtlZeroMemory(_DWORD, _DWORD);
// 403000: using guessed type int dword_403000;
// 403094: using guessed type int (__stdcall *dword_403094)(_DWORD, _DWORD);

//----- (004012D8) --------------------------------------------------------
char __stdcall sub_4012D8(char *a1, int *a2)
{
  char *v2; // esi
  char *v3; // edi
  int i; // eax
  char *v5; // edi
  int v6; // ecx
  char result; // al

  v2 = a1;
  v3 = a1;
  for ( i = 0; i != 92; *v3++ = i )
    LOBYTE(i) = *v2++;
  v5 = a1;
  v6 = *a2;
  do
  {
    result = *v2++;
    *v5++ = result;
    --v6;
  }
  while ( v6 != 0 );
  return result;
}

//----- (004012FE) --------------------------------------------------------
int __stdcall sub_4012FE(char *a1, char *a2)
{
  char v4; // al
  char v5; // dl

  while ( 1 )
  {
    v4 = *a1++;
    v5 = *a2++;
    if ( v4 != v5 )
      break;
    if ( v4 == 0 )
      return 0;
  }
  return 1;
}

//----- (00401327) --------------------------------------------------------
unsigned int __stdcall sub_401327(char *a1, char *a2, char *a3)
{
  unsigned int v3; // edx
  unsigned int v5; // [esp+Ch] [ebp-8h]
  unsigned int v6; // [esp+10h] [ebp-4h]

  v6 = sub_40137D(a1);
  v5 = sub_40137D(a2);
  if ( v6 < 0x400 && v5 < 0x100 )
  {
    qmemcpy(a3, a1, v6);
    v3 = v5 + v6;
    qmemcpy(&a3[v6], a2, v5);
  }
  return v3;
}
// 401374: variable 'v3' is possibly undefined

//----- (0040137D) --------------------------------------------------------
int __stdcall sub_40137D(char *a1)
{
  int v1; // edx
  char v3; // al

  v1 = 0;
  do
  {
    v3 = *a1++;
    ++v1;
  }
  while ( v3 != 0 );
  return v1 - 1;
}

//----- (0040139D) --------------------------------------------------------
int __stdcall sub_40139D(LPCSTR lpFileName)
{
  int result; // eax
  DWORD NumberOfBytesRead; // [esp+0h] [ebp-1Ch] BYREF
  HANDLE hFile; // [esp+4h] [ebp-18h]
  _BYTE Buffer[20]; // [esp+8h] [ebp-14h] BYREF

  result = (int)CreateFileA(lpFileName, 0x80000000, 1u, nullptr, 3u, 0x80u, nullptr);
  hFile = (HANDLE)result;
  if ( result != -1 )
  {
    SetFilePointer(hFile, 0, nullptr, 0);
    ReadFile(hFile, Buffer, 0x13u, &NumberOfBytesRead, nullptr);
    CloseHandle(hFile);
    if ( NumberOfBytesRead == 19 )
      return sub_401409(Buffer);
    else
      return 2;
  }
  return result;
}

//----- (00401409) --------------------------------------------------------
int __stdcall sub_401409(_BYTE *a1)
{
  unsigned __int16 v1; // ax
  int v2; // ebx
  int v3; // edx
  int v4; // ecx
  int v7; // [esp-10h] [ebp-14h]

  HIBYTE(v1) = 0;
  v2 = 2;
  v3 = 3;
  v4 = 4;
  while ( 1 )
  {
    LOBYTE(v1) = *a1++;
    HIBYTE(v1) = v1 % (unsigned __int8)v2;
    if ( HIBYTE(v1) != 0 )
      break;
    v7 = v3;
    v3 += v2;
    v2 = v7;
    if ( --v4 == 0 )
      return 0;
  }
  return 1;
}

//----- (0040146B) --------------------------------------------------------
char __stdcall sub_40146B(char *a1)
{
  char *v1; // esi
  char *v2; // edi
  int v3; // ecx
  char v4; // al
  char result; // al

  v1 = a1;
  v2 = a1;
  v3 = sub_40137D(a1);
  do
  {
    v4 = *v1++;
    result = v4 ^ 0x25;
    *v2++ = result;
    --v3;
  }
  while ( v3 != 0 );
  return result;
}

//----- (00401490) --------------------------------------------------------
char __stdcall sub_401490(char *lpText, char *lpCaption)
{
  sub_40146B(lpCaption);
  sub_40146B(lpText);
  MessageBoxA(nullptr, lpText, lpCaption, 0);
  sub_40146B(lpCaption);
  return sub_40146B(lpText);
}

//----- (004014CC) --------------------------------------------------------
char __stdcall sub_4014CC(LPSTR lpFilename)
{
  CHAR *v1; // ecx
  char result; // al

  v1 = &lpFilename[GetModuleFileNameA(nullptr, lpFilename, 0x80u) - 6];
  do
    result = *v1--;
  while ( result != 92 );
  v1[2] = 0;
  return result;
}

// nfuncs=35 queued=11 decompiled=11 lumina nreq=0 worse=0 better=0
// ALL OK, 11 function(s) have been successfully decompiled
