/* This file was generated by the Hex-Rays decompiler version 9.4.0.260714.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

void __cdecl __noreturn start(UINT a1);
// int __stdcall MessageBoxA(HWND hWnd, LPCSTR lpText, LPCSTR lpCaption, UINT uType);

//-------------------------------------------------------------------------
// Data declarations

// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
CHAR Text[] = "Add a nag screen and patch this message by your name !"; // idb
CHAR Caption[] = "Patched ?"; // idb


//----- (00401000) --------------------------------------------------------
void __cdecl __noreturn start(UINT a1)
{
  MessageBoxA(nullptr, Text, Caption, 0);
  ExitProcess(a1);
}

// nfuncs=2 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
