/* This file was generated by the Hex-Rays decompiler version 9.4.0.260610.
   Copyright (c) 2007-2025 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

// int __thiscall __vbaFreeVar(_DWORD); weak
// int __stdcall __vbaStrVarMove(_DWORD); weak
// int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall rtcAnsiValueBstr(_DWORD); weak
// int __stdcall __vbaHresultCheckObj(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaObjSet(_DWORD, _DWORD); weak
// int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall rtcMidCharVar(_DWORD, _DWORD, _DWORD, _DWORD); weak
// int __stdcall __vbaStrCmp(_DWORD, _DWORD); weak
// int __stdcall __vbaStrR8(_DWORD, _DWORD); weak
// void __noreturn __vbaErrorOverflow(void); weak
// int __fastcall __vbaStrCopy(_DWORD, _DWORD); weak
// int __fastcall __vbaVarDup(_DWORD, _DWORD); weak
// int __stdcall rtcLeftCharVar(_DWORD, _DWORD, _DWORD); weak
// int __fastcall __vbaStrMove(_DWORD, _DWORD); weak
// int __stdcall rtcRightCharVar(_DWORD, _DWORD, _DWORD); weak
// int __thiscall __vbaFreeObj(_DWORD); weak
// int __thiscall __vbaFreeStr(_DWORD); weak
// int __usercall sub_4010C0@<eax>(unsigned int a1@<eax>, char a2@<cl>, _DWORD *a3@<ebp>);
// void __cdecl __noreturn _vbaFPException(_DWORD); weak
// double __stdcall adj_fdiv_m64(_DWORD, _DWORD); weak
int __cdecl sub_451814(int a1);
int __cdecl sub_451D90(int a1);
// int __userpurge sub_452239@<eax>(int a1@<ebp>, int a2);

//-------------------------------------------------------------------------
// Data declarations

// extern _UNKNOWN _vbaChkstk; weak
int dword_4519F4[5] = { 866995937, 298804889, -1442837321, -1814863872, 122 }; // weak
int dword_453000 = 0; // weak


//----- (004010C0) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __usercall sub_4010C0@<eax>(unsigned int a1@<eax>, char a2@<cl>, _DWORD *a3@<ebp>)
{
  *(_BYTE *)a1 += a2;
  *a3 &= a1;
  LOBYTE(a1) = a1 + 34;
  *(_DWORD *)((char *)a3 + 1) &= a1;
  return ((int (*)(void))_vbaChkstk)();
}
// 4010C1: positive sp value 4 has been found

//----- (00451814) --------------------------------------------------------
int __cdecl sub_451814(int a1)
{
  return sub_451D90(a1 - 67);
}

//----- (00451D90) --------------------------------------------------------
// bad sp value at call has been detected, the output may be wrong!
int __cdecl sub_451D90(int a1)
{
  int v1; // edx
  int v2; // eax
  int v3; // edi
  int v4; // eax
  int v5; // edx
  int v6; // eax
  int v7; // eax
  int v8; // eax
  unsigned __int16 v9; // si
  __int16 v10; // ax
  __int16 v11; // si
  unsigned __int16 v12; // kr00_2
  double v13; // st7
  char v14; // fps
  int v15; // eax
  int v16; // eax
  int v17; // esi
  int v18; // eax
  int v19; // esi
  _DWORD v21[3]; // [esp-Ch] [ebp-104h] BYREF
  double v22; // [esp+0h] [ebp-F8h]
  int v23; // [esp+8h] [ebp-F0h]
  double v24; // [esp+Ch] [ebp-ECh]
  int v25; // [esp+14h] [ebp-E4h]
  int v26; // [esp+18h] [ebp-E0h]
  int v27; // [esp+1Ch] [ebp-DCh]
  int v28; // [esp+20h] [ebp-D8h]
  int v29; // [esp+24h] [ebp-D4h]
  int v30; // [esp+28h] [ebp-D0h]
  int v31; // [esp+2Ch] [ebp-CCh]
  int v32; // [esp+30h] [ebp-C8h]
  int v33; // [esp+34h] [ebp-C4h]
  int v34; // [esp+38h] [ebp-C0h]
  int v35; // [esp+3Ch] [ebp-BCh]
  int v36; // [esp+40h] [ebp-B8h]
  int v37; // [esp+44h] [ebp-B4h]
  int v38; // [esp+48h] [ebp-B0h]
  int v39; // [esp+4Ch] [ebp-ACh]
  _DWORD v40[2]; // [esp+50h] [ebp-A8h] BYREF
  const wchar_t *v41; // [esp+58h] [ebp-A0h]
  int v42; // [esp+5Ch] [ebp-9Ch]
  _DWORD v43[2]; // [esp+60h] [ebp-98h] BYREF
  const wchar_t *v44; // [esp+68h] [ebp-90h]
  int v45; // [esp+6Ch] [ebp-8Ch]
  _DWORD v46[2]; // [esp+70h] [ebp-88h] BYREF
  int v47; // [esp+78h] [ebp-80h]
  int v48; // [esp+7Ch] [ebp-7Ch]
  _DWORD v49[2]; // [esp+80h] [ebp-78h] BYREF
  int v50; // [esp+88h] [ebp-70h]
  int v51; // [esp+8Ch] [ebp-6Ch]
  _DWORD v52[4]; // [esp+90h] [ebp-68h] BYREF
  _DWORD v53[2]; // [esp+A0h] [ebp-58h] BYREF
  int v54; // [esp+A8h] [ebp-50h]
  int v55; // [esp+ACh] [ebp-4Ch]
  int v56; // [esp+B0h] [ebp-48h] BYREF
  int v57; // [esp+B4h] [ebp-44h] BYREF
  _DWORD v58[2]; // [esp+B8h] [ebp-40h] BYREF
  double v59; // [esp+C0h] [ebp-38h]
  int v60; // [esp+C8h] [ebp-30h] BYREF
  int v61; // [esp+CCh] [ebp-2Ch] BYREF
  _DWORD *v62; // [esp+D0h] [ebp-28h]
  _DWORD *v63; // [esp+D4h] [ebp-24h] BYREF
  int (__userpurge *v64)@<eax>(int@<ebp>, int); // [esp+D8h] [ebp-20h]
  int v65; // [esp+DCh] [ebp-1Ch] BYREF
  _DWORD v66[5]; // [esp+E0h] [ebp-18h] BYREF
  int v67; // [esp+F4h] [ebp-4h]
  unsigned int v68; // [esp+100h] [ebp+8h]

  v66[3] = v21;
  v66[4] = sub_4010C0;
  v67 = a1 & 1;
  v68 = a1 & 0xFFFFFFFE;
  (*(void (__stdcall **)(unsigned int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int, _DWORD, _DWORD, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, _DWORD, _DWORD, const wchar_t *, int, _DWORD, _DWORD, const wchar_t *, int, _DWORD, _DWORD, int, int, _DWORD, _DWORD, int, int, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, _DWORD, int, int, int, int, _DWORD, _DWORD, _DWORD, _DWORD, int, int, _DWORD *, _DWORD *))(*(_DWORD *)v68 + 4))(
    v68,
    v21[0],
    v21[1],
    v21[2],
    LODWORD(v22),
    HIDWORD(v22),
    v23,
    LODWORD(v24),
    HIDWORD(v24),
    v25,
    v26,
    v27,
    v28,
    v29,
    v30,
    v31,
    v32,
    v33,
    v34,
    v35,
    v36,
    v37,
    v38,
    v39,
    v40[0],
    v40[1],
    v41,
    v42,
    v43[0],
    v43[1],
    v44,
    v45,
    v46[0],
    v46[1],
    v47,
    v48,
    v49[0],
    v49[1],
    v50,
    v51,
    v52[0],
    v52[1],
    v52[2],
    v52[3],
    v53[0],
    v53[1],
    v54,
    v55,
    v56,
    v57,
    v58[0],
    v58[1],
    LODWORD(v59),
    HIDWORD(v59),
    v60,
    v61,
    v62,
    v63);
  v1 = *(_DWORD *)v68;
  v66[0] = 0;
  v65 = 0;
  v61 = 0;
  v60 = 0;
  v58[0] = 0;
  v57 = 0;
  v56 = 0;
  v53[0] = 0;
  v52[0] = 0;
  v49[0] = 0;
  v46[0] = 0;
  v43[0] = 0;
  v40[0] = 0;
  v2 = (*(int (__stdcall **)(_DWORD))(v1 + 772))(0);
  v3 = __vbaObjSet(&v56, v2);
  v4 = (*(int (__stdcall **)(int, int *))(*(_DWORD *)v3 + 160))(v3, &v57);
  __asm { fnclex }
  if ( v4 < 0 )
    __vbaHresultCheckObj(v4, v3, dword_4519F4, 160);
  v5 = v57;
  v57 = 0;
  __vbaStrMove(&v65, v5);
  __vbaFreeObj(&v56);
  rtcLeftCharVar(v53, v43, 1);
  v6 = __vbaStrVarMove(v53);
  __vbaStrMove(&v61, v6);
  __vbaFreeVar(v53);
  rtcRightCharVar(v53, v43, 1);
  v7 = __vbaStrVarMove(v53);
  __vbaStrMove(v66, v7);
  __vbaFreeVar(v53);
  v44 = (const wchar_t *)&v65;
  v54 = 1;
  v53[0] = 2;
  v43[0] = 16392;
  rtcMidCharVar(v52, v43, 3, v53);
  v8 = __vbaStrVarMove(v52);
  __vbaStrMove(&v63, v8);
  v63 = v52;
  v62 = v53;
  v61 = 2;
  ((void (*)(void))__vbaFreeVarList)();
  v64 = (int (__userpurge *)@<eax>(int@<ebp>, int))rtcAnsiValueBstr(v61);
  v9 = rtcAnsiValueBstr(v66[0]);
  v10 = rtcAnsiValueBstr(v63);
  v12 = v9;
  v11 = (_WORD)v64 * v9;
  if ( !is_mul_ok((unsigned __int16)v64, v12) )
    __vbaErrorOverflow();
  v25 = v11;
  v24 = (double)v11;
  v23 = v10;
  v22 = (double)v10;
  v13 = v24;
  if ( dword_453000 != 0 )
    adj_fdiv_m64(LODWORD(v22), HIDWORD(v22));
  else
    v13 = v24 / v22;
  v59 = v13;
  if ( (v14 & 0xD) != 0 )
    _vbaFPException(v68);
  v15 = __vbaStrR8(LODWORD(v59), HIDWORD(v59));
  __vbaStrMove(&v60, v15);
  v16 = (*(int (__stdcall **)(unsigned int))(*(_DWORD *)v68 + 768))(v68);
  v17 = __vbaObjSet(&v56, v16);
  v18 = (*(int (__stdcall **)(int, int *))(*(_DWORD *)v17 + 160))(v17, &v57);
  __asm { fnclex }
  if ( v18 < 0 )
    __vbaHresultCheckObj(v18, v17, dword_4519F4, 160);
  v19 = -(__vbaStrCmp(v57, v60) == 0);
  __vbaFreeStr(&v57);
  __vbaFreeObj(&v56);
  v47 = -2147352572;
  v46[0] = 10;
  v50 = -2147352572;
  v49[0] = 10;
  if ( (_WORD)v19 != 0 )
  {
    v41 = L"Well done!";
    v40[0] = 8;
    __vbaVarDup(v52, v40);
    v44 = L"Well done! Now write a tutorial and submit it on CrackMes.de!";
  }
  else
  {
    __vbaVarDup(v52, v40);
    __vbaVarDup(v53, v43);
    rtcMsgBox(v53, 0, v52, v49, v46);
    __vbaFreeVarList(4, v53, v52, v49, v46);
    v47 = -2147352572;
    v46[0] = 10;
    v50 = -2147352572;
    v49[0] = 10;
    v41 = L"I'm sorry";
    v40[0] = 8;
    __vbaVarDup(v52, v40);
    v44 = L"That's not right! You should work harder!";
  }
  v43[0] = 8;
  __vbaVarDup(v53, v43);
  rtcMsgBox(v53, 0, v52, v49, v46);
  __vbaFreeVarList(4, v53, v52, v49, v46);
  __vbaStrCopy(v58, L"I don't think you belong here! Get away from here before I hijack your computer!");
  v67 = 0;
  v64 = sub_452239;
  __vbaFreeStr(v66);
  __vbaFreeStr(&v65);
  __vbaFreeStr(&v63);
  __vbaFreeStr(&v61);
  __vbaFreeStr(&v60);
  return __vbaFreeStr(v58);
}
// 451E16: bad sp value at call
// 451E25: bad sp value at call
// 451E57: bad sp value at call
// 451E7D: bad sp value at call
// 451E8D: bad sp value at call
// 451E94: bad sp value at call
// 451E99: bad sp value at call
// 451EBF: bad sp value at call
// 451EC9: bad sp value at call
// 451ED5: bad sp value at call
// 451F0D: bad sp value at call
// 451F17: bad sp value at call
// 451F1E: bad sp value at call
// 451FD1: bad sp value at call
// 451FE1: bad sp value at call
// 451FF0: bad sp value at call
// 452028: bad sp value at call
// 452031: bad sp value at call
// 452079: bad sp value at call
// 4520ED: bad sp value at call
// 452108: bad sp value at call
// 45211F: bad sp value at call
// 45213A: bad sp value at call
// 452170: bad sp value at call
// 452094: bad sp value at call
// 4520AB: bad sp value at call
// 4521BD: bad sp value at call
// 4521CE: bad sp value at call
// 452222: bad sp value at call
// 452227: bad sp value at call
// 45222C: bad sp value at call
// 452231: bad sp value at call
// 452236: bad sp value at call
// 401008: using guessed type int __thiscall __vbaFreeVar(_DWORD);
// 40100C: using guessed type int __stdcall __vbaStrVarMove(_DWORD);
// 401010: using guessed type int __cdecl __vbaFreeVarList(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 401018: using guessed type int __stdcall rtcAnsiValueBstr(_DWORD);
// 401020: using guessed type int __stdcall __vbaHresultCheckObj(_DWORD, _DWORD, _DWORD, _DWORD);
// 401028: using guessed type int __stdcall __vbaObjSet(_DWORD, _DWORD);
// 40102C: using guessed type int __stdcall rtcMsgBox(_DWORD, _DWORD, _DWORD, _DWORD, _DWORD);
// 40103C: using guessed type int __stdcall rtcMidCharVar(_DWORD, _DWORD, _DWORD, _DWORD);
// 401048: using guessed type int __stdcall __vbaStrCmp(_DWORD, _DWORD);
// 401050: using guessed type int __stdcall __vbaStrR8(_DWORD, _DWORD);
// 401074: using guessed type void __noreturn __vbaErrorOverflow(void);
// 401080: using guessed type int __fastcall __vbaStrCopy(_DWORD, _DWORD);
// 401090: using guessed type int __fastcall __vbaVarDup(_DWORD, _DWORD);
// 401094: using guessed type int __stdcall rtcLeftCharVar(_DWORD, _DWORD, _DWORD);
// 40109C: using guessed type int __fastcall __vbaStrMove(_DWORD, _DWORD);
// 4010A0: using guessed type int __stdcall rtcRightCharVar(_DWORD, _DWORD, _DWORD);
// 4010B0: using guessed type int __thiscall __vbaFreeObj(_DWORD);
// 4010B4: using guessed type int __thiscall __vbaFreeStr(_DWORD);
// 4010DC: using guessed type void __cdecl __noreturn _vbaFPException(_DWORD);
// 4010F4: using guessed type double __stdcall adj_fdiv_m64(_DWORD, _DWORD);
// 4519F4: using guessed type int dword_4519F4[5];
// 451A08: using guessed type wchar_t aWellDoneNowWri[62];
// 451A88: using guessed type wchar_t aWellDone[11];
// 451ACC: using guessed type wchar_t aThatSNotRightY[42];
// 451B24: using guessed type wchar_t aIMSorry[10];
// 451B64: using guessed type wchar_t aIDonTThinkYouB[81];
// 453000: using guessed type int dword_453000;

//----- (00452239) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
int __userpurge sub_452239@<eax>(int a1@<ebp>, int a2)
{
  (*(void (__cdecl **)(_DWORD))(**(_DWORD **)(a1 + 8) + 8))(*(_DWORD *)(a1 + 8));
  return *(_DWORD *)(a1 - 4);
}
// 452255: positive sp value C has been found
// 452239: could not find valid save-restore pair for ebx
// 452239: could not find valid save-restore pair for edi
// 452239: could not find valid save-restore pair for esi

// nfuncs=49 queued=4 decompiled=4 lumina nreq=0 worse=0 better=0
// ALL OK, 4 function(s) have been successfully decompiled
