// !!! AUTOGENERATED HEADER FILE !!!

#include <stdint.h>
#include "../vm.h"

#define JITFUNC(name) int jit_gen_##name(struct vm_program_info *info, struct vm_insn *insn, uint8_t **pos, uint32_t currentPc)

#define OP_NOP 0
JITFUNC(NOP);

#define OP_VMCALL 1
JITFUNC(VMCALL);

#define OP_VMQUIT 2
JITFUNC(VMQUIT);

#define OP_ADD 3
JITFUNC(ADD);

#define OP_SUB 4
JITFUNC(SUB);

#define OP_MUL 5
JITFUNC(MUL);

#define OP_NEG 6
JITFUNC(NEG);

#define OP_AND 7
JITFUNC(AND);

#define OP_OR 8
JITFUNC(OR);

#define OP_XOR 9
JITFUNC(XOR);

#define OP_SEQ 10
JITFUNC(SEQ);

#define OP_SNEQ 11
JITFUNC(SNEQ);

#define OP_SLT 12
JITFUNC(SLT);

#define OP_SLET 13
JITFUNC(SLET);

#define OP_SLTU 14
JITFUNC(SLTU);

#define OP_SLETU 15
JITFUNC(SLETU);

#define OP_SEQI 16
JITFUNC(SEQI);

#define OP_SNEQI 17
JITFUNC(SNEQI);

#define OP_SLTI 18
JITFUNC(SLTI);

#define OP_SLETI 19
JITFUNC(SLETI);

#define OP_SGTI 20
JITFUNC(SGTI);

#define OP_SGETI 21
JITFUNC(SGETI);

#define OP_STORE 22
JITFUNC(STORE);

#define OP_LOAD 23
JITFUNC(LOAD);

#define OP_J 24
JITFUNC(J);

#define OP_JR 25
JITFUNC(JR);

#define OP_JZ 26
JITFUNC(JZ);

#define OP_JNZ 27
JITFUNC(JNZ);

#define OP_RETADR 28
JITFUNC(RETADR);

#define OP_LDI 29
JITFUNC(LDI);

#define OP_LDIU 30
JITFUNC(LDIU);

#define OP_LUI 31
JITFUNC(LUI);

#define OP_ADDI 32
JITFUNC(ADDI);

#define OP_MULI 33
JITFUNC(MULI);

#define OP_ORI 34
JITFUNC(ORI);

#define OP_ANDI 35
JITFUNC(ANDI);

#define OP_XORI 36
JITFUNC(XORI);

#define OP_SHLI 37
JITFUNC(SHLI);

#define OP_SHRI 38
JITFUNC(SHRI);

#define OP_SHRIU 39
JITFUNC(SHRIU);

#define OP_INVALID_OP 40
JITFUNC(INVALID_OP);

#ifdef JITTERY_NEED_FUNCTION_TABLE
typedef int (*jit_gen_fn)(struct vm_program_info *info, struct vm_insn *insn, uint8_t **pos, uint32_t currentPc);

static jit_gen_fn jit_funcs[] = {
	[OP_NOP] = jit_gen_NOP,
	[OP_VMCALL] = jit_gen_VMCALL,
	[OP_VMQUIT] = jit_gen_VMQUIT,
	[OP_ADD] = jit_gen_ADD,
	[OP_SUB] = jit_gen_SUB,
	[OP_MUL] = jit_gen_MUL,
	[OP_NEG] = jit_gen_NEG,
	[OP_AND] = jit_gen_AND,
	[OP_OR] = jit_gen_OR,
	[OP_XOR] = jit_gen_XOR,
	[OP_SEQ] = jit_gen_SEQ,
	[OP_SNEQ] = jit_gen_SNEQ,
	[OP_SLT] = jit_gen_SLT,
	[OP_SLET] = jit_gen_SLET,
	[OP_SLTU] = jit_gen_SLTU,
	[OP_SLETU] = jit_gen_SLETU,
	[OP_SEQI] = jit_gen_SEQI,
	[OP_SNEQI] = jit_gen_SNEQI,
	[OP_SLTI] = jit_gen_SLTI,
	[OP_SLETI] = jit_gen_SLETI,
	[OP_SGTI] = jit_gen_SGTI,
	[OP_SGETI] = jit_gen_SGETI,
	[OP_STORE] = jit_gen_STORE,
	[OP_LOAD] = jit_gen_LOAD,
	[OP_J] = jit_gen_J,
	[OP_JR] = jit_gen_JR,
	[OP_JZ] = jit_gen_JZ,
	[OP_JNZ] = jit_gen_JNZ,
	[OP_RETADR] = jit_gen_RETADR,
	[OP_LDI] = jit_gen_LDI,
	[OP_LDIU] = jit_gen_LDIU,
	[OP_LUI] = jit_gen_LUI,
	[OP_ADDI] = jit_gen_ADDI,
	[OP_MULI] = jit_gen_MULI,
	[OP_ORI] = jit_gen_ORI,
	[OP_ANDI] = jit_gen_ANDI,
	[OP_XORI] = jit_gen_XORI,
	[OP_SHLI] = jit_gen_SHLI,
	[OP_SHRI] = jit_gen_SHRI,
	[OP_SHRIU] = jit_gen_SHRIU,
	[OP_INVALID_OP] = jit_gen_INVALID_OP,
};
#endif
