;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2026 Hex-Rays, <support@hex-rays.com>           |
; |            <error retrieving user info: Invalid input data>             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 15AF16B8A7B88B86691F7C1E72952BCD2BD31A919B00F37D044BF21AA650F32D
; Input MD5    : 7A45656539CC4E1B85FA35EEE21E366B
; Input CRC32  : 265AC9C4
; Compiler     : Visual C++ (guessed)

; File Name   : /home/petik/Downloads/virusshare/crackme-writeups/timotei-family/timotei-crackme-10/timotei-crackme-10.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 64AC50E6 (Mon Jul 10 18:41:42 2023 UTC)
; Section 1. (virtual address 00001000)
; Virtual size                  : 0000024C (    588.)
; Section size in file          : 00000400 (   1024.)
; Offset to raw data for section: 00000400
; Flags 60000020: Text Executable Readable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Execute
_text segment para public 'CODE' use32
assume cs:_text
;org 401000h
assume es:nothing, ss:nothing, ds:_data, fs:nothing, gs:nothing


; Attributes: noreturn

public start
start proc near
call    InitCommonControls
push    0               ; lpModuleName
call    GetModuleHandleA
mov     hInstance, eax
push    0C8h            ; lpIconName
push    eax             ; hInstance
call    LoadIconA
mov     lParam, eax
push    7F89h           ; lpCursorName
push    0               ; hInstance
call    LoadCursorA
mov     hCursor, eax
push    0               ; dwInitParam
push    offset DialogFunc ; lpDialogFunc
push    0               ; hWndParent
push    64h ; 'd'       ; lpTemplateName
push    hInstance       ; hInstance
call    DialogBoxParamA
push    0               ; uExitCode
call    ExitProcess
start endp



; Attributes: bp-based frame

; INT_PTR __stdcall DialogFunc(HWND, UINT, WPARAM, LPARAM)
DialogFunc proc near

hWnd= dword ptr  8
arg_4= dword ptr  0Ch
arg_8= dword ptr  10h

push    ebp
mov     ebp, esp
cmp     [ebp+arg_4], 110h
jnz     short loc_4010D8
push    offset sub_40110D ; dwNewLong
push    0FFFFFFFCh      ; nIndex
push    eax             ; hWnd
call    SetWindowLongA
mov     lpPrevWndFunc, eax
push    lParam          ; lParam
push    1               ; wParam
push    80h             ; Msg
push    [ebp+hWnd]      ; hWnd
call    SendMessageA
push    0               ; lParam
push    31h ; '1'       ; wParam
push    0C5h            ; Msg
push    195h            ; nIDDlgItem
push    [ebp+hWnd]      ; hDlg
call    SendDlgItemMessageA
push    offset String   ; ".::."
push    190h            ; nIDDlgItem
push    [ebp+hWnd]      ; hDlg
call    SetDlgItemTextA
push    offset aTimotei ; "timotei"
push    195h            ; nIDDlgItem
push    [ebp+hWnd]      ; hDlg
call    SetDlgItemTextA
push    offset aCrackmesOne ; "CraCkMeS.oNe"
push    196h            ; nIDDlgItem
push    [ebp+hWnd]      ; hDlg
call    SetDlgItemTextA
push    [ebp+hWnd]      ; hDlg
call    sub_401144
jmp     short loc_401107

loc_4010D8:
cmp     [ebp+arg_4], 111h
jnz     short loc_4010F4
cmp     [ebp+arg_8], 192h
jnz     short loc_401107
push    [ebp+hWnd]      ; hDlg
call    sub_401144
jmp     short loc_401107

loc_4010F4:
cmp     [ebp+arg_4], 200h
jnz     short loc_401107
push    0               ; nResult
push    [ebp+hWnd]      ; hDlg
call    EndDialog

loc_401107:
xor     eax, eax
leave
retn    10h
DialogFunc endp



; Attributes: bp-based frame

; int __stdcall sub_40110D(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
sub_40110D proc near

hWnd= dword ptr  8
Msg= dword ptr  0Ch
wParam= dword ptr  10h
lParam= dword ptr  14h

push    ebp
mov     ebp, esp
cmp     [ebp+Msg], 20h ; ' '
jnz     short loc_401123
push    hCursor         ; hCursor
call    SetCursor
jmp     short loc_40113E

loc_401123:             ; lParam
push    [ebp+lParam]
push    [ebp+wParam]    ; wParam
push    [ebp+Msg]       ; Msg
push    [ebp+hWnd]      ; hWnd
push    lpPrevWndFunc   ; lpPrevWndFunc
call    CallWindowProcA
leave
retn    10h

loc_40113E:
xor     eax, eax
leave
retn    10h
sub_40110D endp



; Attributes: bp-based frame

; int __stdcall sub_401144(HWND hDlg)
sub_401144 proc near

hDlg= dword ptr  8

push    ebp
mov     ebp, esp
push    edi
push    esi
push    ebx
push    32h ; '2'       ; cchMax
push    offset dword_403072 ; lpString
push    196h            ; nIDDlgItem
push    [ebp+hDlg]      ; hDlg
call    GetDlgItemTextA
cmp     eax, 0
jz      short loc_4011DF
push    32h ; '2'       ; cchMax
push    offset dword_403040 ; lpString
push    195h            ; nIDDlgItem
push    [ebp+hDlg]      ; hDlg
call    GetDlgItemTextA
cmp     eax, 4
jl      short loc_4011DF
lea     esi, dword_403040
mov     ecx, eax
mov     ebx, eax
dec     ebx

loc_401187:
mov     ecx, ebx

loc_401189:
mov     al, [esi]
mov     dl, [esi+1]
cmp     al, dl
jle     short loc_40119C
mov     ah, [esi+1]
mov     [esi], ah
mov     ah, al
mov     [esi+1], ah

loc_40119C:
inc     esi
loop    loc_401189
dec     ebx
mov     esi, offset dword_403040
jnz     short loc_401187
mov     eax, dword_403040
mov     edx, dword_403072
mov     ebx, eax
xor     ebx, edx
jnz     short loc_4011DF
mul     edx
mov     edi, edx
push    offset byte_403076 ; String
call    ds:atoi         ; msvcrt
xor     eax, edi
jnz     short loc_4011DF
push    offset aRegistered ; "Registered"
push    190h            ; nIDDlgItem
push    [ebp+hDlg]      ; hDlg
call    SetDlgItemTextA
jmp     short loc_4011F1

loc_4011DF:
push    offset aUnregistered ; "Unregistered"
push    190h            ; nIDDlgItem
push    [ebp+hDlg]      ; hDlg
call    SetDlgItemTextA

loc_4011F1:
pop     ebx
pop     esi
pop     edi
leave
retn    4
sub_401144 endp ; sp-analysis failed

; [00000006 BYTES: COLLAPSED FUNCTION CallWindowProcA]
; [00000006 BYTES: COLLAPSED FUNCTION DialogBoxParamA]
; [00000006 BYTES: COLLAPSED FUNCTION EndDialog]
; [00000006 BYTES: COLLAPSED FUNCTION GetDlgItemTextA]
; [00000006 BYTES: COLLAPSED FUNCTION LoadCursorA]
; [00000006 BYTES: COLLAPSED FUNCTION LoadIconA]
; [00000006 BYTES: COLLAPSED FUNCTION SendDlgItemMessageA]
; [00000006 BYTES: COLLAPSED FUNCTION SendMessageA]
; [00000006 BYTES: COLLAPSED FUNCTION SetCursor]
; [00000006 BYTES: COLLAPSED FUNCTION SetDlgItemTextA]
; [00000006 BYTES: COLLAPSED FUNCTION SetWindowLongA]
; [00000006 BYTES: COLLAPSED FUNCTION ExitProcess]
; [00000006 BYTES: COLLAPSED FUNCTION GetModuleHandleA]
; [00000006 BYTES: COLLAPSED FUNCTION InitCommonControls]
align 200h
dd 300h dup(?)
_text ends

; Section 2. (virtual address 00002000)
; Virtual size                  : 00000226 (    550.)
; Section size in file          : 00000400 (   1024.)
; Offset to raw data for section: 00000800
; Flags 40000040: Data Readable
; Alignment     : default
;
; Imports from comctl32.dll
;

; Segment type: Externs
; _idata
; void (__stdcall *InitCommonControls)()
extrn __imp_InitCommonControls:dword ; comctl32

;
; Imports from kernel32.dll
;
; HMODULE (__stdcall *GetModuleHandleA)(LPCSTR lpModuleName)
extrn __imp_GetModuleHandleA:dword ; kernel32
; void (__stdcall __noreturn *ExitProcess)(UINT uExitCode)
extrn __imp_ExitProcess:dword ; kernel32

;
; Imports from msvcrt.dll
;
; int (__cdecl *atoi)(const char *String)
extrn atoi:dword        ; msvcrt

;
; Imports from user32.dll
;
; LRESULT (__stdcall *SendMessageA)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
extrn __imp_SendMessageA:dword ; user32
; HCURSOR (__stdcall *SetCursor)(HCURSOR hCursor)
extrn __imp_SetCursor:dword ; user32
; LRESULT (__stdcall *SendDlgItemMessageA)(HWND hDlg, int nIDDlgItem, UINT Msg, WPARAM wParam, LPARAM lParam)
extrn __imp_SendDlgItemMessageA:dword ; user32
; LONG (__stdcall *SetWindowLongA)(HWND hWnd, int nIndex, LONG dwNewLong)
extrn __imp_SetWindowLongA:dword ; user32
; HICON (__stdcall *LoadIconA)(HINSTANCE hInstance, LPCSTR lpIconName)
extrn __imp_LoadIconA:dword ; user32
; HCURSOR (__stdcall *LoadCursorA)(HINSTANCE hInstance, LPCSTR lpCursorName)
extrn __imp_LoadCursorA:dword ; user32
; UINT (__stdcall *GetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPSTR lpString, int cchMax)
extrn __imp_GetDlgItemTextA:dword ; user32
; BOOL (__stdcall *EndDialog)(HWND hDlg, INT_PTR nResult)
extrn __imp_EndDialog:dword ; user32
; INT_PTR (__stdcall *DialogBoxParamA)(HINSTANCE hInstance, LPCSTR lpTemplateName, HWND hWndParent, DLGPROC lpDialogFunc, LPARAM dwInitParam)
extrn __imp_DialogBoxParamA:dword ; user32
; BOOL (__stdcall *SetDlgItemTextA)(HWND hDlg, int nIDDlgItem, LPCSTR lpString)
extrn __imp_SetDlgItemTextA:dword ; user32
; LRESULT (__stdcall *CallWindowProcA)(WNDPROC lpPrevWndFunc, HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
extrn __imp_CallWindowProcA:dword ; user32



; Segment type: Pure data
; Segment permissions: Read
_rdata segment para public 'DATA' use32
assume cs:_rdata
;org 40204Ch
align 10h
__IMPORT_DESCRIPTOR_user32 dd rva off_4020D0 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aUser32Dll       ; DLL Name
dd rva __imp_SendMessageA ; Import Address Table
__IMPORT_DESCRIPTOR_kernel32 dd rva off_4020BC ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva __imp_GetModuleHandleA ; Import Address Table
__IMPORT_DESCRIPTOR_comctl32 dd rva off_4020B4 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aComctl32Dll     ; DLL Name
dd rva __imp_InitCommonControls ; Import Address Table
__IMPORT_DESCRIPTOR_msvcrt dd rva off_4020C8 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aMsvcrtDll       ; DLL Name
dd rva atoi             ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
;
; Import names for comctl32.dll
;
off_4020B4 dd rva word_4021EE
dd 0
;
; Import names for kernel32.dll
;
off_4020BC dd rva word_4021CC
dd rva word_4021BE
dd 0
;
; Import names for msvcrt.dll
;
off_4020C8 dd rva word_402212
dd 0
;
; Import names for user32.dll
;
off_4020D0 dd rva word_402172
dd rva word_402182
dd rva word_40215C
dd rva word_4021A0
dd rva word_402150
dd rva word_402142
dd rva word_402130
dd rva word_402124
dd rva word_402112
dd rva word_40218E
dd rva word_402100
dd 0
word_402100 dw 15h
db 'CallWindowProcA',0
word_402112 dw 90h
db 'DialogBoxParamA',0
word_402124 dw 0B4h
db 'EndDialog',0
word_402130 dw 0FCh
db 'GetDlgItemTextA',0
word_402142 dw 194h
db 'LoadCursorA',0
word_402150 dw 198h
db 'LoadIconA',0
word_40215C dw 1F8h
db 'SendDlgItemMessageA',0
word_402172 dw 1FDh
db 'SendMessageA',0
align 2
word_402182 dw 20Eh
db 'SetCursor',0
word_40218E dw 213h
db 'SetDlgItemTextA',0
word_4021A0 dw 238h
db 'SetWindowLongA',0
align 2
aUser32Dll db 'user32.dll',0
align 2
word_4021BE dw 9Bh
db 'ExitProcess',0
word_4021CC dw 134h
db 'GetModuleHandleA',0
align 10h
aKernel32Dll db 'kernel32.dll',0
align 2
word_4021EE dw 54h
db 'InitCommonControls',0
align 4
aComctl32Dll db 'comctl32.dll',0
align 2
word_402212 dw 220h
db 'atoi',0
align 2
aMsvcrtDll db 'msvcrt.dll',0
align 1000h
_rdata ends

; Section 3. (virtual address 00003000)
; Virtual size                  : 000000B8 (    184.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00000C00
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
_data segment para public 'DATA' use32
assume cs:_data
;org 403000h
; CHAR String[]
String db '.::.',0
; CHAR aTimotei[]
aTimotei db 'timotei',0
; CHAR aCrackmesOne[]
aCrackmesOne db 'CraCkMeS.oNe',0
; CHAR aUnregistered[]
aUnregistered db 'Unregistered',0
; CHAR aRegistered[]
aRegistered db 'Registered',0
align 10h
; CHAR dword_403040[]
dword_403040 dd 0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
; CHAR dword_403072[]
dword_403072 dd 0
; char byte_403076[50]
byte_403076 db 32h dup(0)
; HINSTANCE hInstance
hInstance dd 0
; LPARAM lParam
lParam dd 0
; HCURSOR hCursor
hCursor dd 0
; WNDPROC lpPrevWndFunc
lpPrevWndFunc dd 0
align 1000h
_data ends


end start
